import { GITHUB_EVENT_KINDS, TRIGGER_ANY_SCOPE, type GithubTrigger, type SlackTrigger } from "../../../shared/automations.js";
import type { PollingPolicy } from "../../../internal/scheduling.js";
import { describeScopeIssues, type ListenerScopeIssue } from "../../automations/listener-integrations.js";
export class SandBackendRelayError extends Error {}
export const DEFAULT_REGISTER_INTERVAL_MS = 5 * 60_000, DEGRADED_REGISTER_INTERVAL_MS = 60_000, ERROR_BACKOFF_MS = 30_000;
type RelayWireEvent = Record<string, unknown> & { source: "slack" | "github"; kind?: unknown; timestampMs?: number };
export function mapRelayWireEvent(event: RelayWireEvent): Record<string, unknown> | null { const timestampMs = event.timestampMs ?? Date.now(); if (event.source === "slack") { const channelName = typeof event.channelName === "string" ? event.channelName : typeof event.channelId === "string" ? event.channelId : ""; if (!channelName) return null; const channel = channelName === event.channelId || channelName.startsWith("#") ? channelName : `#${channelName}`, sender = typeof event.senderSlackUserId === "string" && event.senderSlackUserId ? `@${event.senderSlackUserId}` : "someone"; if (event.kind === "reaction") { const emoji = typeof event.reactionEmoji === "string" ? event.reactionEmoji : ""; return !emoji ? null : { source: "slack", channel, sender, text: typeof event.text === "string" ? event.text : "", isMention: false, isSelf: event.isSelf === true, reactionEmoji: `:${emoji.replaceAll(":", "")}:`, ...(typeof event.ts === "string" ? { ts: event.ts } : {}), ...(typeof event.threadTs === "string" ? { threadTs: event.threadTs } : {}), timestampMs }; } return { source: "slack", channel, sender, text: typeof event.text === "string" ? event.text : "", isMention: event.isMention === true, ...(typeof event.ts === "string" ? { ts: event.ts } : {}), ...(typeof event.threadTs === "string" ? { threadTs: event.threadTs } : {}), timestampMs }; } const repo = typeof event.repo === "string" ? event.repo : "", kind = event.kind; if (!repo || typeof kind !== "string" || !(GITHUB_EVENT_KINDS as readonly string[]).includes(kind)) return null; return { source: "github", repo, kind, title: typeof event.title === "string" ? event.title : "", actor: typeof event.actor === "string" ? event.actor : "someone", ...(typeof event.url === "string" ? { url: event.url } : {}), ...(typeof event.detail === "string" ? { detail: event.detail } : {}), ...(typeof event.prOwner === "string" && event.prOwner ? { prOwner: event.prOwner } : {}), ...(typeof event.branch === "string" && event.branch ? { branch: event.branch } : {}), timestampMs }; }
export function relaySubscriptionRequestOf(slack: readonly SlackTrigger[], github: readonly GithubTrigger[]) { const slackChannels = new Set(slack.map((listener) => listener.channel === TRIGGER_ANY_SCOPE ? TRIGGER_ANY_SCOPE : listener.channel)), githubRepos = new Set(github.map((listener) => listener.repo.toLowerCase())), githubKinds = new Set(github.flatMap((listener) => listener.events)); return { slackChannels: [...slackChannels].sort(), githubRepos: [...githubRepos].sort(), githubKinds: [...githubKinds].sort() }; }
export interface RelayStatus { readonly state: string; readonly detail?: string; readonly scopeIssues?: readonly ListenerScopeIssue[] }
export function createBackendRelaySources(deps: { readonly getAccessToken: (args: { backendUrl: string }) => Promise<string>; readonly getBackendUrl: () => string; readonly polling: PollingPolicy; readonly fetchImpl?: typeof fetch; readonly registerIntervalMs?: number; readonly degradedRegisterIntervalMs?: number; readonly isNotifyConnected?: () => boolean; readonly isNotifySafetyPollEnabled?: () => boolean }) {
  const fetchImpl = deps.fetchImpl ?? fetch, registerInterval = deps.registerIntervalMs ?? DEFAULT_REGISTER_INTERVAL_MS, degradedInterval = Math.min(deps.degradedRegisterIntervalMs ?? DEGRADED_REGISTER_INTERVAL_MS, registerInterval); let slackSink: ((event: Record<string, unknown>) => boolean) | null = null, githubSink: ((event: Record<string, unknown>) => boolean) | null = null, slackListeners: SlackTrigger[] = [], githubListeners: GithubTrigger[] = [], slackStatus: RelayStatus = { state: "idle" }, githubStatus: RelayStatus = { state: "idle" }, timer: { dispose(): void } | null = null, ticking = false, registeredKey = "", registeredAt = 0, degradedStreak = 0, backoffUntil = 0, pendingAckIds: string[] = [];
  const call = async (path: string, body: unknown): Promise<Record<string, unknown>> => { const backendUrl = deps.getBackendUrl(), token = await deps.getAccessToken({ backendUrl }), response = await fetchImpl(new URL(path, backendUrl), { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${token}` }, body: JSON.stringify(body) }); if (!response.ok) throw new SandBackendRelayError(`relay ${path} returned ${response.status}`); return await response.json() as Record<string, unknown>; };
  const ensureRegistered = async () => { const request = relaySubscriptionRequestOf(slackListeners, githubListeners), key = JSON.stringify(request), staleAfter = degradedStreak === 0 ? registerInterval : Math.min(registerInterval, degradedInterval * 2 ** Math.min(degradedStreak - 1, 10)); if (key === registeredKey && Date.now() - registeredAt <= staleAfter) return; const result = await call("/sand/listener-subscriptions", request); registeredKey = key; registeredAt = Date.now(); const slack = result.slack as { status?: string; teams?: readonly { channels?: readonly { input: string; isBotMember?: boolean }[]; unresolvedChannels?: readonly string[] }[] } | undefined, github = result.github as { status?: string; repos?: readonly { repo: string; isSubscribed: boolean; detail?: string }[] } | undefined; const issues: ListenerScopeIssue[] = []; for (const team of slack?.teams ?? []) { for (const channel of team.channels ?? []) if (channel.isBotMember === false) issues.push({ scope: channel.input, kind: "bot-not-in-channel" }); for (const scope of team.unresolvedChannels ?? []) issues.push({ scope, kind: "not-found" }); } if (slackListeners.length > 0) slackStatus = slack?.status === "not-linked" ? { state: "error", detail: "Slack isn't connected to your Cursor account. Connect it to start listening." } : issues.length > 0 ? { state: "listening", detail: describeScopeIssues(issues), scopeIssues: issues } : { state: "listening" }; const failed = (github?.repos ?? []).filter((repo) => !repo.isSubscribed); if (githubListeners.length > 0) githubStatus = github?.status === "not-connected" ? { state: "error", detail: "GitHub isn't connected to your Cursor account. Connect it to start listening." } : failed.length > 0 ? { state: failed.length === (github?.repos ?? []).length ? "error" : "listening", detail: failed.map((entry) => entry.detail ?? `Can't watch ${entry.repo}.`).join(" ") } : { state: "listening" }; const degraded = slackStatus.state === "error" || (slackStatus.scopeIssues?.length ?? 0) > 0 || githubStatus.state === "error" || githubStatus.detail != null; degradedStreak = degraded ? degradedStreak + 1 : 0; };
  const tick = async () => { if (ticking || Date.now() < backoffUntil) return; ticking = true; try { await ensureRegistered(); if (deps.isNotifyConnected?.() === false && deps.isNotifySafetyPollEnabled?.() === false && pendingAckIds.length === 0) return; const result = await call("/sand/listener-events/poll", { ackIds: pendingAckIds }), events = Array.isArray(result.events) ? result.events as Array<RelayWireEvent & { id: string }> : [], acked = new Set(pendingAckIds), next: string[] = []; for (const wire of events) { if (acked.has(wire.id)) { next.push(wire.id); continue; } const mapped = mapRelayWireEvent(wire), sink = mapped?.source === "slack" ? slackSink : githubSink; if (mapped == null || sink?.(mapped) === true) next.push(wire.id); } pendingAckIds = next; } catch (error) { registeredKey = ""; backoffUntil = Date.now() + ERROR_BACKOFF_MS; const detail = error instanceof Error ? error.message : "relay poll failed"; if (slackListeners.length > 0 && slackSink != null) slackStatus = { state: "error", detail }; if (githubListeners.length > 0 && githubSink != null) githubStatus = { state: "error", detail }; } finally { ticking = false; } };
  const ensureLoop = () => { timer ??= deps.polling.start(async () => { await tick(); }); }, stopIfIdle = () => { if (slackSink != null || githubSink != null) return; timer?.dispose(); timer = null; registeredKey = ""; backoffUntil = 0; };
  const slack = { kind: "slack", async start(sink: typeof slackSink) { slackSink = sink; slackStatus = { state: "connecting" }; ensureLoop(); }, setListeners(listeners: readonly SlackTrigger[]) { slackListeners = [...listeners]; }, async stop() { slackSink = null; slackListeners = []; slackStatus = { state: "idle" }; registeredKey = ""; stopIfIdle(); }, getStatus: () => slackStatus };
  const github = { kind: "github", async start(sink: typeof githubSink) { githubSink = sink; githubStatus = { state: "connecting" }; ensureLoop(); }, setListeners(listeners: readonly GithubTrigger[]) { githubListeners = [...listeners]; }, async stop() { githubSink = null; githubListeners = []; githubStatus = { state: "idle" }; registeredKey = ""; stopIfIdle(); }, getStatus: () => githubStatus };
  return { slack, github, requestDrain: () => { void tick(); } };
}
