import { LinearEndOfCycleEvent, LinearIssueCreatedEvent, LinearStatusChangedEvent, LinearTrigger as LinearTriggerMessage, MicrosoftTeamsTrigger as MicrosoftTeamsTriggerMessage, PagerDutyIncidentAcknowledgedEvent, PagerDutyIncidentAnyEvent, PagerDutyIncidentEscalatedEvent, PagerDutyIncidentResolvedEvent, PagerDutyIncidentTriggeredEvent, PagerDutyTrigger as PagerDutyTriggerMessage, SentryIssueAnyEvent, SentryIssueArchivedEvent, SentryIssueAssignedEvent, SentryIssueCreatedEvent, SentryIssueResolvedEvent, SentryIssueUnresolvedEvent, SentryTrigger as SentryTriggerMessage, Trigger } from "../../../packages/proto/generated/aiserver/v1/automations_pb.js";
import type { LinearTrigger as ProtoLinearTrigger, PagerDutyTrigger as ProtoPagerDutyTrigger, SentryTrigger as ProtoSentryTrigger } from "../../../packages/proto/generated/aiserver/v1/automations_pb.js";
import type { LinearTrigger, MicrosoftTeamsTrigger, PagerDutyTrigger, SentryTrigger } from "../../../shared/automations.js";
export type BackendCloudTrigger = { readonly trigger: { readonly case: string; readonly value: unknown } };
function backendTrigger(value: Trigger): BackendCloudTrigger { return value as unknown as BackendCloudTrigger; }
export function microsoftTeamsCloudTrigger(trigger: MicrosoftTeamsTrigger): BackendCloudTrigger { return backendTrigger(new Trigger({ trigger: { case: "microsoftTeamsTrigger", value: new MicrosoftTeamsTriggerMessage({ tenantId: trigger.tenantId, teamId: trigger.teamId, teamIds: [...trigger.teamIds], channelIds: [...trigger.channelIds], messageContains: trigger.messageContains, messageContainsIsRegex: trigger.messageContainsIsRegex, blockUnauthenticatedTeamsUsers: trigger.blockUnauthenticatedTeamsUsers }) } })); }
export function linearCloudTrigger(trigger: LinearTrigger): BackendCloudTrigger { let event: ProtoLinearTrigger["event"] = { case: undefined }; switch (trigger.event.case) { case "issueCreated": event = { case: "issueCreated", value: new LinearIssueCreatedEvent() }; break; case "statusChanged": event = { case: "statusChanged", value: new LinearStatusChangedEvent({ statusIds: [...trigger.event.statusIds] }) }; break; case "endOfCycle": event = { case: "endOfCycle", value: new LinearEndOfCycleEvent({ cycleIds: [...trigger.event.cycleIds] }) }; break; } return backendTrigger(new Trigger({ trigger: { case: "linear", value: new LinearTriggerMessage({ event, projectIds: [...trigger.projectIds], teamIds: [...trigger.teamIds] }) } })); }
export function sentryCloudTrigger(trigger: SentryTrigger): BackendCloudTrigger { let event: ProtoSentryTrigger["event"] = { case: undefined }; switch (trigger.event.case) { case "issueCreated": event = { case: "issueCreated", value: new SentryIssueCreatedEvent() }; break; case "issueResolved": event = { case: "issueResolved", value: new SentryIssueResolvedEvent() }; break; case "issueAssigned": event = { case: "issueAssigned", value: new SentryIssueAssignedEvent() }; break; case "issueArchived": event = { case: "issueArchived", value: new SentryIssueArchivedEvent() }; break; case "issueUnresolved": event = { case: "issueUnresolved", value: new SentryIssueUnresolvedEvent() }; break; case "issueAny": event = { case: "issueAny", value: new SentryIssueAnyEvent() }; break; } return backendTrigger(new Trigger({ trigger: { case: "sentry", value: new SentryTriggerMessage({ event, projectIds: [...trigger.projectIds] }) } })); }
export function pagerDutyCloudTrigger(trigger: PagerDutyTrigger): BackendCloudTrigger { let event: ProtoPagerDutyTrigger["event"] = { case: undefined }; switch (trigger.event.case) { case "incidentTriggered": event = { case: "incidentTriggered", value: new PagerDutyIncidentTriggeredEvent() }; break; case "incidentAcknowledged": event = { case: "incidentAcknowledged", value: new PagerDutyIncidentAcknowledgedEvent() }; break; case "incidentResolved": event = { case: "incidentResolved", value: new PagerDutyIncidentResolvedEvent() }; break; case "incidentEscalated": event = { case: "incidentEscalated", value: new PagerDutyIncidentEscalatedEvent() }; break; case "incidentAny": event = { case: "incidentAny", value: new PagerDutyIncidentAnyEvent() }; break; } return backendTrigger(new Trigger({ trigger: { case: "pagerduty", value: new PagerDutyTriggerMessage({ event, serviceIds: [...trigger.serviceIds] }) } })); }
export function backendCloudTrigger(trigger: MicrosoftTeamsTrigger | LinearTrigger | SentryTrigger | PagerDutyTrigger): BackendCloudTrigger { switch (trigger.type) { case "microsoftTeams": return microsoftTeamsCloudTrigger(trigger); case "linear": return linearCloudTrigger(trigger); case "sentry": return sentryCloudTrigger(trigger); case "pagerduty": return pagerDutyCloudTrigger(trigger); } }
