import { execFile } from "node:child_process";
import { randomUUID } from "node:crypto";
import { promises as fs, constants as fsConstants } from "node:fs";
import { dirname, join } from "node:path";
import { inflateRawSync } from "node:zlib";
import { scrubbedOnePasswordEnvironment, type CliCandidate, type CliInspection } from "./onepassword-provisioning-bridge.js";

export const MANAGED_ONEPASSWORD_CLI_VERSION = "2.35.0";
export const ONEPASSWORD_CODESIGN_REQUIREMENT = 'identifier "com.1password.op" and anchor apple generic and certificate leaf[subject.OU] = "2BUA8C4S2C"';
export const SAND_OP_LAUNCHER_IDENTIFIER_REQUIREMENT = 'identifier "sand-op-launcher"';
export const SAND_OP_LAUNCHER_CODESIGN_REQUIREMENT = `${SAND_OP_LAUNCHER_IDENTIFIER_REQUIREMENT} and anchor apple generic and certificate leaf[subject.OU] = "DCNK4UB866"`;
export const ONEPASSWORD_SYSTEM_CLI_PATHS = ["/opt/homebrew/bin/op", "/usr/local/bin/op", "/usr/bin/op"] as const;
export const MAX_ARCHIVE_BYTES = 64 * 1024 * 1024, MAX_EXECUTABLE_BYTES = 64 * 1024 * 1024, MAX_PROCESS_OUTPUT_BYTES = 16 * 1024;
const DOWNLOAD_TIMEOUT_MS = 60_000, VERIFY_TIMEOUT_MS = 15_000, VERSION_TIMEOUT_MS = 15_000;
const ALLOWED_ARCHIVE_CONTENT_TYPES = new Set(["application/zip", "application/octet-stream", "binary/octet-stream"]);
export class SandOnePasswordCliError extends Error {}
export interface RuntimeProcessOptions { signal: AbortSignal; timeoutMs: number; maxBufferBytes: number; env?: NodeJS.ProcessEnv }
export type RuntimeProcess = (file: string, args: readonly string[], options: RuntimeProcessOptions) => Promise<{ stdout: string; stderr: string }>;
const defaultProcess: RuntimeProcess = async (file, args, options) => await new Promise((resolve, reject) => execFile(file, [...args], { signal: options.signal, timeout: options.timeoutMs, maxBuffer: options.maxBufferBytes, windowsHide: true, env: options.env == null ? process.env : { ...options.env } }, (error, stdout, stderr) => error == null ? resolve({ stdout: stdout.toString(), stderr: stderr.toString() }) : reject(error)));
const delay = (ms: number, signal: AbortSignal): Promise<void> => new Promise((resolve, reject) => { const timer = setTimeout(resolve, ms); signal.addEventListener("abort", () => { clearTimeout(timer); reject(signal.reason); }, { once: true }); });

interface ZipEntry { name: string; compressedSize: number; size: number; compression: number; externalAttributes: number; localOffset: number }
function zipEntries(archive: Uint8Array): ZipEntry[] {
  const bytes = Buffer.from(archive.buffer, archive.byteOffset, archive.byteLength); let eocd = -1;
  for (let offset = Math.max(0, bytes.length - 65_557); offset <= bytes.length - 22; offset += 1) if (bytes.readUInt32LE(offset) === 0x06054b50) eocd = offset;
  if (eocd < 0) throw new SandOnePasswordCliError("The 1Password CLI archive is invalid.");
  const count = bytes.readUInt16LE(eocd + 10), centralSize = bytes.readUInt32LE(eocd + 12), centralOffset = bytes.readUInt32LE(eocd + 16);
  if (centralOffset + centralSize > bytes.length || count > 16) throw new SandOnePasswordCliError("The 1Password CLI archive is invalid.");
  const entries: ZipEntry[] = []; let offset = centralOffset;
  for (let index = 0; index < count; index += 1) { if (bytes.readUInt32LE(offset) !== 0x02014b50) throw new SandOnePasswordCliError("The 1Password CLI archive is invalid."); const nameLength = bytes.readUInt16LE(offset + 28), extraLength = bytes.readUInt16LE(offset + 30), commentLength = bytes.readUInt16LE(offset + 32); const name = bytes.subarray(offset + 46, offset + 46 + nameLength).toString("utf8"); entries.push({ name, compression: bytes.readUInt16LE(offset + 10), compressedSize: bytes.readUInt32LE(offset + 20), size: bytes.readUInt32LE(offset + 24), externalAttributes: bytes.readUInt32LE(offset + 38), localOffset: bytes.readUInt32LE(offset + 42) }); offset += 46 + nameLength + extraLength + commentLength; }
  return entries;
}
function extractEntry(archive: Uint8Array, entry: ZipEntry): Buffer { const bytes = Buffer.from(archive.buffer, archive.byteOffset, archive.byteLength), offset = entry.localOffset; if (bytes.readUInt32LE(offset) !== 0x04034b50) throw new SandOnePasswordCliError("The 1Password CLI archive is invalid."); const start = offset + 30 + bytes.readUInt16LE(offset + 26) + bytes.readUInt16LE(offset + 28), compressed = bytes.subarray(start, start + entry.compressedSize); const data = entry.compression === 0 ? Buffer.from(compressed) : entry.compression === 8 ? inflateRawSync(compressed) : (() => { throw new SandOnePasswordCliError("The 1Password CLI archive is invalid."); })(); if (data.length !== entry.size) throw new SandOnePasswordCliError("The 1Password CLI executable size is invalid."); return data; }
export function strictOpEntry(archive: Uint8Array): Buffer { if (archive.byteLength === 0 || archive.byteLength > MAX_ARCHIVE_BYTES) throw new SandOnePasswordCliError("The 1Password CLI archive size is invalid."); const entries = zipEntries(archive); const names = new Set(entries.map((entry) => entry.name)); if (entries.length !== 2 || !names.has("op") || !names.has("op.sig")) throw new SandOnePasswordCliError("The 1Password CLI archive has unexpected entries."); const op = entries.find((entry) => entry.name === "op")!, signature = entries.find((entry) => entry.name === "op.sig")!; if (op.size <= 0 || op.size > MAX_EXECUTABLE_BYTES) throw new SandOnePasswordCliError("The 1Password CLI archive does not contain a valid op."); if (signature.size <= 0 || signature.size > 4 * 1024) throw new SandOnePasswordCliError("The 1Password CLI archive signature entry is invalid."); const opMode = op.externalAttributes >>> 16 & 0xffff, signatureMode = signature.externalAttributes >>> 16 & 0xffff; if ((opMode & 0xf000) === 0xa000 || (signatureMode & 0xf000) === 0xa000) throw new SandOnePasswordCliError("The 1Password CLI archive entry cannot be a symlink."); return extractEntry(archive, op); }
export function versionIsBounded(raw: string): string | null { const version = raw.trim(); return /^2\.\d{1,3}\.\d{1,3}(?:[-+][0-9A-Za-z.-]{1,64})?$/.test(version) ? version : null; }

export interface OnePasswordCliRuntimeOptions { installRoot: string; launcherPath: string; launcherVerification?: "development" | "production"; platform?: NodeJS.Platform; arch?: string; systemPaths?: readonly string[]; download?: (url: string, signal: AbortSignal) => Promise<Uint8Array>; runProcess?: RuntimeProcess }
export class SandOnePasswordCliRuntime {
  private readonly platform: NodeJS.Platform; private readonly arch: string; private readonly systemPaths: readonly string[]; private readonly download: (url: string, signal: AbortSignal) => Promise<Uint8Array>; private readonly runProcess: RuntimeProcess;
  constructor(private readonly options: OnePasswordCliRuntimeOptions) { this.platform = options.platform ?? process.platform; this.arch = options.arch ?? process.arch; this.systemPaths = options.systemPaths ?? ONEPASSWORD_SYSTEM_CLI_PATHS; this.download = options.download ?? downloadFromOnePassword; this.runProcess = options.runProcess ?? defaultProcess; }
  get managedPath(): string { return join(this.options.installRoot, `v${MANAGED_ONEPASSWORD_CLI_VERSION}`, this.artifactArch(), "op"); }
  async resolveVerifiedLauncherPath(signal: AbortSignal): Promise<string> { if (this.platform !== "darwin") throw new SandOnePasswordCliError("The secure 1Password launcher is supported on macOS only."); await fs.access(this.options.launcherPath, fsConstants.X_OK); const resolved = await fs.realpath(this.options.launcherPath); const requirement = this.options.launcherVerification === "development" ? SAND_OP_LAUNCHER_IDENTIFIER_REQUIREMENT : SAND_OP_LAUNCHER_CODESIGN_REQUIREMENT; await this.runProcess("/usr/bin/codesign", ["--verify", "--strict", "--verbose=4", `-R=${requirement}`, resolved], { signal, timeoutMs: VERIFY_TIMEOUT_MS, maxBufferBytes: MAX_PROCESS_OUTPUT_BYTES }); return resolved; }
  async inspect(signal: AbortSignal): Promise<CliInspection> { if (this.platform !== "darwin") return { platformSupported: false, selected: null, candidates: [], detail: "Managed 1Password CLI is supported on macOS only" }; const launcherPath = await this.resolveVerifiedLauncherPath(signal); const candidates = await Promise.all([...this.systemPaths.map((path) => [path, "system"] as const), [this.managedPath, "managed"] as const].map(async ([path, source]) => await this.inspectCandidate(path, source, launcherPath, signal))); const ready = candidates.filter((candidate) => candidate.state === "ready"); const selected = ready.find((candidate) => candidate.source === "system") ?? ready.find((candidate) => candidate.source === "managed") ?? null; return { platformSupported: true, selected, candidates, detail: selected == null ? "No verified 1Password CLI is ready" : `${selected.source === "system" ? "System" : "Managed"} CLI ready` }; }
  async prepareManaged(signal: AbortSignal): Promise<CliInspection> { const installation = await this.ensureManagedInstalled(signal); return await this.inspect(installation.committed ? new AbortController().signal : signal); }
  async resolveVerifiedPath(signal: AbortSignal, options: { prepareManaged: boolean }): Promise<string> { const inspected = await this.inspect(signal); if (inspected.selected != null) return inspected.selected.path; if (!options.prepareManaged) throw new SandOnePasswordCliError("No verified 1Password CLI is ready."); return (await this.ensureManagedInstalled(signal)).path; }
  async verify(path: string, signal: AbortSignal): Promise<void> { if (this.platform !== "darwin") throw new SandOnePasswordCliError("Managed 1Password CLI is supported on macOS only."); await this.runProcess("/usr/bin/codesign", ["--verify", "--strict", "--verbose=4", `-R=${ONEPASSWORD_CODESIGN_REQUIREMENT}`, await fs.realpath(path)], { signal, timeoutMs: VERIFY_TIMEOUT_MS, maxBufferBytes: MAX_PROCESS_OUTPUT_BYTES }); }
  private async inspectCandidate(path: string, source: "system" | "managed", launcherPath: string, signal: AbortSignal): Promise<CliCandidate> { try { await fs.access(path, fsConstants.X_OK); } catch { return { source, path, state: "missing" }; } try { const version = await this.readVersion(path, launcherPath, signal); if (version == null || source === "managed" && version !== MANAGED_ONEPASSWORD_CLI_VERSION) return { source, path, state: "invalid" }; return { source, path, state: "ready", version, signature: "verified" }; } catch (error) { if (signal.aborted) throw error; return { source, path, state: "invalid" }; } }
  private async readVersion(path: string, launcherPath: string, signal: AbortSignal): Promise<string | null> { const result = await this.runProcess(launcherPath, [await fs.realpath(path), "--version"], { signal, timeoutMs: VERSION_TIMEOUT_MS, maxBufferBytes: MAX_PROCESS_OUTPUT_BYTES, env: scrubbedOnePasswordEnvironment() }); return versionIsBounded(result.stdout); }
  private async ensureManagedInstalled(signal: AbortSignal): Promise<{ path: string; committed: boolean }> { const destination = this.managedPath, launcherPath = await this.resolveVerifiedLauncherPath(signal); try { await fs.access(destination, fsConstants.X_OK); await this.verify(destination, signal); if (await this.readVersion(destination, launcherPath, signal) === MANAGED_ONEPASSWORD_CLI_VERSION) return { path: destination, committed: false }; } catch (error) { if (signal.aborted) throw error; } const directory = dirname(destination); await fs.mkdir(directory, { recursive: true, mode: 0o700 }); await fs.chmod(this.options.installRoot, 0o700); await fs.chmod(directory, 0o700); const downloadController = new AbortController(), deadlineController = new AbortController(); const download = this.download(this.artifactUrl(this.artifactArch()), AbortSignal.any([signal, downloadController.signal])).then((archive) => ({ kind: "download" as const, archive }), (error: unknown) => ({ kind: "error" as const, error })); const deadline = delay(DOWNLOAD_TIMEOUT_MS, deadlineController.signal).then(() => ({ kind: "timeout" as const })); const outcome = await Promise.race([download, deadline]).finally(() => deadlineController.abort()); if (outcome.kind === "timeout") { const error = new DOMException("1Password CLI download timed out", "TimeoutError"); downloadController.abort(error); throw error; } if (outcome.kind === "error") throw outcome.error; const executable = strictOpEntry(outcome.archive), temporaryPath = join(directory, `.op-${process.pid}-${randomUUID()}`); try { const file = await fs.open(temporaryPath, "wx", 0o700); try { await file.writeFile(executable); await file.sync(); } finally { await file.close(); } await fs.chmod(temporaryPath, 0o700); await this.verify(temporaryPath, signal); if (await this.readVersion(temporaryPath, launcherPath, signal) !== MANAGED_ONEPASSWORD_CLI_VERSION) throw new SandOnePasswordCliError(`The managed 1Password CLI did not report version ${MANAGED_ONEPASSWORD_CLI_VERSION}.`); signal.throwIfAborted(); await fs.rename(temporaryPath, destination); const committedSignal = new AbortController().signal; await fs.chmod(destination, 0o700); await this.verify(destination, committedSignal); return { path: destination, committed: true }; } finally { await fs.rm(temporaryPath, { force: true }); } }
  artifactArch(): "arm64" | "amd64" { if (this.platform !== "darwin") throw new SandOnePasswordCliError("Managed 1Password CLI is supported on macOS only."); if (this.arch === "arm64") return "arm64"; if (this.arch === "x64") return "amd64"; throw new SandOnePasswordCliError("Unsupported macOS architecture."); }
  artifactUrl(arch: "arm64" | "amd64"): string { return `https://cache.agilebits.com/dist/1P/op2/pkg/v${MANAGED_ONEPASSWORD_CLI_VERSION}/op_darwin_${arch}_v${MANAGED_ONEPASSWORD_CLI_VERSION}.zip`; }
}
export async function downloadFromOnePassword(rawUrl: string, signal: AbortSignal): Promise<Uint8Array> { const url = new URL(rawUrl), expected = new Set([`/dist/1P/op2/pkg/v${MANAGED_ONEPASSWORD_CLI_VERSION}/op_darwin_arm64_v${MANAGED_ONEPASSWORD_CLI_VERSION}.zip`, `/dist/1P/op2/pkg/v${MANAGED_ONEPASSWORD_CLI_VERSION}/op_darwin_amd64_v${MANAGED_ONEPASSWORD_CLI_VERSION}.zip`]); if (url.protocol !== "https:" || url.hostname !== "cache.agilebits.com" || url.port !== "" || url.username !== "" || url.password !== "" || url.search !== "" || url.hash !== "" || !expected.has(url.pathname)) throw new SandOnePasswordCliError("The 1Password CLI download URL is not vendor-owned."); const response = await fetch(url, { redirect: "error", signal }); if (!response.ok) { await response.body?.cancel().catch(() => undefined); throw new SandOnePasswordCliError(`The 1Password CLI download failed with HTTP ${response.status}.`); } const contentType = response.headers.get("content-type")?.split(";", 1)[0]?.trim().toLowerCase(); if (contentType == null || !ALLOWED_ARCHIVE_CONTENT_TYPES.has(contentType)) { await response.body?.cancel().catch(() => undefined); throw new SandOnePasswordCliError("The 1Password CLI download type could not be verified."); } const length = Number(response.headers.get("content-length")); if (!Number.isSafeInteger(length) || length <= 0 || length > MAX_ARCHIVE_BYTES) { await response.body?.cancel().catch(() => undefined); throw new SandOnePasswordCliError("The 1Password CLI download size could not be verified."); } if (response.body == null) throw new SandOnePasswordCliError("The 1Password CLI download body was missing."); const reader = response.body.getReader(), archive = new Uint8Array(length); let received = 0; for (;;) { const next = await reader.read(); if (next.done) break; const end = received + next.value.byteLength; if (end > MAX_ARCHIVE_BYTES || end > length) { await reader.cancel(); throw new SandOnePasswordCliError("The 1Password CLI download was unexpectedly large."); } archive.set(next.value, received); received = end; } if (received !== length) throw new SandOnePasswordCliError("The 1Password CLI download size did not match."); return archive; }
