import { OnePasswordProvisioningError } from "./onepassword-provisioning-contract.js";
import { classifyOnePasswordProcessFailure, classifyOnePasswordRuntimeFailure, createOnePasswordOpExecutor, type OnePasswordOpExecutor } from "./onepassword-op-executor.js";

export const MINIMUM_SUPPORTED_VERSION = [2, 35, 0] as const; export const MAX_JSON_OUTPUT_BYTES = 1024 * 1024; export const MAX_TOKEN_OUTPUT_BYTES = 16 * 1024;
export interface CliCandidate { source: "system" | "managed"; path: string; state: "ready" | "missing" | "invalid"; version?: string; signature?: "verified" }
export interface CliInspection { platformSupported: boolean; selected: CliCandidate | null; candidates: CliCandidate[]; detail: string }
export interface OnePasswordRuntimePort { inspect(signal: AbortSignal): Promise<CliInspection>; prepareManaged(signal: AbortSignal): Promise<CliInspection>; resolveVerifiedLauncherPath(signal: AbortSignal): Promise<string> }
export interface ProvisioningSink { availability: "available" | "unavailable"; accept(request: Record<string, unknown>, signal: AbortSignal): Promise<{ consumerReference: string }> }
export interface OnePasswordAccount { accountUuid: string; email: string; url: string } export interface OnePasswordVault { vaultId: string; vaultName: string }
const MAX_ACCOUNTS = 50, MAX_VAULTS = 1_000, MAX_PROVIDER_ID_LENGTH = 256, MAX_NAME_LENGTH = 256, MAX_EMAIL_LENGTH = 320, MAX_URL_LENGTH = 2_048, MAX_CONSUMER_REFERENCE_LENGTH = 256;
const READ_TIMEOUT_MS = 30_000, AUTHORIZED_TIMEOUT_MS = 180_000, SINK_TIMEOUT_MS = 30_000, MIN_EXPIRATION_SECONDS = 60, MAX_EXPIRATION_SECONDS = 365 * 24 * 60 * 60;
const unavailableSink: ProvisioningSink = { availability: "unavailable", async accept() { throw new OnePasswordProvisioningError("sink-unavailable", "1Password provisioning is unavailable until a credential consumer is configured."); } };
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value != null && !Array.isArray(value);
export function parseVersion(version: string): number[] | null { if (!/^\d+\.\d+\.\d+$/.test(version)) return null; const parsed = version.split(".").map((part) => Number.parseInt(part, 10)); return parsed.every(Number.isSafeInteger) ? parsed : null; }
export function versionAtLeast(version: readonly number[], minimum: readonly number[]): boolean { for (let index = 0; index < minimum.length; index += 1) { const have = version[index] ?? 0, want = minimum[index] ?? 0; if (have > want) return true; if (have < want) return false; } return true; }
export function selectSupportedCandidate(inspection: CliInspection): CliCandidate | null { const ready = inspection.candidates.filter((candidate) => candidate.state === "ready"); if (inspection.selected != null && !ready.some((candidate) => candidate.path === inspection.selected?.path)) ready.unshift(inspection.selected); const supported = (candidate: CliCandidate) => candidate.version != null && parseVersion(candidate.version) != null && versionAtLeast(parseVersion(candidate.version)!, MINIMUM_SUPPORTED_VERSION); return ready.find((candidate) => candidate.source === "system" && supported(candidate)) ?? ready.find((candidate) => candidate.source === "managed" && supported(candidate)) ?? null; }
const boundedMetadata = (value: unknown, max: number): string | null => { if (typeof value !== "string") return null; const bounded = value.trim(); return bounded.length > 0 && bounded.length <= max ? bounded : null; };
const providerIdentifier = (value: unknown, field: string): string => { if (typeof value !== "string" || !/^[A-Za-z0-9_.-]+$/.test(value) || value.length > MAX_PROVIDER_ID_LENGTH) throw new OnePasswordProvisioningError("invalid-input", `The ${field} is invalid.`); return value; };
const boundedName = (value: unknown, field: string): string => { const name = typeof value === "string" ? value.trim() : ""; if (name.length === 0 || name.length > MAX_NAME_LENGTH || name.startsWith("-") || /[\u0000-\u001f\u007f]/.test(name)) throw new OnePasswordProvisioningError("invalid-input", `The ${field} is invalid.`); return name; };
const safeAccountUrl = (value: unknown): string | null => { const raw = boundedMetadata(value, MAX_URL_LENGTH); if (raw == null) return null; try { const url = new URL(/^[A-Za-z][A-Za-z0-9+.-]*:/.test(raw) ? raw : `https://${raw}`); return url.protocol === "https:" && url.hostname !== "" && url.username === "" && url.password === "" ? url.toString() : null; } catch { return null; } };
export function parseAccounts(value: unknown): OnePasswordAccount[] { if (!Array.isArray(value) || value.length > MAX_ACCOUNTS) throw new OnePasswordProvisioningError("invalid-output", "1Password returned an invalid account list."); const output: OnePasswordAccount[] = [], seen = new Set<string>(); for (const entry of value) { if (!isRecord(entry)) throw new OnePasswordProvisioningError("invalid-output", "1Password returned an invalid account list."); const accountUuid = boundedMetadata(entry.account_uuid, MAX_PROVIDER_ID_LENGTH), email = boundedMetadata(entry.email, MAX_EMAIL_LENGTH), url = safeAccountUrl(entry.url); if (accountUuid == null || !/^[A-Za-z0-9_.-]+$/.test(accountUuid) || email == null || url == null || seen.has(accountUuid)) throw new OnePasswordProvisioningError("invalid-output", "1Password returned an invalid account list."); seen.add(accountUuid); output.push({ accountUuid, email, url }); } return output; }
export function parseVaults(value: unknown): OnePasswordVault[] { if (!Array.isArray(value) || value.length > MAX_VAULTS) throw new OnePasswordProvisioningError("invalid-output", "1Password returned an invalid vault list."); const output: OnePasswordVault[] = [], seen = new Set<string>(); for (const entry of value) { if (!isRecord(entry)) throw new OnePasswordProvisioningError("invalid-output", "1Password returned an invalid vault list."); const vaultId = boundedMetadata(entry.id, MAX_PROVIDER_ID_LENGTH), vaultName = boundedMetadata(entry.name, MAX_NAME_LENGTH); if (vaultId == null || !/^[A-Za-z0-9_.-]+$/.test(vaultId) || vaultName == null || seen.has(vaultId)) throw new OnePasswordProvisioningError("invalid-output", "1Password returned an invalid vault list."); seen.add(vaultId); output.push({ vaultId, vaultName }); } return output; }
const parseCreatedVault = (value: unknown): OnePasswordVault => { if (!isRecord(value)) throw new OnePasswordProvisioningError("invalid-output", "1Password did not return the created vault."); const vaultId = boundedMetadata(value.id, MAX_PROVIDER_ID_LENGTH), vaultName = boundedMetadata(value.name, MAX_NAME_LENGTH); if (vaultId == null || !/^[A-Za-z0-9_.-]+$/.test(vaultId) || vaultName == null) throw new OnePasswordProvisioningError("invalid-output", "1Password did not return the created vault."); return { vaultId, vaultName }; };
const validToken = (stdout: string): string => { const token = stdout.trim(); if (token.length === 0 || token.length > MAX_TOKEN_OUTPUT_BYTES || !/^ops_[A-Za-z0-9_-]+$/.test(token)) throw new OnePasswordProvisioningError("invalid-output", "1Password did not return a valid service-account credential."); return token; };
export function scrubbedOnePasswordEnvironment(env: NodeJS.ProcessEnv = process.env): NodeJS.ProcessEnv { const scrubbed: NodeJS.ProcessEnv = {}; for (const [key, value] of Object.entries(env)) if (value != null && !key.startsWith("OP_")) scrubbed[key] = value; return { ...scrubbed, OP_CACHE: "false", OP_BIOMETRIC_UNLOCK_ENABLED: "true", OP_LOAD_DESKTOP_APP_SETTINGS: "false" }; }

export class OnePasswordDesktopProvisioningBridge {
  private mutationInProgress = false; private deliveryIndeterminate = false; private readonly executor: OnePasswordOpExecutor; private readonly sink: ProvisioningSink; private readonly prepareManagedCli: boolean;
  constructor(private readonly options: { runtime: OnePasswordRuntimePort; sink?: ProvisioningSink; executor?: OnePasswordOpExecutor; prepareManagedCli?: boolean }) { this.executor = options.executor ?? createOnePasswordOpExecutor(); this.sink = options.sink ?? unavailableSink; this.prepareManagedCli = options.prepareManagedCli ?? true; }
  async inspectReadiness(signal: AbortSignal) { const inspection = await this.options.runtime.inspect(signal).catch((error: unknown) => { throw classifyOnePasswordRuntimeFailure(error); }); if (!inspection.platformSupported) return { state: "unsupported-platform" as const }; const selected = selectSupportedCandidate(inspection); if (selected?.version != null) return { state: "ready" as const, source: selected.source, path: selected.path, version: selected.version }; return inspection.selected == null ? { state: "missing-cli" as const } : { state: "unsupported-version" as const, version: inspection.selected.version }; }
  async listAccounts(signal: AbortSignal): Promise<OnePasswordAccount[]> { return parseAccounts(await this.runJson(["account", "list", "--format=json"], READ_TIMEOUT_MS, signal)); }
  async listVaults(request: { accountUuid: string }, signal: AbortSignal): Promise<OnePasswordVault[]> { const id = providerIdentifier(request.accountUuid, "1Password account identifier"); return parseVaults(await this.runJson(["vault", "list", "--account", id, "--format=json"], READ_TIMEOUT_MS, signal)); }
  async findVault(request: { accountUuid: string; vaultName: string }, signal: AbortSignal): Promise<OnePasswordVault | null> { const wanted = boundedName(request.vaultName, "vault name"); const matches = (await this.listVaults(request, signal)).filter((vault) => vault.vaultName === wanted); if (matches.length > 1) throw new OnePasswordProvisioningError("conflict", "More than one 1Password vault has the requested name."); return matches[0] ?? null; }
  async createVault(request: { accountUuid: string; vaultName: string }, signal: AbortSignal): Promise<OnePasswordVault> { this.assertSinkAvailable(); const id = providerIdentifier(request.accountUuid, "1Password account identifier"), name = boundedName(request.vaultName, "vault name"); return await this.runMutation(signal, async (mutationSignal) => parseCreatedVault(await this.runJson(["vault", "create", name, "--account", id, "--format=json"], AUTHORIZED_TIMEOUT_MS, mutationSignal))); }
  async mintAndDeliver(request: { accountUuid: string; vaultId: string; serviceAccountName: string; expiresInSeconds: number }, signal: AbortSignal): Promise<{ consumerReference: string; expiresInSeconds: number }> { this.assertSinkAvailable(); const accountUuid = providerIdentifier(request.accountUuid, "1Password account identifier"), vaultId = providerIdentifier(request.vaultId, "1Password vault identifier"), name = boundedName(request.serviceAccountName, "service-account name"), expires = request.expiresInSeconds; if (!Number.isSafeInteger(expires) || expires < MIN_EXPIRATION_SECONDS || expires > MAX_EXPIRATION_SECONDS) throw new OnePasswordProvisioningError("invalid-input", "The provisioning policy returned an invalid expiration duration."); return await this.runMutation(signal, async (mutationSignal) => { const account = (await this.listAccounts(mutationSignal)).find((item) => item.accountUuid === accountUuid); if (account == null) throw new OnePasswordProvisioningError("invalid-input", "The selected 1Password account is unavailable."); const vault = (await this.listVaults({ accountUuid }, mutationSignal)).find((item) => item.vaultId === vaultId); if (vault == null) throw new OnePasswordProvisioningError("permission", "The selected 1Password vault is unavailable to this account."); const token = validToken((await this.runOp(["service-account", "create", name, "--account", accountUuid, "--vault", `${vaultId}:read_items`, "--expires-in", `${expires}s`, "--raw"], AUTHORIZED_TIMEOUT_MS, MAX_TOKEN_OUTPUT_BYTES, mutationSignal)).stdout); const sinkController = new AbortController(); let timer: NodeJS.Timeout | undefined; try { const timeout = new Promise<never>((_, reject) => { timer = setTimeout(() => { sinkController.abort(new DOMException("Provisioning sink timed out", "TimeoutError")); reject(new DOMException("Provisioning sink timed out", "TimeoutError")); }, SINK_TIMEOUT_MS); }); const receipt = await Promise.race([this.sink.accept({ accountUuid, accountUrl: account.url, vaultId, vaultName: vault.vaultName, serviceAccountName: name, expiresInSeconds: expires, token }, sinkController.signal), timeout]); const consumerReference = boundedMetadata(receipt.consumerReference, MAX_CONSUMER_REFERENCE_LENGTH); if (consumerReference == null) throw new Error("invalid receipt"); return { consumerReference, expiresInSeconds: expires }; } catch { this.deliveryIndeterminate = true; throw new OnePasswordProvisioningError("delivery-indeterminate", "The credential delivery outcome is unknown and must be reconciled before provisioning again."); } finally { if (timer != null) clearTimeout(timer); } }); }
  private assertSinkAvailable(): void { if (this.sink.availability !== "available") throw new OnePasswordProvisioningError("sink-unavailable", "1Password provisioning is unavailable until a credential consumer is configured."); }
  private async runMutation<T>(signal: AbortSignal, operation: (signal: AbortSignal) => Promise<T>): Promise<T> { if (this.deliveryIndeterminate) throw new OnePasswordProvisioningError("delivery-indeterminate", "The previous credential delivery must be reconciled before provisioning again."); if (this.mutationInProgress) throw new OnePasswordProvisioningError("busy", "A 1Password provisioning operation is already running."); this.mutationInProgress = true; try { if (signal.aborted) throw new OnePasswordProvisioningError("cancelled", "The 1Password operation was canceled."); return await operation(signal); } finally { this.mutationInProgress = false; } }
  private async runJson(args: string[], timeoutMs: number, signal: AbortSignal): Promise<unknown> { const result = await this.runOp(args, timeoutMs, MAX_JSON_OUTPUT_BYTES, signal); try { return JSON.parse(result.stdout) as unknown; } catch { throw new OnePasswordProvisioningError("invalid-output", "1Password returned malformed JSON."); } }
  private async runOp(args: string[], timeoutMs: number, maxBufferBytes: number, signal: AbortSignal) { const opPath = await this.resolveSupportedPath(signal); let launcherPath: string; try { launcherPath = await this.options.runtime.resolveVerifiedLauncherPath(signal); } catch (error) { throw classifyOnePasswordRuntimeFailure(error); } try { return await this.executor(launcherPath, [opPath, ...args], { signal, timeoutMs, maxBufferBytes, env: scrubbedOnePasswordEnvironment() }); } catch (error) { throw classifyOnePasswordProcessFailure(error); } }
  private async resolveSupportedPath(signal: AbortSignal): Promise<string> { let readiness = await this.inspectReadiness(signal); if (readiness.state === "ready") return readiness.path; if ((readiness.state === "missing-cli" || readiness.state === "unsupported-version") && this.prepareManagedCli && !signal.aborted) { try { await this.options.runtime.prepareManaged(signal); } catch (error) { throw classifyOnePasswordRuntimeFailure(error); } readiness = await this.inspectReadiness(signal); if (readiness.state === "ready") return readiness.path; } if (readiness.state === "unsupported-platform") throw new OnePasswordProvisioningError("unsupported-platform", "1Password desktop provisioning is supported on macOS only."); if (readiness.state === "unsupported-version") throw new OnePasswordProvisioningError("unsupported-version", "The detected 1Password CLI does not support expiring service accounts."); throw new OnePasswordProvisioningError("missing-cli", "No verified 1Password CLI is ready."); }
}
