import { execFile } from "node:child_process";
import { OnePasswordProvisioningError } from "./onepassword-provisioning-contract.js";

export type OnePasswordFailureKind = "denied" | "integration-off" | "permission" | "conflict" | "timeout" | "unknown";
export class OnePasswordProcessError extends Error {
  constructor(readonly processCode: unknown, readonly killed: boolean, readonly failureKind: OnePasswordFailureKind) { super("The 1Password CLI command failed."); this.name = "OnePasswordProcessError"; }
}
export interface OnePasswordProcessOptions { signal: AbortSignal; timeoutMs: number; maxBufferBytes: number; env: NodeJS.ProcessEnv }
export type OnePasswordOpExecutor = (file: string, args: readonly string[], options: OnePasswordProcessOptions) => Promise<{ stdout: string; stderr: string }>;
export function onePasswordFailureKind(raw: string): OnePasswordFailureKind { const text = raw.toLowerCase(); if (["authorization prompt dismissed", "request was denied", "authorization denied", "rejected"].some((part) => text.includes(part))) return "denied"; if (["connecting to desktop app", "desktop app not running", "cli is not enabled", "couldn't connect to the 1password app", "no accounts configured"].some((part) => text.includes(part))) return "integration-off"; if (["permission", "not allowed", "(403)", "forbidden"].some((part) => text.includes(part))) return "permission"; if (["already exists", "(409)", "conflict"].some((part) => text.includes(part))) return "conflict"; if (text.includes("etimedout") || text.includes("timed out")) return "timeout"; return "unknown"; }
export function createOnePasswordOpExecutor(): OnePasswordOpExecutor { return async (file, args, options) => await new Promise((resolve, reject) => { execFile(file, [...args], { signal: options.signal, timeout: options.timeoutMs, maxBuffer: options.maxBufferBytes, windowsHide: true, env: { ...options.env } }, (error, stdout, stderr) => { if (error != null) { reject(new OnePasswordProcessError(Reflect.get(error, "code"), Reflect.get(error, "killed") === true, onePasswordFailureKind(`${error.message}\n${stderr.toString()}`))); return; } resolve({ stdout: stdout.toString(), stderr: stderr.toString() }); }); }); }
export function classifyOnePasswordProcessFailure(error: unknown): OnePasswordProvisioningError { if (error instanceof OnePasswordProvisioningError) return error; if (error instanceof DOMException && (error.name === "AbortError" || error.name === "TimeoutError")) return new OnePasswordProvisioningError(error.name === "AbortError" ? "cancelled" : "timeout", error.name === "AbortError" ? "The 1Password operation was canceled." : "The 1Password operation timed out."); const processError = error instanceof OnePasswordProcessError ? error : undefined; const processCode = processError?.processCode ?? (typeof error === "object" && error != null ? Reflect.get(error, "code") : undefined); const killed = processError?.killed ?? (typeof error === "object" && error != null && Reflect.get(error, "killed") === true); if (processCode === "ENOENT") return new OnePasswordProvisioningError("missing-cli", "The secure 1Password CLI runtime is unavailable."); if (processCode === "ABORT_ERR") return new OnePasswordProvisioningError("cancelled", "The 1Password operation was canceled."); const kind = processError?.failureKind ?? onePasswordFailureKind(error instanceof Error ? error.message : ""); if (killed || kind === "timeout") return new OnePasswordProvisioningError("timeout", "The 1Password desktop app did not respond in time."); const messages: Partial<Record<OnePasswordFailureKind, [string, string]>> = { denied: ["denied", "The request was not approved in the 1Password desktop app."], "integration-off": ["integration-off", "1Password desktop CLI integration is unavailable."], permission: ["permission", "The selected 1Password account does not allow this operation."], conflict: ["conflict", "The requested 1Password object already exists."] }; const mapped = messages[kind]; return mapped == null ? new OnePasswordProvisioningError("op-error", "The secure 1Password CLI operation failed.") : new OnePasswordProvisioningError(mapped[0], mapped[1]); }
export function classifyOnePasswordRuntimeFailure(error: unknown): OnePasswordProvisioningError { if (error instanceof OnePasswordProvisioningError) return error; if (error instanceof DOMException && (error.name === "AbortError" || error.name === "TimeoutError")) return new OnePasswordProvisioningError(error.name === "AbortError" ? "cancelled" : "timeout", error.name === "AbortError" ? "The 1Password operation was canceled." : "The secure 1Password runtime verification timed out."); const code = typeof error === "object" && error != null ? Reflect.get(error, "code") : undefined; if (code === "ABORT_ERR") return new OnePasswordProvisioningError("cancelled", "The 1Password operation was canceled."); if (code === "ENOENT") return new OnePasswordProvisioningError("missing-cli", "The secure 1Password CLI runtime is unavailable."); return new OnePasswordProvisioningError("op-error", "The secure 1Password runtime failed verification."); }
