import { createHash } from "node:crypto";
import type { FileHandle } from "node:fs/promises";
import type { Stats } from "node:fs";

export class TranscriptOccurrenceConflictError extends Error { override name = "TranscriptOccurrenceConflictError"; }
export class TranscriptJournalCorruptionError extends Error { override name = "TranscriptJournalCorruptionError"; }
export class TranscriptJournalWriteError extends Error { override name = "TranscriptJournalWriteError"; }
export interface TranscriptCheckpoint { turns: readonly Uint8Array[] }
export interface DeferredTranscriptStep { turnIndex: number; stepIndex: number }
export interface PendingTranscriptCheckpoint { version: 1; previousCheckpointHash: string; checkpointHash: string; appendOffset: number; fileDevice: string; fileInode: string; lines: string[]; cursor: { turnCount: number; deferredStep?: DeferredTranscriptStep } }
export function sha256(value: string | NodeJS.ArrayBufferView): string { return createHash("sha256").update(value).digest("hex"); }
export function bytesEqual(left: Uint8Array, right: Uint8Array): boolean { return Buffer.from(left).equals(Buffer.from(right)); }
export function checkpointIdentity(checkpoint: TranscriptCheckpoint): string { const hex = (index: number) => { const turn = checkpoint.turns.at(index); return turn == null ? "" : Buffer.from(turn).toString("hex"); }; return sha256(`${checkpoint.turns.length}:${hex(-2)}:${hex(-1)}`); }
export function isMissingFile(error: unknown): boolean { return error instanceof Error && "code" in error && error.code === "ENOENT"; }
export function fileIdentity(stats: Stats | { size: number | bigint; dev: number | bigint; ino: number | bigint }) { return { size: Number(stats.size), device: String(stats.dev), inode: String(stats.ino) }; }
export function parseDeferredStep(value: unknown): DeferredTranscriptStep | undefined { if (value == null) return undefined; if (typeof value !== "object" || Array.isArray(value)) throw new TranscriptJournalCorruptionError("transcript deferred cursor is invalid"); const { turnIndex, stepIndex } = value as Record<string, unknown>; if (typeof turnIndex !== "number" || !Number.isSafeInteger(turnIndex) || turnIndex < 0 || typeof stepIndex !== "number" || !Number.isSafeInteger(stepIndex) || stepIndex < 0) throw new TranscriptJournalCorruptionError("transcript deferred cursor is invalid"); return { turnIndex, stepIndex }; }
export function parsePendingCheckpoint(raw: string): PendingTranscriptCheckpoint { let parsed: unknown; try { parsed = JSON.parse(raw); } catch (error) { throw new TranscriptJournalCorruptionError("pending transcript checkpoint is not valid JSON", { cause: error }); } if (parsed == null || typeof parsed !== "object" || Array.isArray(parsed)) throw new TranscriptJournalCorruptionError("pending transcript checkpoint is not an object"); const record = parsed as Record<string, unknown>, cursor = record.cursor; const hash = (value: unknown) => typeof value === "string" && /^[0-9a-f]{64}$/.test(value); if (record.version !== 1 || !hash(record.previousCheckpointHash) || !hash(record.checkpointHash) || typeof record.appendOffset !== "number" || !Number.isSafeInteger(record.appendOffset) || record.appendOffset < 0 || typeof record.fileDevice !== "string" || typeof record.fileInode !== "string" || !Array.isArray(record.lines) || cursor == null || typeof cursor !== "object" || Array.isArray(cursor)) throw new TranscriptJournalCorruptionError("pending transcript checkpoint metadata is invalid"); const lines = record.lines.map(line => { if (typeof line !== "string") throw new TranscriptJournalCorruptionError("pending transcript line is invalid"); let value: unknown; try { value = JSON.parse(line); } catch { throw new TranscriptJournalCorruptionError("pending transcript line is invalid"); } if (value == null || typeof value !== "object" || Array.isArray(value) || !("role" in value) || !("message" in value)) throw new TranscriptJournalCorruptionError("pending transcript line does not use the legacy message envelope"); return line; }); const cursorRecord = cursor as Record<string, unknown>; if (typeof cursorRecord.turnCount !== "number" || !Number.isSafeInteger(cursorRecord.turnCount) || cursorRecord.turnCount < 0) throw new TranscriptJournalCorruptionError("pending transcript checkpoint cursor is invalid"); const deferredStep = parseDeferredStep(cursorRecord.deferredStep); return { version: 1, previousCheckpointHash: record.previousCheckpointHash as string, checkpointHash: record.checkpointHash as string, appendOffset: record.appendOffset, fileDevice: record.fileDevice, fileInode: record.fileInode, lines, cursor: { turnCount: cursorRecord.turnCount, ...(deferredStep === undefined ? {} : { deferredStep }) } }; }
export async function writeAll(handle: FileHandle, bytes: Uint8Array, position: number): Promise<number> { let written = 0; while (written < bytes.byteLength) { const result = await handle.write(bytes, written, bytes.byteLength - written, position + written); if (result.bytesWritten === 0) throw new TranscriptJournalWriteError("transcript JSONL write made no progress"); written += result.bytesWritten; } return position + written; }
export function formatTextLine(role: "user" | "assistant", text: string): string | null { if (text.length === 0) return null; return JSON.stringify({ role, message: { content: [{ type: "text", text }] } }); }
export function formatToolLine(role: "assistant" | "tool", name: string, payload: unknown): string { return JSON.stringify({ role, message: { content: role === "assistant" ? [{ type: "tool_use", name, input: payload }] : [{ type: "tool_result", name, result: payload }] } }); }
