import { randomUUID } from "node:crypto";
import { mkdir, open, readFile, rename, stat, unlink } from "node:fs/promises";
import { dirname, join } from "node:path";
import { checkpointIdentity, fileIdentity, isMissingFile, parseDeferredStep, parsePendingCheckpoint, TranscriptJournalCorruptionError, writeAll, type DeferredTranscriptStep, type PendingTranscriptCheckpoint, type TranscriptCheckpoint } from "./transcript-journal-codec.js";
import { RoutedTranscriptMirror, type LegacyMirrorPort } from "./transcript-mirror-router.js";
import { SandError } from "../../shared/errors/registry.js";
import { brandedErrno } from "../../shared/errors/bounded.js";

const writeLanes = new Map<string, Promise<unknown>>();
function safeId(id: string): string { if (/^[A-Za-z0-9._-]+$/.test(id) && id !== "." && id !== "..") return id; throw new TranscriptJournalCorruptionError("unsafe conversation id"); }
export interface TranscriptOccurrence { id: string; line: string }
export interface TranscriptDeriver<Store> { derive(ctx: unknown, store: Store, previous: TranscriptCheckpoint, checkpoint: TranscriptCheckpoint, finalize: boolean, deferred?: DeferredTranscriptStep): Promise<{ occurrences: readonly TranscriptOccurrence[]; deferredStep?: DeferredTranscriptStep }>; initial(ctx: unknown, store: Store, checkpoint: TranscriptCheckpoint): Promise<readonly TranscriptOccurrence[]> }
export interface JournalOutcome { op: string; outcome: "ok" | "failed"; conversationId: string; entryCount?: number; bytes?: number; durationMs: number; cause?: unknown }
interface FileState { bytes: number; device: string; inode: string }

export class FileTranscriptMirror<Store = unknown> {
  readonly states = new Map<string, FileState>(); readonly durableCheckpoints = new Map<string, TranscriptCheckpoint>(); readonly preparedCheckpoints = new Map<string, TranscriptCheckpoint>(); readonly deferredSteps = new Map<string, DeferredTranscriptStep>(); readonly preparedDeferredSteps = new Map<string, DeferredTranscriptStep | null>(); readonly routes = new Map<string, Promise<"journal" | "legacy">>();
  readonly reportedFailures = new WeakSet<object>();
  constructor(readonly transcriptsDir: string, readonly reportOutcome: (outcome: JournalOutcome) => void = () => {}, readonly deriver?: TranscriptDeriver<Store>) {}
  private requireDeriver(): TranscriptDeriver<Store> { if (this.deriver == null) throw new TranscriptJournalCorruptionError("transcript occurrence derivation is unavailable"); return this.deriver; }
  private async withOutcomeReport<T extends { entryCount?: number; bytes?: number } | void>(op: string, conversationId: string, mintCause: (errno?: string) => unknown, operation: () => Promise<T>): Promise<T> { const startedAt = performance.now(); try { const counts = await operation(); this.reportOutcome({ op, outcome: "ok", conversationId, ...(counts ?? {}), durationMs: performance.now() - startedAt }); return counts; } catch (error) { if (typeof error !== "object" || error == null || !this.reportedFailures.has(error)) { if (typeof error === "object" && error != null) this.reportedFailures.add(error); const code = typeof error === "object" && error != null && "code" in error && typeof error.code === "string" ? brandedErrno(error.code) : undefined; this.reportOutcome({ op, outcome: "failed", conversationId, cause: mintCause(code), durationMs: performance.now() - startedAt }); } throw error; } }
  routed(legacy: LegacyMirrorPort<TranscriptCheckpoint, Store>, enabled: () => Promise<boolean>): RoutedTranscriptMirror<TranscriptCheckpoint, Store> { return new RoutedTranscriptMirror(this, legacy, enabled, this.routes); }
  jsonlPathFor(id: string): string { const safe = safeId(id); return join(this.transcriptsDir, safe, `${safe}.jsonl`); }
  pendingPathFor(id: string): string { const safe = safeId(id); return join(this.transcriptsDir, safe, `${safe}.journal-pending.json`); }
  cursorPathFor(id: string): string { const safe = safeId(id); return join(this.transcriptsDir, safe, `${safe}.journal-cursor.json`); }
  modePathFor(id: string): string { const safe = safeId(id); return join(this.transcriptsDir, safe, `${safe}.journal-mode`); }
  private async syncParent(path: string): Promise<void> { const handle = await open(dirname(path), "r"); try { await handle.sync(); } finally { await handle.close(); } }
  private async installAtomic(path: string, bytes: Uint8Array): Promise<void> { await mkdir(dirname(path), { recursive: true }); const temporary = join(dirname(path), `.transcript.${randomUUID()}.part`); let handle; try { handle = await open(temporary, "wx"); await writeAll(handle, bytes, 0); await handle.sync(); await handle.close(); handle = undefined; await rename(temporary, path); await this.syncParent(path); } catch (error) { await handle?.close().catch(() => {}); await unlink(temporary).catch(() => {}); throw error; } }
  async ownsConversation(id: string): Promise<boolean> { try { await stat(this.modePathFor(id)); return true; } catch (error) { if (isMissingFile(error)) return false; throw error; } }
  async claimConversation(id: string): Promise<void> { const path = this.modePathFor(id); if (await this.ownsConversation(id)) return; await this.installAtomic(path, Buffer.from("1\n")); }
  private serialize<T>(id: string, operation: () => Promise<T>): Promise<T> { const key = this.jsonlPathFor(id), previous = writeLanes.get(key) ?? Promise.resolve(); const current = previous.then(operation, operation); writeLanes.set(key, current); void current.finally(() => { if (writeLanes.get(key) === current) writeLanes.delete(key); }).catch(() => {}); return current; }
  private async readPending(id: string): Promise<PendingTranscriptCheckpoint | null> { try { return parsePendingCheckpoint(await readFile(this.pendingPathFor(id), "utf8")); } catch (error) { if (isMissingFile(error)) return null; throw error; } }
  private async removePending(id: string): Promise<void> { const path = this.pendingPathFor(id); try { await unlink(path); await this.syncParent(path); } catch (error) { if (!isMissingFile(error)) throw error; } }
  private async readDeferred(id: string): Promise<DeferredTranscriptStep | undefined> { try { return parseDeferredStep(JSON.parse(await readFile(this.cursorPathFor(id), "utf8"))); } catch (error) { if (isMissingFile(error)) return undefined; throw error; } }
  private async writeDeferred(id: string, step?: DeferredTranscriptStep): Promise<void> { const path = this.cursorPathFor(id); if (step == null) { try { await unlink(path); await this.syncParent(path); } catch (error) { if (!isMissingFile(error)) throw error; } return; } await this.installAtomic(path, Buffer.from(JSON.stringify(step))); }
  private async initialize(ctx: unknown, id: string, checkpoint: TranscriptCheckpoint, store: Store): Promise<FileState> { const path = this.jsonlPathFor(id); await mkdir(dirname(path), { recursive: true }); let needsBuild = false; try { const info = await stat(path); if (info.size === 0) needsBuild = checkpoint.turns.length > 0; else { const handle = await open(path, "r"); try { const tail = Buffer.alloc(1); const result = await handle.read(tail, 0, 1, info.size - 1); needsBuild = result.bytesRead !== 1 || tail[0] !== 10; } finally { await handle.close(); } } } catch (error) { if (!isMissingFile(error)) throw error; needsBuild = true; } if (needsBuild) { const occurrences = await this.requireDeriver().initial(ctx, store, checkpoint); await this.installAtomic(path, Buffer.from(occurrences.map(entry => `${entry.line}\n`).join(""))); } const identity = fileIdentity(await stat(path)); const state = { bytes: identity.size, device: identity.device, inode: identity.inode }; this.states.set(id, state); return state; }
  private async appendPending(id: string, pending: PendingTranscriptCheckpoint): Promise<FileState> { const path = this.jsonlPathFor(id), identity = fileIdentity(await stat(path)); if (identity.device !== pending.fileDevice || identity.inode !== pending.fileInode || identity.size < pending.appendOffset) throw new TranscriptJournalCorruptionError("canonical transcript changed before WAL commit"); const expected = Buffer.from(pending.lines.map(line => `${line}\n`).join("")); const tailLength = identity.size - pending.appendOffset; if (tailLength > expected.length) throw new TranscriptJournalCorruptionError("canonical transcript has data beyond the pending WAL"); const handle = await open(path, "r+"); try { if (tailLength > 0) { const tail = Buffer.alloc(tailLength); await handle.read(tail, 0, tail.length, pending.appendOffset); if (!expected.subarray(0, tailLength).equals(tail)) throw new TranscriptJournalCorruptionError("canonical transcript tail conflicts with the pending WAL"); } if (tailLength < expected.length) { await handle.truncate(pending.appendOffset); await writeAll(handle, expected, pending.appendOffset); await handle.sync(); } const updated = fileIdentity(await handle.stat()); const state = { bytes: pending.appendOffset + expected.length, device: updated.device, inode: updated.inode }; this.states.set(id, state); return state; } finally { await handle.close(); } }
  recover(ctx: unknown, id: string, checkpoint: TranscriptCheckpoint, store: Store): Promise<unknown> { return this.serialize(id, () => this.withOutcomeReport("replay", id, errno => SandError.journalReplayFailed({ errno }), async () => { const pending = await this.readPending(id); let state = this.states.get(id); const hash = checkpointIdentity(checkpoint); if (pending != null) { if (pending.checkpointHash === hash) { state = await this.appendPending(id, pending); await this.writeDeferred(id, pending.cursor.deferredStep); await this.removePending(id); } else if (pending.previousCheckpointHash === hash) await this.removePending(id); else throw new TranscriptJournalCorruptionError("pending transcript WAL does not match the durable checkpoint"); } state ??= await this.initialize(ctx, id, checkpoint, store); this.states.set(id, state); this.durableCheckpoints.set(id, checkpoint); this.preparedCheckpoints.delete(id); this.preparedDeferredSteps.delete(id); const deferred = await this.readDeferred(id); if (deferred == null) this.deferredSteps.delete(id); else { if (checkpoint.turns[deferred.turnIndex] == null) throw new TranscriptJournalCorruptionError("deferred transcript step is absent from the durable checkpoint"); this.deferredSteps.set(id, deferred); } return {}; })); }
  prepareCheckpoint(ctx: unknown, id: string, checkpoint: TranscriptCheckpoint, store: Store, finalize = false): Promise<unknown> { return this.serialize(id, () => this.withOutcomeReport("checkpoint", id, errno => SandError.journalCheckpointFailed({ errno }), async () => { if (await this.readPending(id) != null) throw new TranscriptJournalCorruptionError("pending transcript checkpoint must recover before preparing another"); const previous = this.durableCheckpoints.get(id), state = this.states.get(id); if (previous == null || state == null) throw new TranscriptJournalCorruptionError("transcript checkpoint must recover before preparing"); const identity = fileIdentity(await stat(this.jsonlPathFor(id))); if (identity.size !== state.bytes || identity.device !== state.device || identity.inode !== state.inode) throw new TranscriptJournalCorruptionError("canonical transcript changed outside the journal"); const derived = await this.requireDeriver().derive(ctx, store, previous, checkpoint, finalize, this.deferredSteps.get(id)); const seen = new Set<string>(), lines = derived.occurrences.map(entry => { if (seen.has(entry.id)) throw new TranscriptJournalCorruptionError(`transcript occurrence ${entry.id} was derived twice`); seen.add(entry.id); return entry.line; }); const pending: PendingTranscriptCheckpoint = { version: 1, previousCheckpointHash: checkpointIdentity(previous), checkpointHash: checkpointIdentity(checkpoint), appendOffset: state.bytes, fileDevice: state.device, fileInode: state.inode, lines, cursor: { turnCount: checkpoint.turns.length, ...(derived.deferredStep == null ? {} : { deferredStep: derived.deferredStep }) } }; const bytes = Buffer.from(JSON.stringify(pending)); await this.installAtomic(this.pendingPathFor(id), bytes); this.preparedCheckpoints.set(id, checkpoint); this.preparedDeferredSteps.set(id, derived.deferredStep ?? null); return { entryCount: lines.length, bytes: bytes.byteLength }; })); }
  commitCheckpoint(_ctx: unknown, id: string): Promise<unknown> { return this.serialize(id, () => this.withOutcomeReport("append", id, errno => SandError.journalAppendFailed({ errno }), async () => { const pending = await this.readPending(id), checkpoint = this.preparedCheckpoints.get(id); if (pending == null) throw new TranscriptJournalCorruptionError("prepared transcript WAL is missing at commit"); if (checkpoint == null || !this.preparedDeferredSteps.has(id)) throw new TranscriptJournalCorruptionError("prepared transcript checkpoint is missing in memory"); const deferred = this.preparedDeferredSteps.get(id) ?? undefined, state = await this.appendPending(id, pending); await this.writeDeferred(id, deferred); await this.removePending(id); this.preparedCheckpoints.delete(id); this.preparedDeferredSteps.delete(id); this.durableCheckpoints.set(id, checkpoint); if (deferred == null) this.deferredSteps.delete(id); else this.deferredSteps.set(id, deferred); return { entryCount: pending.lines.length, bytes: state.bytes - pending.appendOffset }; })); }
  abortCheckpoint(_ctx: unknown, id: string): Promise<void> { return this.serialize(id, async () => { this.preparedCheckpoints.delete(id); this.preparedDeferredSteps.delete(id); await this.removePending(id); }); }
  skipCheckpoint(_ctx: unknown, id: string, checkpoint: TranscriptCheckpoint, _store: Store): Promise<void> { return this.serialize(id, async () => { this.preparedCheckpoints.delete(id); this.preparedDeferredSteps.delete(id); this.deferredSteps.delete(id); await this.removePending(id); await this.writeDeferred(id); this.durableCheckpoints.set(id, checkpoint); }); }
}
