/** Mechanically recovered from the immutable 0.18 host bundle. */
type GatewayApi = any;
export function parseCommandArgs(body: string): unknown { return body.length > 0 ? JSON.parse(body) : {}; }
export const SAND_GATEWAY_COMMANDS = {
  getTranscript: (api: GatewayApi) => api.getTranscript(),
  getAgentTranscript: (api: GatewayApi, body: string) => api.getAgentTranscript(parseCommandArgs(body)),
  getAgentTranscriptPage: (api: GatewayApi, body: string) => api.getAgentTranscriptPage(parseCommandArgs(body)),
  openAgentWindowed: (api: GatewayApi, body: string) => api.openAgentWindowed(parseCommandArgs(body)),
  getAgentTranscriptWindow: (api: GatewayApi, body: string) => api.getAgentTranscriptWindow(parseCommandArgs(body)),
  openAgentTail: (api: GatewayApi, body: string) => api.openAgentTail(parseCommandArgs(body)),
  getAgentTranscriptTail: (api: GatewayApi, body: string) => api.getAgentTranscriptTail(parseCommandArgs(body)),
  getAgentThread: (api: GatewayApi, body: string) => api.getAgentThread(parseCommandArgs(body)),
  sendPrompt: (api: GatewayApi, body: string) => api.sendPrompt(parseCommandArgs(body)),
  promptAcceptanceStatus: (api: GatewayApi, body: string) => api.promptAcceptanceStatus(parseCommandArgs(body)),
  respondToWidget: (api: GatewayApi, body: string) => api.respondToWidget(parseCommandArgs(body)),
  resolveAutoReviewApproval: (api: GatewayApi, body: string) => api.resolveAutoReviewApproval(parseCommandArgs(body)),
  resolveLocalToolPermission: (api: GatewayApi, body: string) => api.resolveLocalToolPermission(parseCommandArgs(body)),
  dismissWidget: (api: GatewayApi, body: string) => api.dismissWidget(parseCommandArgs(body)),
  submitSecret: (api: GatewayApi, body: string) => api.submitSecret(parseCommandArgs(body)),
  reactToMessage: (api: GatewayApi, body: string) => api.reactToMessage(parseCommandArgs(body)),
  appendConnectorCard: (api: GatewayApi, body: string) => api.appendConnectorCard(parseCommandArgs(body)),
  listAgents: (api: GatewayApi) => api.listAgents(),
  countAgents: (api: GatewayApi) => api.countAgents(),
  searchAgents: (api: GatewayApi, body: string) => api.searchAgents(parseCommandArgs(body)),
  searchMedia: (api: GatewayApi, body: string) => api.searchMedia(parseCommandArgs(body)),
  createAgent: (api: GatewayApi, body: string) => api.createAgent(parseCommandArgs(body)),
  kickstartAgent: (api: GatewayApi, body: string) => api.kickstartAgent(parseCommandArgs(body)),
  requestDiskSaverAudit: (api: GatewayApi, body: string) => api.requestDiskSaverAudit(parseCommandArgs(body)),
  createGroup: (api: GatewayApi, body: string) => api.createGroup(parseCommandArgs(body)),
  setGroupMembers: (api: GatewayApi, body: string) => api.setGroupMembers(parseCommandArgs(body)),
  updateAgent: (api: GatewayApi, body: string) => api.updateAgent(parseCommandArgs(body)),
  deleteAgent: (api: GatewayApi, body: string) => api.deleteAgent(parseCommandArgs(body)),
  deleteAgents: (api: GatewayApi, body: string) => api.deleteAgents(parseCommandArgs(body)),
  duplicateAgent: (api: GatewayApi, body: string) => api.duplicateAgent(parseCommandArgs(body)),
  setAgentUnread: (api: GatewayApi, body: string) => api.setAgentUnread(parseCommandArgs(body)),
  setAgentNotificationsEnabled: (api: GatewayApi, body: string) => api.setAgentNotificationsEnabled(parseCommandArgs(body)),
  setAgentNotifyOnUpdates: (api: GatewayApi, body: string) => api.setAgentNotifyOnUpdates(parseCommandArgs(body)),
  setAgentHiddenFromSidebar: (api: GatewayApi, body: string) => api.setAgentHiddenFromSidebar(parseCommandArgs(body)),
  openAgent: (api: GatewayApi, body: string) => api.openAgent(parseCommandArgs(body)),
  setWindowFocused: (api: GatewayApi, body: string) => api.setWindowFocused(parseCommandArgs(body)),
  getAgentMemories: (api: GatewayApi, body: string) => api.getAgentMemories(parseCommandArgs(body)),
  deleteAgentMemory: (api: GatewayApi, body: string) => api.deleteAgentMemory(parseCommandArgs(body)),
  clearAgentMemories: (api: GatewayApi, body: string) => api.clearAgentMemories(parseCommandArgs(body)),
  getAgentAutomations: (api: GatewayApi, body: string) => api.getAgentAutomations(parseCommandArgs(body)),
  listAllAutomations: (api: GatewayApi) => api.listAllAutomations(),
  isAgentNetworkEnabled: (api: GatewayApi) => api.isAgentNetworkEnabled(),
  isGlobalSearchEnabled: (api: GatewayApi) => api.isGlobalSearchEnabled(),
  isEgressTunnelAvailable: (api: GatewayApi) => api.isEgressTunnelAvailable(),
  getSharingState: (api: GatewayApi) => api.getSharingState(),
  createRoomFromAgent: (api: GatewayApi, body: string) => api.createRoomFromAgent(parseCommandArgs(body)),
  createRoomInvite: (api: GatewayApi, body: string) => api.createRoomInvite(parseCommandArgs(body)),
  joinSharedRoom: (api: GatewayApi, body: string) => api.joinSharedRoom(parseCommandArgs(body)),
  respondToRoomJoinRequest: (api: GatewayApi, body: string) => api.respondToRoomJoinRequest(parseCommandArgs(body)),
  createSharedRoom: (api: GatewayApi, body: string) => api.createSharedRoom(parseCommandArgs(body)),
  addOwnAgentToSharedRoom: (api: GatewayApi, body: string) => api.addOwnAgentToSharedRoom(parseCommandArgs(body)),
  removeOwnAgentFromSharedRoom: (api: GatewayApi, body: string) => api.removeOwnAgentFromSharedRoom(parseCommandArgs(body)),
  setSharedRoomTyping: (api: GatewayApi, body: string) => api.setSharedRoomTyping(parseCommandArgs(body)),
  leaveSharedRoom: (api: GatewayApi, body: string) => api.leaveSharedRoom(parseCommandArgs(body)),
  setAgentAutomationEnabled: (api: GatewayApi, body: string) => api.setAgentAutomationEnabled(parseCommandArgs(body)),
  createAgentAutomation: (api: GatewayApi, body: string) => api.createAgentAutomation(parseCommandArgs(body)),
  updateAgentAutomation: (api: GatewayApi, body: string) => api.updateAgentAutomation(parseCommandArgs(body)),
  deleteAgentAutomation: (api: GatewayApi, body: string) => api.deleteAgentAutomation(parseCommandArgs(body)),
  runAgentAutomationNow: (api: GatewayApi, body: string) => api.runAgentAutomationNow(parseCommandArgs(body)),
  broadcastToAgents: (api: GatewayApi, body: string) => api.broadcastToAgents(parseCommandArgs(body)),
  getAgentWorkflows: (api: GatewayApi, body: string) => api.getAgentWorkflows(parseCommandArgs(body)),
  createAgentWorkflow: (api: GatewayApi, body: string) => api.createAgentWorkflow(parseCommandArgs(body)),
  updateAgentWorkflow: (api: GatewayApi, body: string) => api.updateAgentWorkflow(parseCommandArgs(body)),
  setAgentWorkflowEnabled: (api: GatewayApi, body: string) => api.setAgentWorkflowEnabled(parseCommandArgs(body)),
  deleteAgentWorkflow: (api: GatewayApi, body: string) => api.deleteAgentWorkflow(parseCommandArgs(body)),
  runAgentWorkflowNow: (api: GatewayApi, body: string) => api.runAgentWorkflowNow(parseCommandArgs(body)),
  importAgentWorkflowText: (api: GatewayApi, body: string) => api.importAgentWorkflowText(parseCommandArgs(body)),
  importAgentWorkflowUrl: (api: GatewayApi, body: string) => api.importAgentWorkflowUrl(parseCommandArgs(body)),
  portAgentLocalSkills: (api: GatewayApi, body: string) => api.portAgentLocalSkills(parseCommandArgs(body)),
  getConversationOutline: (api: GatewayApi, body: string) => api.getConversationOutline(parseCommandArgs(body)),
  skillsCatalog: (api: GatewayApi) => api.skillsCatalog(),
  syncPluginSkills: (api: GatewayApi) => api.syncPluginSkills(),
  getPluginSyncStatus: (api: GatewayApi) => api.getPluginSyncStatus(),
  getSkillPublishTargets: (api: GatewayApi) => api.getSkillPublishTargets(),
  publishSkill: (api: GatewayApi, body: string) => api.publishSkill(parseCommandArgs(body)),
  resyncPublishedSkill: (api: GatewayApi, body: string) => api.resyncPublishedSkill(parseCommandArgs(body)),
  unpublishSkill: (api: GatewayApi, body: string) => api.unpublishSkill(parseCommandArgs(body)),
  getAgentChannels: (api: GatewayApi, body: string) => api.getAgentChannels(parseCommandArgs(body)),
  connectChannel: (api: GatewayApi, body: string) => api.connectChannel(parseCommandArgs(body)),
  disconnectChannel: (api: GatewayApi, body: string) => api.disconnectChannel(parseCommandArgs(body)),
  refreshChannel: (api: GatewayApi, body: string) => api.refreshChannel(parseCommandArgs(body)),
  getListenerIntegrations: (api: GatewayApi) => api.getListenerIntegrations(),
  getListenerConnectUrl: (api: GatewayApi, body: string) => api.getListenerConnectUrl(parseCommandArgs(body)),
  getSubagents: (api: GatewayApi, body: string) => api.getSubagents(parseCommandArgs(body)),
  getAsyncTasks: (api: GatewayApi, body: string) => api.getAsyncTasks(parseCommandArgs(body)),
  setAgentAvatarBytes: (api: GatewayApi, body: string) => api.setAgentAvatarBytes(parseCommandArgs(body)),
  getAgentAvatar: (api: GatewayApi, body: string) => api.getAgentAvatar(parseCommandArgs(body)),
  getForeverBoxStatus: (api: GatewayApi, body: string) => api.getForeverBoxStatus(parseCommandArgs(body)),
  getCloudAgentInfo: (api: GatewayApi, body: string) => api.getCloudAgentInfo(parseCommandArgs(body)),
  ensureForeverBox: (api: GatewayApi, body: string) => api.ensureForeverBox(parseCommandArgs(body)),
  resetForeverBox: (api: GatewayApi, body: string) => api.resetForeverBox(parseCommandArgs(body)),
  updateForeverBox: (api: GatewayApi, body: string) => api.updateForeverBox(parseCommandArgs(body)),
  autoUpdateBoxNow: (api: GatewayApi) => api.autoUpdateBoxNow(),
  snapshotBoxStoreNow: (api: GatewayApi, body: string) => api.snapshotBoxStoreNow(parseCommandArgs(body)),
  getBoxStoreStatus: (api: GatewayApi) => api.getBoxStoreStatus(),
  clearBoxStoreNow: (api: GatewayApi) => api.clearBoxStoreNow(),
  updateHostNow: (api: GatewayApi, body: string) => api.updateHostNow(parseCommandArgs(body)),
  getHostStatus: (api: GatewayApi) => api.getHostStatus(),
  setBoxMigrating: (api: GatewayApi, body: string) => api.setBoxMigrating(parseCommandArgs(body)),
  prepareBoxForRecreate: (api: GatewayApi) => api.prepareBoxForRecreate(),
  resumeBoxAfterRecreate: (api: GatewayApi, body: string) => api.resumeBoxAfterRecreate(parseCommandArgs(body)),
  handBackForeverBox: (api: GatewayApi, body: string) => api.handBackForeverBox(parseCommandArgs(body)),
  startTeachRecording: (api: GatewayApi, body: string) => api.startTeachRecording(parseCommandArgs(body)),
  stopTeachRecording: (api: GatewayApi, body: string) => api.stopTeachRecording(parseCommandArgs(body)),
  getTeachRecordingStatus: (api: GatewayApi) => api.getTeachRecordingStatus(),
  getTrays: (api: GatewayApi) => api.getTrays(),
  dismissTray: (api: GatewayApi, body: string) => api.dismissTray(parseCommandArgs(body)),
  clearTrays: (api: GatewayApi) => api.clearTrays(),
  uploadAttachment: (api: GatewayApi, body: string) => api.uploadAttachment(parseCommandArgs(body)),
  readAttachmentImage: (api: GatewayApi, body: string) => api.readAttachmentImage(parseCommandArgs(body)),
  readAttachmentText: (api: GatewayApi, body: string) => api.readAttachmentText(parseCommandArgs(body)),
  readAttachmentChunk: (api: GatewayApi, body: string) => api.readAttachmentChunk(parseCommandArgs(body)),
  getHostSettings: (api: GatewayApi) => api.getHostSettings(),
  setHostSettings: (api: GatewayApi, body: string) => api.setHostSettings(parseCommandArgs(body)),
  setBoxSecrets: (api: GatewayApi, body: string) => api.setBoxSecrets(parseCommandArgs(body)),
  getBoxSecretsStatus: (api: GatewayApi) => api.getBoxSecretsStatus(),
  completeMcpOAuth: (api: GatewayApi, body: string) => api.completeMcpOAuth(parseCommandArgs(body)),
  requestWebAuthnCeremony: (api: GatewayApi, body: string) => api.requestWebAuthnCeremony(parseCommandArgs(body)),
  refreshMcp: (api: GatewayApi, body: string) => api.refreshMcp(parseCommandArgs(body)),
  listRoutedMcpTools: (api: GatewayApi) => api.listRoutedMcpTools(),
  executeRoutedMcpTool: (api: GatewayApi, body: string) => api.executeRoutedMcpTool(parseCommandArgs(body)),
  listBoxMcpServers: (api: GatewayApi, body: string) => api.listBoxMcpServers(parseCommandArgs(body))
};
export const GATEWAY_PREPARE_UPGRADE_PATH = "/prepare-upgrade";
const LOOPBACK_HOSTS = new Set(["127.0.0.1", "localhost", "::1", "[::1]"]);
export function isLoopbackHost(host: string): boolean { return LOOPBACK_HOSTS.has(host.trim().toLowerCase()); }
export interface AgentSummaryLike { readonly avatarDataUrl?: unknown; readonly [key: string]: unknown; }
export function stripSummaryInlineAvatar<T extends AgentSummaryLike>(summary: T): T { return summary.avatarDataUrl == null ? summary : { ...summary, avatarDataUrl: null }; }
export function stripSummaryRows<T extends AgentSummaryLike>(rows: readonly T[]): readonly T[] { let changed = false; const stripped = rows.map((row) => { const slim = stripSummaryInlineAvatar(row); if (slim !== row) changed = true; return slim; }); return changed ? stripped : rows; }
export function stripNullableSummary<T extends AgentSummaryLike>(summary: T | null): T | null { return summary == null ? null : stripSummaryInlineAvatar(summary); }
export function stripCreateAgentResult<T extends { readonly agent: AgentSummaryLike }>(result: T): T { const agent = stripSummaryInlineAvatar(result.agent); return agent === result.agent ? result : { ...result, agent }; }
export const SAND_GATEWAY_SLIM_COMMANDS = {
  ...SAND_GATEWAY_COMMANDS,
  listAgents: async (api: GatewayApi, _body: string) => stripSummaryRows(await SAND_GATEWAY_COMMANDS.listAgents(api)),
  updateAgent: async (api: GatewayApi, body: string) => stripNullableSummary(await SAND_GATEWAY_COMMANDS.updateAgent(api, body)),
  setGroupMembers: async (api: GatewayApi, body: string) => stripNullableSummary(await SAND_GATEWAY_COMMANDS.setGroupMembers(api, body)),
  setAgentAvatarBytes: async (api: GatewayApi, body: string) => stripNullableSummary(await SAND_GATEWAY_COMMANDS.setAgentAvatarBytes(api, body)),
  createAgent: async (api: GatewayApi, body: string) => stripCreateAgentResult(await SAND_GATEWAY_COMMANDS.createAgent(api, body)),
  createGroup: async (api: GatewayApi, body: string) => stripCreateAgentResult(await SAND_GATEWAY_COMMANDS.createGroup(api, body)),
  duplicateAgent: async (api: GatewayApi, body: string) => stripCreateAgentResult(await SAND_GATEWAY_COMMANDS.duplicateAgent(api, body))
};
export function stripInlineAvatarsFromEvent(event: any): any {
  if (event.channel === "agents") { const agents = stripSummaryRows(event.payload.agents); return agents === event.payload.agents ? event : { channel: "agents", payload: { ...event.payload, agents } }; }
  if (event.channel === "agent-upserted") { const agent = stripSummaryInlineAvatar(event.payload.agent); return agent === event.payload.agent ? event : { channel: "agent-upserted", payload: { ...event.payload, agent } }; }
  return event;
}
