import { clampLine } from "../shared/sand-text.js";
export const MAX_ACTIVITY_DETAIL_CHARS = 80, NAMED_ACTIVITY_MAX_HOLD_MS = 2500;
export const THINKING_ACTIVITY = { kind: "thinking" } as const;
export const SEND_MESSAGE_TOOL_CALL_OUTLINE_NAME = "SendMessage";
export const SAND_BOX_SHELL_TOOL_NAME = "Shell", SAND_EXTERNAL_SHELL_TOOL_NAME = "ExternalShell", SAND_BOX_READ_TOOL_NAME = "Read", SAND_EXTERNAL_READ_TOOL_NAME = "ExternalRead", SAND_BOX_AWAIT_SHELL_TOOL_NAME = "AwaitShell", SAND_EXTERNAL_AWAIT_SHELL_TOOL_NAME = "ExternalAwaitShell";
export type AgentActivity = typeof THINKING_ACTIVITY | { kind: "tool"; tool: string; detail?: string; target?: string; callId: string };
export type ActivityTransition = { type: "keep" | "clear" } | { type: "set"; activity: AgentActivity };
export type ActivityUpdate = { type: "thinking-delta" } | { type: "text-delta"; text: string } | { type: "tool-call"; id: string; name: string; status: string; args?: string; summary?: string } | { type: "send-message" | "turn-ended" } | { type: string; [key: string]: unknown };
const unresolved = new Set(["shellToolCall", "readToolCall", "awaitToolCall"]);
export function deriveActivityFromUpdate(update: ActivityUpdate): ActivityTransition { if (update.type === "thinking-delta" || update.type === "text-delta") return { type: "set", activity: THINKING_ACTIVITY }; if (update.type === "send-message" || update.type === "turn-ended") return { type: "clear" }; if (update.type !== "tool-call") return { type: "keep" }; const tool = update as Extract<ActivityUpdate, { type: "tool-call" }>; if (tool.name === SEND_MESSAGE_TOOL_CALL_OUTLINE_NAME || tool.status !== "pending" || unresolved.has(tool.name)) return { type: "keep" }; return { type: "set", activity: deriveToolCallActivity(tool) }; }
export interface NamedActivityHoldState { heldActivity?: AgentActivity; heldSinceMs: number }
export const INITIAL_NAMED_ACTIVITY_HOLD_STATE: NamedActivityHoldState = { heldSinceMs: 0 };
export function resolveNamedActivityHold(update: ActivityUpdate, state: NamedActivityHoldState, nowMs: number, maxHoldMs = NAMED_ACTIVITY_MAX_HOLD_MS): { transition: ActivityTransition; state: NamedActivityHoldState } { const base = deriveActivityFromUpdate(update); if (update.type === "thinking-delta" || update.type === "text-delta") return { transition: state.heldActivity != null && nowMs - state.heldSinceMs < maxHoldMs ? { type: "keep" } : base, state }; if (update.type === "tool-call") { if (base.type === "set") return { transition: base, state: { heldActivity: base.activity, heldSinceMs: nowMs } }; return { transition: base, state: state.heldActivity == null ? state : { ...state, heldSinceMs: nowMs } }; } return base.type === "clear" ? { transition: base, state: INITIAL_NAMED_ACTIVITY_HOLD_STATE } : { transition: base, state }; }
export function createGroupMemberActivityTracker(): (update: ActivityUpdate) => ActivityTransition { let streaming = false; return update => { if (update.type === "text-delta") { if ((update as { text: string }).text.length === 0) return { type: "keep" }; streaming = true; return { type: "clear" }; } if (update.type === "thinking-delta") return streaming ? { type: "keep" } : { type: "set", activity: THINKING_ACTIVITY }; if (update.type === "tool-call" && (update as { status: string }).status === "pending") { streaming = false; if ((update as { name: string }).name === SEND_MESSAGE_TOOL_CALL_OUTLINE_NAME) return { type: "clear" }; } if (update.type === "send-message" || update.type === "turn-ended") streaming = false; return deriveActivityFromUpdate(update); }; }
export function parseArgsJson(raw?: string): Record<string, unknown> | null { if (!raw) return null; try { const parsed: unknown = JSON.parse(raw); return typeof parsed === "object" && parsed != null && !Array.isArray(parsed) ? parsed as Record<string, unknown> : null; } catch { return null; } }
function readString(args: Record<string, unknown> | null, key: string): string | undefined { const value = args?.[key]; if (typeof value !== "string") return undefined; const trimmed = value.trim(); return trimmed || undefined; }
export function fileBasename(path?: string): string | undefined { return path?.split(/[\\/]/).filter(Boolean).at(-1); }
export function urlHostname(raw?: string): string | undefined { try { return raw == null ? undefined : new URL(raw).hostname || undefined; } catch { return undefined; } }
const DISCARD = new Set(["/dev/null", "/dev/stdout", "/dev/stderr"]), OUTPUT = /(?<![\d>&])>{1,2}\s*([^&\s;|<>]+)/, TEE = /\btee\s+(?:-[a-zA-Z]+\s+)*([^\s;|&<>-][^\s;|&<>]*)/, SED = /\bsed\b[^;|&]*\s-i\b/;
const strip = (token: string) => token.replace(/^['"]|['"]$/g, "");
export function extractShellEditTarget(command: string): string | undefined { const redirect = OUTPUT.exec(command)?.[1]; if (redirect) { const target = strip(redirect); if (!DISCARD.has(target)) return fileBasename(target); } const tee = TEE.exec(command)?.[1]; if (tee) { const target = strip(tee); if (!DISCARD.has(target)) return fileBasename(target); } if (SED.test(command)) { const target = command.trim().split(/\s+/).map(strip).reverse().find(token => /[\\/]/.test(token) || /\.[A-Za-z0-9]+$/.test(token)); return fileBasename(target); } return undefined; }
export function deriveToolCallActivity(input: Extract<ActivityUpdate, { type: "tool-call" }>): AgentActivity { const args = parseArgsJson(input.args); let tool = input.name, detail: string | undefined, target: string | undefined; switch (input.name) { case "shellToolCall": case SAND_BOX_SHELL_TOOL_NAME: tool = SAND_BOX_SHELL_TOOL_NAME; detail = extractShellEditTarget(readString(args, "command") ?? ""); break; case SAND_EXTERNAL_SHELL_TOOL_NAME: detail = extractShellEditTarget(readString(args, "command") ?? ""); break; case "readToolCall": case SAND_BOX_READ_TOOL_NAME: tool = SAND_BOX_READ_TOOL_NAME; detail = fileBasename(readString(args, "path")); break; case SAND_EXTERNAL_READ_TOOL_NAME: detail = fileBasename(readString(args, "path")); break; case "webSearchToolCall": tool = "WebSearch"; detail = readString(args, "searchTerm"); break; case "webFetchToolCall": tool = "WebFetch"; detail = urlHostname(readString(args, "url")); break; case "generateImageToolCall": tool = "GenerateImage"; detail = readString(args, "description"); break; case "mcpToolCall": tool = "CallMcpTool"; detail = readString(args, "providerIdentifier") ?? readString(args, "serverIdentifier"); break; case "getMcpToolsToolCall": tool = "GetMcpTools"; detail = readString(args, "server"); break; case "mcpAuthToolCall": tool = "McpAuth"; detail = readString(args, "serverIdentifier"); break; case "awaitToolCall": case SAND_BOX_AWAIT_SHELL_TOOL_NAME: tool = SAND_BOX_AWAIT_SHELL_TOOL_NAME; break; case SAND_EXTERNAL_AWAIT_SHELL_TOOL_NAME: break; case "computerUseToolCall": tool = "Computer"; break; case "Task": detail = input.summary; break; case "Screenshot": break; case "communicateUpdateToolCall": { const payload = parseArgsJson(readString(args, "currentStep")); if (payload?.__sand_tool__ === true) { tool = readString(payload, "tool") ?? tool; detail = readString(payload, "detail"); target = readString(payload, "target"); } break; } } return { kind: "tool", tool, ...(detail ? { detail: clampLine(detail, MAX_ACTIVITY_DETAIL_CHARS) } : {}), ...(target ? { target } : {}), callId: input.id }; }
