import { mintTraceparent, parseTraceparent, shouldSampleSend } from "../shared/observability/send-trace.js";
export interface TraceSpan { setAttribute(key: string, value: unknown): void; recordException(error: Error): void; setStatus(status: { code: number }): void; end(): void }
export interface HostTrace { span: TraceSpan; context?: unknown }
export type TraceFactory = (options: { name: string; traceparent?: string; parentCtx?: unknown; startTime?: number; inheritableAttributes?: Record<string, unknown> }) => HostTrace | undefined;
let traceFactory: TraceFactory | undefined, turnTraceHostBundleVersion: string | undefined;
export function setHostTraceFactory(factory: TraceFactory): void { traceFactory = factory; }
export function beginSendTrace(traceparent?: string): HostTrace | undefined { return adoptRemoteParent(traceparent, "sand.send"); }
export function adoptRemoteParent(traceparent: string | undefined, spanName: string): HostTrace | undefined { if (typeof traceparent !== "string" || parseTraceparent(traceparent) == null) return undefined; try { return traceFactory?.({ name: spanName, traceparent }); } catch { return undefined; } }
export function beginGatewayCommandTrace(options: { traceparent?: string; method: string }): HostTrace | undefined { return adoptRemoteParent(options.traceparent, `sand.gateway.${options.method}`); }
export const SAND_TURN_ROOT_SPAN_NAME = "sand.turn.run";
export function setTurnTraceHostBundleVersion(version?: string): void { const normalized = version?.trim(); turnTraceHostBundleVersion = normalized ? normalized : undefined; }
export function resolveTurnTraceSampleRatio(raw = process.env.SAND_TURN_TRACE_SAMPLE_RATIO): number { if (!raw) return 1; const parsed = Number.parseFloat(raw); return Number.isFinite(parsed) && parsed >= 0 && parsed <= 1 ? parsed : 1; }
export function resolveTurnTraceType(options: { automationWake?: unknown; requestSource?: string; hidden?: boolean }): string { if (options.automationWake != null) return "automation"; if (options.requestSource != null && options.requestSource !== "turn") return options.requestSource; return options.hidden === true ? "hidden" : "user"; }
export function beginTurnTrace(options: { conversationId: string; turnType: string; parentCtx?: unknown; startTime?: number; sampleRatio?: number; attributes?: Record<string, unknown> }): HostTrace | undefined { try { const common = { name: SAND_TURN_ROOT_SPAN_NAME, ...(options.startTime == null ? {} : { startTime: options.startTime }), inheritableAttributes: { "sand.conversation_id": options.conversationId, "sand.turn_type": options.turnType } }; let trace = options.parentCtx === undefined ? undefined : traceFactory?.({ ...common, parentCtx: options.parentCtx }); if (trace == null) { const ratio = options.sampleRatio ?? resolveTurnTraceSampleRatio(); if (!shouldSampleSend(ratio)) return undefined; const minted = mintTraceparent(true); if (minted == null) return undefined; trace = traceFactory?.({ ...common, traceparent: minted.traceparent }); } if (trace == null) return undefined; trace.span.setAttribute("sand.conversation_id", options.conversationId); trace.span.setAttribute("sand.turn_type", options.turnType); if (turnTraceHostBundleVersion) trace.span.setAttribute("sand.host_bundle_version", turnTraceHostBundleVersion); for (const [key, value] of Object.entries(options.attributes ?? {})) trace.span.setAttribute(key, value); return trace; } catch { return undefined; } }
export function resolveTurnTraceOutcome(result: { quiescedForUpgrade?: boolean; aborted?: boolean; awaitingUserSelection?: boolean }): string { if (result.quiescedForUpgrade === true) return "quiesced_for_upgrade"; if (result.aborted) return "aborted"; if (result.awaitingUserSelection === true) return "awaiting_user"; return "success"; }
export function setTurnTraceAttributes(trace: HostTrace | undefined, attributes: Record<string, unknown>): void { try { for (const [key, value] of Object.entries(attributes)) trace?.span.setAttribute(key, value); } catch {} }
export function markTurnTraceError(trace: HostTrace | undefined, error: unknown): void { try { trace?.span.recordException(error instanceof Error ? error : new Error(String(error))); trace?.span.setStatus({ code: 2 }); trace?.span.setAttribute("sand.outcome", "error"); } catch {} }
export async function traceSendPhase<T>(ctx: HostTrace | undefined, name: string, fn: (ctx: HostTrace | undefined) => Promise<T>): Promise<T> { if (ctx == null || traceFactory == null) return await fn(ctx); let child: HostTrace | undefined; try { child = traceFactory({ name, parentCtx: ctx.context }); } catch { return await fn(ctx); } if (child == null) return await fn(ctx); try { return await fn(child); } catch (error) { try { child.span.recordException(error instanceof Error ? error : new Error(String(error))); child.span.setStatus({ code: 2 }); } catch {} throw error; } finally { try { child.span.end(); } catch {} } }
