export function getUpdatedAtFromStats(metadata: { createdAt: number }, stats?: { mtimeMs: number }): number { return Math.max(Number(metadata.createdAt), Math.floor(Number(stats?.mtimeMs ?? 0))); }
export function getSummaryUpdatedAt(metadata: { createdAt: number }, unread: { lastActivityAt: number }): number { return Math.max(Number(metadata.createdAt), unread.lastActivityAt); }
export function seedActivityFromMtime(db: { getUnreadState(): { lastActivityAt: number }; get(key: string): Uint8Array | number; markActivity(at: number): void }, agentId: string, stats?: { mtimeMs: number }): void { if (db.getUnreadState().lastActivityAt > 0) return; const root = db.get("latestRootBlobId"); if (!(root instanceof Uint8Array) || root.length === 0) return; db.markActivity(getUpdatedAtFromStats({ createdAt: Number(db.get("createdAt")) }, stats)); void agentId; }
export function isHttpsUrl(raw: string): boolean { try { return new URL(raw).protocol === "https:"; } catch { return false; } }
export interface AttachmentMessage { type: "attachment"; url: string; file_name?: string | null }
export function isLinkAttachmentMessage(message: { type: string; url: string; file_name?: string | null }): boolean { return message.type === "attachment" && isHttpsUrl(message.url) && !message.file_name; }
function classifyAttachment(value: { fileName?: unknown; urlOrPath?: unknown }): "image" | "video" | "audio" | "document" | "other" { const text = `${String(value.fileName ?? "")} ${String(value.urlOrPath ?? "")}`.toLowerCase(); if (/\.(png|jpe?g|gif|webp|svg)(\?|$)/.test(text)) return "image"; if (/\.(mp4|mov|webm|mkv)(\?|$)/.test(text)) return "video"; if (/\.(mp3|wav|m4a|ogg)(\?|$)/.test(text)) return "audio"; if (/\.(pdf|docx?|xlsx?|pptx?|txt|md)(\?|$)/.test(text)) return "document"; return "other"; }
function countKinds(kinds: readonly string[]): Record<string, number> { const result: Record<string, number> = {}; for (const kind of kinds) result[kind] = (result[kind] ?? 0) + 1; return result; }
function sameBatch(candidate: unknown, anchor: unknown): boolean { return typeof anchor === "string" && anchor.length > 0 && candidate === anchor; }
export function collectLastAttachmentBatchKinds(entries: readonly Record<string, unknown>[], index: number): string[] { const last = entries[index], kinds: string[] = []; if (last?.kind === "user-attachment") { for (let i=index;i>=0;i--) { const entry=entries[i]; if (entry?.kind!=="user-attachment" || i!==index&&!sameBatch(entry.batchId,last.batchId)) break; kinds.push(classifyAttachment({fileName:entry.file_name,urlOrPath:entry.file_path})); } } else if (last?.kind === "send-message" && typeof last.message === "object" && last.message != null && (last.message as Record<string,unknown>).type === "attachment") { for(let i=index;i>=0;i--){const entry=entries[i],message=entry?.message as Record<string,unknown>|undefined;if(entry?.kind!=="send-message"||message?.type!=="attachment"||isLinkAttachmentMessage(message as unknown as AttachmentMessage)||i!==index&&!sameBatch(entry.batchId,last.batchId))break;kinds.push(classifyAttachment({fileName:message.file_name,urlOrPath:message.url}));} } return kinds.reverse(); }
export function buildAttachmentLastEntry(entries: readonly Record<string, unknown>[], index: number): Record<string, unknown> { const kinds=collectLastAttachmentBatchKinds(entries,index);return{kind:"attachment",count:kinds.length,kinds:countKinds(kinds)}; }
function previewText(raw: unknown): string { return String(raw ?? "").replace(/\s+/g," ").replace(/[*_`#>]/g,"").trim().slice(0,280); }
export function lastMessagePreviewText(message: Record<string, unknown>): string { if(message.type==="text")return previewText(message.content);if(message.type==="attachment"&&typeof message.url==="string"&&isLinkAttachmentMessage(message as unknown as AttachmentMessage))return`Sent a link · ${message.url}`;if(message.type==="attachment")return`Sent an attachment · ${classifyAttachment({fileName:message.file_name,urlOrPath:message.url})}`;if(typeof message.title==="string")return previewText(message.title);if(typeof message.label==="string")return previewText(message.label);return previewText(message.type); }
export function getLastMessageFromTranscript(entries: readonly Record<string, unknown>[]): { id: string; preview: string } | null { for(let i=entries.length-1;i>=0;i--){const entry=entries[i];if(entry?.kind!=="send-message"||typeof entry.id!=="string"||entry.message==null||typeof entry.message!=="object")continue;return{id:entry.id,preview:lastMessagePreviewText(entry.message as Record<string,unknown>)}}return null; }
export function getLastEntryFromTranscript(entries: readonly Record<string, unknown>[]): Record<string, unknown> | null { const visible=entries.filter((entry)=>entry.hidden!==true&&entry.branched!==true);for(let i=visible.length-1;i>=0;i--){const entry=visible[i];if(entry==null||entry.peerAgentId!=null)continue;if(entry.kind==="send-message"&&entry.message&&typeof entry.message==="object"){const msg=entry.message as Record<string,unknown>;if(msg.type==="text")return{kind:"text",text:String(msg.content??"")};if(msg.type==="widget"){const widget=msg.widget as Record<string,unknown>|undefined,prompt=typeof widget?.prompt==="string"?widget.prompt:"Question";return{kind:"text",text:entry.respondedValue==null?prompt:`${prompt} — ${String(entry.respondedValue)}`}}if(msg.type==="attachment"&&typeof msg.url==="string"&&isLinkAttachmentMessage(msg as unknown as AttachmentMessage))return{kind:"link",url:msg.url};return msg.type==="attachment"?buildAttachmentLastEntry(visible,i):{kind:"text",text:lastMessagePreviewText(msg)}}if(entry.kind==="message"&&typeof entry.content==="string"&&entry.content.length>0)return{kind:"text",text:entry.content};if(entry.kind==="user-attachment")return buildAttachmentLastEntry(visible,i)}return null; }
