import { readdir } from "node:fs/promises";
import { dirname } from "node:path";
import { getSandProfilePath, readSandProfileFile } from "../../agents/agent-profile.js";
import { getSandSettingsPath, readSandSettingsFile } from "../../agents/settings-file.js";
import { getLastEntryFromTranscript, getLastMessageFromTranscript, getSummaryUpdatedAt, seedActivityFromMtime } from "./session-projection.js";
import { ensureProfileFile, ensureSettingsFile } from "./session-recovery.js";

export interface DbExtras { agentId: string; createdAt: number; updatedAt: number; hasTranscript: boolean; lastEntry: Record<string, unknown> | null; lastMessage: { id: string; preview: string } | null; newestEntryId: unknown; unreadState: { lastActivityAt: number; lastViewedAt: number; isManuallyUnread: boolean; unreadCount: number }; awaitingUserResponse: unknown; origin: unknown; purpose: unknown; conversationPartnerIds: string[]; legacyAvatarPath: string | null }
export interface SummaryDb { get(key: string): unknown; getTranscriptEntries(): Record<string, unknown>[]; getUnreadState(): DbExtras["unreadState"]; getAwaitingUserResponse?(): unknown; getAgentOrigin?(): unknown; getAgentPurpose?(): unknown; getConversationPartnerIds?(): string[]; getSandProfile?(): { description: string; avatarPath: string | null } }
export function loadAgentDbExtras(db: SummaryDb, dbPath: string, dirName: string, stats?: { mtimeMs: number }): DbExtras | null { ensureProfileFile(dbPath, db); return readDbExtras(db, dirName, stats); }
export function readDbExtras(db: SummaryDb, dirName: string, stats?: { mtimeMs: number }): DbExtras | null { try { const agentId=String(db.get("agentId")||dirName);seedActivityFromMtime(db as never,agentId,stats);const createdAt=Number(db.get("createdAt")||0),entries=db.getTranscriptEntries(),unread=db.getUnreadState();return{agentId,createdAt,updatedAt:getSummaryUpdatedAt({createdAt},unread),hasTranscript:entries.length>0,lastEntry:getLastEntryFromTranscript(entries),lastMessage:getLastMessageFromTranscript(entries),newestEntryId:entries.at(-1)?.id??null,unreadState:unread,awaitingUserResponse:db.getAwaitingUserResponse?.()??null,origin:db.getAgentOrigin?.()??"user",purpose:db.getAgentPurpose?.()??null,conversationPartnerIds:db.getConversationPartnerIds?.()??[],legacyAvatarPath:db.getSandProfile?.().avatarPath??null};}catch{return null} }
const orNull=(value?:string|null):string|null=>value!=null&&value.length>0?value:null;
export function minimalAgentSummary(args:{dirName:string;dbPath:string;dbStats?:{mtimeMs:number};activeAgentId?:string}){const profile=readSandProfileFile(getSandProfilePath(dirname(args.dbPath))),time=Math.floor(Number(args.dbStats?.mtimeMs??0));return{id:args.dirName,name:profile?.name?.trim()||"Grok",description:profile?.description??"",title:profile?.title??"",avatarDataUrl:null,avatarVersion:null,avatarShape:orNull(profile?.avatarShape),avatarColor:orNull(profile?.avatarColor),createdAt:time,updatedAt:time,path:args.dbPath,isActive:args.dirName===args.activeAgentId,isRunning:false,isComposingMessage:false,lastEntry:null,lastMessageId:null,lastMessagePreview:null,newestEntryId:null,hasUnread:false,unreadCount:0,lastViewedAt:0,lastActivityAt:0,awaitingUserResponse:null,notificationsEnabled:false,notifyOnUpdatesEnabled:true,isHiddenFromSidebar:false,origin:"user",isGroup:false,memberIds:[],conversationPartnerIds:[]}}
export async function agentHasQuarantinedStoreDb(agentDir:string):Promise<boolean>{try{return(await readdir(agentDir)).some((name)=>name.startsWith("store.db.corrupt-"))}catch{return false}}
export async function agentHasDurableFootprint(agentDir:string,agentHasMemory:(dir:string)=>boolean,hasAutomations:(dir:string)=>boolean=()=>false,hasWorkflows:(dir:string)=>boolean=()=>false):Promise<boolean>{return await agentHasQuarantinedStoreDb(agentDir)||agentHasMemory(agentDir)||hasAutomations(agentDir)||hasWorkflows(agentDir)}
export async function buildSummary(args:{extras?:DbExtras|null;dbPath:string;dirName:string;dbStats?:{mtimeMs:number};activeAgentId?:string;includeBlank:boolean;agentHasMemory?:(dir:string)=>boolean;readAvatar?:(dir:string,legacy:string|null)=>Promise<{dataUrl:string;version:string}|null>;isGroup?:boolean;memberIds?:string[];remoteRoom?:Record<string,unknown>|null}){const agentDir=dirname(args.dbPath);ensureSettingsFile(args.dbPath);const base=minimalAgentSummary(args),profile=readSandProfileFile(getSandProfilePath(agentDir)),settings=readSandSettingsFile(getSandSettingsPath(agentDir)),extras=args.extras??null,name=profile?.name?.trim()||"Grok",description=profile?.description??"",title=profile?.title??"",isGroup=args.isGroup===true,hasIdentity=isGroup||name!=="Grok"||description.trim().length>0||title.length>0;if(extras!=null&&!extras.hasTranscript&&!base.isActive&&!hasIdentity&&!args.includeBlank&&!await agentHasDurableFootprint(agentDir,args.agentHasMemory??(()=>false)))return null;const avatar=await args.readAvatar?.(agentDir,extras?.legacyAvatarPath??null)??null,isUnread=extras!=null&&(extras.unreadState.isManuallyUnread||extras.unreadState.lastActivityAt>extras.unreadState.lastViewedAt);return{...base,id:extras?.agentId??args.dirName,name,description,title,avatarDataUrl:avatar?.dataUrl??null,avatarVersion:avatar?.version??null,createdAt:extras?.createdAt??base.createdAt,updatedAt:extras?.updatedAt??base.updatedAt,lastEntry:extras?.lastEntry??null,lastMessageId:extras?.lastMessage?.id??null,lastMessagePreview:extras?.lastMessage?.preview??null,newestEntryId:extras?.newestEntryId??null,hasUnread:isUnread,unreadCount:isUnread?Math.max(extras?.unreadState.unreadCount??0,1):0,lastViewedAt:extras?.unreadState.lastViewedAt??0,lastActivityAt:extras?.unreadState.lastActivityAt??0,awaitingUserResponse:extras?.awaitingUserResponse??null,notifyOnUpdatesEnabled:settings.notifyOnAgentUpdates,isHiddenFromSidebar:settings.hiddenFromSidebar,origin:extras?.origin??"user",...(extras?.purpose==null?{}:{purpose:extras.purpose}),isGroup,memberIds:args.memberIds??[],...(args.remoteRoom==null?{}:{remoteRoom:args.remoteRoom}),conversationPartnerIds:extras?.conversationPartnerIds??[]}}
