import { lstat, mkdir, readFile, readdir, realpath, rm, stat } from "node:fs/promises";
import { basename, extname, join, resolve } from "node:path";
import grayMatter from "gray-matter";
import { detectHooksSchema, transformClaudeHooksToConfig, type CursorHooksConfig } from "../hooks/claude-code-mapper.js";
import { validateHooksConfig } from "../hooks/validators/hooksConfig.js";
import { PluginComponentDiscovery, type PluginComponentDescriptor, type PluginFileFetcher } from "./component-discovery.js";
import { DefaultPluginCacheManager } from "./cursor-marketplace.js";
import { isPathSafe, parsePluginManifest, PLUGIN_MANIFEST_PATHS, type PluginManifest, type PluginVariableSchema } from "./manifest-parser.js";
import { resolvePluginMcpConfigPaths, resolvePluginMcpConfigWithManifestLookup, type McpParserOptions, type ResolvedMcpConfig } from "./mcp-parser.js";
import { expandPluginVariables } from "./plugin-variables.js";
import { noopPluginMetricsLogger, type PluginMetricsLogger } from "./types.js";
import { validateAndResolveSubpath } from "./validate-subpath.js";
import type { BackendPluginEntry, BackendPluginListFailure } from "./backend-marketplace-client.js";

const MAX_FILE_SIZE = 10 * 1024 * 1024;
type SourceType = "cursor-first-party" | "cursor-third-party";
export interface MarketplacePluginSourceInfo {
  name: string; version: string; pluginDbId?: string | undefined; configuredVariables?: unknown; marketplace?: string | undefined; marketplaceDbId?: string | undefined; isTeamRequired?: boolean | undefined;
}
export interface LoadedSkill { path: string; name: string; description?: string | undefined; globs?: string[] | undefined; alwaysApply: boolean; content: string; environments?: string[] | undefined; disabledEnvironments?: string[] | undefined }
export interface LoadedAgent { path: string; name: string; description?: string | undefined; tools?: string[] | undefined; model: string; prompt: string; permissionMode: "readonly" | "default" }
export interface LoadedCommand { path: string; name: string; description?: string | undefined; argumentHint?: string | undefined; content: string }
export interface LoadedPlugin {
  identifier: { source: SourceType; sourceInfo: MarketplacePluginSourceInfo };
  installPath: string; displayName?: string | undefined; description?: string | undefined; authorName?: string | undefined; variablesSchema?: PluginVariableSchema | undefined;
  skills: LoadedSkill[]; rules: LoadedSkill[]; agents: LoadedAgent[]; commands: LoadedCommand[]; mcpConfig?: ResolvedMcpConfig | undefined; capabilities: string[]; hooks?: PluginHooksResult | undefined; loadError?: string | undefined;
}
type PluginHooksCoreResult = { config: CursorHooksConfig } | { error: { source: "claude-plugin"; message: string } };
export type PluginHooksResult = { config: CursorHooksConfig; sourcePath?: string | undefined } | { error: { source: "claude-plugin"; message: string } };

async function isSymlink(filePath: string): Promise<boolean> { try { return (await lstat(filePath)).isSymbolicLink(); } catch { return false; } }
async function readFileNoSymlink(filePath: string): Promise<string> { if (await isSymlink(filePath)) throw new Error(`Refusing to read symlink: ${filePath}`); return readFile(filePath, "utf-8"); }
async function checkFileSize(filePath: string): Promise<void> { const stats = await stat(filePath); if (stats.size > MAX_FILE_SIZE) throw new Error(`File ${filePath} exceeds maximum size of ${MAX_FILE_SIZE} bytes`); }
function classifyLoadError(error: unknown): "timeout" | "clone" | "manifest" | "parse" | "install" | "unknown" { const message = error instanceof Error ? error.message : String(error); if (/timed?\s*out/i.test(message)) return "timeout"; if (/clone|fetch|git/i.test(message)) return "clone"; if (/manifest|marketplace\.json/i.test(message)) return "manifest"; if (/parse|invalid|malformed/i.test(message)) return "parse"; if (/install|download|copy/i.test(message)) return "install"; return "unknown"; }

export function createLocalPluginFileFetcher(basePath: string, options?: { symlinkTargetRoot?: string | undefined }): PluginFileFetcher {
  const fileContentCache = new Map<string, string>(), resolvedBasePath = resolve(basePath), resolvedSymlinkTargetRoot = resolve(options?.symlinkTargetRoot ?? resolvedBasePath), allowedRealPath = realpath(resolvedSymlinkTargetRoot).catch(() => resolvedSymlinkTargetRoot);
  const assertContained = (fullPath: string): string => { const resolvedFullPath = resolve(fullPath); try { return validateAndResolveSubpath(resolvedBasePath, resolvedFullPath); } catch { throw new Error(`Path escapes plugin directory: ${fullPath}`); } };
  const assertContainedRealPath = async (fullPath: string): Promise<string> => { const contained = assertContained(fullPath), allowed = await allowedRealPath, actual = await realpath(contained); try { return validateAndResolveSubpath(allowed, actual); } catch { throw new Error(`Path escapes plugin directory via symlink: ${fullPath}`); } };
  return {
    async listDirectory(dirPath: string, visitedRealDirPaths?: Set<string>) {
      const candidate = assertContained(dirPath ? join(basePath, dirPath) : basePath);
      try { const fullPath = await assertContainedRealPath(candidate); if (visitedRealDirPaths?.has(fullPath)) return []; visitedRealDirPaths?.add(fullPath); const entries = await readdir(fullPath, { withFileTypes: true }), results = [];
        for (const entry of entries) { const entryFullPath = join(candidate, entry.name); let entryType: "dir" | "file" = entry.isDirectory() ? "dir" : "file"; if (entry.isSymbolicLink()) try { entryType = (await stat(await assertContainedRealPath(entryFullPath))).isDirectory() ? "dir" : "file"; } catch { continue; } results.push({ name: entry.name, type: entryType, path: dirPath ? `${dirPath}/${entry.name}` : entry.name }); }
        return results;
      } catch { return []; }
    },
    async fetchFile(filePath: string) { const cached = fileContentCache.get(filePath); if (cached !== undefined) return { content: cached }; const fullPath = await assertContainedRealPath(assertContained(join(basePath, filePath))); await checkFileSize(fullPath); const content = await readFile(fullPath, "utf-8"); fileContentCache.set(filePath, content); return { content }; },
    async fileExists(filePath: string) { try { const fullPath = await assertContainedRealPath(assertContained(join(basePath, filePath))); return (await stat(fullPath)).isFile(); } catch { return false; } },
  };
}

interface ManifestData {
  manifestFilePath: string;
  manifestOptions?: Pick<PluginManifest, "commands" | "agents" | "skills" | "rules" | "hooks" | "mcpServers"> | undefined;
  metadata?: { displayName?: string | undefined; description?: string | undefined; authorName?: string | undefined; variables?: PluginVariableSchema | undefined; capabilities?: string[] | undefined } | undefined;
}
async function readLocalPluginManifestData(installPath: string, pluginDisplayName: string, pluginLogger: PluginMetricsLogger): Promise<ManifestData | undefined> {
  for (const manifestPath of PLUGIN_MANIFEST_PATHS) {
    const fullPath = join(installPath, manifestPath); let content: string;
    try { if (await isSymlink(fullPath)) continue; const stats = await stat(fullPath); if (!stats.isFile()) continue; await checkFileSize(fullPath); content = await readFileNoSymlink(fullPath); } catch { continue; }
    const parsed = parsePluginManifest(content); if (!parsed.success) continue; const manifest = parsed.data;
    const { commands, agents, skills, rules, hooks, mcpServers } = manifest, hasOptions = commands !== undefined || agents !== undefined || skills !== undefined || rules !== undefined || hooks !== undefined || mcpServers !== undefined;
    const displayName = typeof manifest.displayName === "string" ? manifest.displayName : undefined, description = typeof manifest.description === "string" ? manifest.description : undefined, authorName = manifest.author?.name, variables = manifest.variables, capabilities = manifest.capabilities;
    const hasMetadata = displayName !== undefined || description !== undefined || authorName !== undefined || variables !== undefined || capabilities !== undefined; if (!hasOptions && !hasMetadata) continue;
    if (parsed.unrecognizedSchemaId !== undefined) pluginLogger.log("warn", `${pluginDisplayName}: ${manifestPath} declares an unrecognized $schema, loading anyway: ${parsed.unrecognizedSchemaId}`);
    return { manifestFilePath: fullPath, ...(hasOptions ? { manifestOptions: { commands, agents, skills, rules, hooks, mcpServers } } : {}), ...(hasMetadata ? { metadata: { displayName, description, authorName, variables, capabilities } } : {}) };
  }
  return undefined;
}

function normalizeEnvironmentList(value: unknown): string[] | undefined { if (Array.isArray(value)) { const normalized = value.filter((entry): entry is string => typeof entry === "string" && entry.length > 0); return normalized.length === 0 ? undefined : normalized; } if (typeof value === "string") { const normalized = value.split(",").map(entry => entry.trim()).filter(entry => entry.length > 0); return normalized.length === 0 ? undefined : normalized; } return undefined; }
function splitCommaSeparatedGlobs(value: string): string[] { const globs: string[] = []; let start = 0, braceDepth = 0; for (let index = 0; index < value.length; index++) { const character = value[index]; if (character === "{") braceDepth++; else if (character === "}" && braceDepth > 0) braceDepth--; else if (character === "," && braceDepth === 0) { const glob = value.slice(start, index).trim(); if (glob) globs.push(glob); start = index + 1; } } const glob = value.slice(start).trim(); if (glob) globs.push(glob); return globs; }
function parseGlobs(value: unknown): string[] | undefined { if (typeof value === "string") { const globs = splitCommaSeparatedGlobs(value); return globs.length > 0 ? globs : undefined; } if (Array.isArray(value)) { const globs = value.filter((entry): entry is string => typeof entry === "string").map(entry => entry.trim()).filter(Boolean); return globs.length > 0 ? globs : undefined; } return undefined; }
function parseSkillContent({ content, relativePath }: { content: string; relativePath: string }): LoadedSkill | null { try { const parsed = grayMatter(content), data = parsed.data as Record<string, unknown>, normalized = relativePath.replace(/\\/g, "/"), segments = normalized.split("/").filter(Boolean), parent = segments.length >= 2 ? segments[segments.length - 2] : undefined, fileName = segments[segments.length - 1] ?? normalized, fallbackName = parent ?? fileName.replace(/\.md$/i, ""), frontmatterName = typeof data.name === "string" ? data.name.trim() : undefined, metadata = data.metadata as Record<string, unknown> | undefined; return { path: relativePath, name: frontmatterName && frontmatterName.length > 0 ? frontmatterName : fallbackName, description: typeof data.description === "string" ? data.description : undefined, globs: parseGlobs(data.globs), alwaysApply: data.alwaysApply === true, content, environments: normalizeEnvironmentList(data.environments ?? metadata?.environments), disabledEnvironments: normalizeEnvironmentList(data["disabled-environments"] ?? metadata?.disabledEnvironments) }; } catch { return null; } }
function parsePermissionMode(raw: string | undefined): "readonly" | "default" { return (raw ?? "").trim().toLowerCase() === "readonly" ? "readonly" : "default"; }
function parseAgentContent({ content, relativePath }: { content: string; relativePath: string }): LoadedAgent | null { try { const parsed = grayMatter(content), data = parsed.data as Record<string, unknown>, body = parsed.content.trim(); if (!body) return null; let tools: string[] | undefined; if (typeof data.tools === "string") tools = data.tools.split(",").map(tool => tool.trim()).filter(Boolean); else if (Array.isArray(data.tools)) tools = data.tools.map(tool => typeof tool === "string" ? tool.trim() : String(tool)).filter(Boolean); const fileName = basename(relativePath), permission = data.permissionMode ?? data.permissionmode; return { path: relativePath, name: typeof data.name === "string" ? data.name : basename(fileName, extname(fileName)).replace(/[\s_]+/g, "-"), description: typeof data.description === "string" ? data.description : undefined, tools, model: typeof data.model === "string" ? data.model : "inherit", prompt: body, permissionMode: parsePermissionMode(typeof permission === "string" ? permission : undefined) }; } catch { return null; } }
function parseCommandContent({ content, relativePath }: { content: string; relativePath: string }): LoadedCommand | null { try { const parsed = grayMatter(content), data = parsed.data as Record<string, unknown>; let argumentHint: string | undefined; if (typeof data["argument-hint"] === "string") argumentHint = data["argument-hint"]; else if (Array.isArray(data["argument-hint"])) argumentHint = `[${data["argument-hint"].join(" ")}]`; const fileName = basename(relativePath); return { path: relativePath, name: typeof data.name === "string" ? data.name : basename(fileName, extname(fileName)), description: typeof data.description === "string" ? data.description : undefined, argumentHint, content: parsed.content.trim() }; } catch { return null; } }

async function loadDiscovered<T>(fetcher: PluginFileFetcher, descriptors: PluginComponentDescriptor[], installPath: string, parser: (args: { content: string; relativePath: string }) => T | null): Promise<T[]> { const results: T[] = []; for (const descriptor of descriptors) try { const content = expandPluginVariables((await fetcher.fetchFile(descriptor.path)).content, installPath), parsed = parser({ content, relativePath: descriptor.path }); if (parsed) results.push(parsed); } catch {} return results; }
async function discoverAndLoadComponents(installPath: string, manifest?: ManifestData["manifestOptions"]): Promise<Pick<LoadedPlugin, "skills" | "agents" | "commands" | "rules">> { const fetcher = createLocalPluginFileFetcher(installPath), discovered = await new PluginComponentDiscovery(fetcher).discoverComponents({ manifest }); const [skills, agents, commands, rules] = await Promise.all([loadDiscovered(fetcher, discovered.skills, installPath, parseSkillContent), loadDiscovered(fetcher, discovered.agents, installPath, parseAgentContent), loadDiscovered(fetcher, discovered.commands, installPath, parseCommandContent), loadDiscovered(fetcher, discovered.rules, installPath, (args) => { const skill = parseSkillContent(args); return skill ? { ...skill, name: discovered.rules.find(rule => rule.path === args.relativePath)?.name ?? skill.name } : null; })]); return { skills, agents, commands, rules }; }

function mcpParseOptionsFromPluginSource(sourceInfo?: MarketplacePluginSourceInfo): McpParserOptions | undefined { return sourceInfo === undefined ? undefined : { configuredVariables: sourceInfo.configuredVariables as Readonly<Record<string, unknown>> | undefined }; }
function createSafeFsPluginMcpFileReader(installPath: string) { return async (relativePath: string): Promise<string | null> => { if (!isPathSafe(relativePath)) return null; const fullPath = join(installPath, relativePath); try { if (await isSymlink(fullPath)) return null; if (!(await stat(fullPath)).isFile()) return null; await checkFileSize(fullPath); return await readFileNoSymlink(fullPath); } catch { return null; } }; }
async function readPluginMcpConfigSimple(installPath: string, sourceInfo: MarketplacePluginSourceInfo | undefined, explicit?: McpParserOptions): Promise<ResolvedMcpConfig | null> { const parserOptions = explicit ?? mcpParseOptionsFromPluginSource(sourceInfo); return resolvePluginMcpConfigWithManifestLookup(createSafeFsPluginMcpFileReader(installPath), { fallbackFileNames: resolvePluginMcpConfigPaths(), manifestPrecedence: "override", toSourcePath: relative => join(installPath, relative), installPathForExpansion: installPath, parserOptions }); }

function expandHooksConfigVariables(config: CursorHooksConfig, installPath: string): CursorHooksConfig { const hooks: Record<string, CursorHooksConfig["hooks"][string]> = {}; for (const [step, scripts] of Object.entries(config.hooks)) { if (!Array.isArray(scripts)) continue; hooks[step] = scripts.map(script => "command" in script && typeof script.command === "string" ? { ...script, command: expandPluginVariables(script.command, installPath) } : "prompt" in script && typeof script.prompt === "string" ? { ...script, prompt: expandPluginVariables(script.prompt, installPath) } : script); } return { ...config, hooks }; }
function validateAndTransformHooks(parsed: unknown, pluginDisplayName: string): PluginHooksCoreResult | undefined { const schema = detectHooksSchema(parsed); if (schema === "cursor") { const config = parsed as CursorHooksConfig, validation = validateHooksConfig(config); return validation.isValid ? { config } : { error: { source: "claude-plugin", message: `Plugin ${pluginDisplayName} hooks: ${validation.errors.join("; ")}` } }; } if (schema === "claude-code") { const hooks = (parsed as { hooks?: Record<string, unknown> } | null)?.hooks; if (!hooks || Object.keys(hooks).length === 0) return undefined; const config = transformClaudeHooksToConfig(hooks), validation = validateHooksConfig(config); return validation.isValid ? { config } : { error: { source: "claude-plugin", message: `Plugin ${pluginDisplayName} hooks: ${validation.errors.join("; ")}` } }; } return undefined; }
async function loadPluginHooksInternal(installPath: string, pluginDisplayName: string, manifestHooks: unknown, manifestSourcePath?: string): Promise<PluginHooksResult | undefined> {
  if (typeof manifestHooks === "object" && manifestHooks !== null) { const result = validateAndTransformHooks(manifestHooks, pluginDisplayName); if (result && "config" in result) return { config: expandHooksConfigVariables(result.config, installPath), ...(manifestSourcePath !== undefined ? { sourcePath: manifestSourcePath } : {}) }; return result; }
  let hooksPath: string; if (typeof manifestHooks === "string") { const relative = manifestHooks.replace(/^\.\//, ""); if (!isPathSafe(relative)) return undefined; hooksPath = relative.endsWith(".json") ? join(installPath, relative) : join(installPath, relative, "hooks.json"); } else hooksPath = join(installPath, "hooks", "hooks.json");
  try { if (await isSymlink(hooksPath) || !(await stat(hooksPath)).isFile()) return undefined; } catch { return undefined; }
  let raw: string; try { await checkFileSize(hooksPath); raw = await readFile(hooksPath, "utf-8"); } catch { return undefined; }
  let parsed: unknown; try { parsed = JSON.parse(raw); } catch { return { error: { source: "claude-plugin", message: `Plugin ${pluginDisplayName} ${hooksPath}: invalid JSON` } }; }
  const result = validateAndTransformHooks(parsed, pluginDisplayName); return result && "config" in result ? { config: expandHooksConfigVariables(result.config, installPath), sourcePath: hooksPath } : result;
}

async function loadPluginContentFromDir(installPath: string, pluginDisplayName: string, sourceInfo?: MarketplacePluginSourceInfo, options?: { log?: PluginMetricsLogger | undefined; configuredVariables?: Readonly<Record<string, unknown>> | undefined }) {
  const pluginLogger = options?.log ?? noopPluginMetricsLogger, manifestData = await readLocalPluginManifestData(installPath, pluginDisplayName, pluginLogger), parserOptions = { ...(mcpParseOptionsFromPluginSource(sourceInfo) ?? (options?.configuredVariables ? { configuredVariables: options.configuredVariables } : undefined)), log: pluginLogger };
  const [components, mcpConfig, hooks] = await Promise.all([discoverAndLoadComponents(installPath, manifestData?.manifestOptions), readPluginMcpConfigSimple(installPath, sourceInfo, parserOptions), loadPluginHooksInternal(installPath, pluginDisplayName, manifestData?.manifestOptions?.hooks, manifestData?.manifestFilePath)]);
  return { ...components, ...(manifestData?.metadata?.displayName !== undefined ? { displayName: manifestData.metadata.displayName } : {}), ...(manifestData?.metadata?.description !== undefined ? { description: manifestData.metadata.description } : {}), ...(manifestData?.metadata?.authorName !== undefined ? { authorName: manifestData.metadata.authorName } : {}), variablesSchema: manifestData?.metadata?.variables, mcpConfig, capabilities: manifestData?.metadata?.capabilities ?? [], hooks };
}
export async function loadCursorPluginFromPath(installPath: string, sourceType: SourceType, sourceInfo: MarketplacePluginSourceInfo, options?: { log?: PluginMetricsLogger | undefined }): Promise<LoadedPlugin> { const content = await loadPluginContentFromDir(installPath, `${sourceInfo.name}@${sourceInfo.version}`, sourceInfo, { log: options?.log }); return { identifier: { source: sourceType, sourceInfo }, installPath, ...(content.displayName !== undefined ? { displayName: content.displayName } : {}), ...(content.description !== undefined ? { description: content.description } : {}), ...(content.authorName !== undefined ? { authorName: content.authorName } : {}), variablesSchema: content.variablesSchema, skills: content.skills, rules: content.rules, agents: content.agents, commands: content.commands, mcpConfig: content.mcpConfig ?? undefined, capabilities: content.capabilities, hooks: content.hooks }; }

export interface MarketplaceLoaderClient { listEnabledPlugins(userId: string, teamId?: string): Promise<{ plugins: BackendPluginEntry[]; listFailures?: BackendPluginListFailure[] | undefined }>; installPlugin(entry: BackendPluginEntry, targetDir: string): Promise<void> }
export interface MarketplaceLoadFailure { pluginName: string; pluginId: string; pluginDbId?: string | undefined; marketplaceName?: string | undefined; errorMessage: string; errorType: "timeout" | "clone" | "manifest" | "parse" | "install" | "unknown" }
export interface MarketplaceLoadOptions {
  client: MarketplaceLoaderClient; userId: string; teamId?: string | undefined; userHomeDir?: string | undefined; cacheManager?: DefaultPluginCacheManager | undefined; log?: PluginMetricsLogger | undefined; pruneOldVersions?: boolean | undefined; pluginFilter?: ((entry: BackendPluginEntry) => boolean) | undefined; onCursorError?: ((entry: BackendPluginEntry, error: Error) => void) | undefined; onPluginsListed?: ((entries: readonly BackendPluginEntry[]) => Promise<void>) | undefined;
}
export async function loadFromMarketplaceSource(options: MarketplaceLoadOptions): Promise<{ plugins: LoadedPlugin[]; failures: MarketplaceLoadFailure[]; sourceUnavailable: boolean }> {
  const pluginLogger = options.log ?? noopPluginMetricsLogger, startTime = performance.now(), { client, userId, teamId, onCursorError, pruneOldVersions, pluginFilter, onPluginsListed } = options, failures: MarketplaceLoadFailure[] = [], cacheManager = options.cacheManager ?? new DefaultPluginCacheManager(options.userHomeDir), listStart = performance.now();
  let response: Awaited<ReturnType<MarketplaceLoaderClient["listEnabledPlugins"]>>;
  try { response = await client.listEnabledPlugins(userId, teamId); } catch (error) { pluginLogger.captureException(error, { error_type: "list_enabled_plugins" }); pluginLogger.increment("marketplace.source_unavailable", 1); pluginLogger.log("error", `marketplace listEnabledPlugins failed after ${(performance.now() - listStart).toFixed(1)}ms; treating source as unavailable: ${error instanceof Error ? error.message : String(error)}`); return { plugins: [], failures: [], sourceUnavailable: true }; }
  pluginLogger.log("info", `marketplace listEnabledPlugins completed in ${(performance.now() - listStart).toFixed(1)}ms (${response.plugins.length} plugins)`); if (onPluginsListed) await onPluginsListed(response.plugins);
  const plugins: LoadedPlugin[] = [];
  if (response.listFailures) { failures.push(...response.listFailures); for (const failure of response.listFailures) plugins.push({ identifier: { source: failure.marketplaceName && failure.marketplaceName !== "cursor-public" ? "cursor-third-party" : "cursor-first-party", sourceInfo: { name: failure.pluginName, version: "", ...(failure.pluginDbId !== undefined ? { pluginDbId: failure.pluginDbId } : {}), marketplace: failure.marketplaceName } }, installPath: "", loadError: failure.errorMessage, skills: [], rules: [], agents: [], commands: [], capabilities: [] }); }
  const versionsByKey = new Map<string, { slug: string; pluginId: string; versions: string[] }>();
  for (const entry of response.plugins) {
    if (pluginFilter && !pluginFilter(entry)) continue;
    try {
      const slug = entry.marketplace?.name; if (!slug) { const error = new Error(`Plugin ${entry.name} has no marketplace metadata — cannot determine cache path`); failures.push({ pluginName: entry.name, pluginId: entry.pluginId, marketplaceName: undefined, errorMessage: error.message, errorType: "manifest" }); onCursorError?.(entry, error); continue; }
      const cacheKey = `${slug}/${entry.pluginId}`; let record = versionsByKey.get(cacheKey); if (!record) { record = { slug, pluginId: entry.pluginId, versions: [] }; versionsByKey.set(cacheKey, record); } record.versions.push(entry.version);
      const cacheArgs = { marketplaceSlug: slug, pluginId: entry.pluginId, version: entry.version }; let installPath: string;
      if (await cacheManager.isCached(cacheArgs)) { installPath = cacheManager.getCacheDir(cacheArgs); pluginLogger.log("info", `loadFromMarketplaceSource: Found cached plugin: ${entry.pluginId} at ${installPath}`, { marketplaceSlug: slug, pluginId: entry.pluginId, gitRef: entry.version, marketplaceId: entry.marketplace?.id }); }
      else { const targetDir = cacheManager.getCacheDir(cacheArgs); pluginLogger.log("info", `loadFromMarketplaceSource: Plugin missing from cache, installing: ${entry.pluginId} at ${targetDir}`, { marketplaceSlug: slug, pluginId: entry.pluginId, gitRef: entry.version, marketplaceId: entry.marketplace?.id }); await mkdir(targetDir, { recursive: true }); try { await client.installPlugin(entry, targetDir); await cacheManager.markCacheComplete(cacheArgs); } catch (error) { try { await rm(targetDir, { recursive: true, force: true }); } catch {} throw error; } installPath = targetDir; }
      const marketplaceName = entry.marketplace?.name, sourceType = marketplaceName !== undefined && marketplaceName !== "cursor-public" && marketplaceName.length > 0 ? "cursor-third-party" : "cursor-first-party", sourceInfo: MarketplacePluginSourceInfo = { name: entry.name, version: entry.version, pluginDbId: entry.pluginDbId, configuredVariables: entry.configuredVariables, marketplace: marketplaceName, marketplaceDbId: entry.marketplaceDbId, isTeamRequired: entry.isTeamRequired };
      plugins.push(await loadCursorPluginFromPath(installPath, sourceType, sourceInfo, { log: pluginLogger })); try { await cacheManager.pruneOldVersions({ marketplaceSlug: slug, pluginId: entry.pluginId, keepVersions: [entry.version] }); } catch {}
    } catch (error) {
      pluginLogger.captureException(error, { error_type: "load_plugin_from_marketplace" }); const normalized = error instanceof Error ? error : new Error(String(error)), marketplaceName = entry.marketplace?.name, sourceType = marketplaceName !== undefined && marketplaceName !== "cursor-public" && marketplaceName.length > 0 ? "cursor-third-party" : "cursor-first-party";
      failures.push({ pluginName: entry.name, pluginId: entry.pluginId, marketplaceName, errorMessage: normalized.message, errorType: classifyLoadError(normalized) }); plugins.push({ identifier: { source: sourceType, sourceInfo: { name: entry.name, version: entry.version, pluginDbId: entry.pluginDbId, marketplace: marketplaceName, marketplaceDbId: entry.marketplaceDbId, isTeamRequired: entry.isTeamRequired } }, installPath: "", loadError: normalized.message || "Plugin load failed", skills: [], rules: [], agents: [], commands: [], capabilities: [] }); onCursorError?.(entry, normalized);
    }
  }
  if (pruneOldVersions) for (const { slug, pluginId, versions } of versionsByKey.values()) try { await cacheManager.pruneOldVersions({ marketplaceSlug: slug, pluginId, keepVersions: versions }); } catch {}
  pluginLogger.log("info", `loadFromMarketplaceSource completed in ${(performance.now() - startTime).toFixed(1)}ms (${plugins.length} plugins loaded, ${failures.length} failures)`); return { plugins, failures, sourceUnavailable: false };
}
