import { copyFileSync, existsSync, renameSync, rmSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import { SQLITE_DB_SIDECAR_SUFFIXES } from "./store-db.js";
export function removeSqliteSidecars(dbPath: string): void { for (const suffix of SQLITE_DB_SIDECAR_SUFFIXES) try { rmSync(`${dbPath}${suffix}`, { force: true, recursive: true }); } catch {} }
export function removePathWithRetries(options: { path: string; attempts?: number | undefined; retryDelayMs?: number | undefined; recursive?: boolean | undefined }): void { const attempts = Math.max(1, options.attempts ?? 1); let failure: unknown; for (let attempt = 0; attempt < attempts; attempt += 1) { try { rmSync(options.path, { force: true, recursive: options.recursive === true }); failure = undefined; break; } catch (error) { failure = error; if (attempt < attempts - 1) Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, options.retryDelayMs ?? 50); } } if (failure != null) throw failure; }
export function removeSqliteDb(options: { dbPath: string; attempts?: number | undefined; retryDelayMs?: number | undefined }): void { removePathWithRetries({ path: options.dbPath, attempts: options.attempts, retryDelayMs: options.retryDelayMs }); for (const suffix of SQLITE_DB_SIDECAR_SUFFIXES) removePathWithRetries({ path: `${options.dbPath}${suffix}`, attempts: options.attempts, retryDelayMs: options.retryDelayMs, recursive: true }); }
export function quarantineCorruptSqliteDb(options: { dbPath: string; quarantinePath?: string; preserveSourceOnCopyFailure?: boolean; removeAttempts?: number | undefined; removeRetryDelayMs?: number | undefined }): { quarantinePath: string | null; copied: boolean; renameErrorCode: string | null } { const stamp = new Date().toISOString().replace(/[:.]/g, "-"), quarantinePath = options.quarantinePath ?? `${options.dbPath}.corrupt-${stamp}`; try { rmSync(quarantinePath, { force: true }); removeSqliteSidecars(quarantinePath); } catch {} try { renameSync(options.dbPath, quarantinePath); } catch (error) { const renameErrorCode = String((error as { code?: unknown }).code ?? "error"); let copied = false; try { copyFileSync(options.dbPath, quarantinePath); copied = true; for (const suffix of SQLITE_DB_SIDECAR_SUFFIXES) if (existsSync(`${options.dbPath}${suffix}`)) try { copyFileSync(`${options.dbPath}${suffix}`, `${quarantinePath}${suffix}`); } catch {} } catch { if (options.preserveSourceOnCopyFailure === true) return { quarantinePath: options.dbPath, copied: false, renameErrorCode }; } removeSqliteDb({ dbPath: options.dbPath, attempts: options.removeAttempts, retryDelayMs: options.removeRetryDelayMs }); return { quarantinePath: copied ? quarantinePath : null, copied, renameErrorCode }; } for (const suffix of SQLITE_DB_SIDECAR_SUFFIXES) try { const sidecar = `${options.dbPath}${suffix}`; if (existsSync(sidecar)) renameSync(sidecar, `${quarantinePath}${suffix}`); } catch { rmSync(`${options.dbPath}${suffix}`, { force: true }); } return { quarantinePath, copied: false, renameErrorCode: null }; }
export function openSqliteForSalvage(options: { dbPath: string; busyTimeoutMs?: number }): DatabaseSync | undefined { if (!existsSync(options.dbPath)) return undefined; const open = () => { const db = new DatabaseSync(options.dbPath); try { if (options.busyTimeoutMs != null) db.exec(`PRAGMA busy_timeout = ${options.busyTimeoutMs}`); db.prepare("PRAGMA schema_version").get(); return db; } catch (error) { try { db.close(); } catch {} throw error; } }; try { return open(); } catch { removeSqliteSidecars(options.dbPath); try { return open(); } catch { try { return new DatabaseSync(options.dbPath); } catch { return undefined; } } } }
export function copySalvageableSqliteRows(source: { prepare(sql: string): { iterate(): Iterator<unknown> } }, selectSql: string, insert: { run(...params: unknown[]): unknown }, toParams: (row: unknown) => unknown[]): number { let iterator: Iterator<unknown>; try { iterator = source.prepare(selectSql).iterate(); } catch { return 0; } let copied = 0; try { for (;;) { let next: IteratorResult<unknown>; try { next = iterator.next(); } catch { break; } if (next.done) break; try { insert.run(...toParams(next.value)); copied += 1; } catch {} } } finally { try { iterator.return?.(); } catch {} } return copied; }
