import { resolve } from "node:path";
import type { Context } from "../context/core.js";
import { ForceBackgroundShellResult,ForceBackgroundShellStatus,ShellAbortReason,ShellBackgroundReason,ShellCommandParsingResult,ShellPermissionDenied,ShellRejected,ShellResult,ShellSandboxUnsupported,ShellStream,ShellStreamBackgrounded,ShellStreamExit,ShellStreamStart,ShellStreamStderr,ShellStreamStdout,ShellSuccess,TimeoutBehavior } from "../proto/generated/agent/v1/shell_exec_pb.js";
import type { SandboxPolicy as ProtoSandboxPolicy } from "../proto/generated/agent/v1/sandbox_pb.js";
import { getShellHookApprovalRequirement } from "../agent-exec/shell-hook-approval.js";
import { analyzeShellCommand } from "../shell-exec/shell-parser.js";
import { SandboxUnsupportedError } from "../shell-exec/sandbox/errors.js";
import { convertInternalToProtoPolicy, convertProtoToInternalPolicy } from "./sandbox-conversion.js";
import { isForcedShellEgressEnabled, forcedShellSandboxPolicy } from "./forced-egress.js";
import { resolveShellTimeoutMs } from "./shell-timeout.js";
import { getModelShellAdminCommandDenylistBlockReason } from "./services/admin-command-denylist.js";
import { shellBlockReasonMessage } from "./utils/edit-block-handler.js";
import type { ShellBlockReason } from "./utils/edit-block-handler.js";
import type { BackgroundShellManager } from "./background-shell.js";
import type { BaseShellCoreExecutor,SandboxPolicy,SandboxRule,ShellCoreEvent } from "./shell-core.js";

type Block={kind:"block";reason:ShellBlockReason}|{kind:"allow";policy?:SandboxRule};
export interface ShellPermissions { shouldEnforceShellInvariantBlocks(ctx:Context,options:unknown,policy:SandboxRule|undefined):Promise<Block>;shouldBlockShellCommand(ctx:Context,command:string,options:unknown,policy:SandboxRule|undefined):Promise<Block> }
export interface ShellIgnoreService { getCursorIgnoreMapping():Promise<unknown> }
export interface ShellStreamArgs{command:string;workingDirectory?:string;toolCallId?:string;conversationId?:string;requestedSandboxPolicy?:ProtoSandboxPolicy;closeStdin?:boolean;timeout?:number;timeoutBehavior?:TimeoutBehavior;hardTimeout?:number;fileOutputThresholdBytes?:number;adminCommandDenylist?:readonly string[];skipApproval?:boolean;smartModeApproval?:{reason?:string;requestId?:string};classifierResult?:unknown;description?:string;outputNotification?:unknown;hookApprovalRequirement?:import("../proto/generated/agent/v1/shell_exec_pb.js").ShellHookApprovalRequirement;isBackground?:boolean}
type StopReason={kind:"background";reason:number}|{kind:"abort"};
class BackgroundableIterator<T>{private pending:Promise<IteratorResult<T>>|null=null;private reason?:StopReason;private timer?:ReturnType<typeof setTimeout>;private resolveStop?:()=>void;private readonly stopped=new Promise<void>((r)=>{this.resolveStop=r;});constructor(private readonly iterator:AsyncIterator<T>,private readonly timeoutMs:number){}stop(reason:StopReason):boolean{if(this.reason!==undefined)return false;this.reason=reason;this.resolveStop?.();return true;}get timedOut():boolean{return this.reason?.kind==="background"&&this.reason.reason===ShellBackgroundReason.TIMEOUT;}get backgroundRequested():boolean{return this.reason?.kind==="background";}get backgroundReason():number|undefined{return this.reason?.kind==="background"?this.reason.reason:undefined;}get stopReason():StopReason|undefined{return this.reason;}requestBackground():boolean{return this.stop({kind:"background",reason:ShellBackgroundReason.USER_REQUEST});}abort():void{this.stop({kind:"abort"});}async *iterate():AsyncIterable<T>{this.timer=setTimeout(()=>this.stop({kind:"background",reason:ShellBackgroundReason.TIMEOUT}),this.timeoutMs);try{while(true){this.pending=this.iterator.next();const raced=await Promise.race([this.pending.then(result=>({kind:"result" as const,result})),this.stopped.then(()=>({kind:"stopped" as const}))]);if(raced.kind==="stopped")return;this.pending=null;if(raced.result.done)return;yield raced.result.value;}}finally{clearTimeout(this.timer);}}handoff():AsyncIterator<T>{if(!this.pending)return this.iterator;const pending=this.pending;this.pending=null;let consumed=false;return{next:async()=>{if(!consumed){consumed=true;return pending;}return this.iterator.next();}};}}

export class LocalShellStreamExecutor{
  private readonly active=new Map<string,{requestBackground:()=>ShellResult|undefined}>();
  constructor(private readonly permissions:ShellPermissions,private readonly core:BaseShellCoreExecutor,private readonly ignore:ShellIgnoreService,private readonly background:BackgroundShellManager){}
  async forceBackgroundByToolCallId(id:string):Promise<ForceBackgroundShellResult>{const shellResult=this.active.get(id)?.requestBackground();return shellResult===undefined?new ForceBackgroundShellResult({status:ForceBackgroundShellStatus.NOT_FOUND}):new ForceBackgroundShellResult({status:ForceBackgroundShellStatus.ACCEPTED,shellResult});}
  async *execute(ctx:Context,args:ShellStreamArgs):AsyncIterable<ShellStream>{ctx.signal.throwIfAborted();const command=args.command;let policy=args.requestedSandboxPolicy?convertProtoToInternalPolicy(args.requestedSandboxPolicy):undefined;if(policy&&policy.type!=="insecure_none")policy={...policy,type:policy.type,ignoreMapping:await this.ignore.getCursorIgnoreMapping()};const workingDirectory=args.workingDirectory||await this.core.getCwd(),resolved=resolve(workingDirectory),startTime=Date.now(),timeout=resolveShellTimeoutMs({timeout:args.timeout??0,isBackground:args.isBackground??false,...(args.timeoutBehavior===undefined?{}:{timeoutBehavior:args.timeoutBehavior}),...(args.hardTimeout===undefined?{}:{hardTimeout:args.hardTimeout})}),analysis=analyzeShellCommand(command).structured,parsing=new ShellCommandParsingResult({parsingFailed:analysis.parsingFailed,executableCommands:analysis.executableCommands.map((item)=>({name:item.name,fullText:item.fullText,args:item.args.map((arg)=>({type:arg.type,value:arg.value}))})),hasRedirects:analysis.hasRedirects,hasCommandSubstitution:analysis.hasCommandSubstitution,...(analysis.allRedirectsAreDevNull===undefined?{}:{allRedirectsAreDevNull:analysis.allRedirectsAreDevNull}),redirects:analysis.redirects.map((item)=>({operator:item.operator,destinationFds:[...item.destinationFds],targetNodeType:item.targetNodeType,...(item.targetText===undefined?{}:{targetText:item.targetText})}))});const modelBlock=getModelShellAdminCommandDenylistBlockReason({command,parsingResult:parsing,blockedCommands:args.adminCommandDenylist??[]});if(modelBlock!==undefined){yield new ShellStream({event:{case:"rejected",value:new ShellRejected({command,workingDirectory:resolved,reason:modelBlock})}});return;}
    const invariant=await this.permissions.shouldEnforceShellInvariantBlocks(ctx,{workingDirectory:resolved,skipUnsafeWorkingDirectoryBlock:true,command,parsingResult:parsing,toolCallId:args.toolCallId},policy);if(invariant.kind==="block"){if(invariant.reason.type==="permissionsConfig"){yield new ShellStream({event:{case:"permissionDenied",value:new ShellPermissionDenied({command,workingDirectory:resolved,error:"Command blocked by permissions configuration",isReadonly:invariant.reason.isReadonly??false})}});}else yield new ShellStream({event:{case:"rejected",value:new ShellRejected({command,workingDirectory:resolved,reason:shellBlockReasonMessage(invariant.reason)})}});return;}
    if(!args.skipApproval){const block=await this.permissions.shouldBlockShellCommand(ctx,command,{workingDirectory:resolved,timeout,parsingResult:parsing,toolCallId:args.toolCallId,classifierResult:args.classifierResult,smartModeApprovalReason:args.smartModeApproval?.reason,smartModeApprovalRequestId:args.smartModeApproval?.requestId,hookApprovalRequirement:getShellHookApprovalRequirement(args)},policy);if(block.kind==="block"){if(block.reason.type==="permissionsConfig")yield new ShellStream({event:{case:"permissionDenied",value:new ShellPermissionDenied({command,workingDirectory:resolved,error:"Command blocked by permissions configuration",isReadonly:block.reason.isReadonly??false})}});else yield new ShellStream({event:{case:"rejected",value:new ShellRejected({command,workingDirectory:resolved,reason:shellBlockReasonMessage(block.reason)})}});return;}policy=block.policy;}
    if(isForcedShellEgressEnabled()){policy=forcedShellSandboxPolicy(command,parsing);if(policy.type!=="insecure_none")policy={...policy,type:policy.type,ignoreMapping:await this.ignore.getCursorIgnoreMapping()};}
    yield new ShellStream({event:{case:"start",value:policy===undefined?new ShellStreamStart({}):new ShellStreamStart({sandboxPolicy:convertInternalToProtoPolicy(policy)!})}});const backgroundOnTimeout=args.timeoutBehavior===TimeoutBehavior.BACKGROUND,pipe=backgroundOnTimeout&&!args.closeStdin&&args.smartModeApproval===undefined,abort=new AbortController(),signal=backgroundOnTimeout?abort.signal:AbortSignal.any([ctx.signal,abort.signal]);const sandboxPolicy:SandboxPolicy|undefined=policy===undefined?undefined:{perRepo:policy};const iterable=this.core.execute(ctx,{command,workingDirectory,signal,...(args.conversationId===undefined?{}:{conversationId:args.conversationId}),...(sandboxPolicy===undefined?{}:{sandboxPolicy}),...(args.fileOutputThresholdBytes===undefined?{}:{fileOutputThresholdBytes:args.fileOutputThresholdBytes}),pipeStdin:pipe,showElapsedTime:true});let cancel:ReturnType<typeof setTimeout>|undefined;if(!backgroundOnTimeout)cancel=setTimeout(()=>abort.abort(),timeout);const bg=backgroundOnTimeout?new BackgroundableIterator(iterable[Symbol.asyncIterator](),timeout):null;let output="",stdin:NodeJS.WritableStream|undefined,pid:number|undefined,shellId:number|undefined,killed=false;const foreground=args.toolCallId&&bg?{requestBackground:()=>{if(!bg.requestBackground())return undefined;shellId??=this.background.generateShellId();return new ShellResult({result:{case:"success",value:new ShellSuccess({shellId,...(pid===undefined?{}:{pid}),command,workingDirectory:resolved,msToWait:Date.now()-startTime,backgroundReason:ShellBackgroundReason.USER_REQUEST,interleavedOutput:output})}});}}:undefined;if(args.toolCallId&&foreground)this.active.set(args.toolCallId,foreground);if(bg)ctx.signal.addEventListener("abort",()=>{if(!bg.backgroundRequested){abort.abort();bg.abort();}},{once:true});let hard:ReturnType<typeof setTimeout>|undefined;if(args.hardTimeout!==undefined&&args.hardTimeout>0)hard=setTimeout(()=>{if(shellId!==undefined){if(!this.background.abort(shellId))abort.abort();}else{killed=true;abort.abort();bg?.abort();}},args.hardTimeout);
    try{for await(const event of (bg?.iterate()??iterable)){if(event.type==="stdout"||event.type==="stderr"){output+=event.data;yield new ShellStream({event:{case:event.type,value:event.type==="stdout"?new ShellStreamStdout({data:event.data}):new ShellStreamStderr({data:event.data})}});}else if(event.type==="stdin_ready"){stdin=event.stdin;pid=event.pid;}else if(event.type==="exit")yield new ShellStream({event:{case:"exit",value:new ShellStreamExit({code:(event.code??0)>>>0,cwd:await this.core.getCwd(),outputLocation:event.outputLocation!,aborted:event.aborted,...(event.aborted?{abortReason:ctx.signal.aborted?ShellAbortReason.USER_ABORT:ShellAbortReason.TIMEOUT}:{}),localExecutionTimeMs:event.localExecutionTimeMs})}});}}catch(error){if(!(error instanceof SandboxUnsupportedError))throw error;const type=(policy as {type?:string}|undefined)?.type??"unknown";yield new ShellStream({event:{case:"sandboxUnsupported",value:new ShellSandboxUnsupported({command,workingDirectory:resolved,sandboxPolicyType:type,reason:error.reason??error.message,isReadonly:type==="workspace_readonly"})}});return;}finally{clearTimeout(cancel);if(!bg?.backgroundRequested)clearTimeout(hard);if(args.toolCallId&&this.active.get(args.toolCallId)===foreground)this.active.delete(args.toolCallId);}
    if(bg?.backgroundRequested&&!killed){shellId??=this.background.generateShellId();const reason=bg.backgroundReason===ShellBackgroundReason.USER_REQUEST?ShellBackgroundReason.USER_REQUEST:ShellBackgroundReason.TIMEOUT,ms=reason===ShellBackgroundReason.USER_REQUEST?Date.now()-startTime:timeout;await this.background.adopt({ctx,shellId,command,workingDirectory:resolved,...(args.toolCallId===undefined?{}:{toolCallId:args.toolCallId}),...(sandboxPolicy===undefined?{}:{sandboxPolicy}),initialOutput:output,...(stdin===undefined?{}:{stdin}),...(pid===undefined?{}:{pid}),abortController:abort,eventIterator:bg.handoff(),startTime,showElapsedTime:true,...(args.description===undefined?{}:{description:args.description}),...(args.outputNotification===undefined?{}:{outputNotification:args.outputNotification})});yield new ShellStream({event:{case:"backgrounded",value:new ShellStreamBackgrounded({shellId,command,workingDirectory:resolved,...(pid===undefined?{}:{pid}),msToWait:ms,reason})}});}else if(ctx.signal.aborted&&bg?.stopReason!==undefined)yield new ShellStream({event:{case:"exit",value:new ShellStreamExit({code:4294967295,cwd:await this.core.getCwd(),aborted:true,abortReason:ShellAbortReason.USER_ABORT})}});else clearTimeout(hard);
  }
}
