import { readdirSync, readFileSync, renameSync, rmSync, statSync } from "node:fs"; import { join } from "node:path"; import { createDebouncePolicy, realClock } from "../../internal/scheduling.js"; import { LEGACY_WORKFLOW_FILENAME, WORKFLOW_FILENAME, WORKFLOW_MAX_PER_AGENT, clampWorkflowBody, clampWorkflowDescription, clampWorkflowName, parseWorkflowFile, serializeWorkflowFile, slugifyWorkflowName, type WorkflowSpec } from "../../shared/workflow-model.js"; import { isSafeFolderId } from "../storage/folder-id.js"; import { WatchedDirectory } from "../watched-directory.js"; import { StatKeyedParseCache } from "./stat-keyed-parse-cache.js";
export const WORKFLOW_CHANGE_DEBOUNCE_MS = 50; const RESERVED_WORKFLOW_FILES = new Set([WORKFLOW_FILENAME, LEGACY_WORKFLOW_FILENAME, "runs.json"]); const recordParseCache = new StatKeyedParseCache();
export function getGlobalWorkflowsDir(sandRoot: string): string { return join(sandRoot, "workflows"); }
export interface GlobalWorkflowRecord { id: string; name: string; description: string; body: string; suggestedTrigger: WorkflowSpec["trigger"]; sourceRef: string | null; helperScripts: string[]; createdAt: number; filePath: string }
export class GlobalWorkflowLibrary { readonly dir: WatchedDirectory; constructor(readonly libraryDir: string) { this.dir = new WatchedDirectory(libraryDir, createDebouncePolicy(realClock, { name: "sand-workflow-library-change", delayMs: WORKFLOW_CHANGE_DEBOUNCE_MS })); this.renameLegacyRecipeFiles(); }
  renameLegacyRecipeFiles(): void { for (const id of this.listIds()) { const legacy = join(this.folder(id), LEGACY_WORKFLOW_FILENAME); try { if (!statSync(legacy).isFile()) continue; } catch { continue; } try { statSync(this.path(id)); continue; } catch {} try { renameSync(legacy, this.path(id)); } catch {} } }
  getLocation(): string { return this.libraryDir; } setOnChange(onChange?: (() => void) | null): void { this.dir.setOnChange(onChange); } folder(id: string): string { return join(this.libraryDir, id); } path(id: string): string { return join(this.folder(id), WORKFLOW_FILENAME); } listIds(): string[] { return this.dir.listSubdirectoryNames(); }
  listHelperScripts(id: string): string[] { try { return readdirSync(this.folder(id), { withFileTypes: true }).filter((entry) => entry.isFile() && !RESERVED_WORKFLOW_FILES.has(entry.name)).map((entry) => entry.name).sort(); } catch { return []; } }
  get(id: string): GlobalWorkflowRecord | null { if (!isSafeFolderId(id)) return null; return recordParseCache.read([this.path(id), this.folder(id)], () => this.#readRecord(id)); }
  #readRecord(id: string): GlobalWorkflowRecord | null { let raw: string; try { raw = readFileSync(this.path(id), "utf8"); } catch { return null; } const parsed = parseWorkflowFile(raw); if (parsed == null || parsed.body.length === 0) return null; let createdAt = Date.now(); try { const stats = statSync(this.path(id)); createdAt = Math.floor(stats.birthtimeMs || stats.mtimeMs); } catch {} return { id, name: parsed.name || id, description: parsed.description, body: parsed.body, suggestedTrigger: parsed.trigger, sourceRef: parsed.sourceRef, helperScripts: this.listHelperScripts(id), createdAt, filePath: this.path(id) }; }
  has(id: string): boolean { return this.get(id) != null; } list(): GlobalWorkflowRecord[] { return this.listIds().flatMap((id) => { const record = this.get(id); return record == null ? [] : [record]; }).sort((a, b) => a.createdAt - b.createdAt); } count(): number { return this.listIds().filter((id) => this.get(id) != null).length; }
  uniqueId(name: string): string { const base = slugifyWorkflowName(name); const existing = new Set(this.listIds()); if (!existing.has(base)) return base; for (let suffix = 2; suffix < 1_000; suffix += 1) { const candidate = `${base}-${suffix}`; if (!existing.has(candidate)) return candidate; } return `${base}-${Date.now()}`; }
  create(spec: WorkflowSpec): GlobalWorkflowRecord | null { const name = clampWorkflowName(spec.name), body = clampWorkflowBody(spec.body); if (!name || !body || this.count() >= WORKFLOW_MAX_PER_AGENT) return null; return this.#write(this.uniqueId(name), { name, description: clampWorkflowDescription(spec.description), body, trigger: null, sourceRef: spec.sourceRef ?? null }); }
  update(id: string, spec: WorkflowSpec): GlobalWorkflowRecord | null { if (!isSafeFolderId(id) || this.get(id) == null) return null; const name = clampWorkflowName(spec.name), body = clampWorkflowBody(spec.body); return !name || !body ? null : this.#write(id, { name, description: clampWorkflowDescription(spec.description), body, trigger: null, sourceRef: spec.sourceRef ?? null }); }
  writeAt(id: string, spec: WorkflowSpec): GlobalWorkflowRecord | null { return isSafeFolderId(id) ? this.#write(id, { ...spec, trigger: null }) : null; }
  #existingFrontmatter(id: string): Record<string, unknown> { try { return parseWorkflowFile(readFileSync(this.path(id), "utf8"))?.data ?? {}; } catch { return {}; } }
  #write(id: string, spec: WorkflowSpec): GlobalWorkflowRecord | null { this.dir.writeFileAtomic(this.path(id), serializeWorkflowFile(spec, this.#existingFrontmatter(id))); return this.get(id); }
  remove(id: string): boolean { if (!isSafeFolderId(id)) return false; const folder = this.folder(id); try { if (!statSync(folder).isDirectory()) return false; } catch { return false; } rmSync(folder, { recursive: true, force: true }); this.dir.scheduleNotify(); return true; }
}
