interface RoomMember { kind: string; authId: string; agentId?: string; displayName?: string; avatarDataUrl?: string }
export interface XuserRoom { roomId: string; name: string; hostAuthId: string; members: RoomMember[]; avatarDataUrl?: string }
interface DepartureFacade { isRoomAbandoned(roomId: string): boolean; flushPendingDepartures(): Promise<void>; pruneRoomTombstones(ids: ReadonlySet<string>): void }
export interface XuserStateReconcileHost { relay: { fetchShareState(): Promise<{ pendingJoinRequests: Array<Record<string, unknown>>; rooms: XuserRoom[] }>; addOwnAgent(args: unknown): Promise<{ room?: XuserRoom }>; setRoomPicture(args: unknown): Promise<{ room?: XuserRoom }> }; manager: { getAgentDisplayProfile(id: string): Promise<{ name: string } | null>; findRoomAgentId(roomId: string): Promise<string | null>; ensureMirrorRoom(room: XuserRoom, selfAuthId: string): Promise<void>; ensureHostedSharedRoom(args: unknown): Promise<string | null> }; isEnabled(): boolean; getSelfAuthId(): string | null; setSelfAuthId(id: string | null): void; readSelfAuthId(operation: string): Promise<string | null>; getRooms(): XuserRoom[]; setRooms(rooms: XuserRoom[]): void; setPendingJoinRequests(requests: Array<Record<string, unknown>>): void; typingUsers: Map<string, { roomId: string; authId: string }>; typingExpiryHandles: Map<string, { dispose(): void }>; emit(): void; departures(): DepartureFacade; agentAvatarPayload(agentId: string): Promise<string | undefined> }
export class SandXuserStateReconcile {
  readonly publishedProjectionPushes = new Map<string, string>(); private reconcileInFlight: Promise<void> | null = null; private readonly roomAgentChains = new Map<string, Promise<void>>(); constructor(readonly host: XuserStateReconcileHost) {}
  async installRoom(room: XuserRoom): Promise<void> { if (this.host.departures().isRoomAbandoned(room.roomId)) return; this.host.setRooms([...this.host.getRooms().filter((item) => item.roomId !== room.roomId), room]); const humans = new Set(room.members.filter((member) => member.kind === "human").map((member) => member.authId)); for (const [key, user] of this.host.typingUsers) if (user.roomId !== room.roomId || !humans.has(user.authId)) { this.host.typingUsers.delete(key); this.host.typingExpiryHandles.get(key)?.dispose(); this.host.typingExpiryHandles.delete(key); } await this.materializeRoom(room); this.host.emit(); }
  reconcileShareState(): Promise<void> { if (this.reconcileInFlight != null) return this.reconcileInFlight; const pass = this.runReconcilePass().finally(() => { this.reconcileInFlight = null; }); this.reconcileInFlight = pass; return pass; }
  async runReconcilePass(): Promise<void> { if (!this.host.isEnabled()) return; await this.host.departures().flushPendingDepartures(); let wire: Awaited<ReturnType<XuserStateReconcileHost["relay"]["fetchShareState"]>>; try { wire = await this.host.relay.fetchShareState(); } catch { return; } if (this.host.getSelfAuthId() == null) this.host.setSelfAuthId(await this.host.readSelfAuthId("share-state reconcile")); this.host.setPendingJoinRequests(wire.pendingJoinRequests.map((request) => ({ ...request }))); this.host.setRooms(wire.rooms.filter((room) => !this.host.departures().isRoomAbandoned(room.roomId))); this.host.departures().pruneRoomTombstones(new Set(wire.rooms.map((room) => room.roomId))); for (const [key, user] of this.host.typingUsers) { const member = this.host.getRooms().find((room) => room.roomId === user.roomId)?.members.some((item) => item.kind === "human" && item.authId === user.authId) === true; if (!member) { this.host.typingUsers.delete(key); this.host.typingExpiryHandles.get(key)?.dispose(); this.host.typingExpiryHandles.delete(key); } } await this.materializeRooms(); await this.refreshPublishedProjections(); this.host.emit(); }
  async refreshPublishedProjections(): Promise<void> { const selfAuthId = this.host.getSelfAuthId(); if (selfAuthId == null) return; for (const room of this.host.getRooms()) { for (const member of room.members) { if (member.kind !== "agent" || member.authId !== selfAuthId || member.agentId == null) continue; const profile = await this.host.manager.getAgentDisplayProfile(member.agentId), liveName = profile != null && profile.name !== member.displayName ? profile.name : undefined, avatar = await this.host.agentAvatarPayload(member.agentId), liveAvatar = avatar != null && avatar !== member.avatarDataUrl ? avatar : undefined; if (liveName == null && liveAvatar == null) continue; const agentName = liveName ?? member.displayName ?? "Agent", avatarDataUrl = liveAvatar ?? member.avatarDataUrl; await this.pushProjectionOnce({ pushKey: `member\0${room.roomId}\0${member.agentId}`, payload: `${agentName}\0${avatarDataUrl ?? ""}`, push: () => this.host.relay.addOwnAgent({ roomId: room.roomId, agentId: member.agentId, agentName, ...(avatarDataUrl == null ? {} : { avatarDataUrl }) }) }); } if (room.hostAuthId !== selfAuthId) continue; const roomAgentId = await this.host.manager.findRoomAgentId(room.roomId).catch(() => null); if (roomAgentId == null) continue; const avatar = await this.host.agentAvatarPayload(roomAgentId); if (avatar != null && avatar !== room.avatarDataUrl) await this.pushProjectionOnce({ pushKey: `room\0${room.roomId}`, payload: avatar, push: () => this.host.relay.setRoomPicture({ roomId: room.roomId, avatarDataUrl: avatar }) }); } }
  async pushProjectionOnce(args: { pushKey: string; payload: string; push(): Promise<{ room?: XuserRoom }> }): Promise<void> { if (this.publishedProjectionPushes.get(args.pushKey) === args.payload) return; try { const result = await args.push(); this.publishedProjectionPushes.set(args.pushKey, args.payload); if (result.room != null) await this.installRoom(result.room); } catch {} }
  async materializeRooms(): Promise<void> { for (const room of this.host.getRooms()) try { await this.materializeRoom(room); } catch {} }
  enqueueRoomAgentWork<T>(roomId: string, work: () => Promise<T>): Promise<T> { const previous = this.roomAgentChains.get(roomId) ?? Promise.resolve(), run = Promise.allSettled([previous]).then(work); this.roomAgentChains.set(roomId, run.then(() => {}, () => {})); return run; }
  materializeRoom(room: XuserRoom): Promise<void> { return this.enqueueRoomAgentWork(room.roomId, () => this.materializeRoomNow(room)); }
  async materializeRoomNow(room: XuserRoom): Promise<void> { const selfAuthId = this.host.getSelfAuthId(); if (selfAuthId == null || this.host.departures().isRoomAbandoned(room.roomId)) return; if (room.hostAuthId === selfAuthId) { await this.ensureHostedRoom(room, { isCreationAllowed: false }); return; } if (room.members.some((member) => member.kind === "human" && member.authId === selfAuthId)) await this.host.manager.ensureMirrorRoom(room, selfAuthId); }
  mintLocalRoomAgent(room: XuserRoom): Promise<string | null> { return this.enqueueRoomAgentWork(room.roomId, () => this.ensureHostedRoom(room, { isCreationAllowed: true })); }
  ensureHostedRoom(room: XuserRoom, options: { isCreationAllowed: boolean }): Promise<string | null> { const selfAuthId = this.host.getSelfAuthId() ?? "", localMemberIds: string[] = [], remoteMembers: Array<Record<string, unknown>> = []; for (const member of room.members) { if (member.kind !== "agent" || member.agentId == null) continue; if (member.authId === selfAuthId) localMemberIds.push(member.agentId); else remoteMembers.push({ ownerAuthId: member.authId, agentId: member.agentId, name: member.displayName ?? "Agent", ...(member.avatarDataUrl == null ? {} : { avatarDataUrl: member.avatarDataUrl }) }); } return this.host.manager.ensureHostedSharedRoom({ roomId: room.roomId, name: room.name, localMemberIds, remoteMembers, isCreationAllowed: options.isCreationAllowed }); }
}
