import type { Clock, PollingPolicy } from "../../../internal/scheduling.js";
import { getSandBackendClientHeaders } from "../../../shared/node/sand-client-metadata.js";
import { createNotifyDrainGate } from "../../notify-drain-gate.js";

export const XUSER_RELAY_POLL_INTERVAL_MS = 4_000;
export const XUSER_RELAY_ERROR_BACKOFF_MS = 30_000;
export class SandXuserRelayHttpError extends Error { constructor(readonly status: number, readonly path: string) { super(`sand sharing ${path} returned ${status}`); this.name = "SandXuserRelayHttpError"; } }
export interface XuserRelayClientDependencies { readonly getBackendUrl: () => string; readonly getAccessToken: (options: { backendUrl: string }) => Promise<string>; readonly onEvent: (event: Record<string, unknown>) => Promise<boolean>; readonly pollPolicy: PollingPolicy; readonly clock: Pick<Clock, "now">; readonly fetchImpl?: typeof fetch; readonly isNotifyConnected?: () => boolean; readonly isNotifySafetyPollEnabled?: () => boolean; readonly onPollError?: (error: unknown) => void }
export class SandXuserRelayClient {
  private readonly fetchImpl: typeof fetch; private polling: { dispose(): void } | null = null; private isTicking = false; private backoffUntilMs = 0; private pendingAckIds: string[] = []; private readonly notifyGate;
  constructor(readonly deps: XuserRelayClientDependencies) { this.fetchImpl = deps.fetchImpl ?? fetch; this.notifyGate = createNotifyDrainGate({ isConnected: () => deps.isNotifyConnected?.() ?? false, isSafetyPollEnabled: () => deps.isNotifySafetyPollEnabled?.() ?? true, now: () => deps.clock.now() }); }
  start(): void { if (this.polling != null) return; this.notifyGate.reset(); this.polling = this.deps.pollPolicy.start(() => this.tick()); }
  stop(): void { this.polling?.dispose(); this.polling = null; this.backoffUntilMs = 0; }
  requestDrain(): void { this.notifyGate.recordNotify(); if (this.polling != null) void this.tick(); }
  async tick(): Promise<void> { if (this.isTicking || this.deps.clock.now() < this.backoffUntilMs || !this.notifyGate.shouldDrain({ hasOwedWork: this.pendingAckIds.length > 0 })) return; this.isTicking = true; try { const result = await this.call<{ events?: unknown }>("/sand/xuser/poll", { ackIds: this.pendingAckIds }), previouslyAcked = new Set(this.pendingAckIds), nextAckIds: string[] = [], nextAckSet = new Set<string>(), recordAck = (id: string) => { nextAckIds.push(id); nextAckSet.add(id); }; for (const value of Array.isArray(result.events) ? result.events : []) { if (typeof value !== "object" || value === null) continue; const event = value as Record<string, unknown>; if (typeof event.id !== "string" || typeof event.kind !== "string") continue; if (previouslyAcked.has(event.id) || nextAckSet.has(event.id)) { recordAck(event.id); continue; } try { if (await this.deps.onEvent(event)) recordAck(event.id); } catch {} } this.pendingAckIds = nextAckIds; this.notifyGate.recordPoll(); } catch (error) { this.backoffUntilMs = this.deps.clock.now() + XUSER_RELAY_ERROR_BACKOFF_MS; this.deps.onPollError?.(error); } finally { this.isTicking = false; } }
  async call<Result>(path: string, body: unknown): Promise<Result> { const backendUrl = this.deps.getBackendUrl(), accessToken = await this.deps.getAccessToken({ backendUrl }), response = await this.fetchImpl(new URL(path, backendUrl).toString(), { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${accessToken}`, ...getSandBackendClientHeaders() }, body: JSON.stringify(body) }); if (!response.ok) throw new SandXuserRelayHttpError(response.status, path); return await response.json() as Result; }
  async createRoomFromAgent(args: unknown): Promise<Record<string, unknown>> { try { const result = await this.call<{ shareUrl: string; expiresAtMs: number; room: { roomId: string } }>("/sand/share-rooms/from-agent", args); return { status: "ok", shareUrl: result.shareUrl, expiresAtMs: result.expiresAtMs, roomId: result.room.roomId }; } catch (error) { return { status: "error", message: describeRelayError(error) }; } }
  createRoom<Result>(args: unknown): Promise<Result> { return this.call("/sand/share-rooms", args); }
  async createRoomInvite(roomId: string): Promise<Record<string, unknown>> { try { const result = await this.call<{ shareUrl: string; expiresAtMs: number; room: { roomId: string } }>("/sand/share-rooms/invite-links", { roomId }); return { status: "ok", shareUrl: result.shareUrl, expiresAtMs: result.expiresAtMs, roomId: result.room.roomId }; } catch (error) { return { status: "error", message: describeRelayError(error) }; } }
  async joinRoom(link: string): Promise<Record<string, unknown>> { try { const result = await this.call<Record<string, unknown>>("/sand/share-rooms/join", { link }); if (result.status === "pending") return { status: "pending", roomName: result.roomName ?? "the shared room" }; if (result.status === "already-member") { const room = typeof result.room === "object" && result.room !== null ? result.room as Record<string, unknown> : undefined; return { status: "already-member", roomName: room?.name ?? "the shared room", ...(room?.roomId != null ? { roomId: room.roomId } : {}) }; } if (result.status === "invalid" || result.status === "denied" || result.status === "rate-limited") return { status: result.status }; return { status: "error", message: "Unexpected response." }; } catch (error) { return { status: "error", message: describeRelayError(error) }; } }
  respondToJoinRequest<Result>(args: unknown): Promise<Result> { return this.call("/sand/share-rooms/join/respond", args); }
  addOwnAgent<Result>(args: unknown): Promise<Result> { return this.call("/sand/share-rooms/agents/add", args); }
  setRoomPicture<Result>(args: unknown): Promise<Result> { return this.call("/sand/share-rooms/picture", args); }
  removeOwnAgent<Result>(args: unknown): Promise<Result> { return this.call("/sand/share-rooms/agents/remove", args); }
  removeDeletedAgent<Result>(agentId: string): Promise<Result> { return this.call("/sand/share-rooms/agents/remove-deleted", { agentId }); }
  leaveRoom<Result>(roomId: string, targetAuthId?: string): Promise<Result> { return this.call("/sand/share-rooms/leave", { roomId, ...(targetAuthId == null ? {} : { targetAuthId }) }); }
  fetchShareState<Result>(): Promise<Result> { return this.call("/sand/share-state", {}); }
  async send(payload: unknown): Promise<{ timestampMs?: number }> { const result = await this.call<{ timestampMs?: unknown }>("/sand/xuser/send", payload); return typeof result.timestampMs === "number" && Number.isFinite(result.timestampMs) ? { timestampMs: result.timestampMs } : {}; }
}
export function describeRelayError(error: unknown): string { if (error instanceof SandXuserRelayHttpError) { if (error.status === 403) return "Sharing isn't enabled for your account."; if (error.status === 429) return "You're doing that too often. Try again in a minute."; } return "Couldn't reach the sharing service. Check your connection and try again."; }
