import { MAX_INLINE_IMAGES_PER_ENTRY, type InlineImage } from "./xuser-wire-normalization.js";

export const SAND_SHARED_ROOM_IMAGE_BYTES_MAX = 1_100_000;
export const REMOTE_AGENT_ID_PREFIX = "sand-remote:";
export function parseRemoteAgentId(id: string): { ownerAuthId: string; agentId: string } | null { if (!id.startsWith(REMOTE_AGENT_ID_PREFIX)) return null; const body = id.slice(REMOTE_AGENT_ID_PREFIX.length), separator = body.indexOf("/"); if (separator <= 0 || separator === body.length - 1) return null; try { const ownerAuthId = decodeURIComponent(body.slice(0, separator)), agentId = decodeURIComponent(body.slice(separator + 1)); return ownerAuthId && agentId ? { ownerAuthId, agentId } : null; } catch { return null; } }
export interface XuserEntryPublisherHost { readonly relay: { send(payload: unknown): Promise<{ timestampMs?: number }> }; readonly manager: { restampRoomEntry(args: { roomId: string; entryId: string; timestampMs: number }): Promise<void> }; readonly clock: { now(): number }; isEnabled(): boolean; getSelfAuthId(): string | null; resolveAttachment(url: string): Promise<{ data: Uint8Array; mimeType: string } | null> }
export type PublishableEntry = { id: string; kind: "message"; role: string; content: string; fromAgent?: unknown; toAgent?: unknown; channel?: unknown; fromUser?: unknown; images?: readonly { url: string; alt?: string }[]; clientNonce?: string; timestampMs?: number } | { id: string; kind: "send-message"; message: { type: string; content: string; images?: readonly { url: string; alt?: string }[] }; author?: { id: string; name: string }; streaming?: boolean; timestampMs?: number } | { id: string; kind: string };
export class SandXuserEntryPublisher {
  private readonly publishChains = new Map<string, Promise<void>>(); constructor(readonly host: XuserEntryPublisherHost) {}
  enqueuePublish(sharedRoomId: string, entry: PublishableEntry): void { const previous = this.publishChains.get(sharedRoomId) ?? Promise.resolve(), next = previous.then(() => this.publishEntry(sharedRoomId, entry)).catch(() => {}); this.publishChains.set(sharedRoomId, next); }
  async publishEntry(sharedRoomId: string, entry: PublishableEntry): Promise<void> { if (!this.host.isEnabled()) return; const selfAuthId = this.host.getSelfAuthId(); if (selfAuthId == null) return; const wire = await this.serializeEntry(entry, selfAuthId); if (wire == null) return; const result = await this.host.relay.send({ kind: "room-entry", roomId: sharedRoomId, entry: wire }); if (result.timestampMs != null) await this.host.manager.restampRoomEntry({ roomId: sharedRoomId, entryId: entry.id, timestampMs: result.timestampMs }); }
  async serializeEntry(entry: PublishableEntry, selfAuthId: string): Promise<Record<string, unknown> | null> { if (entry.kind === "message" && "role" in entry && entry.role === "user") { if (entry.fromAgent != null || entry.toAgent != null || entry.channel != null || entry.fromUser != null || entry.content.trim().length === 0) return null; return { kind: "human-message", entryId: entry.id, authorAuthId: selfAuthId, authorName: "Host", text: entry.content, images: await this.inlineImages(entry.images), ...(entry.clientNonce == null ? {} : { clientNonce: entry.clientNonce }), timestampMs: entry.timestampMs ?? this.host.clock.now() }; } if (entry.kind === "send-message" && "message" in entry && entry.message.type === "text" && entry.author != null && entry.streaming !== true) { if (parseRemoteAgentId(entry.author.id) != null) return null; return { kind: "agent-message", entryId: entry.id, agentOwnerAuthId: selfAuthId, agentId: entry.author.id, authorName: entry.author.name, text: entry.message.content, images: await this.inlineImages(entry.message.images), timestampMs: entry.timestampMs ?? this.host.clock.now() }; } return null; }
  async inlineImages(images?: readonly { url: string; alt?: string }[]): Promise<InlineImage[]> { if (images == null || images.length === 0) return []; const inlined: InlineImage[] = []; let totalBytes = 0; for (const image of images.slice(0, MAX_INLINE_IMAGES_PER_ENTRY)) try { const resolved = await this.host.resolveAttachment(image.url); if (resolved == null || totalBytes + resolved.data.byteLength > SAND_SHARED_ROOM_IMAGE_BYTES_MAX || !resolved.mimeType.startsWith("image/")) continue; totalBytes += resolved.data.byteLength; inlined.push({ base64: Buffer.from(resolved.data).toString("base64"), mediaType: resolved.mimeType, ...(image.alt != null && image.alt.length > 0 ? { alt: image.alt } : {}) }); } catch {} return inlined; }
}
