import type { Clock, DeadlinePolicy, ExpiryPolicy, PollingPolicy } from "../../../internal/scheduling.js";
import { EMPTY_SAND_SHARING_STATE, isPublishableShareAvatarDataUrl } from "../../../shared/agents/sharing.js";
import { clampGuestName } from "../../groups/xuser.js";
import { SandXuserDepartureObligations, type XuserDepartureHost } from "./xuser-departure-obligations.js";
import { SandXuserEntryPublisher, type PublishableEntry, type XuserEntryPublisherHost } from "./xuser-entry-publisher.js";
import { createInMemoryXuserPendingDepartures, type XuserPendingDepartureStore } from "./xuser-pending-departure-store.js";
import { SandXuserRelayClient } from "./xuser-relay.js";
import { SandXuserRemoteTurns, type RemoteTurnsHost } from "./xuser-remote-turns.js";
import { createInMemoryXuserRoomTombstones, type XuserRoomTombstoneStore } from "./xuser-room-tombstone-store.js";
import { SandXuserStateReconcile, type XuserRoom, type XuserStateReconcileHost } from "./xuser-state-reconcile.js";
import { createInMemoryXuserTurnDedupe, type XuserTurnDedupe } from "./xuser-turn-dedupe-store.js";
import { normalizeInlineImages, normalizeMirrorEntry } from "./xuser-wire-normalization.js";

export const STATE_RECONCILE_INTERVAL_MS = 5 * 60_000; export const SELF_IDENTITY_RETRY_MS = 1_000;
export interface SharingManager { getSharedRoomIdForAgent(id: string): Promise<string | null>; listRoomAgentIds(roomId: string): Promise<string[]>; markMirrorRoomRevoked(roomId: string): Promise<void>; getAgentDisplayProfile(id: string): Promise<{ name: string; description: string } | null>; getAgentAvatar(id: string): Promise<{ dataUrl: string } | null>; restampRoomEntry(args: { roomId: string; entryId: string; timestampMs: number }): Promise<void>; appendSharedRoomActivityNotice(args: { roomId: string; text: string }): Promise<void>; runRemoteRequestedMemberTurn(args: { agentId: string; systemPrompt: string; prompt: string }): Promise<string[]>; appendMirrorRoomEntry(args: unknown): Promise<boolean>; postSharedRoomGuestMessage(args: unknown): Promise<void>; ensureMirrorRoom(room: XuserRoom, id: string): Promise<void>; ensureHostedSharedRoom(args: unknown): Promise<string | null>; findRoomAgentId(roomId: string): Promise<string | null>; isAgentCapReached(): Promise<boolean> }
export interface SharingDependencies { getAccessToken(options: { backendUrl: string }): Promise<string>; getBackendUrl(): string; getSelfAuthId(): Promise<string | null>; isEnabled(): boolean; manager: SharingManager; emitSharing(state: unknown): void; resolveAttachment(url: string): Promise<{ data: Uint8Array; mimeType: string } | null>; timing: { clock: Clock; relayPoll: PollingPolicy; reconcilePoll: PollingPolicy; selfIdentityRetry: PollingPolicy; remoteTurnDeadline: DeadlinePolicy; typingExpiry(delayMs: number): ExpiryPolicy }; fetchImpl?: typeof fetch; pendingDepartures?: XuserPendingDepartureStore; roomTombstones?: XuserRoomTombstoneStore; turnDedupe?: XuserTurnDedupe; isNotifyConnected?: () => boolean; isNotifySafetyPollEnabled?: () => boolean }
export interface SandSharingState { isEnabled: boolean; selfAuthId: string | null; pendingJoinRequests: Array<Record<string, unknown>>; rooms: XuserRoom[]; typingUsers: Array<{ roomId: string; authId: string; name: string; avatarUrl?: string; expiresAtMs: number }> }
export class SandXuserSharingService {
  readonly relay: SandXuserRelayClient; readonly remoteTurns: SandXuserRemoteTurns; readonly departures: SandXuserDepartureObligations; readonly reconcile: SandXuserStateReconcile; readonly publisher: SandXuserEntryPublisher; readonly turnDedupe: XuserTurnDedupe; private isStarted = false; private startGeneration = 0; private selfAuthId: string | null = null; private pendingJoinRequests: Array<Record<string, unknown>> = []; private rooms: XuserRoom[] = []; readonly typingUsers = new Map<string, { roomId: string; authId: string; name: string; avatarUrl?: string; expiresAtMs: number }>(); readonly typingExpiryHandles = new Map<string, { dispose(): void }>(); private readonly roomMintsByAgent = new Map<string, Promise<Record<string, unknown>>>(); private reconcilePolling: { dispose(): void } | null = null; private selfIdentityPolling: { dispose(): void } | null = null;
  constructor(readonly deps: SharingDependencies) { this.turnDedupe = deps.turnDedupe ?? createInMemoryXuserTurnDedupe(); this.relay = new SandXuserRelayClient({ getAccessToken: deps.getAccessToken, getBackendUrl: deps.getBackendUrl, ...(deps.fetchImpl == null ? {} : { fetchImpl: deps.fetchImpl }), clock: deps.timing.clock, pollPolicy: deps.timing.relayPoll, onEvent: (event) => this.handleEvent(event), ...(deps.isNotifyConnected == null ? {} : { isNotifyConnected: deps.isNotifyConnected }), ...(deps.isNotifySafetyPollEnabled == null ? {} : { isNotifySafetyPollEnabled: deps.isNotifySafetyPollEnabled }) }); const base = { relay: this.relay, manager: deps.manager, clock: deps.timing.clock, isEnabled: deps.isEnabled, getSelfAuthId: () => this.selfAuthId, getRooms: () => this.rooms }; this.remoteTurns = new SandXuserRemoteTurns({ ...base, remoteTurnDeadline: deps.timing.remoteTurnDeadline, turnDedupe: this.turnDedupe, reconcileShareState: () => this.reconcileShareState() } as unknown as RemoteTurnsHost); this.departures = new SandXuserDepartureObligations({ ...base, setSelfAuthId: (id: string) => { this.selfAuthId = id; }, readSelfAuthId: (operation: string) => this.readSelfAuthId(operation), setRooms: (rooms: XuserRoom[]) => { this.rooms = rooms; }, emit: () => this.emit(), installRoom: (room: XuserRoom) => this.reconcile.installRoom(room) } as unknown as XuserDepartureHost, deps.pendingDepartures ?? createInMemoryXuserPendingDepartures(), deps.roomTombstones ?? createInMemoryXuserRoomTombstones()); this.reconcile = new SandXuserStateReconcile({ ...base, setSelfAuthId: (id: string | null) => { this.selfAuthId = id; }, readSelfAuthId: (operation: string) => this.readSelfAuthId(operation), setRooms: (rooms: XuserRoom[]) => { this.rooms = rooms; }, setPendingJoinRequests: (requests: Array<Record<string, unknown>>) => { this.pendingJoinRequests = requests; }, typingUsers: this.typingUsers, typingExpiryHandles: this.typingExpiryHandles, emit: () => this.emit(), departures: () => this.departures, agentAvatarPayload: (id: string) => this.agentAvatarPayload(id) } as unknown as XuserStateReconcileHost); this.publisher = new SandXuserEntryPublisher({ ...base, resolveAttachment: deps.resolveAttachment } as unknown as XuserEntryPublisherHost); }
  requestRelayDrain(): void { this.relay.requestDrain(); }
  async start(): Promise<void> { if (this.isStarted) return; if (!this.deps.isEnabled()) { this.deps.emitSharing(EMPTY_SAND_SHARING_STATE); return; } this.isStarted = true; const generation = ++this.startGeneration; this.selfAuthId = await this.readSelfAuthId("start"); if (!this.isCurrentStart(generation)) return; await this.reconcileShareState(); if (!this.isCurrentStart(generation)) return; this.relay.start(); this.startReconcilePolling(); this.startSelfIdentityPolling(); }
  private isCurrentStart(generation: number): boolean { return this.isStarted && this.startGeneration === generation; }
  private startReconcilePolling(): void { let initial = true; this.reconcilePolling = this.deps.timing.reconcilePoll.start(async () => { if (initial) { initial = false; return; } if (this.isStarted && this.selfAuthId != null) await this.reconcileShareState(); }); }
  private startSelfIdentityPolling(): void { if (this.selfAuthId != null || this.selfIdentityPolling != null) return; let initial = true; this.selfIdentityPolling = this.deps.timing.selfIdentityRetry.start(async () => { if (initial) { initial = false; return; } if (!this.isStarted || this.selfAuthId != null) return; const id = await this.readSelfAuthId("identity retry"); if (id == null || !this.isStarted) return; this.selfAuthId = id; this.selfIdentityPolling?.dispose(); this.selfIdentityPolling = null; await this.reconcileShareState(); }); }
  stop(): void { if (!this.isStarted) return; this.isStarted = false; this.startGeneration += 1; this.relay.stop(); this.reconcilePolling?.dispose(); this.reconcilePolling = null; this.selfIdentityPolling?.dispose(); this.selfIdentityPolling = null; this.remoteTurns.stop(); for (const expiry of this.typingExpiryHandles.values()) expiry.dispose(); this.typingExpiryHandles.clear(); this.typingUsers.clear(); }
  getState(): SandSharingState | typeof EMPTY_SAND_SHARING_STATE { if (!this.deps.isEnabled()) return EMPTY_SAND_SHARING_STATE; return { isEnabled: true, selfAuthId: this.selfAuthId, pendingJoinRequests: this.pendingJoinRequests, rooms: this.rooms, typingUsers: [...this.typingUsers.values()].filter((user) => user.expiresAtMs > this.deps.timing.clock.now() && user.authId !== this.selfAuthId) }; }
  emit(): void { this.deps.emitSharing(this.getState()); } installRoom(room: XuserRoom): Promise<void> { return this.reconcile.installRoom(room); } reconcileShareState(): Promise<void> { return this.reconcile.reconcileShareState(); } isRoomAbandoned(roomId: string): boolean { return this.departures.isRoomAbandoned(roomId); }
  async handleEvent(event: Record<string, unknown>): Promise<boolean> { if (!this.deps.isEnabled()) return true; switch (event.kind) { case "room-join-request": return this.handleRoomJoinRequest(event); case "room-join-decision": if (event.isApproved === true && event.room != null) { const room = event.room as XuserRoom; this.departures.clearRoomTombstones(room.roomId); await this.installRoom(room); } return true; case "room-upsert": if (event.room != null) await this.installRoom(event.room as XuserRoom); return true; case "room-typing": return this.handleRoomTyping(event); case "room-post": return this.handleRoomPost(event); case "room-entry": return this.handleRoomEntry(event); case "turn-request": return this.remoteTurns.handleTurnRequest(event); case "turn-result": return this.remoteTurns.handleTurnResult(event); case "member-left": case "room-ended": if (typeof event.roomId === "string") { await this.deps.manager.markMirrorRoomRevoked(event.roomId); this.departures.abandonRoomLocally(event.roomId); } await this.reconcileShareState(); return true; default: return true; } }
  private handleRoomJoinRequest(event: Record<string, unknown>): boolean { if (typeof event.request !== "object" || event.request === null) return true; const request = event.request as Record<string, unknown>; if (typeof request.requestId !== "string" || this.pendingJoinRequests.some((item) => item.requestId === request.requestId)) return true; this.pendingJoinRequests.push({ requestId: request.requestId, roomId: request.roomId ?? "", roomName: request.roomName ?? "Shared room", requesterAuthId: request.requesterAuthId ?? "", requesterName: clampGuestName(typeof request.requesterName === "string" ? request.requesterName : ""), ...(typeof request.requesterAvatarUrl === "string" && request.requesterAvatarUrl ? { requesterAvatarUrl: request.requesterAvatarUrl } : {}), createdAtMs: request.createdAtMs ?? this.deps.timing.clock.now() }); this.emit(); return true; }
  private handleRoomTyping(event: Record<string, unknown>): boolean { if (typeof event.user !== "object" || event.user === null) return true; const user = event.user as Record<string, unknown>; if (typeof user.roomId !== "string" || typeof user.authId !== "string" || typeof user.name !== "string" || typeof user.expiresAtMs !== "number") return true; const room = this.rooms.find((item) => item.roomId === user.roomId); if (room == null || !room.members.some((member) => member.kind === "human" && member.authId === user.authId)) return true; const key = `${user.roomId}\0${user.authId}`; this.typingExpiryHandles.get(key)?.dispose(); this.typingExpiryHandles.delete(key); const now = this.deps.timing.clock.now(); if (event.isTyping !== true || user.expiresAtMs <= now) { if (this.typingUsers.delete(key)) this.emit(); return true; } const normalized = { roomId: user.roomId, authId: user.authId, name: clampGuestName(user.name), ...(typeof user.avatarUrl === "string" && user.avatarUrl ? { avatarUrl: user.avatarUrl } : {}), expiresAtMs: user.expiresAtMs }; this.typingUsers.set(key, normalized); this.emit(); this.typingExpiryHandles.set(key, this.deps.timing.typingExpiry(Math.max(0, user.expiresAtMs - now)).arm(key, () => { this.typingExpiryHandles.delete(key); if (this.typingUsers.get(key)?.expiresAtMs === user.expiresAtMs) { this.typingUsers.delete(key); this.emit(); } })); return true; }
  private async handleRoomPost(event: Record<string, unknown>): Promise<boolean> { if (typeof event.roomId !== "string" || typeof event.authorAuthId !== "string" || this.isRoomAbandoned(event.roomId)) return true; await this.deps.manager.postSharedRoomGuestMessage({ roomId: event.roomId, authorAuthId: event.authorAuthId, authorName: clampGuestName(typeof event.authorName === "string" ? event.authorName : ""), text: typeof event.text === "string" ? event.text : "", images: normalizeInlineImages(event.images), ...(typeof event.timestampMs === "number" && Number.isFinite(event.timestampMs) ? { timestampMs: event.timestampMs } : {}) }); return true; }
  private async handleRoomEntry(event: Record<string, unknown>): Promise<boolean> { if (typeof event.roomId !== "string" || event.entry == null || this.isRoomAbandoned(event.roomId)) return true; if (this.selfAuthId == null) return false; const entry = normalizeMirrorEntry(event.entry, this.deps.timing.clock.now()); return entry == null ? true : this.deps.manager.appendMirrorRoomEntry({ roomId: event.roomId, entry, selfAuthId: this.selfAuthId }); }
  async agentAvatarPayload(agentId: string): Promise<string | undefined> { const avatar = await this.deps.manager.getAgentAvatar(agentId).catch(() => null), dataUrl = avatar?.dataUrl ?? null; return dataUrl != null && isPublishableShareAvatarDataUrl(dataUrl) ? dataUrl : undefined; }
  async createRoomFromAgent(agentId: string): Promise<Record<string, unknown>> { if (!this.deps.isEnabled()) return { status: "error", message: "Sharing isn't enabled." }; const existing = this.roomMintsByAgent.get(agentId); if (existing != null) return existing; const mint = this.mintRoomForAgent(agentId); this.roomMintsByAgent.set(agentId, mint); try { return await mint; } finally { this.roomMintsByAgent.delete(agentId); } }
  private async mintRoomForAgent(agentId: string): Promise<Record<string, unknown>> { const profile = await this.deps.manager.getAgentDisplayProfile(agentId); if (profile == null) return { status: "error", message: "That agent no longer exists." }; const existing = this.findAgentShareRoomId(agentId); if (existing != null) return this.relay.createRoomInvite(existing); const avatarDataUrl = await this.agentAvatarPayload(agentId); const result = await this.relay.createRoomFromAgent({ agentId, agentName: profile.name, ...(avatarDataUrl == null ? {} : { avatarDataUrl }) }); if (result.status === "ok") await this.reconcileShareState(); return result; }
  findAgentShareRoomId(agentId: string): string | null { if (this.selfAuthId == null) return null; for (const room of this.rooms) if (room.hostAuthId === this.selfAuthId && !this.isRoomAbandoned(room.roomId)) { const agents = room.members.filter((member) => member.kind === "agent"); if (agents.length === 1 && agents[0]?.authId === this.selfAuthId && agents[0]?.agentId === agentId) return room.roomId; } return null; }
  createRoomInvite(roomId: string): Promise<Record<string, unknown>> { return this.deps.isEnabled() ? this.relay.createRoomInvite(roomId) : Promise.resolve({ status: "error", message: "Sharing isn't enabled." }); }
  async joinRoom(link: string): Promise<Record<string, unknown>> { if (!this.deps.isEnabled()) return { status: "error", message: "Sharing isn't enabled." }; const result = await this.relay.joinRoom(link); if (result.status === "already-member") await this.reconcileShareState(); return result; }
  async respondToJoinRequest(args: { requestId: string; [key: string]: unknown }): Promise<unknown> { if (!this.deps.isEnabled()) return this.getState(); try { const result = await this.relay.respondToJoinRequest<Record<string, unknown>>(args); this.pendingJoinRequests = this.pendingJoinRequests.filter((request) => request.requestId !== args.requestId); if (result.status === "approved" && result.room != null) await this.installRoom(result.room as XuserRoom); else this.emit(); } catch {} return this.getState(); }
  async createSharedRoom(args: { agents: Array<Record<string, unknown>>; [key: string]: unknown }): Promise<Record<string, unknown>> { if (!this.deps.isEnabled()) return { status: "error", message: "Sharing isn't enabled." }; if (this.selfAuthId == null) return { status: "error", message: "Sign in to create shared groups." }; try { const agents = await Promise.all(args.agents.map(async (agent) => { const avatar = typeof agent.agentId === "string" ? await this.agentAvatarPayload(agent.agentId) : undefined; return { ...agent, ...(avatar == null ? {} : { avatarDataUrl: avatar }) }; })), result = await this.relay.createRoom<Record<string, unknown>>({ ...args, agents }); if (result.status !== "created" || result.room == null) return { status: "error", message: "The room couldn't be created." }; const room = result.room as XuserRoom; await this.installRoom(room); return { status: "ok", roomId: room.roomId, localRoomAgentId: await this.reconcile.mintLocalRoomAgent(room) }; } catch { return { status: "error", message: "The room couldn't be created. Try again." }; } }
  async addOwnAgent(args: { agentId: string; [key: string]: unknown }): Promise<unknown> { if (!this.deps.isEnabled()) return this.getState(); try { const avatar = await this.agentAvatarPayload(args.agentId), result = await this.relay.addOwnAgent<Record<string, unknown>>({ ...args, ...(avatar == null ? {} : { avatarDataUrl: avatar }) }); if (result.room != null) await this.installRoom(result.room as XuserRoom); } catch {} return this.getState(); }
  async removeOwnAgent(roomId: string, agentId: string): Promise<unknown> { if (!this.deps.isEnabled()) return this.getState(); try { const result = await this.relay.removeOwnAgent<Record<string, unknown>>({ roomId, agentId }); if (result.room != null) await this.installRoom(result.room as XuserRoom); } catch {} return this.getState(); }
  async leaveSharedRoom(roomId: string, targetAuthId?: string): Promise<unknown> { if (!this.deps.isEnabled()) return this.getState(); try { await this.relay.leaveRoom(roomId, targetAuthId); if (targetAuthId == null || targetAuthId === this.selfAuthId) { await this.deps.manager.markMirrorRoomRevoked(roomId); this.departures.abandonRoomLocally(roomId); } await this.reconcileShareState(); } catch {} return this.getState(); }
  async noteAgentDeleted(id: string): Promise<void> { await this.departures.noteAgentDeleted(id); }
  async readSelfAuthId(operation: string): Promise<string | null> { return this.deps.getSelfAuthId().catch(() => { console.warn(`[sand:sharing] self-identity read failed (${operation})`); return null; }); }
  async setRoomTyping(roomId: string, isTyping: boolean): Promise<void> { if (this.deps.isEnabled()) await this.relay.send({ kind: "room-typing", roomId, isTyping }); }
  prepareForUpgrade(): void { this.stop(); }
  buildManagerDelegate(): { isEnabled(): boolean; publishRoomEntry(roomId: string, entry: PublishableEntry): void } { return { isEnabled: () => this.deps.isEnabled(), publishRoomEntry: (roomId, entry) => this.publisher.enqueuePublish(roomId, entry) }; }
}
