import { randomUUID } from "node:crypto";
import type { DeadlinePolicy } from "../../../internal/scheduling.js";
import { parseRemoteAgentId } from "../../../shared/agents/sharing.js";
import { buildRemoteMemberTurnPrompts, clampGuestName, toXuserTurnMessages } from "../../groups/xuser.js";
import { normalizeTurnMessages } from "./xuser-wire-normalization.js";
import type { XuserTurnDedupe } from "./xuser-turn-dedupe-store.js";

export const REMOTE_MEMBER_UNREACHABLE_BACKOFF_MS = 10 * 60_000;
export const REMOTE_TURN_BUDGET_WINDOW_MS = 10 * 60_000;
export const REMOTE_TURN_BUDGET_MAX = 30;
interface SharedRoom { roomId: string; name: string; hostName: string; hostAuthId: string; members: Array<{ kind: string; authId: string; agentId?: string }> }
export interface RemoteTurnsHost { relay: { send(payload: unknown): Promise<unknown>; requestDrain(): void; removeDeletedAgent(agentId: string): Promise<unknown> }; manager: { getAgentDisplayProfile(agentId: string): Promise<{ name: string; description: string } | null>; appendSharedRoomActivityNotice(args: { roomId: string; text: string }): Promise<void>; runRemoteRequestedMemberTurn(args: { agentId: string; systemPrompt: string; prompt: string }): Promise<string[]> }; clock: { now(): number }; remoteTurnDeadline: DeadlinePolicy; isEnabled(): boolean; getSelfAuthId(): string | null; getRooms(): SharedRoom[]; turnDedupe: XuserTurnDedupe; reconcileShareState(): Promise<void> }
export class SandXuserRemoteTurns {
  private readonly pendingRemoteTurns = new Map<string, { resolve(messages: string[]): void }>(); private readonly unreachableRemoteMembers = new Map<string, number>(); private readonly remoteTurnStarts = new Map<string, number[]>(); constructor(readonly host: RemoteTurnsHost) {}
  stop(): void { for (const [nonce, pending] of this.pendingRemoteTurns) { pending.resolve([]); this.pendingRemoteTurns.delete(nonce); } this.remoteTurnStarts.clear(); }
  handleTurnRequest(event: Record<string, unknown>): boolean { const roomId = typeof event.roomId === "string" ? event.roomId : null, turnNonce = typeof event.turnNonce === "string" ? event.turnNonce : null, agentId = typeof event.agentId === "string" ? event.agentId : null, hostAuthId = typeof event.hostAuthId === "string" ? event.hostAuthId : null; if (roomId == null || turnNonce == null || agentId == null || hostAuthId == null) return true; const selfAuthId = this.host.getSelfAuthId(), room = this.host.getRooms().find((item) => item.roomId === roomId); if (selfAuthId == null || room == null || room.hostAuthId !== hostAuthId || !room.members.some((item) => item.kind === "human" && item.authId === selfAuthId) || !room.members.some((item) => item.kind === "agent" && item.authId === selfAuthId && item.agentId === agentId) || !this.host.turnDedupe.markSeenIfNew(turnNonce)) return true; const key = `${roomId}\0${hostAuthId}\0${agentId}`, now = this.host.clock.now(), recent = (this.remoteTurnStarts.get(key) ?? []).filter((started) => now - started < REMOTE_TURN_BUDGET_WINDOW_MS); if (recent.length >= REMOTE_TURN_BUDGET_MAX) { this.remoteTurnStarts.set(key, recent); return true; } this.remoteTurnStarts.set(key, [...recent, now]); void this.runRequestedTurn(event, room); return true; }
  async runRequestedTurn(event: Record<string, unknown>, room: SharedRoom): Promise<void> { const agentId = typeof event.agentId === "string" ? event.agentId : "", roomId = typeof event.roomId === "string" ? event.roomId : "", turnNonce = typeof event.turnNonce === "string" ? event.turnNonce : ""; try { const profile = await this.host.manager.getAgentDisplayProfile(agentId); if (profile == null) { await this.host.relay.removeDeletedAgent(agentId); await this.host.reconcileShareState(); return; } await this.host.manager.appendSharedRoomActivityNotice({ roomId, text: `${profile.name} is responding in ${room.name} at the request of ${room.hostName}.` }); const rawPeers = Array.isArray(event.peers) ? event.peers : [], peers = rawPeers.map((value, index) => { const peer = typeof value === "object" && value !== null ? value as Record<string, unknown> : {}; return { id: `peer:${index}`, name: clampGuestName(typeof peer.name === "string" ? peer.name : ""), description: typeof peer.description === "string" ? peer.description : "" }; }), prompts = buildRemoteMemberTurnPrompts({ member: { id: agentId, name: profile.name, description: profile.description }, group: { name: typeof event.groupName === "string" ? event.groupName : "Shared room", description: typeof event.groupDescription === "string" ? event.groupDescription : "" }, peers, hostName: room.hostName, newMessages: normalizeTurnMessages(event.newMessages) }); const messages = await this.host.manager.runRemoteRequestedMemberTurn({ agentId, ...prompts }); await this.host.relay.send({ kind: "turn-result", roomId, turnNonce, agentId, messages: messages.slice(0, 2) }); } catch { try { await this.host.relay.send({ kind: "turn-result", roomId, turnNonce, agentId, messages: [] }); } catch {} } }
  handleTurnResult(event: Record<string, unknown>): boolean { if (typeof event.turnNonce !== "string") return true; const pending = this.pendingRemoteTurns.get(event.turnNonce); if (pending == null) return true; this.pendingRemoteTurns.delete(event.turnNonce); pending.resolve((Array.isArray(event.messages) ? event.messages : []).filter((message): message is string => typeof message === "string").slice(0, 2)); return true; }
  async runRemoteMemberTurn(args: { member: { id: string }; sharedRoomId: string; group: { name: string; description: string }; peers: Array<{ name: string; description: string }>; newMessages: Parameters<typeof toXuserTurnMessages>[0] }): Promise<string[]> { if (!this.host.isEnabled()) return []; const ref = parseRemoteAgentId(args.member.id); if (ref == null || this.host.clock.now() < (this.unreachableRemoteMembers.get(args.member.id) ?? 0)) return []; const turnNonce = randomUUID(), result = new Promise<string[]>((resolve) => this.pendingRemoteTurns.set(turnNonce, { resolve })); try { await this.host.relay.send({ kind: "turn-request", roomId: args.sharedRoomId, turnNonce, ownerAuthId: ref.ownerAuthId, agentId: ref.agentId, groupName: args.group.name, groupDescription: args.group.description, peers: args.peers.map((peer) => ({ name: peer.name, description: peer.description })), newMessages: toXuserTurnMessages(args.newMessages, args.member.id) }); } catch { this.pendingRemoteTurns.delete(turnNonce); return []; } this.host.relay.requestDrain(); let messages: string[]; try { messages = await this.host.remoteTurnDeadline.run(async () => result); } catch { this.pendingRemoteTurns.delete(turnNonce); this.unreachableRemoteMembers.set(args.member.id, this.host.clock.now() + REMOTE_MEMBER_UNREACHABLE_BACKOFF_MS); return []; } if (messages.length > 0) this.unreachableRemoteMembers.delete(args.member.id); return messages; }
}
