const LIFECYCLE_REASONS: Record<string, string> = { "stream-ended": "stream_ended", "stall-timeout": "stall_timeout", "forced-reconnect": "forced_reconnect" }; const FAILURE_REASONS = ["refused", "dns", "timeout", "network", "no_storage", "access_denied", "box_blocked", "http_5xx"]; const ERRNO_TOKEN = /^[A-Z][A-Z0-9_]*$/;
const DEFINITIONS: Record<string, { domain: string; retryable: boolean; payload: string[] }> = { "SAND-E0101": { domain: "transport", retryable: true, payload: ["errno"] }, "SAND-E0102": { domain: "transport", retryable: true, payload: ["errno"] }, "SAND-E0103": { domain: "transport", retryable: true, payload: ["httpStatus"] }, "SAND-E0104": { domain: "transport", retryable: true, payload: ["errno"] }, "SAND-E0105": { domain: "transport", retryable: true, payload: ["errno"] }, "SAND-E0110": { domain: "transport", retryable: true, payload: [] }, "SAND-E0201": { domain: "auth", retryable: false, payload: [] }, "SAND-E0202": { domain: "auth", retryable: false, payload: ["httpStatus"] } };
export interface TransportRegisteredError { readonly code: string; readonly [key: string]: unknown }
export function transportErrorTags(error: TransportRegisteredError): Record<string, string> { const definition = DEFINITIONS[error.code]; if (definition == null) return {}; const tags: Record<string, string> = { error_code: error.code, error_domain: definition.domain, error_retryable: String(definition.retryable) }; for (const field of definition.payload) { const value = error[field]; if (typeof value === "string" || typeof value === "number" && Number.isFinite(value)) tags[field.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)] = String(value); } return tags; }
export function errnoFromCauseSummary(cause: string | null | undefined): string | undefined { const token = cause?.split("/").at(-1); return token !== undefined && ERRNO_TOKEN.test(token) ? token : undefined; }
export function gatewayOutcomeError(outcome: string, detail: { causeSummary?: string; httpStatus?: number }): TransportRegisteredError | null { const errno = errnoFromCauseSummary(detail.causeSummary); switch (outcome) { case "refused": return { code: "SAND-E0101", errno }; case "dns": return { code: "SAND-E0104", errno }; case "timeout": return { code: "SAND-E0102", errno }; case "network": return { code: "SAND-E0105", errno }; case "no_storage": return { code: "SAND-E0201" }; case "access_denied": return { code: "SAND-E0202", httpStatus: detail.httpStatus }; case "http_5xx": return detail.httpStatus === undefined ? null : { code: "SAND-E0103", httpStatus: detail.httpStatus }; default: return null; } }
export function streamDownError(reason: string, cause?: string): TransportRegisteredError | null { return reason === "stall-timeout" ? { code: "SAND-E0110" } : gatewayOutcomeError(reason, { ...(cause === undefined ? {} : { causeSummary: cause }) }); }
export function streamDownTelemetry(payload: { reason: string; cause?: string | null; generation: number }, streamLifetimeMs?: number) { const reason = LIFECYCLE_REASONS[payload.reason] ?? (FAILURE_REASONS.includes(payload.reason) ? payload.reason : "unknown"); const error = streamDownError(payload.reason, payload.cause ?? undefined); return { level: payload.reason === "stall-timeout" ? "warn" : "info", metadata: { reason, cause: payload.cause ?? undefined, generation: String(payload.generation), stream_lifetime_ms: streamLifetimeMs === undefined ? undefined : String(Math.round(streamLifetimeMs)), ...(error === null ? {} : transportErrorTags(error)) } }; }
export function createTransportStreamTelemetry(deps: { readonly monotonicNow: () => number; readonly report: (level: string, metadata: Record<string, string | undefined>) => void }) { let connected: { generation: number; atMs: number } | null = null; return { onConnected: ({ generation }: { generation: number }) => { connected = { generation, atMs: deps.monotonicNow() }; }, onDown: (payload: { generation: number; reason: string; cause?: string | null }) => { if (payload.generation === 0) return; const lifetime = connected !== null && connected.generation === payload.generation ? deps.monotonicNow() - connected.atMs : undefined; connected = null; const value = streamDownTelemetry(payload, lifetime); deps.report(value.level, value.metadata); } }; }
