import { mkdtemp, rm } from "node:fs/promises";
import { join } from "node:path";
import { realClock, type Clock } from "../../internal/scheduling.js";
import { SAND_PRODUCT_DISPLAY_NAME } from "../../shared/product-name.js";
import { NIGHTLY_UPDATE_TRACK_DISABLED, availableUpdateTracks, resolveEffectiveTrack, selectableUpdateTracks, type SandUpdateTrack } from "../../shared/update-track.js";
import { type UpdateApplyMarker, decideUpdateApplySettlement } from "./apply-marker.js";
import { downloadAndVerify } from "./update-download.js";
import { DEFAULT_UPDATE_BASE_URL, UpdateHttpStatusError, buildUpdateRequestUrl, parseUpdateResponse, resolveUpdatePlatform, updateResponseKind } from "./update-feed.js";
import { runPeriodicIdleApplyTick, tryApplyStagedWhenIdle } from "./idle-relaunch-apply.js";
import { SquirrelFeedServer } from "./squirrel-feed-server.js";
import { classifyUpdateCheckError, updateDisabledError, updateError } from "./update-telemetry.js";
import { compareVersions, isNewerVersion, isPrerelease, parseVersion } from "./update-version.js";

export const DEFAULT_INITIAL_CHECK_DELAY_MS = 30_000;
export const DEFAULT_CHECK_INTERVAL_MS = 60 * 60_000;
export const DEFAULT_CHECK_INTERVAL_JITTER_MS = 5 * 60_000;
export const DEFAULT_STAGING_TIMEOUT_MS = 10 * 60_000;
export const PROGRESS_EMIT_STEP = 0.01;
export class SandUpdateApplyError extends Error {}
export type UpdateDisabledReason = "disabled-by-env" | "lab-build" | "not-packaged" | "unsupported-platform";
export type SandUpdateState = { type: "disabled"; reason: UpdateDisabledReason } | { type: "idle"; lastCheck?: unknown } | { type: "checking" } | { type: "available" | "staging" | "ready"; version: string; lastCheck?: unknown } | { type: "downloading"; version: string; progress: number | null };

interface SquirrelPort { on(event: string, listener: (...args: any[]) => void): void; setFeedURL(options: { url: string }): void; checkForUpdates(): void; quitAndInstall(): void }
interface WindowsPort { verifySignature(path: string): Promise<void>; quit(): void; installOnQuit(path: string, options: { forceRun: boolean; onSpawnError(error: unknown): void }): void }
interface ApplyMarkerPort { peek(): UpdateApplyMarker | null; recordStaged(input: any): void; recordRequested(input: any): void; recordSpawned(): void; recordSpawnFailed(error: unknown): void; clear(): void }
export interface SandUpdateServiceOptions {
  readonly currentVersion: string; readonly buildDefaultTrack: SandUpdateTrack | null; readonly disabledReason?: UpdateDisabledReason | null; readonly squirrel?: SquirrelPort | null; readonly windows?: WindowsPort | null; readonly tempDir: string; readonly machineId: string; readonly feedBaseUrl?: string; readonly platform?: NodeJS.Platform; readonly arch?: string;
  readonly getTrackOverride: () => SandUpdateTrack | null | undefined; readonly persistTrackOverride: (track: SandUpdateTrack | null) => void; readonly getReleaseTrackGate?: () => { managedTrack?: SandUpdateTrack | undefined; unlockInternalTracks: boolean }; readonly hasLiveExperimentBootstrap?: () => boolean; readonly getFlagsAgeMs?: () => number | undefined; readonly getMinimumVersion?: () => unknown;
  readonly getAutoUpdateWhenIdleOptIn?: () => boolean; readonly persistAutoUpdateWhenIdleOptIn?: (enabled: boolean) => void; readonly getAutoUpdateWhenIdleGateEnabled?: () => boolean; readonly idleRelaunchSignals?: any;
  readonly onStatusChange: (status: any) => void; readonly reportOutcome?: (report: any) => void; readonly reportCheck?: (report: any) => void; readonly reportApply?: (report: any) => void; readonly applyMarker?: ApplyMarkerPort; readonly log?: (message: string) => void; readonly fetchImpl?: typeof fetch;
  readonly initialCheckDelayMs?: number; readonly checkIntervalMs?: number; readonly checkIntervalJitterMs?: number; readonly stagingTimeoutMs?: number; readonly random?: () => number; readonly clock?: Clock; readonly now?: () => number; readonly feedServer?: SquirrelFeedServer; readonly reportCleanupFailure?: (leg: string, error: unknown) => void;
}

export class SandUpdateService {
  private state: SandUpdateState;
  readonly updatePlatform: string;
  readonly responseKind: "squirrel" | "iupdate";
  private readonly clock: Clock; private readonly now: () => number; private readonly feedServer: SquirrelFeedServer;
  private checkAbort: AbortController | null = null; private attemptTrack: SandUpdateTrack | null = null; private notedEffectiveTrack: SandUpdateTrack | null = null; private stagedZipPath: string | null = null; private stagedVersion: string | null = null; private stagedAtMs: number | null = null; private checkSeq = 0; private stagedInstallerPath: string | null = null; private forceRunOnQuit = false; private initialArm: { dispose(): void } | null = null; private periodicArm: { dispose(): void } | null = null; private periodicTickInFlight = false; private stagingArm: { dispose(): void } | null = null; private isDisposed = false; private backendRequiresUpdate = false; private stagingDir: string | null = null; private installerLaunched = false;

  constructor(private readonly options: SandUpdateServiceOptions) {
    this.clock = options.clock ?? realClock; this.now = options.now ?? Date.now; this.feedServer = options.feedServer ?? new SquirrelFeedServer();
    this.updatePlatform = resolveUpdatePlatform(options.platform ?? process.platform, options.arch ?? process.arch); this.responseKind = updateResponseKind(this.updatePlatform); this.state = options.disabledReason != null ? { type: "disabled", reason: options.disabledReason } : { type: "idle" };
    options.squirrel?.on("update-downloaded", () => this.onSquirrelStaged()); options.squirrel?.on("error", (...args) => this.onSquirrelError(args[0] instanceof Error ? args[0].message : String(args[0]), "failed")); options.squirrel?.on("update-not-available", () => this.onSquirrelError("Squirrel declined the staged update (update-not-available)", "declined"));
  }
  start(): void { this.settleApplyMarker(); if (this.state.type === "disabled") { this.emitCheckReport({ action: "result", seq: ++this.checkSeq, trigger: "startup", track: this.effectiveTrack(), result: "disabled", error: updateDisabledError(this.state.reason) }); return; } this.initialArm = this.clock.schedule(this.options.initialCheckDelayMs ?? DEFAULT_INITIAL_CHECK_DELAY_MS, () => { void this.checkForUpdates({ trigger: "startup" }); }); this.scheduleNextPeriodicCheck(); }
  applyDisabledReason(reason: UpdateDisabledReason | null): void { if (this.isDisposed) return; if (reason != null) { if (this.state.type === "disabled" && this.state.reason === reason) return; this.stopChecks(); this.discardStaged(); this.setState({ type: "disabled", reason }); this.emitCheckReport({ action: "result", seq: ++this.checkSeq, trigger: "gate_change", track: this.effectiveTrack(), result: "disabled", error: updateDisabledError(reason) }); return; } if (this.state.type !== "disabled") return; this.setState({ type: "idle" }); this.start(); }
  private clearPeriodicArm(): void { this.periodicArm?.dispose(); this.periodicArm = null; }
  private stopChecks(): void { this.initialArm?.dispose(); this.initialArm = null; this.clearPeriodicArm(); this.checkAbort?.abort(); this.checkAbort = null; this.cleanupStagingArtifacts(); }
  private discardStaged(): void { if (this.stagedInstallerPath != null) { void this.removeFile(this.stagedInstallerPath, "staged-cleanup"); this.stagedInstallerPath = null; } this.stagedVersion = null; this.stagedAtMs = null; this.forceRunOnQuit = false; this.options.applyMarker?.clear(); }
  private scheduleNextPeriodicCheck(): void { if (this.isDisposed || this.state.type === "disabled") return; this.clearPeriodicArm(); this.periodicArm = this.clock.schedule(this.nextPeriodicDelayMs(), () => { this.scheduleNextPeriodicCheck(); if (this.periodicTickInFlight) return; this.periodicTickInFlight = true; void runPeriodicIdleApplyTick({ isDisposed: () => this.isDisposed, refreshFeed: () => this.checkForUpdates({ trigger: "periodic" }).then(() => undefined), applyWhenIdle: () => tryApplyStagedWhenIdle({ updateReady: this.state.type === "ready", optInEnabled: this.options.getAutoUpdateWhenIdleOptIn?.() ?? false, gateEnabled: this.options.getAutoUpdateWhenIdleGateEnabled?.() ?? false, signals: this.options.idleRelaunchSignals, stillReady: () => this.state.type === "ready", quitAndInstall: () => this.quitAndInstall(), ...(this.options.log === undefined ? {} : { log: this.options.log }) }), cancelRearm: () => this.clearPeriodicArm(), ...(this.options.log === undefined ? {} : { log: this.options.log }) }).finally(() => { this.periodicTickInFlight = false; }); }); }
  nextPeriodicDelayMs(): number { const interval = this.options.checkIntervalMs ?? DEFAULT_CHECK_INTERVAL_MS; const ceiling = this.options.checkIntervalJitterMs ?? DEFAULT_CHECK_INTERVAL_JITTER_MS; return ceiling <= 0 ? interval : interval + Math.floor((this.options.random ?? Math.random)() * ceiling); }
  dispose(): void { this.isDisposed = true; this.initialArm?.dispose(); this.clearPeriodicArm(); this.clearStagingTimer(); this.checkAbort?.abort(); this.feedServer.stop(); if (this.stagingDir != null && !this.installerLaunched && this.stagedInstallerPath == null && this.stagedZipPath == null) void rm(this.stagingDir, { recursive: true, force: true }).catch((error) => this.failure("staging-cleanup", error)); }
  getStatus(): any { const gate = this.releaseTrackGate(); const currentTrack = this.effectiveTrack(); return { state: this.state, currentVersion: this.options.currentVersion, currentTrack, trackOverride: this.options.getTrackOverride(), buildDefaultTrack: this.options.buildDefaultTrack, availableTracks: availableUpdateTracks({ unlockInternalTracks: gate.unlockInternalTracks, effectiveTrack: currentTrack }), isTrackManagedByPolicy: gate.managedTrack != null, isBelowMinimumVersion: this.isBelowMinimumVersion(), autoUpdateWhenIdleOptIn: this.options.getAutoUpdateWhenIdleOptIn?.() ?? false, autoUpdateWhenIdleGateEnabled: this.options.getAutoUpdateWhenIdleGateEnabled?.() ?? false }; }
  setAutoUpdateWhenIdleOptIn(enabled: boolean): any { this.options.persistAutoUpdateWhenIdleOptIn?.(enabled); const status = this.getStatus(); this.options.onStatusChange(status); return status; }
  isBelowMinimumVersion(): boolean { if (this.state.type === "disabled") return false; if (this.backendRequiresUpdate) return true; const minimum = this.options.getMinimumVersion?.(); return typeof minimum === "string" && minimum.length > 0 && parseVersion(minimum) != null && parseVersion(this.options.currentVersion) != null && compareVersions(this.options.currentVersion, minimum) < 0; }
  noteMinimumVersionMayHaveChanged(): void { if (this.isDisposed || this.state.type === "disabled") return; this.emitStatus(); if (this.isBelowMinimumVersion() && this.state.type === "idle") void this.checkForUpdates({ trigger: "min_version" }); }
  noteBackendUpdateRequirement(required: boolean): void { if (this.isDisposed || this.state.type === "disabled" || this.backendRequiresUpdate === required) return; this.backendRequiresUpdate = required; this.emitStatus(); if (required && this.state.type === "idle") void this.checkForUpdates({ trigger: "backend_gate" }); }
  noteReleaseTrackGateMayHaveChanged(): void { if (this.isDisposed || this.state.type === "disabled") return; const gate = this.releaseTrackGate(); const override = this.options.getTrackOverride(); if (override != null && gate.managedTrack == null && this.options.hasLiveExperimentBootstrap?.() === true && !selectableUpdateTracks(gate.unlockInternalTracks).includes(override)) { void this.setTrackOverride("stable").catch((error) => this.options.log?.(`Release-track drain failed: ${message(error)}`)); return; } const effective = this.effectiveTrack(); const previous = this.notedEffectiveTrack; this.notedEffectiveTrack = effective; if (previous != null && previous !== effective) { void this.retargetForTrackChange().catch((error) => this.options.log?.(`Release-track re-target failed: ${message(error)}`)); return; } this.emitStatus(); }
  async checkForUpdates(input: { trigger: string }): Promise<any> {
    if (this.checkAbort != null || this.state.type !== "idle" && this.state.type !== "ready") return this.getStatus(); const abort = new AbortController(); this.checkAbort = abort; const track = this.effectiveTrack(); const explicit = input.trigger === "explicit"; const seq = ++this.checkSeq; const started = this.now(); this.emitCheckReport({ action: "started", seq, trigger: input.trigger, track }); const emit = (result: any) => this.emitCheckReport({ action: "result", seq, trigger: input.trigger, track, durationMs: this.now() - started, ...result }); let emitted = false; if (this.state.type === "idle") this.setState({ type: "checking" }); let attemptedVersion: string | undefined;
    try { const manifest = await this.fetchUpdate(track, abort.signal); if (!abort.signal.aborted) { if (manifest == null || !this.shouldApplyOffer(manifest.version)) { emit(manifest == null ? { result: "no_update" } : { result: "up_to_date", targetVersion: manifest.version }); emitted = true; if (this.stagedVersion == null) this.setState({ type: "idle", lastCheck: { at: this.now(), result: "up-to-date" } }); else this.setState({ type: "ready", version: this.stagedVersion }); } else { attemptedVersion = manifest.version; emit({ result: "offer", targetVersion: manifest.version }); emitted = true; this.attemptTrack = track; this.setState({ type: "available", version: manifest.version }); await this.downloadAndStage(manifest, track, abort.signal); } } }
    catch (error) { if (!abort.signal.aborted) { const text = message(error); this.options.log?.(`Update check failed (track: ${track}, trigger: ${input.trigger}): ${text}`); if (attemptedVersion !== undefined) this.emitOutcome("failed", error instanceof Error ? error.constructor.name : undefined); else { emit({ result: "error", error: classifyUpdateCheckError(error), errorClass: error instanceof Error ? error.constructor.name : undefined }); emitted = true; } this.feedServer.stop(); if (this.stagedVersion == null) this.setState({ type: "idle", lastCheck: { at: this.now(), result: "error", errorMessage: text } }); else if (explicit) this.setState({ type: "ready", version: this.stagedVersion, lastCheck: { at: this.now(), result: "error", errorMessage: text } }); else if (this.state.type !== "ready") this.setState({ type: "ready", version: this.stagedVersion }); } }
    finally { if (abort.signal.aborted && !emitted && attemptedVersion === undefined) emit({ result: "error", error: updateError("SAND-E0504") }); if (this.checkAbort === abort) { this.checkAbort = null; if (abort.signal.aborted) this.foldTransientStateToParked(); } } return this.getStatus();
  }
  private foldTransientStateToParked(): void { if (["checking", "available", "downloading"].includes(this.state.type)) { this.feedServer.stop(); this.setState(this.parkedState()); } }
  private parkedState(): SandUpdateState { return this.stagedVersion != null ? { type: "ready", version: this.stagedVersion } : { type: "idle" }; }
  async setTrackOverride(track: SandUpdateTrack | null): Promise<any> { const previous = this.effectiveTrack(); this.options.persistTrackOverride(track); if (this.state.type === "disabled" || this.effectiveTrack() === previous) { this.emitStatus(); return this.getStatus(); } return await this.retargetForTrackChange(); }
  private async retargetForTrackChange(): Promise<any> { this.notedEffectiveTrack = this.effectiveTrack(); if (["checking", "available", "downloading"].includes(this.state.type)) { this.checkAbort?.abort(); this.checkAbort = null; this.feedServer.stop(); this.setState(this.parkedState()); } else { if (this.state.type === "ready") { this.checkAbort?.abort(); this.checkAbort = null; } this.emitStatus(); } return this.state.type === "idle" || this.state.type === "ready" ? await this.checkForUpdates({ trigger: "track_change" }) : this.getStatus(); }
  quitAndInstall(): boolean { if (this.state.type !== "ready") return false; if (this.responseKind === "iupdate") { if (this.stagedInstallerPath == null || this.forceRunOnQuit) return false; this.recordApplyRequested(this.state.version); this.forceRunOnQuit = true; this.options.windows?.quit(); return true; } if (this.options.squirrel == null) return false; this.recordApplyRequested(this.state.version); this.options.squirrel.quitAndInstall(); return true; }
  private applyMechanism(): "nsis" | "squirrel" { return this.responseKind === "iupdate" ? "nsis" : "squirrel"; }
  private settleApplyMarker(): void { const marker = this.options.applyMarker?.peek(); if (marker == null) return; for (const report of decideUpdateApplySettlement(marker, this.options.currentVersion, this.now())) this.options.reportApply?.(report); this.options.applyMarker?.clear(); }
  private recordApplyRequested(targetVersion: string): void { const mechanism = this.applyMechanism(); this.options.applyMarker?.recordRequested({ mechanism, targetVersion, fromVersion: this.options.currentVersion }); this.options.reportApply?.({ outcome: "requested", mechanism, targetVersion }); }
  applyStagedOnQuit(): void { if (this.stagedInstallerPath == null || !this.forceRunOnQuit) return; const path = this.stagedInstallerPath; this.stagedInstallerPath = null; this.installerLaunched = true; this.options.applyMarker?.recordSpawned(); this.options.windows?.installOnQuit(path, { forceRun: true, onSpawnError: (error) => this.options.applyMarker?.recordSpawnFailed(error) }); }
  willRunStagedInstallerOnQuit(): boolean { return this.stagedInstallerPath != null && this.forceRunOnQuit; }
  private releaseTrackGate() { return this.options.getReleaseTrackGate?.() ?? { managedTrack: undefined, unlockInternalTracks: false }; }
  private effectiveTrack(): SandUpdateTrack { const managedTrack = this.releaseTrackGate().managedTrack; const userOverride = this.options.getTrackOverride(); return resolveEffectiveTrack({ ...(managedTrack === undefined ? {} : { managedTrack }), ...(userOverride == null ? {} : { userOverride }), buildDefault: this.options.buildDefaultTrack }); }
  shouldApplyOffer(offerVersion: string): boolean { const baseline = this.stagedVersion ?? this.options.currentVersion; if (isNewerVersion(offerVersion, baseline)) return true; const offerTrack = parseVersion(offerVersion)?.prerelease[0]; const currentTrack = parseVersion(this.options.currentVersion)?.prerelease[0]; if (this.stagedVersion == null && offerVersion !== this.options.currentVersion && offerTrack != null && offerTrack !== currentTrack) return true; return NIGHTLY_UPDATE_TRACK_DISABLED && this.stagedVersion == null && isPrerelease(this.options.currentVersion) && !isPrerelease(offerVersion) && offerVersion !== this.options.currentVersion; }
  private async fetchUpdate(track: SandUpdateTrack, signal: AbortSignal): Promise<any | null> { const url = buildUpdateRequestUrl(this.options.feedBaseUrl ?? DEFAULT_UPDATE_BASE_URL, track, this.options.currentVersion, this.options.machineId, this.updatePlatform); const response = await (this.options.fetchImpl ?? fetch)(url, { redirect: "follow", signal, headers: { "cache-control": "no-cache" } }); if (response.status === 204) return null; if (!response.ok) throw new UpdateHttpStatusError(response.status, url); return parseUpdateResponse(await response.json(), this.responseKind); }
  private async ensureStagingDir(): Promise<string> { this.stagingDir ??= await mkdtemp(join(this.options.tempDir, "sand-update-")); return this.stagingDir; }
  private async downloadAndStage(manifest: any, track: SandUpdateTrack, signal: AbortSignal): Promise<void> { const path = join(await this.ensureStagingDir(), `sand-update-${manifest.version}.${this.responseKind === "iupdate" ? "exe" : "zip"}`); let last = -1; this.setState({ type: "downloading", version: manifest.version, progress: null }); await downloadAndVerify({ url: manifest.url, ...(manifest.sha256 === undefined ? {} : { sha256: manifest.sha256 }), destinationPath: path, ...(this.options.fetchImpl === undefined ? {} : { fetchImpl: this.options.fetchImpl }), signal, onProgress: ({ receivedBytes, totalBytes }) => { if (totalBytes == null || signal.aborted) return; const progress = Math.min(receivedBytes / totalBytes, 1); if (progress - last >= PROGRESS_EMIT_STEP) { last = progress; this.setState({ type: "downloading", version: manifest.version, progress }); } }, reportCleanupFailure: (error) => this.failure("download-cleanup", error) }); if (signal.aborted || this.effectiveTrack() !== track) { await this.removeFile(path, "download-cleanup"); if (!signal.aborted) this.setState(this.parkedState()); return; } if (this.responseKind === "iupdate") return await this.stageWindowsInstaller(manifest.version, path, signal, track); if (this.options.squirrel == null) { await this.removeFile(path, "download-cleanup"); throw new SandUpdateApplyError("Update downloaded and verified, but applying updates requires Squirrel.Mac (macOS only)."); } this.setState({ type: "staging", version: manifest.version }); this.stagedZipPath = path; const feedUrl = await this.feedServer.start({ version: manifest.version, zipPath: path, ...(manifest.name === undefined ? {} : { releaseName: manifest.name }), ...(manifest.pubDate === undefined ? {} : { pubDate: manifest.pubDate }) }); this.options.squirrel.setFeedURL({ url: feedUrl }); this.stagedVersion = null; this.stagedAtMs = null; this.invalidatePendingApply(manifest.version); this.options.squirrel.checkForUpdates(); this.startStagingTimeout(manifest.version); }
  private async stageWindowsInstaller(version: string, path: string, signal: AbortSignal, track: SandUpdateTrack): Promise<void> { const windows = this.options.windows; if (windows == null) { await this.removeFile(path, "installer-cleanup"); throw new SandUpdateApplyError("Update downloaded, but no installer backend is available to apply it on this platform."); } this.setState({ type: "staging", version }); try { await windows.verifySignature(path); } catch (error) { await this.removeFile(path, "installer-cleanup"); throw new SandUpdateApplyError(`Installer signature verification failed: ${message(error)}`); } if (signal.aborted || this.effectiveTrack() !== track) { await this.removeFile(path, "installer-cleanup"); if (!signal.aborted) this.setState(this.parkedState()); return; } if (this.stagedInstallerPath != null && this.stagedInstallerPath !== path) void this.removeFile(this.stagedInstallerPath, "staged-cleanup"); this.invalidatePendingApply(version); this.stagedInstallerPath = path; this.stagedVersion = version; this.stagedAtMs = this.now(); this.recordApplyStaged(version); this.emitOutcome("staged"); this.setState({ type: "ready", version }); }
  private invalidatePendingApply(supersedingVersion: string): void { const marker = this.options.applyMarker?.peek(); if (marker != null && marker.phase !== "staged") this.options.reportApply?.({ outcome: "superseded_during_confirm", mechanism: marker.mechanism, targetVersion: marker.targetVersion, fromVersion: marker.fromVersion, phase: marker.phase, supersedingVersion }); this.options.applyMarker?.clear(); }
  private startStagingTimeout(version: string): void { this.clearStagingTimer(); this.stagingArm = this.clock.schedule(this.options.stagingTimeoutMs ?? DEFAULT_STAGING_TIMEOUT_MS, () => { this.stagingArm = null; if (this.state.type !== "staging") return; this.cleanupStagingArtifacts(); const text = `Squirrel did not finish staging ${SAND_PRODUCT_DISPLAY_NAME} ${version} in time; will retry on the next check.`; this.options.log?.(text); this.emitOutcome("timeout"); this.setState({ type: "idle", lastCheck: { at: this.now(), result: "error", errorMessage: text } }); }); }
  private clearStagingTimer(): void { this.stagingArm?.dispose(); this.stagingArm = null; }
  private onSquirrelStaged(): void { if (this.state.type !== "staging") return; const version = this.state.version; this.cleanupStagingArtifacts(); this.stagedVersion = version; this.stagedAtMs = this.now(); this.recordApplyStaged(version); this.emitOutcome("staged"); this.setState({ type: "ready", version }); }
  private recordApplyStaged(targetVersion: string): void { this.options.applyMarker?.recordStaged({ mechanism: this.applyMechanism(), targetVersion, fromVersion: this.options.currentVersion }); }
  private onSquirrelError(text: string, outcome: string): void { if (this.state.type !== "staging") { this.options.log?.(`Squirrel error outside staging: ${text}`); return; } this.cleanupStagingArtifacts(); this.options.log?.(`Squirrel failed to stage the update: ${text}`); this.emitOutcome(outcome); this.setState({ type: "idle", lastCheck: { at: this.now(), result: "error", errorMessage: text } }); }
  private cleanupStagingArtifacts(): void { this.clearStagingTimer(); this.feedServer.stop(); if (this.stagedZipPath != null) { void this.removeFile(this.stagedZipPath, "staged-cleanup"); this.stagedZipPath = null; } }
  private setState(state: SandUpdateState): void { this.state = state; this.emitStatus(); }
  private emitStatus(): void { this.options.onStatusChange(this.getStatus()); }
  private emitOutcome(outcome: string, errorClass?: string): void { this.options.reportOutcome?.({ outcome, phase: this.state.type, track: this.attemptTrack ?? this.effectiveTrack(), currentVersion: this.options.currentVersion, targetVersion: "version" in this.state ? this.state.version : undefined, errorClass }); }
  private emitCheckReport(report: any): void { const flagsAgeMs = this.options.getFlagsAgeMs?.(); const stagedAge = this.stagedAtMs != null ? { stagedAgeMs: Math.max(0, this.now() - this.stagedAtMs) } : {}; this.options.reportCheck?.({ ...report, currentVersion: this.options.currentVersion, ...(flagsAgeMs == null ? {} : { flagsAgeMs }), ...(this.stagedVersion == null ? {} : { stagedVersion: this.stagedVersion, ...stagedAge }) }); }
  private async removeFile(path: string, leg: string): Promise<void> { await rm(path, { force: true }).catch((error) => this.failure(leg, error)); }
  private failure(leg: string, error: unknown): void { try { this.options.reportCleanupFailure?.(leg, error); } catch {} }
}
function message(error: unknown): string { return error instanceof Error ? error.message : String(error); }
