import { compareVersions, parseVersion } from "./update-version.js";
import { UpdateHttpStatusError, UpdateResponseFormatError } from "./update-feed.js";
export { UpdateHttpStatusError, UpdateResponseFormatError } from "./update-feed.js";

const UPDATE_ERRORS = {
  "SAND-E0501": { name: "updateFeedFetchFailed", retryable: true, payload: [] }, "SAND-E0502": { name: "updateFeedHttpStatus", retryable: true, payload: ["httpStatus"] }, "SAND-E0503": { name: "updateFeedMalformed", retryable: false, payload: [] }, "SAND-E0504": { name: "updateCheckAborted", retryable: true, payload: [] }, "SAND-E0505": { name: "updateDisabledByEnv", retryable: false, payload: [] }, "SAND-E0506": { name: "updateDisabledLabBuild", retryable: false, payload: [] }, "SAND-E0507": { name: "updateDisabledNotPackaged", retryable: false, payload: [] }, "SAND-E0508": { name: "updateDisabledUnsupportedPlatform", retryable: false, payload: [] }, "SAND-E0509": { name: "updateStagedNotAdopted", retryable: true, payload: [] }, "SAND-E0510": { name: "updateApplyIncomplete", retryable: true, payload: [] }, "SAND-E0511": { name: "updateInstallerSpawnFailed", retryable: true, payload: ["errno"] }, "SAND-E0512": { name: "updateAutoRelaunchFailed", retryable: false, payload: [] },
} as const;
type UpdateCode = keyof typeof UPDATE_ERRORS;
export type UpdateError = { readonly code: UpdateCode; readonly [key: string]: unknown };
export function updateError(code: UpdateCode, payload: Record<string, unknown> = {}): UpdateError { return { code, ...payload }; }
export function updateErrorTags(error: UpdateError): Record<string, string> { const definition = UPDATE_ERRORS[error.code]; const tags: Record<string, string> = { error_code: error.code, error_domain: "update", error_retryable: String(definition.retryable) }; for (const field of definition.payload) { const value = error[field]; if (typeof value === "string" || typeof value === "number" && Number.isFinite(value)) tags[field.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)] = String(value); } return tags; }

export function classifyUpdateCheckError(error: unknown): UpdateError { return error instanceof UpdateHttpStatusError ? updateError("SAND-E0502", { httpStatus: error.status }) : error instanceof UpdateResponseFormatError ? updateError("SAND-E0503") : updateError("SAND-E0501"); }
const DISABLED_CODES = { "disabled-by-env": "SAND-E0505", "lab-build": "SAND-E0506", "not-packaged": "SAND-E0507", "unsupported-platform": "SAND-E0508" } as const;
export function updateDisabledError(reason: keyof typeof DISABLED_CODES): UpdateError { return updateError(DISABLED_CODES[reason]); }
const CHECK_CAUSES: Record<string, string> = { updateFeedFetchFailed: "fetch_throw", updateFeedHttpStatus: "http_non_ok", updateFeedMalformed: "malformed_body", updateCheckAborted: "aborted", updateDisabledByEnv: "disabled-by-env", updateDisabledLabBuild: "lab-build", updateDisabledNotPackaged: "not-packaged", updateDisabledUnsupportedPlatform: "unsupported-platform" };
export function updateCheckCauseForError(error: UpdateError | undefined): string | undefined { return error === undefined ? undefined : CHECK_CAUSES[UPDATE_ERRORS[error.code].name]; }
export function updateDirection(targetVersion: string | undefined, currentVersion: string): "upgrade" | "downgrade" | "same" | "unknown" { if (targetVersion === undefined || parseVersion(targetVersion) == null || parseVersion(currentVersion) == null) return "unknown"; const order = compareVersions(targetVersion, currentVersion); return order > 0 ? "upgrade" : order < 0 ? "downgrade" : "same"; }
export function updateOutcomeToTelemetry(report: any) { return { level: report.outcome === "staged" ? "info" : "warn", metadata: { outcome: report.outcome, phase: report.phase, track: report.track, direction: updateDirection(report.targetVersion, report.currentVersion), target_version: report.targetVersion, error_class: report.errorClass } }; }
export function updateCheckToTelemetry(report: any) { const cause = updateCheckCauseForError(report.error); return { level: report.result === "error" && cause !== "aborted" ? "warn" : "info", metadata: { action: report.action, check_seq: String(report.seq), trigger: report.trigger, track: report.track, result: report.result, cause, error_class: report.errorClass, direction: report.targetVersion === undefined ? undefined : updateDirection(report.targetVersion, report.currentVersion), target_version: report.targetVersion, duration_ms: report.durationMs === undefined ? undefined : String(Math.round(report.durationMs)), staged_version: report.stagedVersion, staged_age_ms: report.stagedAgeMs === undefined ? undefined : String(Math.round(report.stagedAgeMs)), flags_age_ms: report.flagsAgeMs === undefined ? undefined : String(Math.round(report.flagsAgeMs)), ...(report.error === undefined ? {} : updateErrorTags(report.error)) } }; }
export function updateApplyToTelemetry(report: any) { return { level: ["confirmed_late", "stale_version"].includes(report.outcome) ? "warn" : "info", metadata: { outcome: report.outcome, mechanism: report.mechanism, target_version: report.targetVersion, from_version: report.fromVersion, phase: report.phase, duration_ms: report.durationMs === undefined ? undefined : String(Math.round(report.durationMs)), relaunch_gap_ms: report.relaunchGapBucketMs === undefined ? undefined : String(report.relaunchGapBucketMs), superseding_version: report.supersedingVersion, ...(report.error === undefined ? {} : updateErrorTags(report.error)) } }; }
export function createUpdateTelemetryRelay(cap = 64) { let attached: any = null; const pending: ((sink: any) => void)[] = []; const deliver = (send: (sink: any) => void) => { if (attached != null) send(attached); else if (pending.length < cap) pending.push(send); }; return { reportOutcome: (report: any) => { const value = updateOutcomeToTelemetry(report); deliver((sink) => sink.reportUpdateOutcome(value.level, value.metadata)); }, reportCheck: (report: any) => { const value = updateCheckToTelemetry(report); deliver((sink) => sink.reportUpdateCheck(value.level, value.metadata)); }, reportApply: (report: any) => { const value = updateApplyToTelemetry(report); deliver((sink) => sink.reportUpdateApply(value.level, value.metadata)); }, attach: (sink: any) => { attached = sink; for (const send of pending.splice(0)) send(sink); } }; }
export const UPDATE_PROMPT_SURFACES = ["footer_pill", "account_menu", "palette", "settings", "blocker"] as const; export const UPDATE_PROMPT_ACTIONS = ["shown", "clicked", "confirmed", "canceled", "refused_superseded"] as const; export const UPDATE_PROMPT_KINDS = ["check", "progress", "ready", "error", "disabled"] as const; const VERSION_SHAPE = /^[0-9A-Za-z.+-]{1,64}$/;
export function isValidUpdatePromptReport(value: unknown): boolean { if (typeof value !== "object" || value === null) return false; const r = value as Record<string, unknown>; return typeof r.surface === "string" && (UPDATE_PROMPT_SURFACES as readonly string[]).includes(r.surface) && typeof r.action === "string" && (UPDATE_PROMPT_ACTIONS as readonly string[]).includes(r.action) && typeof r.kind === "string" && (UPDATE_PROMPT_KINDS as readonly string[]).includes(r.kind) && (r.targetVersion === undefined || typeof r.targetVersion === "string" && VERSION_SHAPE.test(r.targetVersion)); }
export function updatePromptToTelemetry(report: any) { return { level: "info", metadata: { surface: report.surface, action: report.action, kind: report.kind, target_version: report.targetVersion } }; }
