import { SandCloudAgentLaunchError } from "./cloud-agent-launch-error.js";
import { fetchSandModelCatalog } from "./model-catalog-fetch.js";
import type { SandModelCatalogEntry } from "../../../shared/agents/model-catalog.js";
export const CLOUD_AGENT_MAX_WAIT_MS = 5 * 60 * 60_000, CLOUD_AGENT_POLL_INTERVAL_MS = 10_000, CLOUD_AGENT_POLL_RPC_TIMEOUT_MS = 30_000, CLOUD_AGENT_RATE_LIMIT_FALLBACK_MS = 60_000, CLOUD_AGENT_RATE_LIMIT_JITTER_RATIO = 0.25, CLOUD_AGENT_RUN_RESTART_GRACE_MS = 3 * 60_000, SAVED_ENVIRONMENT_LIST_LIMIT = 500, MAX_LISTED_SAVED_ENVIRONMENTS = 25, MODEL_CATALOG_TTL_MS = 5 * 60_000, TEAM_ADMIN_POLICY_TTL_MS = 5 * 60_000, TEAM_ADMIN_POLICY_REQUEST_TIMEOUT_MS = 10_000;
export type CloudAgentRunStatus = "unspecified" | "creating" | "running" | "finished" | "error" | "expired" | number;
export interface DetailedComposer { readonly composer?: { readonly status?: CloudAgentRunStatus; readonly prUrl?: string; readonly branchName?: string; readonly commitCount?: number; readonly filesChanged?: number; readonly linesAdded?: number; readonly linesRemoved?: number }; readonly prs?: readonly { readonly prUrl?: string; readonly branchName?: string; readonly pullNumber?: number; readonly prStatus?: unknown }[]; readonly summary?: string; readonly permanentError?: { readonly details?: { readonly title: string; readonly detail: string; readonly additionalInfo?: { readonly rateLimitReason?: string } } } }
const statusName = (status: CloudAgentRunStatus): CloudAgentRunStatus => { if (typeof status === "string") return status; switch (status) { case 1: return "running"; case 2: return "finished"; case 3: return "error"; case 4: return "creating"; case 5: return "expired"; default: return "unspecified"; } };
export function cloudAgentRateLimitPauseMs(error: unknown, random = Math.random): number { const retryAfter = typeof error === "object" && error != null && typeof (error as { retryAfterMs?: unknown }).retryAfterMs === "number" ? (error as { retryAfterMs: number }).retryAfterMs : CLOUD_AGENT_RATE_LIMIT_FALLBACK_MS; return Math.round(retryAfter + random() * retryAfter * CLOUD_AGENT_RATE_LIMIT_JITTER_RATIO); }
export function availableEnvironmentsNote(environments: readonly { name: string; publicId: string }[]): string { if (environments.length === 0) return " This account has no saved environments; create one from the Cloud Agents dashboard on cursor.com."; const listed = environments.slice(0, MAX_LISTED_SAVED_ENVIRONMENTS).map((environment) => environment.name.trim() ? `${environment.name.trim()} (${environment.publicId})` : environment.publicId).join(", "), hidden = environments.length - MAX_LISTED_SAVED_ENVIRONMENTS; return ` Available: ${listed}${hidden > 0 ? ` (+${hidden} more; set environment.id to launch one that isn't listed)` : ""}.`; }
export function resolveSandLimitError(detailed: DetailedComposer | null | undefined): string | null { const details = detailed?.permanentError?.details; return details?.additionalInfo?.rateLimitReason !== "sand_included_limit" ? null : [details.title, details.detail].map((value) => value.trim()).filter(Boolean).join("\n"); }
export function formatDiffStats(detailed?: DetailedComposer): string | undefined { const composer = detailed?.composer; if (composer == null) return undefined; const parts: string[] = []; if ((composer.commitCount ?? 0) > 0) parts.push(`${composer.commitCount} commit${composer.commitCount === 1 ? "" : "s"}`); if ((composer.filesChanged ?? 0) > 0) parts.push(`+${composer.linesAdded ?? 0}/-${composer.linesRemoved ?? 0} across ${composer.filesChanged} file${composer.filesChanged === 1 ? "" : "s"}`); return parts.length > 0 ? `Changes: ${parts.join(", ")}.` : undefined; }
export function buildWatchResult(bcId: string, status: CloudAgentRunStatus, detailed?: DetailedComposer) { const normalized = statusName(status), composer = detailed?.composer, summary = detailed?.summary?.trim(), prUrl = (composer?.prUrl || detailed?.prs?.find((pr) => pr.prUrl)?.prUrl) ?? ""; if (normalized === "error" || normalized === "expired") { const lines = [`The Cursor agent (${bcId}) ${normalized === "expired" ? "expired" : "errored"} before finishing.`], limit = resolveSandLimitError(detailed); if (limit) lines.push("", limit); if (summary) lines.push("", summary); return { status: "error" as const, text: lines.join("\n") }; } const lines = ["The Cursor agent finished."]; if (composer?.branchName) lines.push(`Branch: ${composer.branchName}`); lines.push(prUrl ? `Pull request: ${prUrl}` : "No pull request link is available yet (the agent may have made no changes, or the PR is still being created)."); const stats = formatDiffStats(detailed); if (stats) lines.push(stats); if (summary) lines.push("", "Summary from the Cursor agent:", summary); return { status: "completed" as const, text: lines.join("\n") }; }
export interface SavedEnvironmentClient { getEnvironment(request: { publicId: string }): Promise<{ environment?: SavedEnvironment }>; listEnvironments(request: { includeRepositoryScopeEnvironments: true; limit: number }): Promise<{ environments: readonly SavedEnvironment[] }> }
export interface SavedEnvironment { readonly publicId: string; readonly name: string; readonly [key: string]: unknown }
async function listSavedEnvironments(client: SavedEnvironmentClient): Promise<readonly SavedEnvironment[]> { return (await client.listEnvironments({ includeRepositoryScopeEnvironments: true, limit: SAVED_ENVIRONMENT_LIST_LIMIT })).environments; }
export async function resolveSavedEnvironment(client: SavedEnvironmentClient, selector: { publicId?: string; name?: string }): Promise<SavedEnvironment> { const id = selector.publicId?.trim(), name = selector.name?.trim(); if (id) { const value = (await client.getEnvironment({ publicId: id })).environment; if (value != null) return value; throw new SandCloudAgentLaunchError(`No saved environment with id '${id}'.${availableEnvironmentsNote(await listSavedEnvironments(client))}`); } if (!name) throw new SandCloudAgentLaunchError("A saved-environment launch requires the environment's public id or name."); const values = await listSavedEnvironments(client), matches = values.filter((value) => value.name.trim().toLowerCase() === name.toLowerCase()); if (matches.length === 1 && matches[0] != null) return matches[0]; if (matches.length === 0) throw new SandCloudAgentLaunchError(`No saved environment named '${name}'.${availableEnvironmentsNote(values)}`); throw new SandCloudAgentLaunchError(`Multiple saved environments are named '${name}'. Set environment.id to one of: ${matches.map((value) => value.publicId).join(", ")}.`); }
export interface Clock { monotonicNow(): number }
export class CloudAgentModelCatalogCache { private cache?: { catalog: readonly SandModelCatalogEntry[]; fetchedAtMs: number }; constructor(private readonly options: { readonly clock: Clock; readonly getCursorAccessToken: (options: { readonly backendUrl: string }) => Promise<string>; readonly getMachineId: () => Promise<string>; readonly onRequestId?: (requestId: string) => void; readonly modelCatalogForTesting?: readonly SandModelCatalogEntry[] }) {} async listModels(): Promise<readonly SandModelCatalogEntry[]> { if (this.options.modelCatalogForTesting != null) return this.options.modelCatalogForTesting; const now = this.options.clock.monotonicNow(); if (this.cache != null && now - this.cache.fetchedAtMs < MODEL_CATALOG_TTL_MS) return this.cache.catalog; const catalog = await fetchSandModelCatalog({ getAccessToken: this.options.getCursorAccessToken, getMachineId: this.options.getMachineId, ...(this.options.onRequestId === undefined ? {} : { onRequestId: this.options.onRequestId }) }); this.cache = { catalog, fetchedAtMs: now }; return catalog; } }
export class CloudAgentTeamAdminPolicyCache { private cache?: { disabled: boolean; fetchedAtMs: number }; private fetch: Promise<void> | undefined; constructor(private readonly options: { readonly clock: Clock; readonly load: () => Promise<{ disableCloudAgentsInSand?: boolean }> }) {} isDisabledByTeamAdmin(): boolean { this.refresh(); return this.cache?.disabled ?? false; } prefetchTeamAdminPolicy(): void { this.refresh(); } private refresh(): void { if (this.fetch != null) return; const now = this.options.clock.monotonicNow(); if (this.cache != null && now - this.cache.fetchedAtMs < TEAM_ADMIN_POLICY_TTL_MS) return; this.fetch = this.options.load().then((value) => { this.cache = { disabled: value.disableCloudAgentsInSand === true, fetchedAtMs: this.options.clock.monotonicNow() }; }).catch(() => { this.cache = { disabled: this.cache?.disabled ?? false, fetchedAtMs: this.options.clock.monotonicNow() }; }).finally(() => { this.fetch = undefined; }); } }
export interface PollingPolicy { start(run: () => void | Promise<void>): { dispose(): void } }
export class CloudAgentCompletionPoller {
  private readonly active = new Set<{ dispose(): void }>();
  constructor(private readonly options: { readonly completionPolling: PollingPolicy; readonly clock: Clock; readonly maxWaitMs?: number; readonly runRestartGraceMs?: number; readonly randomFn?: () => number; readonly isRateLimitError?: (error: unknown) => boolean }, private readonly getClient: () => { getBackgroundComposerInfo(request: { bcId: string; includeDiff: false; doNotThrowIfSetupNotFinished: true }, options: { timeoutMs: number }): Promise<{ composer?: DetailedComposer }> }) {}
  dispose(): void { for (const poll of this.active) poll.dispose(); this.active.clear(); }
  async awaitCompletion(bcId: string, options?: { waitForRestart?: boolean }): Promise<{ status: "completed" | "error"; text: string }> { const client = this.getClient(), maxWaitMs = this.options.maxWaitMs ?? CLOUD_AGENT_MAX_WAIT_MS, deadline = this.options.clock.monotonicNow() + maxWaitMs, restartDeadline = this.options.clock.monotonicNow() + (this.options.runRestartGraceMs ?? CLOUD_AGENT_RUN_RESTART_GRACE_MS); let awaitingRestart = options?.waitForRestart ?? false, skip = true, pausedUntil = 0; return await new Promise((resolve) => { let settled = false; let poll: { dispose(): void } | undefined; const timeout = () => ({ status: "error" as const, text: `The Cursor agent (${bcId}) is still running after ${Math.round(maxWaitMs / 60_000)} minutes. It keeps running on the VM; check the Cursor cloud agents dashboard for the result.` }); const finish = (value: { status: "completed" | "error"; text: string }) => { if (settled) return; settled = true; poll?.dispose(); if (poll != null) this.active.delete(poll); resolve(value); }; poll = this.options.completionPolling.start(async () => { try { if (skip) { skip = false; return; } const now = this.options.clock.monotonicNow(); if (now < pausedUntil) { if (now >= deadline) finish(timeout()); return; } let detailed: DetailedComposer | undefined; try { detailed = (await client.getBackgroundComposerInfo({ bcId, includeDiff: false, doNotThrowIfSetupNotFinished: true }, { timeoutMs: CLOUD_AGENT_POLL_RPC_TIMEOUT_MS })).composer; } catch (error) { if (this.options.isRateLimitError?.(error)) pausedUntil = now + cloudAgentRateLimitPauseMs(error, this.options.randomFn); if (now >= deadline) finish(timeout()); return; } const status = statusName(detailed?.composer?.status ?? "unspecified"), active = status === "running" || status === "creating"; if (awaitingRestart) { if (active || now >= restartDeadline) awaitingRestart = false; else { if (now >= deadline) finish(timeout()); return; } } if (active || status === "unspecified") { if (now >= deadline) finish(timeout()); return; } finish(buildWatchResult(bcId, status, detailed)); } catch { finish({ status: "error", text: `The Cursor agent (${bcId}) status check failed unexpectedly. Check the Cursor cloud agents dashboard for the result.` }); } }); if (!settled) this.active.add(poll); }); }
}
