import { randomUUID } from "node:crypto";
import { SandCloudAgentLaunchError } from "./cloud-agent-launch-error.js";
export interface SavedEnvironment { readonly publicId: string; readonly name: string; readonly repoConfig?: { readonly repos: readonly { readonly repoUrl: string; readonly scmRepoNodeId?: string; readonly gitEnterpriseUuid?: string }[] } }
export type CloudAgentEnvironment = { readonly type: "cloud" } | { readonly type: "environment"; readonly publicId?: string; readonly name?: string } | { readonly type: "pool"; readonly name?: string; readonly teamId?: number } | { readonly type: "machine"; readonly name: string; readonly teamId?: number };
export function buildCloudAgentRequestedModel(modelId?: string | null, params?: Readonly<Record<string, string>> | null) { const parameters = Object.entries(params ?? {}).map(([id, value]) => ({ id, value })), trimmed = modelId?.trim(); if (!trimmed) { if (parameters.length > 0) throw new SandCloudAgentLaunchError("'model' is required when 'model_params' are provided."); return null; } return { modelId: trimmed, maxMode: true, parameters }; }
export function buildCloudAgentUserMessage(args: { readonly prompt: string; readonly mode?: unknown; readonly images?: readonly { readonly data: Uint8Array; readonly path?: string; readonly mimeType?: string }[] }) { const images = args.images ?? []; return { text: args.prompt, messageId: randomUUID(), ...(args.mode == null ? {} : { mode: args.mode }), ...(images.length === 0 ? {} : { selectedContext: { selectedImages: images.map((image) => ({ dataOrBlobId: { case: "data" as const, value: image.data }, path: image.path ?? "", mimeType: image.mimeType ?? "" })) } }) }; }
export function buildCloudAgentConversationAction(userMessage: ReturnType<typeof buildCloudAgentUserMessage>) { return { action: { case: "userMessageAction" as const, value: { userMessage, sendToInteractionListener: true } } }; }
function trimRemotePath(pathname: string): string { const normalized = pathname.replace(/\/+$/, "").replace(/\.git$/i, ""); return !normalized || normalized === "/" ? "" : normalized.startsWith("/") ? normalized : `/${normalized}`; }
function toSanitizationCandidate(rawUrl: string): string { if (/^[a-z][a-z0-9+.-]*:\/\//i.test(rawUrl)) return rawUrl; const https = `https://${rawUrl}`; try { void new URL(https); return https; } catch { const match = rawUrl.match(/^([^@/\s]+@)?([^:/\s]+):(.+)$/); return match == null ? https : `ssh://${match[1] ?? ""}${match[2]}/${match[3]}`; } }
export function sanitizeRemoteUrl(raw: string): string { const value = raw.trim(); if (!value) return ""; try { const parsed = new URL(toSanitizationCandidate(value)); return `${parsed.hostname}${trimRemotePath(parsed.pathname)}`.toLowerCase(); } catch { return ""; } }
export function sanitizeRemoteUrlForHttpUrl(raw: string): string { const value = raw.trim(); if (!value) return ""; try { const parsed = new URL(toSanitizationCandidate(value)), protocol = parsed.protocol === "http:" || parsed.protocol === "https:" ? parsed.protocol : "https:"; return `${protocol}//${parsed.host.toLowerCase()}${trimRemotePath(parsed.pathname)}`; } catch { const normalized = sanitizeRemoteUrl(value); return normalized ? `https://${normalized}` : ""; } }
export function normalizeRepoReference(ref: string): string { const value = ref.trim(); return /^[A-Za-z0-9][A-Za-z0-9._-]*\/[A-Za-z0-9][A-Za-z0-9._-]*$/.test(value) ? `https://github.com/${value}` : value; }
export function buildRepoFromRemote(remote: string, baseBranch?: string) { const normalized = normalizeRepoReference(remote), sanitizedRepoUrl = sanitizeRemoteUrl(normalized), httpRepoUrl = sanitizeRemoteUrlForHttpUrl(normalized); if (!sanitizedRepoUrl || !httpRepoUrl) throw new SandCloudAgentLaunchError(`The Cursor agent could not parse the repository '${remote}'.`); return { sanitizedRepoUrl, httpRepoUrl, ...(baseBranch === undefined ? {} : { baseBranch }) }; }
function describeSavedEnvironment(environment: SavedEnvironment): string { return environment.name.trim() || environment.publicId; }
const canonical = (value: string) => sanitizeRemoteUrl(normalizeRepoReference(value));
export function resolveLaunchRepoReference(repoUrl: string | undefined, savedEnvironment?: SavedEnvironment) { const requested = repoUrl?.trim() ?? ""; if (savedEnvironment == null) { if (!requested) throw new SandCloudAgentLaunchError("'repo_url' is required to launch a cloud agent."); return requested; } const label = describeSavedEnvironment(savedEnvironment), repos = savedEnvironment.repoConfig?.repos ?? [], primary = repos[0]?.repoUrl.trim() ?? ""; if (!primary) { if (!requested) throw new SandCloudAgentLaunchError(`The '${label}' environment has no repositories configured, so pass repo_url to pick the repo to launch on.`); return requested; } if (!requested || canonical(requested) === canonical(primary)) return primary; const secondary = repos.slice(1).some((entry) => canonical(entry.repoUrl) === canonical(requested)); throw new SandCloudAgentLaunchError(secondary ? `'${requested}' is a secondary repo of the '${label}' environment; the launch's branch/PR lands on its primary repo '${primary}'. Omit repo_url to use it.` : `'${requested}' is not part of the '${label}' environment (repos: ${repos.map((entry) => entry.repoUrl).join(", ")}). Omit repo_url to use its primary repo, or pick a different environment.`); }
export function toStartRepoConfig(config?: SavedEnvironment["repoConfig"]) { return config == null || config.repos.length === 0 ? undefined : { repos: config.repos.map(({ repoUrl, scmRepoNodeId, gitEnterpriseUuid }) => ({ repoUrl, ...(scmRepoNodeId === undefined ? {} : { scmRepoNodeId }), ...(gitEnterpriseUuid === undefined ? {} : { gitEnterpriseUuid }) })) }; }
export const PRIVATE_WORKER_SHARED_ASSIGNMENT_ALLOWED_LABEL_KEY = "cursor.private_worker.shared_assignment_allowed";
function deriveRepoLabelValueFromUrl(url: string): string | null { const normalized = sanitizeRemoteUrl(url); return normalized || null; }
export function resolveCloudAgentEnvironmentFields(repoUrl: string, environment?: CloudAgentEnvironment) { if (environment == null || environment.type === "cloud" || environment.type === "environment") return {}; if (environment.type === "pool") { const repo = deriveRepoLabelValueFromUrl(repoUrl); if (repo == null) throw new SandCloudAgentLaunchError(`The Cursor agent could not derive private-worker routing labels from '${repoUrl}'.`); const labels = [{ key: "repo", value: repo }]; const name = environment.name?.trim(); if (name) labels.push({ key: "pool", value: name }); return { usePrivateWorker: true, labels }; } const name = environment.name.trim(); if (!name) throw new SandCloudAgentLaunchError("A private-worker machine environment requires a registered name."); return { usePrivateWorker: true, labels: [{ key: "name", value: name }, { key: PRIVATE_WORKER_SHARED_ASSIGNMENT_ALLOWED_LABEL_KEY, value: "true" }] }; }
