import { posix } from "node:path";
import { findSystemErrno } from "../../shared/system-errno.js";

export const SAND_BOX_UPLOADS_DIR = "/workspace/uploads", SAND_BOX_WORKSPACE_ROOT = "/workspace";
export const BOX_PATH_ROOTS = ["/workspace", "/home", "/root"] as const;
export function isBoxRootPath(path: string): boolean { return BOX_PATH_ROOTS.some(root => path === root || path.startsWith(`${root}/`)); }
export function resolveBoxWorkspacePath(boxPath: string): string { return posix.isAbsolute(boxPath) ? posix.normalize(boxPath) : posix.join(SAND_BOX_WORKSPACE_ROOT, boxPath); }
export class BoxTransferError extends Error { override name = "BoxTransferError"; }
export class BoxFileUnreadableError extends Error { override name = "BoxFileUnreadableError"; }
export const DEFAULT_BOX_TRANSFER_MAX_BYTES = 256 * 1024 * 1024, DEFAULT_BOX_TRANSFER_CONCURRENCY = 4;
export interface TransferBox { downloadFile(ctx: unknown, agentId: string, path: string): Promise<Uint8Array>; uploadFile(ctx: unknown, agentId: string, path: string, data: Uint8Array): Promise<void> }
interface TransferEndpoint { box: TransferBox; agentId: string; path: string; label: string }
function errorMessage(error: unknown): string { return error instanceof Error ? error.message : String(error); }
export function isSourceMissingError(error: unknown): boolean { if (error instanceof BoxFileUnreadableError || findSystemErrno(error) === "ENOENT") return true; const message = errorMessage(error).toLowerCase(); return message.includes("no such file or directory") || message.includes("enoent"); }
export async function transferFileBetweenBoxes(ctx: unknown, args: { source: TransferEndpoint; dest: TransferEndpoint; maxBytes?: number }): Promise<number> { const { source, dest } = args; let data: Uint8Array; try { data = await source.box.downloadFile(ctx, source.agentId, source.path); } catch (error) { if (isSourceMissingError(error)) throw new BoxTransferError(`source file not found on ${source.label}: ${source.path}`, { cause: error }); throw new BoxTransferError(`failed to read ${source.path} from ${source.label}: ${errorMessage(error)}`, { cause: error }); } const max = args.maxBytes ?? DEFAULT_BOX_TRANSFER_MAX_BYTES; if (data.byteLength > max) throw new BoxTransferError(`file is too large to transfer: ${source.path} on ${source.label} is ${data.byteLength} bytes, over the ${max}-byte limit`); try { await dest.box.uploadFile(ctx, dest.agentId, dest.path, data); } catch (error) { throw new BoxTransferError(`failed to write ${dest.path} on ${dest.label}: ${errorMessage(error)}`, { cause: error }); } return data.byteLength; }
export async function forEachBounded<T>(items: readonly T[], limit: number, fn: (item: T) => Promise<void>): Promise<void> { let cursor = 0, aborted = false; async function worker() { while (cursor < items.length && !aborted) { const item = items[cursor++]; if (item === undefined) return; try { await fn(item); } catch (error) { aborted = true; throw error; } } } await Promise.all(Array.from({ length: Math.min(Math.max(1, limit), items.length) }, worker)); }
export async function forEachWavePipelined<T, Work>(items: readonly T[], opts: { waveSize: number; concurrency: number; prepareWave(wave: readonly T[]): Promise<readonly Work[]>; process(work: Work): Promise<void> }): Promise<void> { const waveSize = Math.max(1, opts.waveSize), queue: Work[] = []; let next = 0, preparing: Promise<void> | undefined, failure: unknown, failed = false, waiters: Array<() => void> = []; const wake = () => { const current = waiters; waiters = []; current.forEach(resolve => resolve()); }; const begin = () => { if (failed || preparing != null || next >= items.length || queue.length >= waveSize) return; const wave = items.slice(next, next + waveSize); next += waveSize; preparing = opts.prepareWave(wave).then(work => { queue.push(...work); }).catch(error => { failed = true; failure ??= error; }).finally(() => { preparing = undefined; begin(); wake(); }); }; async function worker() { for (;;) { if (failed) return; const work = queue.shift(); if (work !== undefined) { begin(); try { await opts.process(work); } catch (error) { failed = true; failure ??= error; wake(); return; } continue; } if (preparing == null && next >= items.length) return; begin(); if (queue.length === 0 && !(preparing == null && next >= items.length)) await new Promise<void>(resolve => waiters.push(resolve)); } } begin(); await Promise.all(Array.from({ length: Math.max(1, opts.concurrency) }, worker)); if (failed) throw failure; }
export async function downloadBoxFiles(ctx: unknown, box: TransferBox, agentId: string, boxPaths: readonly string[], opts?: { maxConcurrency?: number }): Promise<Map<string, Uint8Array>> { const unique = [...new Set(boxPaths)], downloaded = new Map<string, Uint8Array>(); await forEachBounded(unique, opts?.maxConcurrency ?? DEFAULT_BOX_TRANSFER_CONCURRENCY, async path => { downloaded.set(path, await box.downloadFile(ctx, agentId, path)); }); return new Map(unique.map(path => { const bytes = downloaded.get(path); if (bytes === undefined) throw new Error(`download from box ${path} produced no bytes`); return [path, bytes]; })); }
export async function uploadBoxFiles(ctx: unknown, box: TransferBox, agentId: string, uploads: readonly { boxPath: string; data: Uint8Array }[], opts?: { maxConcurrency?: number }): Promise<string[]> { const seen = new Set<string>(), unique = uploads.filter(({ boxPath }) => !seen.has(boxPath) && Boolean(seen.add(boxPath))); await forEachBounded(unique, opts?.maxConcurrency ?? DEFAULT_BOX_TRANSFER_CONCURRENCY, async upload => box.uploadFile(ctx, agentId, upload.boxPath, upload.data)); return unique.map(upload => upload.boxPath); }
