import { decodeBackgroundWorkMetadata } from "../../packages/agent-exec/background-work-metadata.js";

export interface BackgroundWorkRecord { readonly id: string; readonly kind: string; readonly state: string; readonly ownerId?: string; readonly abort?: () => void; readonly metadata?: unknown }
export interface BackgroundWakeup { readonly id?: string; readonly conversationId?: string; readonly payload: { readonly kind: string; readonly reason?: string; readonly taskId: string; readonly title?: string; readonly status?: string; readonly detail?: string; readonly outputPath?: string } }
export class RevivingBackgroundWorkRegistry {
  readonly #work = new Map<string, BackgroundWorkRecord>();
  readonly #wakeups: BackgroundWakeup[] = [];
  readonly #completions: BackgroundWakeup["payload"][] = [];
  readonly #quietOrigins = new Map<string, string>();
  constructor(readonly onShellCompletion?: (item: BackgroundWakeup["payload"], quietOrigin?: string) => void, readonly onShellWorkRegistered?: (record: BackgroundWorkRecord, quietOrigin?: string) => void, readonly onWorkSetChanged?: () => void) {}
  upsertWork(record: BackgroundWorkRecord): void { this.#work.set(record.id, record); this.onWorkSetChanged?.(); }
  clearWork(id: string): BackgroundWorkRecord | undefined { const value = this.#work.get(id); this.#work.delete(id); this.onWorkSetChanged?.(); return value; }
  abortWork(id: string): boolean { const record = this.#work.get(id); if (record == null) return false; record.abort?.(); this.#work.delete(id); this.onWorkSetChanged?.(); return true; }
  abortAllWork(filter: { kind?: string } = {}): number { let count = 0; for (const record of this.listWork(filter)) { this.#work.get(record.id)?.abort?.(); this.#work.delete(record.id); count += 1; } this.onWorkSetChanged?.(); return count; }
  hasRunningWork(filter: { kind?: string } = {}): boolean { return this.listWork(filter).some((record) => record.state === "running"); }
  listWork(filter: { kind?: string } = {}): BackgroundWorkRecord[] { return [...this.#work.values()].filter((record) => filter.kind == null || record.kind === filter.kind); }
  enqueue(wakeup: BackgroundWakeup): void { const item = wakeup.payload; if (item.kind === "shell" && item.reason !== "task_progress") { const origin = this.#quietOrigins.get(item.taskId); this.#quietOrigins.delete(item.taskId); this.onShellCompletion?.(item, origin); return; } this.#wakeups.push(wakeup); }
  pull(conversationId: string): BackgroundWakeup[] { return this.#wakeups.filter((item) => item.conversationId == null || item.conversationId === conversationId); }
  ack(ids: readonly string[]): void { const selected = new Set(ids); for (let index = this.#wakeups.length - 1; index >= 0; index -= 1) if (selected.has(this.#wakeups[index]?.id ?? "")) this.#wakeups.splice(index, 1); }
  nack(_ids: readonly string[], _options?: unknown): void {}
  suppress(conversationId: string, id: string): void { for (let index = this.#wakeups.length - 1; index >= 0; index -= 1) { const wake = this.#wakeups[index]; if (wake?.conversationId === conversationId && wake.id === id) this.#wakeups.splice(index, 1); } }
  enqueueCompletion(item: BackgroundWakeup["payload"]): void { this.#completions.push(item); }
  drainCompletions(): BackgroundWakeup["payload"][] { return this.#completions.splice(0); }
  hasPendingCompletions(_conversationId: string): boolean { return this.#completions.length > 0; }
  markAwaitedCompletion(_taskId: string): void {}
  recordWorkOrigin(id: string, origin?: string): void { if (origin != null) this.#quietOrigins.set(id, origin); else this.#quietOrigins.delete(id); }
  forTurn(origin?: string) { const inner = this; return { upsertWork(record: BackgroundWorkRecord) { inner.recordWorkOrigin(record.id, origin); inner.upsertWork(record); if (record.kind === "shell" && record.state === "running") inner.onShellWorkRegistered?.(record, origin); }, clearWork: (id: string) => inner.clearWork(id), abortWork: (id: string) => inner.abortWork(id), hasRunningWork: (filter?: { kind?: string }) => inner.hasRunningWork(filter), abortAllWork: (filter?: { kind?: string }) => inner.abortAllWork(filter), listWork: (filter?: { kind?: string }) => inner.listWork(filter), enqueue: (wake: BackgroundWakeup) => inner.enqueue(wake), pull: (id: string) => inner.pull(id), ack: (ids: readonly string[]) => inner.ack(ids), nack: (ids: readonly string[], options?: unknown) => inner.nack(ids, options), suppress: (conversationId: string, id: string) => inner.suppress(conversationId, id), enqueueCompletion: (item: BackgroundWakeup["payload"]) => inner.enqueueCompletion(item), drainCompletions: () => inner.drainCompletions(), hasPendingCompletions: (id: string) => inner.hasPendingCompletions(id), markAwaitedCompletion: (id: string) => inner.markAwaitedCompletion(id) }; }
}
export const SHELL_REWATCH_POLL_DEFAULT_MS = 10_000;
export const SHELL_REWATCH_MAX_WAIT_MS = 5 * 60 * 60 * 1_000;
export const SHELL_REWATCH_MISSING_FILE_GIVE_UP = 5;
export function shellRewatchPollMs(env: NodeJS.ProcessEnv = process.env): number { const parsed = Number.parseInt(env.SAND_SHELL_REWATCH_POLL_MS?.trim() ?? "", 10); return Number.isFinite(parsed) && parsed > 0 ? parsed : SHELL_REWATCH_POLL_DEFAULT_MS; }
export function parseShellTerminalFooter(content: string): { isComplete: boolean; exitCode?: number; isStreamFailure?: boolean } { const match = content.match(/\n---\n([\s\S]*?)\n---\s*$/); if (match == null) return { isComplete: false }; const footer = match[1] ?? "", exit = footer.match(/(?:^|\n)exit_code:\s*([^\n]*)/); if (exit != null) { const raw = (exit[1] ?? "").trim(), parsed = Number(raw); return { isComplete: true, ...(raw && Number.isInteger(parsed) ? { exitCode: parsed } : {}) }; } return /(?:^|\n)error:\s*([^\n]*)/.test(footer) && /(?:^|\n)ended_at:\s*\S/.test(footer) ? { isComplete: true, isStreamFailure: true } : { isComplete: false }; }
export function deriveBackgroundSubagentTitle(prompt: string): string { const oneLine = prompt.replace(/\s+/g, " ").trim(); if (oneLine.length === 0) return "Background task"; const maxLength = 80; return oneLine.length <= maxLength ? oneLine : `${oneLine.slice(0, maxLength - 1)}\u2026`; }
export function formatSteerPrompt(message: string): string { return ["[Steering message from the parent agent that dispatched you]", message.trim(), "Take this into account and continue your task from where you are — do not start over."].join("\n\n"); }
export interface BackgroundWatchesHost {
  getConversationId(): string; emitAsyncTasksChanged(): void;
  pendingWakeArmedHandler(): ((event: unknown) => void) | undefined;
  backgroundShellSettledHandler(): ((event: unknown) => void) | undefined;
  notifyBackgroundWorkSettled(completion: unknown): void;
  cloudAgentWatcher(): { awaitCompletion(id: string, options: { waitForRestart: boolean }): Promise<{ status: string; text: string }> } | null;
  pollShellTerminalFile(id: string, cancelled: () => boolean, settle: (status: string, detail?: string, outputPath?: string) => void): void;
}
export function createBackgroundWatches(host: BackgroundWatchesHost) {
  const cloud = new Map<string, { title: string; startedAtMs: number }>(), shell = new Map<string, { cancel(): void; title: string; startedAtMs: number }>(); let registryValue: RevivingBackgroundWorkRegistry | undefined;
  const cancelShellRewatch = (shellId: string): void => { shell.get(shellId)?.cancel(); };
  const registry = () => registryValue ??= new RevivingBackgroundWorkRegistry((item, quietOrigin) => host.backgroundShellSettledHandler()?.({ agentId: host.getConversationId(), shellId: item.taskId, title: item.title, status: item.status, detail: item.detail, outputPath: item.outputPath, ...(quietOrigin == null ? {} : { quietOrigin }) }), (record, quietOrigin) => { cancelShellRewatch(record.id); const metadata = typeof record.metadata === "object" && record.metadata !== null && !Array.isArray(record.metadata) ? Object.fromEntries(Object.entries(record.metadata)) : undefined; const title = decodeBackgroundWorkMetadata(metadata).title ?? `Background command ${record.id}`; host.pendingWakeArmedHandler()?.({ parentAgentId: host.getConversationId(), kind: "shell", workId: record.id, title, ...(quietOrigin == null ? {} : { quietOrigin }) }); }, () => host.emitAsyncTasksChanged());
  const watchCloudAgent = (bcId: string, options?: { quietOrigin?: string; afterFollowup?: boolean }): void => { const id = bcId.trim(), watcher = host.cloudAgentWatcher(); if (!id || watcher == null || cloud.has(id)) return; const title = `Cloud agent ${id}`, startedAtMs = Date.now(), entry = { title, startedAtMs }; cloud.set(id, entry); host.pendingWakeArmedHandler()?.({ parentAgentId: host.getConversationId(), kind: "cloud-agent", workId: id, title, ...(options?.quietOrigin == null ? {} : { quietOrigin: options.quietOrigin }) }); host.emitAsyncTasksChanged(); const base = { parentAgentId: host.getConversationId(), subagentAgentId: id, subagentType: "cursor-agent", toolCallId: "", title, ...(options?.quietOrigin == null ? {} : { quietOrigin: options.quietOrigin }) }; void watcher.awaitCompletion(id, { waitForRestart: options?.afterFollowup ?? false }).then((result) => { if (cloud.get(id) !== entry) return; cloud.delete(id); host.emitAsyncTasksChanged(); host.notifyBackgroundWorkSettled({ ...base, status: result.status === "error" ? "error" : "completed", result: result.text.trim() || "(the cloud agent finished without producing any output)" }); }, (error) => { if (cloud.get(id) !== entry) return; cloud.delete(id); host.emitAsyncTasksChanged(); host.notifyBackgroundWorkSettled({ ...base, status: "error", result: error instanceof Error ? error.message : String(error) }); }); };
  const watchBackgroundShell = (shellId: string, options?: { title?: string; quietOrigin?: string }): void => { const id = shellId.trim(); if (!id) return; const title = options?.title ?? `Background command ${id}`; host.pendingWakeArmedHandler()?.({ parentAgentId: host.getConversationId(), kind: "shell", workId: id, title, ...(options?.quietOrigin == null ? {} : { quietOrigin: options.quietOrigin }) }); if (shell.has(id) || registry().listWork({ kind: "shell" }).some((work) => work.id === id)) return; let cancelled = false; const cancel = () => { cancelled = true; shell.delete(id); host.emitAsyncTasksChanged(); }; shell.set(id, { cancel, title, startedAtMs: Date.now() }); host.emitAsyncTasksChanged(); host.pollShellTerminalFile(id, () => cancelled, (status, detail, outputPath) => { if (cancelled) return; shell.delete(id); host.emitAsyncTasksChanged(); host.backgroundShellSettledHandler()?.({ agentId: host.getConversationId(), shellId: id, title, status, detail, outputPath, ...(options?.quietOrigin == null ? {} : { quietOrigin: options.quietOrigin }) }); }); };
  const cancelBackgroundShellRewatches = () => { for (const watch of shell.values()) watch.cancel(); shell.clear(); };
  const cancelBackgroundWatches = () => { cancelBackgroundShellRewatches(); registryValue?.abortAllWork({ kind: "shell" }); cloud.clear(); host.emitAsyncTasksChanged(); };
  return { registry, listRegisteredShellWork: (filter?: { kind?: string }) => registryValue?.listWork(filter), watchCloudAgent, watchBackgroundShell, pendingCloudAgentWatchBcIds: () => [...cloud.keys()], pendingShellRewatchIds: () => [...shell.keys()], hasRunningBackgroundShellWork: () => shell.size > 0 || (registryValue?.hasRunningWork({ kind: "shell" }) ?? false), cancelBackgroundShellRewatches, cancelBackgroundWatches, shellRewatchEntries: () => shell.entries(), cloudAgentWatchEntries: () => cloud.entries() };
}
