export const BOX_RECREATE_STALLED_AFTER_MS = 600_000;
export const SETUP_REBEGIN_DEDUPE_MS = 1_000;
const BOUNDED_TOKEN = /^[0-9A-Za-z._:|-]{1,128}$/;
type Event = "setup" | "recreate"; type Surface = "foreground" | "background";
export interface BoxVisibilityReport { event: Event; phase: "begin" | "heartbeat" | "end" | "stage_transition"; trigger?: string; outcome?: string; operationId?: string; kind?: string; surface?: string; stage?: string; fromStage?: string; migrationPhase?: string; stageElapsedMs?: number }
export interface BoxVisibilitySink { emit(event: Event, payload: Record<string, unknown>): void; emitRecreateHeartbeat(payload: Record<string, unknown>): void; emitRebuildStage(payload: Record<string, unknown>): void }
const boundedToken = (value: unknown): string | undefined => typeof value === "string" && BOUNDED_TOKEN.test(value) ? value : undefined;
const boundedSurface = (value: unknown): Surface | undefined => value === "foreground" || value === "background" ? value : undefined;
export interface FrameIdentity { processId: number; frameToken: string; isDestroyed(): boolean }
export const documentKeyOf = (frame: FrameIdentity): string => `${frame.processId}:${frame.frameToken}`;
export function installBoxVisibilityDocumentReset(contents: { on(event: string, listener: () => void): void }, onDocumentGone: () => void): void { contents.on("did-navigate", onDocumentGone); contents.on("render-process-gone", onDocumentGone); contents.on("destroyed", onDocumentGone); }
export function createBoxVisibilityReportHandler(tracker: () => { handle(report: BoxVisibilityReport, key: string): void } | null | undefined) { return ({ report, senderFrame, currentMainFrame }: { report: unknown; senderFrame: FrameIdentity | null; currentMainFrame: FrameIdentity | null }): void => { if (typeof report !== "object" || report == null) return; const candidate = report as BoxVisibilityReport; if (candidate.event !== "setup" && candidate.event !== "recreate") return; if (!["begin", "heartbeat", "end", "stage_transition"].includes(candidate.phase)) return; if (senderFrame == null || currentMainFrame == null || senderFrame.isDestroyed() || currentMainFrame.isDestroyed()) return; const key = documentKeyOf(senderFrame); if (key !== documentKeyOf(currentMainFrame)) return; tracker()?.handle(candidate, key); }; }

interface OpenWindow { trigger: string; startedAtMs: number; documentKey: string; operationId?: string; kind?: string; surface?: Surface }
export class SandBoxVisibilityTracker {
  private readonly open = new Map<Event, OpenWindow>(); private setupEnd: { documentKey: string; atMs: number } | null = null; private accountSlot: unknown; private accountSlotSeen = false;
  constructor(private readonly sink: BoxVisibilitySink, private readonly now: () => number = Date.now) {}
  noteAccountSlot(slot: unknown): void { const changed = this.accountSlotSeen && slot !== this.accountSlot; this.accountSlotSeen = true; this.accountSlot = slot; if (!changed) return; const setup = this.open.get("setup"); if (setup != null) { this.open.delete("setup"); this.emit("setup", setup, "abandoned", setup.surface); } this.setupEnd = null; }
  handle(report: BoxVisibilityReport, documentKey: string): void { if (report.phase === "begin") this.begin(report, documentKey); else if (report.phase === "heartbeat") this.heartbeat(report, documentKey); else if (report.phase === "stage_transition") this.stageTransition(report, documentKey); else this.end(report, documentKey); }
  private begin(report: BoxVisibilityReport, documentKey: string): void { if (report.event === "setup" && this.setupEnd != null) { if (this.setupEnd.documentKey === documentKey && this.now() - this.setupEnd.atMs < SETUP_REBEGIN_DEDUPE_MS) return; this.setupEnd = null; } const existing = this.open.get(report.event); if (existing?.documentKey === documentKey) return; const operationId = boundedToken(report.operationId); const kind = boundedToken(report.kind); const surface = boundedSurface(report.surface); this.open.set(report.event, { trigger: typeof report.trigger === "string" && report.trigger.length > 0 ? report.trigger : "unknown", startedAtMs: this.now(), documentKey, ...(operationId === undefined ? {} : { operationId }), ...(kind === undefined ? {} : { kind }), ...(surface === undefined ? {} : { surface }) }); }
  private heartbeat(report: BoxVisibilityReport, documentKey: string): void { if (report.event !== "recreate") return; let window = this.open.get("recreate"); if (window == null || window.documentKey !== documentKey) return; const surface = boundedSurface(report.surface); if (surface !== undefined && surface !== window.surface) { window = { ...window, surface }; this.open.set("recreate", window); } const elapsedMs = Math.max(0, this.now() - window.startedAtMs); const stage = boundedToken(report.stage); const migrationPhase = boundedToken(report.migrationPhase); const operationId = boundedToken(report.operationId) ?? window.operationId; this.sink.emitRecreateHeartbeat({ elapsedMs, trigger: window.trigger, isStalled: elapsedMs >= BOX_RECREATE_STALLED_AFTER_MS, ...(stage === undefined ? {} : { stage }), ...(migrationPhase === undefined ? {} : { migrationPhase }), ...(operationId === undefined ? {} : { operationId }) }); }
  private stageTransition(report: BoxVisibilityReport, documentKey: string): void { if (report.event !== "recreate") return; const window = this.open.get("recreate"); if (window == null || window.documentKey !== documentKey) return; const kind = boundedToken(report.kind); const toStage = boundedToken(report.stage); const stageElapsedMs = typeof report.stageElapsedMs === "number" && Number.isFinite(report.stageElapsedMs) && report.stageElapsedMs >= 0 ? Math.round(report.stageElapsedMs) : undefined; if (kind === undefined || toStage === undefined || stageElapsedMs === undefined) return; const fromStage = boundedToken(report.fromStage); const migrationPhase = boundedToken(report.migrationPhase); const operationId = boundedToken(report.operationId) ?? window.operationId; this.sink.emitRebuildStage({ kind, toStage, stageElapsedMs, ...(fromStage === undefined ? {} : { fromStage }), ...(migrationPhase === undefined ? {} : { migrationPhase }), ...(operationId === undefined ? {} : { operationId }) }); }
  private end(report: BoxVisibilityReport, documentKey: string): void { const window = this.open.get(report.event); if (window == null || window.documentKey !== documentKey) return; this.open.delete(report.event); this.emit(report.event, window, report.outcome ?? "abandoned", boundedSurface(report.surface) ?? window.surface); }
  isRecreateCoverOpen(): boolean { return this.open.has("recreate"); }
  abandonAll(): void { for (const [event, window] of this.open) this.emit(event, window, "abandoned", window.surface); this.open.clear(); }
  private emit(event: Event, window: OpenWindow, outcome: string, surface?: Surface): void { if (event === "setup") this.setupEnd = { documentKey: window.documentKey, atMs: this.now() }; this.sink.emit(event, { durationMs: Math.max(0, this.now() - window.startedAtMs), trigger: window.trigger, outcome, ...(window.operationId === undefined ? {} : { operationId: window.operationId }), ...(window.kind === undefined ? {} : { kind: window.kind }), ...(surface === undefined ? {} : { surface }) }); }
}
