import type { McpHostService } from "./mcp-service.js";
import type { PluginAuthBlock, PluginSkillRecord, PluginSkillsCache } from "./plugin-skills-cache.js";
import { pinMcpDiagnosticsReporter } from "../../../shared/node/mcp/mcp-diagnostics.js";
export interface AuthRenewalPort { getAccessToken?(args: { backendUrl: string }): Promise<string>; getMachineId?(): string; peekAccessToken(): string | null; subscribeToRenewal?(listener: (event: { outcome: string; isFirstCredential?: boolean }) => void): () => void; onDidChange?(listener: () => void): () => void }
export interface PollingPort { start(fn: () => void | Promise<void>): { dispose(): void } }
export function startPluginSkillsWhenAuthenticated(options: { auth: AuthRenewalPort; service?: { sync(trigger: string): Promise<unknown>; handleAuthChange?(): void }; pluginSkills?: { start(): void; handleAuthChange(): void; dispose(): void }; polling?: PollingPort; onStartupSyncSucceeded?: () => void }): () => void { let started=false,disposed=false,poll:{dispose():void}|undefined;const start=()=>{if(started||disposed)return;started=true;if(options.polling==null){options.pluginSkills?.start();return}let first=true;poll=options.polling.start(async()=>{const trigger=first?"startup":"refresh";first=false;try{await options.service?.sync(trigger);if(trigger==="startup"&&!disposed)options.onStartupSyncSucceeded?.()}catch{}})};const renewal=(event:{outcome:string;isFirstCredential?:boolean})=>{if(disposed||event.outcome!=="renewed")return;if(!started){if(options.auth.peekAccessToken()!=null)start();return}if(event.isFirstCredential)(options.service?.handleAuthChange??options.pluginSkills?.handleAuthChange)?.call(options.service??options.pluginSkills)};const unsubscribe=options.auth.subscribeToRenewal?.(renewal)??options.auth.onDidChange?.(()=>renewal({outcome:"renewed",isFirstCredential:true}))??(()=>{});if(options.auth.peekAccessToken()!=null)start();return()=>{if(disposed)return;disposed=true;unsubscribe();poll?.dispose();options.pluginSkills?.dispose()}};
export interface McpPluginSkillsService { sync(trigger: string): Promise<PluginSkillRecord[]>; handleAuthChange(): void; dispose(): void; currentIndex(): PluginSkillsCache | null; currentAuthBlocked(): PluginAuthBlock[] }
export type McpAuthCleanupOutcome = "not_found" | "error" | "deleted";
export interface McpExtensionContext { deps: { auth: AuthRenewalPort; telemetry: { logs: { reportHostExtensionDiagnostic(event: unknown): void; reportMcpAuthCleanup(outcome: McpAuthCleanupOutcome, removedCount: number): void } } }; createPluginSkills(): McpPluginSkillsService; createPolling(): PollingPort; createService(pluginSkills: McpPluginSkillsService): McpHostService; createSkillPublish(pluginSkills: McpPluginSkillsService): unknown; cleanupLegacyAuth?(): Promise<{ outcome: McpAuthCleanupOutcome; removedCount: number }>; sweepLegacyReferences?(): Promise<void>; onStop(fn: () => void | Promise<void>): void }
export const mcpExtension={id:"mcp",dependencies:["auth","experiments","forever-box","settings","telemetry"]as const,async start(context:McpExtensionContext){pinMcpDiagnosticsReporter(failure=>context.deps.telemetry.logs.reportHostExtensionDiagnostic({extension:"mcp",...failure}));try{const result=await context.cleanupLegacyAuth?.();if(result!=null)context.deps.telemetry.logs.reportMcpAuthCleanup(result.outcome,result.removedCount)}catch{}const pluginSkills=context.createPluginSkills(),stopStartup=startPluginSkillsWhenAuthenticated({auth:context.deps.auth,service:pluginSkills,polling:context.createPolling(),onStartupSyncSucceeded:()=>{void context.sweepLegacyReferences?.()}}),service=context.createService(pluginSkills),skillPublish=context.createSkillPublish(pluginSkills);context.onStop(async()=>{stopStartup();pluginSkills.dispose();await service.dispose()});return{...service.api,skillPublish}}};
