import { WriteEpoch } from "./write-epoch.js";
export interface HostSettingsPort<Settings extends object> { isReadable(): boolean; read(): Promise<Settings>; write(update: Partial<Settings>): Promise<Settings | null> }
export interface HostSettingsMirror<Value> { read(): Value | undefined; write(value: Value): void; clear?: () => void }
export class BoxSettingsField<Settings extends object, Field extends keyof Settings, Value = Exclude<Settings[Field], null | undefined>> { readonly #writes = new WriteEpoch(); #answeredThisSession = false; #sentToBox: Value | undefined; constructor(readonly port: HostSettingsPort<Settings>, readonly field: Field, readonly mirror?: HostSettingsMirror<Value>) {}
  async reconcile(): Promise<Value | null> { if (this.mirror === undefined) return this.#resolve(await this.port.read()); const readAt = this.#writes.snapshot(); const settings = await this.#readOrNull(); if (settings === null || this.#writes.isStale(readAt)) return this.mirror.read() ?? null; return this.#resolve(settings); }
  async apply(value: Value): Promise<{ status: "unreachable" } | { status: "persisted"; value: Value | null }> { this.mirror?.write(value); this.#answeredThisSession = true; const settle = this.#writes.begin(); try { const echo = await this.port.write({ [this.field]: value } as unknown as Partial<Settings>); if (echo === null) return { status: "unreachable" }; this.#sentToBox = value; return { status: "persisted", value: this.#boxValue(echo) }; } finally { settle(); } }
  async absorbFromBox(): Promise<"none" | "backfilled" | "repainted" | "cleared"> { if (this.mirror === undefined) return "none"; const readAt = this.#writes.snapshot(); const settings = await this.#readOrNull(); if (settings === null || this.#writes.isStale(readAt)) return "none"; const onBox = this.#boxValue(settings); if (onBox === null) return this.#giveUnwrittenBoxThisSessionsAnswer(); const local = this.mirror.read(); if (onBox === local) return "none"; this.mirror.write(onBox); return local === undefined ? "backfilled" : "repainted"; }
  abandonInFlight(): void { this.#writes.reset(); this.#answeredThisSession = false; this.#sentToBox = undefined; }
  async #giveUnwrittenBoxThisSessionsAnswer(): Promise<"none" | "cleared"> { if (!this.#answeredThisSession) { if (this.mirror?.read() === undefined || this.mirror.clear === undefined) return "none"; this.mirror.clear(); return "cleared"; } const local = this.mirror?.read(); if (local !== undefined && local !== this.#sentToBox) await this.apply(local); return "none"; }
  async #readOrNull(): Promise<Settings | null> { if (!this.port.isReadable()) return null; const [read] = await Promise.allSettled([this.port.read()]); return read?.status === "fulfilled" ? read.value : null; }
  #resolve(settings: Settings): Value | null { if (!this.#answeredThisSession) return this.#boxValue(settings); return this.#boxValue(settings) ?? this.mirror?.read() ?? null; }
  #boxValue(settings: Settings): Value | null { const value = settings[this.field]; return value == null ? null : value as unknown as Value; }
}
