import { WORKFLOW_REFERENCE_NODE_TYPE } from "./workflows.js";
import { cronTrigger } from "./automations.js";
import { describeSchedule } from "./automation-schedule.js";
export const WORKFLOW_FILENAME = "SKILL.md"; export const LEGACY_WORKFLOW_FILENAME = "workflow.md"; export const AGENT_READABLE_SKILL_DIR_MODE = 0o755; export const AGENT_READABLE_SKILL_FILE_MODE = 0o644; export const WORKFLOW_MAX_NAME_LENGTH = 80; export const WORKFLOW_MAX_DESCRIPTION_LENGTH = 1_536; export const WORKFLOW_MAX_BODY_LENGTH = 100_000; export const WORKFLOW_INJECTED_BODY_LIMIT = 8_000; export const WORKFLOW_UI_LIMIT = 100; export const WORKFLOW_MAX_PER_AGENT = 100;
export interface WorkflowTrigger { schedule: string; isEnabled: boolean } export interface WorkflowSpec { name: string; description: string; body: string; trigger: WorkflowTrigger | null; sourceRef?: string | null } export interface ParsedWorkflow extends WorkflowSpec { sourceRef: string | null; data: Record<string, unknown> }
export interface WorkflowRecord { id: string; name: string; description: string; body: string; trigger: WorkflowTrigger | null; source: "managed" | "plugin" | "workflow" | "automation"; sourceRef: string | null; pluginId?: string | null; publishedByCurrentUser?: boolean; isEnabledForAgent: boolean; disableModelInvocation?: boolean; scheduleDescription?: string | null; createdAt: number; lastRunAt?: number | null; nextRunAt?: number | null; helperScripts: readonly string[]; runs?: readonly unknown[]; filePath: string }
export interface AutomationProjection { id: string; name: string; prompt: string; trigger: ReturnType<typeof cronTrigger>; schedule: string; triggerDescription: string; isEnabled: boolean; createdAt: number; lastRunAt: number | null; nextRunAt: number | null; runs: readonly unknown[]; filePath: string }
function clampLine(value: unknown, max: number): string { return typeof value === "string" ? value.replace(/[\r\n]+/g, " ").trim().slice(0, max) : ""; } function clampBlock(value: unknown, max: number): string { return typeof value === "string" ? value.trim().slice(0, max) : ""; }
export function clampWorkflowName(value: unknown): string { return clampLine(value, WORKFLOW_MAX_NAME_LENGTH); } export function clampWorkflowDescription(value: unknown): string { return clampLine(value, WORKFLOW_MAX_DESCRIPTION_LENGTH); } export function clampWorkflowBody(value: unknown): string { return clampBlock(value, WORKFLOW_MAX_BODY_LENGTH); }
export function slugifyWorkflowName(name: string): string { const slug = name.normalize("NFKD").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 64).replace(/-+$/g, ""); return slug || "workflow"; }
function scalar(raw: string): unknown { const value = raw.trim(); if (value === "true") return true; if (value === "false") return false; if (value === "null" || value === "~") return null; if (/^-?\d+(?:\.\d+)?$/.test(value)) return Number(value); if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) { try { return value.startsWith('"') ? JSON.parse(value) : value.slice(1, -1).replace(/''/g, "'"); } catch {} } return value; }
function parseFrontmatter(text: string): Record<string, unknown> { const root: Record<string, unknown> = {}; const stack: Array<{ indent: number; value: Record<string, unknown> }> = [{ indent: -1, value: root }]; for (const raw of text.split(/\r?\n/)) { if (raw.trim().length === 0 || raw.trimStart().startsWith("#")) continue; const match = /^(\s*)([^:#][^:]*):(?:\s*(.*))?$/.exec(raw); if (match == null) continue; const indent = match[1]?.length ?? 0; const key = match[2]?.trim(); if (!key) continue; while ((stack.at(-1)?.indent ?? -1) >= indent) stack.pop(); const parent = stack.at(-1)?.value ?? root; const tail = match[3] ?? ""; if (tail.trim().length === 0) { const nested: Record<string, unknown> = {}; parent[key] = nested; stack.push({ indent, value: nested }); } else parent[key] = scalar(tail); } return root; }
function splitMatter(raw: string): { data: Record<string, unknown>; content: string } { if (!raw.startsWith("---")) return { data: {}, content: raw }; const lineEnd = raw.indexOf("\n"); if (lineEnd < 0) return { data: {}, content: raw }; const close = raw.indexOf("\n---", lineEnd); if (close < 0) return { data: {}, content: raw }; return { data: parseFrontmatter(raw.slice(lineEnd + 1, close)), content: raw.slice(close + 4).replace(/^\r?\n/, "") }; }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value != null && !Array.isArray(value); } function sourceRefOf(data: Record<string, unknown>): string | null { const metadata = isRecord(data.metadata) ? data.metadata : {}; const raw = typeof metadata.source === "string" ? metadata.source : data.source; return typeof raw === "string" && raw.trim().length > 0 ? raw.trim() : null; }
function normalizeSchedule(value: string): string { return value.trim().replace(/\s+/g, " "); } function triggerOf(data: Record<string, unknown>): WorkflowTrigger | null { if (!isRecord(data.trigger)) return null; const schedule = normalizeSchedule(typeof data.trigger.schedule === "string" ? data.trigger.schedule : ""); return schedule.length === 0 ? null : { schedule, isEnabled: data.trigger.enabled !== false }; }
export function parseWorkflowFile(raw: string): ParsedWorkflow | null { let data: Record<string, unknown>; let content: string; try { ({ data, content } = splitMatter(raw)); } catch { data = {}; content = raw; } const body = clampWorkflowBody(content); if (body.length === 0 && Object.keys(data).length === 0) return null; return { name: clampWorkflowName(data.name), description: clampWorkflowDescription(data.description), trigger: triggerOf(data), body, sourceRef: sourceRefOf(data), data }; }
function yamlValue(value: unknown): string { if (typeof value === "string") return JSON.stringify(value); if (typeof value === "number" || typeof value === "boolean") return String(value); if (value == null) return "null"; return JSON.stringify(value); } function emitYaml(data: Record<string, unknown>, indent = 0): string[] { const lines: string[] = []; for (const [key, value] of Object.entries(data)) { if (isRecord(value)) { lines.push(`${" ".repeat(indent)}${key}:`); lines.push(...emitYaml(value, indent + 2)); } else lines.push(`${" ".repeat(indent)}${key}: ${yamlValue(value)}`); } return lines; }
export function serializeWorkflowFile(spec: WorkflowSpec, existingData: Record<string, unknown> = {}): string { const data: Record<string, unknown> = { ...existingData, name: spec.name }; if (spec.description.length > 0) data.description = spec.description; else delete data.description; const legacySource = data.source; delete data.source; const metadata = isRecord(data.metadata) ? { ...data.metadata } : {}; const nextSource = spec.sourceRef === undefined ? metadata.source ?? legacySource : spec.sourceRef; if (typeof nextSource === "string" && nextSource.length > 0) metadata.source = nextSource; else delete metadata.source; if (Object.keys(metadata).length > 0) data.metadata = metadata; else delete data.metadata; if (spec.trigger != null) data.trigger = { schedule: spec.trigger.schedule, enabled: spec.trigger.isEnabled }; else delete data.trigger; return `---\n${emitYaml(data).join("\n")}\n---\n${spec.body.trim()}\n`; }
export function workflowToAutomation(workflow: WorkflowRecord): AutomationProjection | null { if (workflow.trigger == null) return null; return { id: workflow.id, name: workflow.name, prompt: workflow.body, trigger: cronTrigger(workflow.trigger.schedule), schedule: workflow.trigger.schedule, triggerDescription: workflow.scheduleDescription ?? describeSchedule(workflow.trigger.schedule), isEnabled: workflow.trigger.isEnabled, createdAt: workflow.createdAt, lastRunAt: workflow.lastRunAt ?? null, nextRunAt: workflow.nextRunAt ?? null, runs: workflow.runs ?? [], filePath: workflow.filePath }; }
export function automationToWorkflow(automation: { id: string; name: string; prompt: string; trigger: { type: string; schedule?: string }; triggerDescription: string; isEnabled: boolean; createdAt: number; lastRunAt?: number | null; nextRunAt?: number | null; runs?: readonly unknown[]; filePath: string }): WorkflowRecord { return { id: automation.id, name: automation.name, description: "", body: automation.prompt, trigger: { schedule: automation.trigger.type === "cron" ? automation.trigger.schedule ?? "" : "", isEnabled: automation.isEnabled }, source: "automation", sourceRef: null, pluginId: null, publishedByCurrentUser: false, isEnabledForAgent: true, scheduleDescription: automation.triggerDescription, createdAt: automation.createdAt, lastRunAt: automation.lastRunAt ?? null, nextRunAt: automation.nextRunAt ?? null, helperScripts: [], runs: automation.runs ?? [], filePath: automation.filePath }; }
export function limitSurfacedWorkflows<T extends Pick<WorkflowRecord, "source">>(workflows: readonly T[]): T[] { const managed: T[] = [], user: T[] = []; for (const workflow of workflows) (workflow.source === "managed" || workflow.source === "plugin" ? managed : user).push(workflow); return [...managed, ...user.slice(0, WORKFLOW_UI_LIMIT)]; }
export function agentSkillsFromWorkflows(workflows: readonly WorkflowRecord[]): Array<{ fullPath: string; description: string }> { return limitSurfacedWorkflows(workflows).filter((workflow) => workflow.trigger == null && workflow.isEnabledForAgent && workflow.disableModelInvocation !== true && workflow.filePath.length > 0).map((workflow) => ({ fullPath: workflow.filePath, description: workflow.description })); }
export function workflowSpecFromMarkdown(markdown: string, fallbackName?: string): WorkflowSpec | null { const parsed = parseWorkflowFile(markdown); if (parsed == null) return null; const name = parsed.name || clampWorkflowName(deriveWorkflowNameFromMarkdown(parsed.body) ?? fallbackName ?? ""); return name.length === 0 || parsed.body.length === 0 ? null : { name, description: parsed.description, body: parsed.body, trigger: parsed.trigger, sourceRef: parsed.sourceRef }; }
export function buildLiveSourcePointerBody(source: string): string { return [`This workflow is a live reference to the skill at \`${source}\`.`, "Read that source now with your file or fetch tools and follow it as written. Do not assume its contents from this note; the source is the source of truth and may have changed since this workflow was created."].join("\n"); }
export function liveWorkflowSpecFromSource(args: { name: string; source: string; description?: string }): WorkflowSpec { const source = args.source.trim(); const name = clampWorkflowName(args.name); const explicit = clampWorkflowDescription(args.description ?? ""); return { name, description: explicit || clampWorkflowDescription(`Use when the "${name}" skill applies; it is a live reference to ${source}.`), body: clampWorkflowBody(buildLiveSourcePointerBody(source)), trigger: null, sourceRef: source }; }
export function deriveWorkflowNameFromMarkdown(body: string): string | null { for (const raw of body.split("\n")) { const line = raw.trim(); if (!line) continue; const text = (/^#+\s+(.*)$/.exec(line)?.[1] ?? line).replace(/[*_`#>]/g, "").trim(); if (text) return text.slice(0, WORKFLOW_MAX_NAME_LENGTH); } return null; }
export function deriveWorkflowNameFromUrl(url: string): string { let pathname = url; try { pathname = new URL(url).pathname; } catch {} const last = pathname.split("/").filter(Boolean).at(-1) ?? "Imported skill"; return clampWorkflowName(last.replace(/\.(md|markdown|mdc|txt)$/i, "").replace(/[-_]+/g, " ").trim() || "Imported skill"); }
export function collectWorkflowReferences(richText: string | null | undefined): Array<{ id: string; teachQueueScope: string | null }> { if (!richText) return []; let doc: unknown; try { doc = JSON.parse(richText); } catch { return []; } const result: Array<{ id: string; teachQueueScope: string | null }> = []; const seen = new Set<string>(); const visit = (node: unknown): void => { if (!isRecord(node)) return; if (node.type === WORKFLOW_REFERENCE_NODE_TYPE && isRecord(node.attrs) && typeof node.attrs.id === "string" && node.attrs.id && !seen.has(node.attrs.id)) { seen.add(node.attrs.id); result.push({ id: node.attrs.id, teachQueueScope: typeof node.attrs.teachQueueScope === "string" ? node.attrs.teachQueueScope : null }); } if (Array.isArray(node.content)) for (const child of node.content) visit(child); }; visit(doc); return result; }
function handles(workflow: Pick<WorkflowRecord, "id" | "name">): string[] { const values = new Set<string>(); const name = workflow.name.trim().toLowerCase(); if (name) { values.add(name); values.add(name.replace(/\s+/g, "")); } const id = workflow.id.trim().toLowerCase(); if (id) values.add(id); return [...values]; }
export function collectMentionedWorkflows<T extends Pick<WorkflowRecord, "id" | "name">>(prompt: string, workflows: readonly T[]): T[] { const found = new Set<string>(); const byId = new Map(workflows.map((workflow) => [workflow.id.toLowerCase(), workflow])); for (const match of prompt.matchAll(/sand-workflow:([a-z0-9]+(?:-[a-z0-9]+)*)/gi)) if (match[1] != null && byId.has(match[1].toLowerCase())) found.add(match[1].toLowerCase()); const candidates = workflows.flatMap((workflow) => handles(workflow).map((handle) => ({ handle, id: workflow.id.toLowerCase() }))).sort((a, b) => b.handle.length - a.handle.length); const lower = prompt.toLowerCase(); const claimed: Array<{ start: number; end: number }> = []; for (const { handle, id } of candidates) { const needle = `@${handle}`; for (let index = lower.indexOf(needle); index >= 0; index = lower.indexOf(needle, index + 1)) { const end = index + needle.length; const word = (char: string | undefined) => char !== undefined && /[a-z0-9]/.test(char); if (!word(lower[index - 1]) && !word(lower[end]) && !claimed.some((range) => index < range.end && range.start < end)) { claimed.push({ start: index, end }); found.add(id); } } } return workflows.filter((workflow) => found.has(workflow.id.toLowerCase())); }
export function promptReferencesWorkflow(prompt: string, workflow: Pick<WorkflowRecord, "id" | "name">): boolean { return collectMentionedWorkflows(prompt, [workflow]).length > 0; }
export function workflowDir(filePath: string): string { const slash = Math.max(filePath.lastIndexOf("/"), filePath.lastIndexOf("\\")); return slash === -1 ? filePath : filePath.slice(0, slash); }
export function renderWorkflowsSystemPrompt(location: string | null | undefined): string { return location == null ? "" : `Workflows are a GLOBAL, shared library across all of the user's assistants. User-created skills live as files at ${location}: one subfolder per workflow, each holding a SKILL.md. Prefer the update_state tool (target "workflow") to save, rewrite, and delete them. Reference workflows as [name](sand-workflow:<id>).`; }
