import { existsSync } from "node:fs";
import { createHash } from "node:crypto";
import type { DatabaseSync, StatementSync } from "node:sqlite";
import { ConversationStateStructure } from "../../packages/proto/generated/agent/v1/agent_pb.js";
import { openConversationBlobDb, readConversationBlobMigrationState, CONVERSATION_BLOB_ADOPTION_COMPLETE } from "./conversation-blob-db.js";
import { collectReachableBlobHexIds } from "./conversation-blob-gc.js";
import { verifyLegacyBlobRetirement } from "./legacy-blob-retirement.js";
import { findLatestRootBlobIdInDatabase } from "../extensions/session/conversation-recovery.js";
const MAX_STALE_ROOT_SCAN_BYTES = 64 * 1024 * 1024, MAX_TRACKED_RECENT_WRITES = 16_384, VACUUM_MIN_DELETED_BYTES = 64 * 1024 * 1024, VACUUM_MIN_DELETED_SHARE = 1 / 8;
const toHex = (bytes: Uint8Array) => Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength).toString("hex");
export class ConversationBlobStoreDb { readonly db: DatabaseSync; readonly getBlobStmt: StatementSync; readonly setBlobStmt: StatementSync; readonly clearBlobsStmt: StatementSync; readonly scanBlobIndexStmt: StatementSync; readonly recentWriteMsByHexId = new Map<string, number>(); isClosed = false; constructor(readonly options: { agentId: string; blobDbPath: string; busyTimeoutMs: number; legacyBlobDbPath?: string; log?: (message: string) => void }) { const log = options.log ?? (message => console.error(message)); this.db = openConversationBlobDb({ dbPath: options.blobDbPath, agentId: options.agentId, busyTimeoutMs: options.busyTimeoutMs, log }); if (options.legacyBlobDbPath != null) this.adoptLegacyBlobs(options.legacyBlobDbPath, log); this.getBlobStmt = this.db.prepare("SELECT data FROM blobs WHERE id = ?"); this.setBlobStmt = this.db.prepare("INSERT INTO blobs (id, data) VALUES (?, ?) ON CONFLICT(id) DO UPDATE SET data = excluded.data"); this.clearBlobsStmt = this.db.prepare("DELETE FROM blobs"); this.scanBlobIndexStmt = this.db.prepare("SELECT id, length(data) AS len FROM blobs"); }
  private adoptLegacyBlobs(path: string, log: (message: string) => void): void { if (!["unstarted", "recovery-rebuilt"].includes(readConversationBlobMigrationState(this.db)) || !existsSync(path)) return; try { this.db.prepare("ATTACH DATABASE ? AS legacy").run(path); try { this.db.exec("INSERT OR IGNORE INTO blobs (id, data) SELECT id, data FROM legacy.blobs"); } finally { this.db.exec("DETACH DATABASE legacy"); } } catch (error) { log(`[agent-store-worker] legacy blob adoption failed: ${String(error)}`); return; } this.db.exec(`PRAGMA user_version = ${CONVERSATION_BLOB_ADOPTION_COMPLETE}`); }
  getBlob(id: Uint8Array): Uint8Array | undefined { if (this.isClosed) return undefined; const data = (this.getBlobStmt.get(toHex(id)) as { data?: unknown } | undefined)?.data; return data instanceof Uint8Array ? data : undefined; }
  setBlob(id: Uint8Array, data: Uint8Array): void { if (this.isClosed) return; const hex = toHex(id); this.setBlobStmt.run(hex, data); this.recentWriteMsByHexId.delete(hex); this.recentWriteMsByHexId.set(hex, Date.now()); while (this.recentWriteMsByHexId.size > MAX_TRACKED_RECENT_WRITES) { const oldest = this.recentWriteMsByHexId.keys().next().value; if (oldest == null) break; this.recentWriteMsByHexId.delete(oldest); } }
  clearBlobs(): void { if (!this.isClosed) this.clearBlobsStmt.run(); }
  findLatestRootBlobId(): Uint8Array | undefined { if (this.isClosed) return undefined; return findLatestRootBlobIdInDatabase(this.db) ?? undefined; }
  clearStaleCheckpointRoots(retainedRootIdHex: string): number { if (this.isClosed) return 0; const presentIds = new Set<string>(), candidates: string[] = []; for (const raw of this.scanBlobIndexStmt.iterate()) { const row = raw as { id?: unknown; len?: unknown }; if (typeof row.id !== "string") continue; presentIds.add(row.id); if (row.id !== retainedRootIdHex && typeof row.len === "number" && row.len > 0 && row.len <= MAX_STALE_ROOT_SCAN_BYTES) candidates.push(row.id); } const stale: string[] = []; for (const id of candidates) { const data = (this.getBlobStmt.get(id) as { data?: unknown } | undefined)?.data; if (!(data instanceof Uint8Array) || createHash("sha256").update(data).digest("hex") !== id) continue; let structure: ConversationStateStructure; try { structure = ConversationStateStructure.fromBinary(data); } catch { continue; } if (structure.turns.length > 0 && structure.turns.every((turn: Uint8Array) => turn.length === 32 && presentIds.has(toHex(turn)))) stale.push(id); } if (stale.length === 0) return 0; const remove = this.db.prepare("DELETE FROM blobs WHERE id = ?"); let deleted = 0, inTransaction = false; try { this.db.exec("BEGIN IMMEDIATE"); inTransaction = true; for (const id of stale) deleted += Number(remove.run(id).changes); this.db.exec("COMMIT"); } catch (error) { if (inTransaction) this.db.exec("ROLLBACK"); throw error; } return deleted; }
  collectGarbage({ retainedRootIdHex, pendingWriteRetentionMs }: { retainedRootIdHex: string; pendingWriteRetentionMs: number }) { if (this.isClosed) return { outcome: "skipped" as const, reason: "no-root" as const }; const root = (this.getBlobStmt.get(retainedRootIdHex) as { data?: unknown } | undefined)?.data; if (!(root instanceof Uint8Array)) return { outcome: "skipped" as const, reason: "no-root" as const }; let walk; try { walk = collectReachableBlobHexIds({ rootBytes: root, getBlobByHexId: id => { const data = (this.getBlobStmt.get(id) as { data?: unknown } | undefined)?.data; return data instanceof Uint8Array ? data : undefined; } }); } catch { return { outcome: "skipped" as const, reason: "root-undecodable" as const }; } if (walk.unresolvedProtoRefs > 0) return { outcome: "skipped" as const, reason: "unresolved-refs" as const, unresolvedProtoRefs: walk.unresolvedProtoRefs }; const floor = Date.now() - pendingWriteRetentionMs, deletable: string[] = []; let liveRows = 0, retainedPendingRows = 0, deletedBytes = 0, liveBytes = 0; for (const raw of this.scanBlobIndexStmt.iterate()) { const row = raw as { id?: unknown; len?: unknown }; if (typeof row.id !== "string" || typeof row.len !== "number") continue; if (row.id === retainedRootIdHex || walk.reachableHexIds.has(row.id)) { liveRows++; liveBytes += row.len; continue; } const last = this.recentWriteMsByHexId.get(row.id); if (last != null && last > floor) { retainedPendingRows++; liveRows++; liveBytes += row.len; continue; } deletable.push(row.id); deletedBytes += row.len; } if (deletable.length) { const remove = this.db.prepare("DELETE FROM blobs WHERE id = ?"); let inTransaction = false; try { this.db.exec("BEGIN IMMEDIATE"); inTransaction = true; for (const id of deletable) remove.run(id); this.db.exec("COMMIT"); } catch (error) { if (inTransaction) this.db.exec("ROLLBACK"); throw error; } } const vacuumed = deletedBytes >= VACUUM_MIN_DELETED_BYTES || deletedBytes > 0 && deletedBytes >= (deletedBytes + liveBytes) * VACUUM_MIN_DELETED_SHARE; if (vacuumed) this.db.exec("VACUUM"); this.db.exec("PRAGMA wal_checkpoint(TRUNCATE)"); return { outcome: "collected" as const, deletedRows: deletable.length, deletedBytes, liveRows, liveBytes, retainedPendingRows, vacuumed }; }
  verifyLegacyBlobRetirement(root: string, legacy: string) { return this.isClosed ? { isRetirable: false as const, reason: "store-closed", legacyRows: 0 as const, legacyBytes: 0 as const } : verifyLegacyBlobRetirement({ db: this.db, legacyBlobDbPath: legacy, retainedRootIdHex: root }); }
  close(): void { if (!this.isClosed) { this.isClosed = true; this.db.close(); } }
}
