import { access, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { HostBundleSource } from "./host-bundle-source.js";
import type { HostUpgradeMarker } from "./host-upgrade-marker.js";

export const SAND_SUPERVISOR_DIR = "/tmp/sand-supervisor";
export const SAND_SUPERVISOR_COMMAND_PATH = `${SAND_SUPERVISOR_DIR}/command.json`;
export const SAND_SUPERVISOR_COMMAND_PART_PATH = `${SAND_SUPERVISOR_COMMAND_PATH}.part`;
export const SAND_SUPERVISOR_ACKS_DIR = `${SAND_SUPERVISOR_DIR}/acks`;
export const SAND_SUPERVISOR_STAGED_BUNDLE_PATH = `${SAND_SUPERVISOR_DIR}/incoming-host-bundle.tgz`;
export const SAND_SUPERVISOR_STAGED_BUNDLE_PART_PATH = `${SAND_SUPERVISOR_STAGED_BUNDLE_PATH}.part`;
export const SAND_BOX_HOST_VERSION_PATH = "/home/box/sand-host/version";
export const MAX_FAILED_SWAP_RESTAGE_RETRIES = 2;
export const POST_SWAP_CRASH_LOOP_ERROR_CLASS = "post-swap-crash-loop";
export const HOST_BUNDLE_WATCH_INTERVAL_MS = 24 * 60 * 60_000;
export const HOST_BUNDLE_WATCH_JITTER_RATIO = 0.5;
export interface SandSupervisorUpgradeCommand { id: string; kind: "upgrade"; issuedAtMs: number; mode?: string; version?: string; bundlePath?: string; reason?: string; forceNow?: true }
export interface HostBundleUpdateState { stagedVersion: string | null; lastFailedVersion: string | undefined; swapRetryAttempts: Map<string, number> }
export function buildSandSupervisorCommand(args: { id: string; kind: "upgrade"; nowMs: number; mode?: string; version?: string; bundlePath?: string; reason?: string; forceNow?: boolean }): SandSupervisorUpgradeCommand { return { id: args.id, kind: args.kind, issuedAtMs: args.nowMs, ...(args.reason === undefined ? {} : { reason: args.reason }), ...(args.mode === undefined ? {} : { mode: args.mode }), ...(args.version === undefined ? {} : { version: args.version }), ...(args.bundlePath === undefined ? {} : { bundlePath: args.bundlePath }), ...(args.forceNow === true ? { forceNow: true as const } : {}) }; }
export function serializeSandSupervisorCommand(command: SandSupervisorUpgradeCommand): string { return JSON.stringify(command); }
export function isSandHostUpgradeAvailable(current: string | null, target: string | null | undefined): boolean { return target != null && target.length > 0 && current !== target; }
export async function readLocalHostVersion(versionPath = SAND_BOX_HOST_VERSION_PATH): Promise<string | null> { try { const raw = (await readFile(versionPath, "utf8")).trim(); return raw.length > 0 ? raw : null; } catch { return null; } }
export async function stageHostBundleUpgrade(args: { version: string; bytes: Uint8Array; reason?: string; forceNow?: boolean; nowMs?: number; dir?: string; stagedBundlePath?: string; stagedBundlePartPath?: string; commandPath?: string; commandPartPath?: string }): Promise<SandSupervisorUpgradeCommand> { const dir = args.dir ?? SAND_SUPERVISOR_DIR, bundle = args.stagedBundlePath ?? SAND_SUPERVISOR_STAGED_BUNDLE_PATH, bundlePart = args.stagedBundlePartPath ?? SAND_SUPERVISOR_STAGED_BUNDLE_PART_PATH, commandPath = args.commandPath ?? SAND_SUPERVISOR_COMMAND_PATH, commandPart = args.commandPartPath ?? SAND_SUPERVISOR_COMMAND_PART_PATH, command = buildSandSupervisorCommand({ id: `upgrade-${args.version}`, kind: "upgrade", nowMs: args.nowMs ?? Date.now(), mode: "bundle", version: args.version, bundlePath: bundle, ...(args.reason === undefined ? {} : { reason: args.reason }), ...(args.forceNow === undefined ? {} : { forceNow: args.forceNow }) }); await mkdir(dir, { recursive: true }); await writeFile(bundlePart, args.bytes); await rename(bundlePart, bundle); await writeFile(commandPart, serializeSandSupervisorCommand(command)); await rename(commandPart, commandPath); return command; }
export async function fetchStageAndReportHostBundle(deps: { source: HostBundleSource; fromVersion: string | null; trigger: string; state: HostBundleUpdateState; stage(bytes: Uint8Array): Promise<void>; reportUpgrade(metadata: Record<string, string | undefined>): void; log?(level: "info" | "warn", message: string): void }): Promise<{ ok: true } | { ok: false; error: unknown; phase: "fetch" | "stage" }> { let phase: "fetch" | "stage" = "fetch"; try { const bytes = await deps.source.loadBundleBytes(); phase = "stage"; await deps.stage(bytes); deps.state.stagedVersion = deps.source.version; deps.state.lastFailedVersion = undefined; deps.log?.("info", `host bundle update (${deps.trigger}): staged ${deps.source.version}; supervisor swaps when idle`); return { ok: true }; } catch (error) { deps.log?.("warn", `host bundle update (${deps.trigger}): ${phase} failed (box unchanged): ${String(error)}`); if (deps.state.lastFailedVersion !== deps.source.version) { deps.state.lastFailedVersion = deps.source.version; deps.reportUpgrade({ outcome: "failed", phase, mode: "bundle", trigger: deps.trigger, from_version: deps.fromVersion ?? undefined, to_version: deps.source.version, error_class: error instanceof Error ? error.constructor.name : "unknown" }); } return { ok: false, error, phase }; } }
export async function isHostVersionSwapVetoed(args: { version: string; localVersion: string | null; acksDir?: string }): Promise<boolean> { if (!args.version || args.localVersion === args.version) return false; const ackName = `upgrade-${args.version}`.replace(/[^a-zA-Z0-9_.-]/g, "_"); try { await access(join(args.acksDir ?? SAND_SUPERVISOR_ACKS_DIR, ackName)); return true; } catch { return false; } }
export function noteFailedSwapMarkerForRetry(state: HostBundleUpdateState, marker: HostUpgradeMarker, maxRetries = MAX_FAILED_SWAP_RESTAGE_RETRIES): boolean { if (marker.outcome !== "failed" || marker.mode !== "bundle" || !marker.toVersion || marker.swapError === POST_SWAP_CRASH_LOOP_ERROR_CLASS || state.stagedVersion !== marker.toVersion) return false; const attempts = state.swapRetryAttempts.get(marker.toVersion) ?? 0; if (attempts >= maxRetries) return false; state.swapRetryAttempts.set(marker.toVersion, attempts + 1); state.stagedVersion = null; return true; }
function describeErrorNode(error: Error, seen: Set<unknown>): string { const code = (error as Error & { code?: unknown }).code, suffix = typeof code === "string" && code.length > 0 && !error.message.includes(code) ? ` (${code})` : ""; let node = `${error.name}: ${error.message}${suffix}`, aggregate = (error as Error & { errors?: unknown }).errors; if (Array.isArray(aggregate) && aggregate.length > 0) { const inner = aggregate.filter((item) => !seen.has(item)).map((item) => { if (item instanceof Error) { seen.add(item); return describeErrorNode(item, seen); } return String(item); }).join("; "); if (inner) node += ` [${inner}]`; } return node; }
export function describeHostBundleErrorDetail(error: unknown, phase?: string): string { const parts: string[] = [], seen = new Set<unknown>(); let current: unknown = error; while (current != null && !seen.has(current)) { seen.add(current); if (current instanceof Error) { parts.push(describeErrorNode(current, seen)); current = current.cause; } else { parts.push(String(current)); break; } } const chain = parts.length > 0 ? parts.join(" → ") : String(error); return phase == null ? chain : `@phase:${phase} ${chain}`; }
function clamp(value: number, low: number, high: number): number { return Number.isFinite(value) ? Math.min(high, Math.max(low, value)) : low; }
export function hostBundleWatchInitialDelayMs(baseMs: number, jitterRatio: number, random: () => number = Math.random): number { return !(baseMs > 0) || !(jitterRatio > 0) ? 0 : Math.round(clamp(random(), 0, 1) * baseMs); }
export function hostBundleWatchNextDelayMs(baseMs: number, jitterRatio: number, random: () => number = Math.random): number { const base = baseMs > 0 ? baseMs : 0, ratio = clamp(jitterRatio, 0, 1); if (ratio === 0) return base; return Math.max(0, Math.round(base + (clamp(random(), 0, 1) * 2 - 1) * base * ratio)); }
