import { describeHostBundleErrorDetail, fetchStageAndReportHostBundle, hostBundleWatchInitialDelayMs, hostBundleWatchNextDelayMs, isSandHostUpgradeAvailable, noteFailedSwapMarkerForRetry, type HostBundleUpdateState } from "./host-bundle-upgrade.js";
import type { HostBundleSource } from "./host-bundle-source.js";
import { forwardHostUpgradeMarkerWith, type HostUpgradeMetadata } from "./host-upgrade-marker.js";

interface Disposable { dispose(): void }
interface WakePolicy { start(callback: () => Promise<void>): Disposable }
export interface HostUpgradeServiceDependencies {
  readonly automations: { suspendWakes(): Promise<void> };
  readonly sharing: { prepareForUpgrade(): void };
  readonly transcript: { quiesceForUpgrade(): Promise<unknown>; resumeInterruptedUpgradeTurns(): Promise<void> };
  readonly telemetry: { reportHostUpgrade(metadata: Record<string, string | undefined>): void; reportHostUpgradeConfirmed(metadata: HostUpgradeMetadata): Promise<boolean> };
  readonly markerStore: { readRaw(): Promise<string | null>; deleteMarker(): Promise<void> };
  readonly markerForwardPolicy: WakePolicy;
  readonly createUpdateWatchDelayPolicy: (delayMs: number) => WakePolicy;
  readonly clock: { now(): number };
  readonly random: () => number;
  readonly isInBox: boolean;
  readonly isAutoUpdateEnabled: boolean;
  readonly updateWatchIntervalMs: number;
  readonly updateWatchJitterRatio: number;
  readonly resolveBundleSource: () => Promise<HostBundleSource | undefined>;
  readonly readLocalVersion: () => Promise<string | null>;
  readonly isVersionSwapVetoed: (args: { version: string; localVersion: string | null }) => Promise<boolean>;
  readonly stageUpgrade: (args: { version: string; bytes: Uint8Array; forceNow: boolean; reason: string }) => Promise<unknown>;
  readonly log: (level: "info" | "warn", message: string) => void;
}
export type HostUpdateNowResult = { started: true; version: string } | { started: false; reason: string; version?: string };
export class HostUpgradeService {
  readonly updateState: HostBundleUpdateState = { stagedVersion: null, lastFailedVersion: undefined, swapRetryAttempts: new Map() };
  private updateInFlight = false; private localVersion: string | null = null; private latestVersion: string | null = null; private markerForwarding: Disposable | undefined; private markerForwardInFlight = false; private hostIdentityReady = false; private markerForwardNow: { raw: string; nowMs: number } | undefined; private lastHandledMarker: string | undefined; private sharedUpdateWatchStarted = false; private sharedUpdateWatchActive = false; private sharedUpdateDelay: Disposable | undefined; private runRootUpdateTick: (() => Promise<void>) | undefined;
  constructor(readonly deps: HostUpgradeServiceDependencies) {}
  get isAutoUpdateEnabled(): boolean { return this.deps.isAutoUpdateEnabled; }
  async resolveHostBundleIdentityVersion(fallbackVersion?: string): Promise<string> { const disk = await this.deps.readLocalVersion(); if (disk !== null) this.localVersion = disk; return disk ?? this.localVersion ?? fallbackVersion ?? "unknown"; }
  startMarkerForwardWake(): void { if (this.markerForwarding != null) return; this.markerForwarding = this.deps.markerForwardPolicy.start(async () => { if (this.hostIdentityReady) await this.forwardHostUpgradeMarker(); }); }
  activateAfterHostIdentityReady(): void { if (this.hostIdentityReady) return; this.hostIdentityReady = true; void this.forwardHostUpgradeMarker(); }
  startSharedUpdateWatch(options: { isBoxAutoUpdateEnabled: boolean; runRootUpdateTick(): Promise<void> }): void { if (this.sharedUpdateWatchStarted) return; this.sharedUpdateWatchStarted = true; this.runRootUpdateTick = options.runRootUpdateTick; if (!options.isBoxAutoUpdateEnabled && !this.deps.isAutoUpdateEnabled && !this.deps.isInBox) return; void this.deps.readLocalVersion().then((version) => { this.localVersion = version; }); void this.deps.resolveBundleSource().then((source) => { if (source != null) this.latestVersion = source.version; }).catch(() => {}); this.sharedUpdateWatchActive = true; this.scheduleSharedUpdateWatch(hostBundleWatchInitialDelayMs(this.deps.updateWatchIntervalMs, this.deps.updateWatchJitterRatio, this.deps.random)); }
  async updateHostNow(options: { force?: boolean; includeErrorDetail?: boolean } = {}): Promise<HostUpdateNowResult> { const force = options.force ?? true, source = await this.deps.resolveBundleSource(); if (source == null) return { started: false, reason: "no-bundle-source" }; this.latestVersion = source.version; const local = await this.deps.readLocalVersion(); this.localVersion = local; if (!isSandHostUpgradeAvailable(local, source.version)) return { started: false, reason: "already-latest", version: source.version }; if (await this.deps.isVersionSwapVetoed({ version: source.version, localVersion: local })) return { started: false, reason: "host-version-rolled-back", version: source.version }; const result = await this.runHostBundleFetchStage({ source, localVersion: local, trigger: force ? "manual-update-host" : "manual-update-host-idle", forceNow: force }); if (!result.ok) return { started: false, reason: options.includeErrorDetail === true && process.env.SAND_HOST_DEV_ERROR_DETAIL === "1" ? describeHostBundleErrorDetail(result.error, result.phase) : String(result.error) }; return { started: true, version: source.version }; }
  getVersionState(): { hostVersion: string | null; latestHostVersion: string | null; hostUpdateAvailable: boolean | null } { return { hostVersion: this.localVersion, latestHostVersion: this.latestVersion, hostUpdateAvailable: this.latestVersion === null ? null : isSandHostUpgradeAvailable(this.localVersion, this.latestVersion) }; }
  async prepareForUpgrade(): Promise<unknown> { await this.deps.automations.suspendWakes(); this.deps.sharing.prepareForUpgrade(); return this.deps.transcript.quiesceForUpgrade(); }
  async resumeInterruptedUpgradeTurns(): Promise<void> { await this.deps.transcript.resumeInterruptedUpgradeTurns(); }
  async forwardHostUpgradeMarker(): Promise<unknown> { if (this.markerForwardInFlight) return undefined; this.markerForwardInFlight = true; try { return await forwardHostUpgradeMarkerWith({ readRaw: () => this.deps.markerStore.readRaw(), deleteMarker: () => this.deps.markerStore.deleteMarker(), emit: (metadata) => this.deps.telemetry.reportHostUpgradeConfirmed(metadata), warn: (message) => this.deps.log("warn", message), now: (raw) => { if (this.markerForwardNow?.raw !== raw) this.markerForwardNow = { raw, nowMs: this.deps.clock.now() }; return this.markerForwardNow.nowMs; }, wasForwarded: (raw) => raw === this.lastHandledMarker, markForwarded: (raw) => { this.lastHandledMarker = raw; }, onForwarded: (marker) => { if (noteFailedSwapMarkerForRetry(this.updateState, marker)) this.deps.log("info", `supervisor swap of ${marker.toVersion ?? "?"} failed (${marker.swapError ?? "swap-failed"}); re-staging on the next idle watch tick`); } }); } finally { this.markerForwardInFlight = false; } }
  dispose(): void { this.sharedUpdateWatchActive = false; this.sharedUpdateDelay?.dispose(); this.sharedUpdateDelay = undefined; this.markerForwarding?.dispose(); this.markerForwarding = undefined; }
  private scheduleSharedUpdateWatch(delayMs: number): void { if (!this.sharedUpdateWatchActive) return; if (delayMs === 0) { void this.runSharedUpdateWatchAndRearm(); return; } let primed = false, handle: Disposable | undefined; handle = this.deps.createUpdateWatchDelayPolicy(delayMs).start(async () => { if (!primed) { primed = true; return; } handle?.dispose(); if (this.sharedUpdateDelay === handle) this.sharedUpdateDelay = undefined; await this.runSharedUpdateWatchAndRearm(); }); this.sharedUpdateDelay = handle; }
  private async runSharedUpdateWatchAndRearm(): Promise<void> { try { await this.runRootUpdateTick?.(); await this.maybeAutoUpdateHostBundle(); } catch (error) { this.deps.log("warn", `shared update watch failed: ${String(error)}`); } finally { if (this.sharedUpdateWatchActive) this.scheduleSharedUpdateWatch(hostBundleWatchNextDelayMs(this.deps.updateWatchIntervalMs, this.deps.updateWatchJitterRatio, this.deps.random)); } }
  private async maybeAutoUpdateHostBundle(): Promise<void> { if (!this.deps.isAutoUpdateEnabled || this.updateInFlight) return; const source = await this.deps.resolveBundleSource(); if (source == null) return; this.latestVersion = source.version; const local = this.localVersion ?? await this.deps.readLocalVersion(); this.localVersion = local; if (!isSandHostUpgradeAvailable(local, source.version) || this.updateState.stagedVersion === source.version || await this.deps.isVersionSwapVetoed({ version: source.version, localVersion: local })) return; await this.runHostBundleFetchStage({ source, localVersion: local, trigger: "idle-auto-update", forceNow: false }); }
  private async runHostBundleFetchStage(args: { source: HostBundleSource; localVersion: string | null; trigger: string; forceNow: boolean }): Promise<{ ok: true } | { ok: false; error: unknown; phase?: "fetch" | "stage" }> { if (this.updateInFlight) return { ok: false, error: new Error("host bundle update already in flight") }; this.updateInFlight = true; try { return await fetchStageAndReportHostBundle({ source: args.source, fromVersion: args.localVersion, trigger: args.trigger, state: this.updateState, stage: async (bytes) => { await this.deps.stageUpgrade({ version: args.source.version, bytes, forceNow: args.forceNow, reason: args.trigger }); }, reportUpgrade: (metadata) => this.deps.telemetry.reportHostUpgrade(metadata), log: (level, message) => this.deps.log(level, message) }); } finally { this.updateInFlight = false; } }
}
