import { createDeadlinePolicy, realClock, type PollingPolicy } from "../../../internal/scheduling.js";
import type { WatchReceiver } from "./privacy-mode.js";
export const CodebaseEnvironment = { SAND_BOX: 1 } as const;
export interface CsnapsState { readonly tracked: readonly { readonly codebaseUuid: string; readonly path: string; readonly kind: number; readonly environment: number }[] }
export interface CsnapsHandle { readonly terminalFailure: Promise<Error>; applyCodebaseSpecs(codebases: readonly unknown[]): Promise<{ state: CsnapsState; rejected: readonly unknown[] }>; snapshot(reason: unknown): Promise<void>; triggerUpload(credentials: Record<string, unknown>): Promise<void>; flushPendingUploads(credentials: Record<string, unknown>): Promise<void>; close(): Promise<void> }
export class CsnapsAdapterError extends Error { constructor(message: string) { super(message); this.name = "CsnapsAdapterError"; } }
function channel<T>(initial: T, onError: (error: unknown) => void) { let value = initial; const listeners = new Set<(value: T) => void>(); return { receiver: { get: () => value, subscribe(listener: (next: T) => void) { listeners.add(listener); return { dispose: () => listeners.delete(listener) }; } } satisfies WatchReceiver<T>, send(next: T) { value = next; for (const listener of listeners) try { listener(next); } catch (error) { onError(error); } }, dispose: () => listeners.clear() }; }
export function toCodebase(authId: string, codebase: CsnapsState["tracked"][number]) { if (![1,2].includes(codebase.kind) || codebase.environment !== CodebaseEnvironment.SAND_BOX) throw new CsnapsAdapterError("csnaps returned a codebase outside Sand"); return { codebaseUuid: codebase.codebaseUuid, authId, path: codebase.path, kind: codebase.kind, environment: codebase.environment }; }
export function toAdapterState(authId: string, state: CsnapsState) { return { trackedCodebases: state.tracked.map((codebase) => toCodebase(authId, codebase)), isWithinStorageBudget: true }; }
export class CsnapsCodebaseTelemetryAdapter {
  readonly state: WatchReceiver<ReturnType<typeof toAdapterState>>; readonly terminalFailure: Promise<Error>; private readonly sender: ReturnType<typeof channel<ReturnType<typeof toAdapterState>>>; private uploadPolling: { dispose(): void } | undefined; private closePromise: Promise<{ kind: "closed" } | { kind: "cleanupFailed"; errors: readonly unknown[] }> | undefined;
  static async create(options: { readonly credentials: { authId: string }; readonly paths: { codebaseUuidStatePath: string; snapshotsBaseDir: string }; readonly backendUrl: string; readonly csnapsBinPath: string; readonly spawnCsnaps: typeof import("./csnaps-process.js").spawnCsnaps; readonly uploadPolling: PollingPolicy; readonly createUploadCredentials: () => Promise<Record<string, unknown>>; readonly logger: Logger; readonly signal?: AbortSignal }) { const spawned = await options.spawnCsnaps({ executablePath: options.csnapsBinPath, initializeParams: { authId: options.credentials.authId, codebaseUuidStatePath: options.paths.codebaseUuidStatePath, snapshotsBaseDir: options.paths.snapshotsBaseDir, environment: CodebaseEnvironment.SAND_BOX, backendUrl: options.backendUrl }, deadlines: { ping: createDeadlinePolicy(realClock, { name: "csnaps-ping", timeoutMs: 10_000 }), initialize: createDeadlinePolicy(realClock, { name: "csnaps-initialize", timeoutMs: 2 * 60_000 }), applyCodebaseSpecs: createDeadlinePolicy(realClock, { name: "csnaps-apply-codebase-specs", timeoutMs: 10 * 60_000 }), snapshot: createDeadlinePolicy(realClock, { name: "csnaps-snapshot", timeoutMs: 10 * 60_000 }), triggerUpload: createDeadlinePolicy(realClock, { name: "csnaps-trigger-upload", timeoutMs: 30_000 }), flushPendingUploads: createDeadlinePolicy(realClock, { name: "csnaps-flush-pending-uploads", timeoutMs: 30 * 60_000 }), shutdown: createDeadlinePolicy(realClock, { name: "csnaps-shutdown", timeoutMs: 15_000 }), exit: createDeadlinePolicy(realClock, { name: "csnaps-exit", timeoutMs: 3_000 }) }, ...(options.signal === undefined ? {} : { signal: options.signal }) }); return new CsnapsCodebaseTelemetryAdapter({ csnaps: spawned.handle, authId: options.credentials.authId, initialState: spawned.initialState, uploadPolling: options.uploadPolling, createUploadCredentials: options.createUploadCredentials, logger: options.logger }); }
  constructor(private readonly options: { csnaps: CsnapsHandle; authId: string; initialState: CsnapsState; uploadPolling: PollingPolicy; createUploadCredentials: () => Promise<Record<string, unknown>>; logger: Logger }) { this.sender = channel(toAdapterState(options.authId, options.initialState), (error) => options.logger.error("Adapter state subscriber failed", error)); this.state = this.sender.receiver; const terminal = Promise.withResolvers<Error>(); this.terminalFailure = terminal.promise; void options.csnaps.terminalFailure.then((error) => { if (this.isDisposed) return; this.sender.send({ trackedCodebases: [], isWithinStorageBudget: false }); terminal.resolve(error); }); }
  async reconcileFeatureGates(_values: unknown): Promise<void> {}
  async setDesiredCodebases(codebases: readonly unknown[]): Promise<void> { if (this.isDisposed) return; const result = await this.options.csnaps.applyCodebaseSpecs(codebases); if (this.isDisposed) return; if (result.rejected.length > 0) throw new CsnapsAdapterError("csnaps rejected a required codebase"); this.sender.send(toAdapterState(this.options.authId, result.state)); this.uploadPolling ??= this.options.uploadPolling.start(() => this.triggerUpload()); }
  snapshot(reason: unknown): Promise<void> { return this.isDisposed ? Promise.resolve() : this.options.csnaps.snapshot(reason); }
  async runGitHistoryCapture(): Promise<void> {}
  async flushPendingUploads(): Promise<void> { if (this.isDisposed) return; const credentials = await this.options.createUploadCredentials(); if (!this.isDisposed) await this.options.csnaps.flushPendingUploads(credentials); }
  close() { return this.closePromise ??= this.releaseResources(); }
  dispose(): void { void this.close().then((result) => { if (result.kind === "cleanupFailed") this.options.logger.error("Failed to close adapter", result.errors); }, (error) => this.options.logger.error("Failed to close adapter", error)); }
  private get isDisposed(): boolean { return this.closePromise != null; }
  private async releaseResources(): Promise<{ kind: "closed" } | { kind: "cleanupFailed"; errors: readonly unknown[] }> { const errors: unknown[] = []; try { this.uploadPolling?.dispose(); } catch (error) { errors.push(error); } try { await this.options.csnaps.close(); } catch (error) { errors.push(error); } try { this.sender.dispose(); } catch (error) { errors.push(error); } return errors.length === 0 ? { kind: "closed" } : { kind: "cleanupFailed", errors }; }
  private async triggerUpload(): Promise<void> { if (this.isDisposed) return; try { const credentials = await this.options.createUploadCredentials(); if (!this.isDisposed) await this.options.csnaps.triggerUpload(credentials); } catch (error) { if (!this.isDisposed) this.options.logger.warn("Failed to trigger snapshot upload", error); } }
}
export interface Logger { error(message: string, error?: unknown): void; warn(message: string, error?: unknown): void; info(message: string, error?: unknown): void; debug(message: string, error?: unknown): void }
