import type { WatchReceiver, TelemetryAuth } from "./privacy-mode.js";
export const SAND_CODEBASE_TELEMETRY_FEATURE_GATE = "sand_codebase_telemetry";
export const CodebaseTelemetryFeatureGate = { MAIN: "main", GIT_HISTORY: "git-history", AGENT_DOT_DIRS: "agent-dot-dirs" } as const;
export const CodebaseKind = { WORKSPACE_ROOT: 1, HOME_DIRECTORY: 2 } as const;
export const SAND_BOX_WORKSPACE_ROOT = "/workspace", SAND_BOX_HOME_DIR = "/home/box";
function jwtSubject(token: string): string | undefined { try { const payload = token.split(".")[1]; if (payload == null) return undefined; const parsed = JSON.parse(Buffer.from(payload, "base64url").toString("utf8")) as { sub?: unknown }; return typeof parsed.sub === "string" ? parsed.sub : undefined; } catch { return undefined; } }
function source<T>(initial: T, onError: (error: unknown) => void) { let value = initial; const listeners = new Set<(value: T) => void>(); return { receiver: { get: () => value, subscribe(listener: (next: T) => void) { listeners.add(listener); return { dispose: () => listeners.delete(listener) }; } } satisfies WatchReceiver<T>, send(next: T) { value = next; for (const listener of listeners) try { listener(next); } catch (error) { onError(error); } }, dispose: () => listeners.clear() }; }
export function createAuthSource(options: { auth: { peekAccessToken(): string | null; subscribeToRenewal(listener: (event: { outcome: string }) => void): () => void }; logger: { warn(message: string): void; error(message: string, error?: unknown): void }; privacyMode: { setAuth(auth: TelemetryAuth): void; clearAuth(): void } }) { const channel = source<TelemetryAuth | undefined>(undefined, (error) => options.logger.error("Authentication subscriber failed", error)); const clear = () => { if (channel.receiver.get() != null) { options.privacyMode.clearAuth(); channel.send(undefined); } }; const push = () => { const token = options.auth.peekAccessToken(); if (!token) { clear(); return; } const authId = jwtSubject(token); if (!authId) { options.logger.warn("Credential has no usable subject claim"); clear(); return; } const next = { authId, authToken: token }, current = channel.receiver.get(); if (current?.authId === authId && current.authToken === token) return; options.privacyMode.setAuth(next); channel.send(next); }; const off = options.auth.subscribeToRenewal(({ outcome }) => { if (outcome === "renewed" || !options.auth.peekAccessToken()) push(); }); push(); return { receiver: channel.receiver, dispose() { off(); channel.dispose(); } }; }
export function createFeatureGateSource(options: { experiments: { checkFeatureGate(name: string): boolean; checkGate(name: string): boolean | Promise<boolean>; subscribe(listener: () => void): () => void }; logger: { error(message: string, error?: unknown): void } }) { let last = options.experiments.checkFeatureGate(SAND_CODEBASE_TELEMETRY_FEATURE_GATE); const listeners = new Set<(value: { kind: "some"; gates: readonly string[] }) => void>(), off = options.experiments.subscribe(() => { const next = options.experiments.checkFeatureGate(SAND_CODEBASE_TELEMETRY_FEATURE_GATE); if (next === last) return; last = next; for (const listener of listeners) try { listener({ kind: "some", gates: [CodebaseTelemetryFeatureGate.MAIN] }); } catch (error) { options.logger.error("Feature gate subscriber failed", error); } }); return { receiver: { changes: { subscribe(listener: (value: { kind: "some"; gates: readonly string[] }) => void) { listeners.add(listener); return { dispose: () => listeners.delete(listener) }; } }, async check(gate: string) { return gate === CodebaseTelemetryFeatureGate.MAIN ? await options.experiments.checkGate(SAND_CODEBASE_TELEMETRY_FEATURE_GATE) : false; } }, dispose() { off(); listeners.clear(); } }; }
export function createSandCodebaseTelemetryHost(options: { auth: Parameters<typeof createAuthSource>[0]["auth"]; experiments: Parameters<typeof createFeatureGateSource>[0]["experiments"]; privacyMode: { receiver: WatchReceiver<unknown>; setAuth(auth: TelemetryAuth): void; clearAuth(): void }; createAdapter: (options: unknown) => Promise<unknown>; logger: Parameters<typeof createAuthSource>[0]["logger"] }) { const auth = createAuthSource({ auth: options.auth, logger: options.logger, privacyMode: options.privacyMode }), gates = createFeatureGateSource({ experiments: options.experiments, logger: options.logger }); return { logger: options.logger, auth: auth.receiver, privacyMode: options.privacyMode.receiver, featureGates: gates.receiver, desiredCodebases: { changes: { subscribe: () => ({ dispose() {} }) }, get: () => [{ path: SAND_BOX_WORKSPACE_ROOT, kind: CodebaseKind.WORKSPACE_ROOT }, { path: SAND_BOX_HOME_DIR, kind: CodebaseKind.HOME_DIRECTORY }] }, createAdapter: options.createAdapter, dispose() { auth.dispose(); gates.dispose(); } }; }
