export const MAX_FRAME_BYTES = 1024 * 1024;
export class CsnapsProtocolError extends Error { constructor(message: string, options?: ErrorOptions) { super(message, options); this.name = "CsnapsProtocolError"; } }
export type CsnapsOperation = { method: "ping" | "shutdown" } | { method: "initialize" | "apply_codebase_specs" | "snapshot" | "trigger_upload" | "flush_pending_uploads"; params: Record<string, unknown> };
export type CsnapsResponse = { id: number; ok: true; result: unknown } | { id: number; ok: false; error: CsnapsErrorCode };
export type CsnapsErrorCode = "unknown_method"|"invalid_params"|"already_initialized"|"not_initialized"|"codebases_not_reconciled"|"shutting_down"|"server_busy"|"invalid_configuration"|"invalid_codebases"|"codebase_environment_conflict"|"corrupt_uuid_state"|"state_io"|"snapshot_failed"|"upload_disabled"|"internal_error";
const ERROR_CODES = new Set<CsnapsErrorCode>(["unknown_method","invalid_params","already_initialized","not_initialized","codebases_not_reconciled","shutting_down","server_busy","invalid_configuration","invalid_codebases","codebase_environment_conflict","corrupt_uuid_state","state_io","snapshot_failed","upload_disabled","internal_error"]);
const exact = (value: object, keys: readonly string[]) => { const actual = Object.keys(value).sort(), expected = [...keys].sort(); return actual.length === expected.length && actual.every((key,index) => key === expected[index]); };
export function encodeFrame(payload: Buffer): Buffer { if (payload.length > MAX_FRAME_BYTES) throw new CsnapsProtocolError(`csnaps request frame length ${payload.length} exceeds ${MAX_FRAME_BYTES}-byte limit`); const frame = Buffer.allocUnsafe(4 + payload.length); frame.writeUInt32BE(payload.length, 0); payload.copy(frame, 4); return frame; }
export function decodeFramePayloads(input: Buffer): { payloads: Buffer[]; remainder: Buffer } { const payloads: Buffer[] = []; let offset = 0; while (input.length - offset >= 4) { const length = input.readUInt32BE(offset); if (length > MAX_FRAME_BYTES) throw new CsnapsProtocolError(`csnaps response frame length ${length} exceeds ${MAX_FRAME_BYTES}-byte limit`); if (input.length - offset < 4 + length) break; payloads.push(input.subarray(offset + 4, offset + 4 + length)); offset += 4 + length; } return { payloads, remainder: input.subarray(offset) }; }
export function encodeCsnapsRequest(id: number, operation: CsnapsOperation): Buffer { if (!Number.isSafeInteger(id) || id < 0) throw new CsnapsProtocolError("invalid csnaps request ID"); const request = { id, method: operation.method, params: "params" in operation ? operation.params : {} }; return encodeFrame(Buffer.from(JSON.stringify(request), "utf8")); }
export function parseCsnapsResponse(payload: Buffer): CsnapsResponse { let value: unknown; try { value = JSON.parse(payload.toString("utf8")); } catch (cause) { throw new CsnapsProtocolError("invalid csnaps response JSON", { cause }); } if (value == null || typeof value !== "object" || !("id" in value) || typeof value.id !== "number" || !Number.isSafeInteger(value.id) || value.id < 0 || !("ok" in value) || typeof value.ok !== "boolean") throw new CsnapsProtocolError("invalid csnaps response envelope"); if (value.ok) { if (!exact(value,["id","ok","result"]) || !("result" in value)) throw new CsnapsProtocolError("invalid csnaps success response"); return { id: value.id, ok: true, result: value.result }; } if (!exact(value,["error","id","ok"]) || !("error" in value) || typeof value.error !== "string" || !ERROR_CODES.has(value.error as CsnapsErrorCode)) throw new CsnapsProtocolError("invalid csnaps error response"); return { id: value.id, ok: false, error: value.error as CsnapsErrorCode }; }
export class CsnapsResponseDecoder { private buffer = Buffer.alloc(0); decode(chunk: Buffer): CsnapsResponse[] { const input = this.buffer.length === 0 ? chunk : Buffer.concat([this.buffer,chunk]), decoded = decodeFramePayloads(input); this.buffer = Buffer.from(decoded.remainder); return decoded.payloads.map(parseCsnapsResponse); } assertComplete(): void { if (this.buffer.length !== 0) throw new CsnapsProtocolError("truncated csnaps response frame"); } }
function state(value: unknown) { if (value == null || typeof value !== "object" || !exact(value,["tracked"]) || !("tracked" in value) || !Array.isArray(value.tracked)) throw new CsnapsProtocolError("invalid csnaps service state"); return { tracked: value.tracked.map((entry) => { if (entry == null || typeof entry !== "object" || !exact(entry,["codebaseUuid","environment","kind","path"]) || !("codebaseUuid" in entry) || typeof entry.codebaseUuid !== "string" || !/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(entry.codebaseUuid) || !("path" in entry) || typeof entry.path !== "string" || !("kind" in entry) || typeof entry.kind !== "number" || !("environment" in entry) || typeof entry.environment !== "number") throw new CsnapsProtocolError("invalid tracked csnaps codebase"); return { codebaseUuid: entry.codebaseUuid, path: entry.path, kind: entry.kind, environment: entry.environment }; }) }; }
export function parseCsnapsOperationResult(operation: CsnapsOperation, value: unknown): unknown { if (["ping","snapshot","trigger_upload","flush_pending_uploads","shutdown"].includes(operation.method)) { if (value == null || typeof value !== "object" || !exact(value,[])) throw new CsnapsProtocolError("invalid empty csnaps result"); return {}; } if (operation.method === "initialize") { if (value == null || typeof value !== "object" || !exact(value,["state"]) || !("state" in value)) throw new CsnapsProtocolError("invalid csnaps initialize result"); return { state: state(value.state) }; } if (value == null || typeof value !== "object" || !exact(value,["rejected","state"]) || !("rejected" in value) || !Array.isArray(value.rejected) || !("state" in value)) throw new CsnapsProtocolError("invalid csnaps apply result"); return { state: state(value.state), rejected: value.rejected.map((entry) => { if (entry == null || typeof entry !== "object" || !exact(entry,["kind","path"]) || !("path" in entry) || typeof entry.path !== "string" || !("kind" in entry) || typeof entry.kind !== "number") throw new CsnapsProtocolError("invalid rejected csnaps codebase"); return { path: entry.path, kind: entry.kind }; }) }; }
