import { spawn, type ChildProcessByStdio } from "node:child_process";
import type { Readable, Writable } from "node:stream";
import type { DeadlinePolicy } from "../../../internal/scheduling.js";
import { CsnapsResponseDecoder, encodeCsnapsRequest, parseCsnapsOperationResult, type CsnapsErrorCode, type CsnapsOperation, type CsnapsResponse } from "./csnaps-protocol.js";
export class CsnapsProcessError extends Error { constructor(message: string, options?: ErrorOptions) { super(message, options); this.name = "CsnapsProcessError"; } }
export class CsnapsRequestError extends CsnapsProcessError { constructor(readonly method: string, readonly code: CsnapsErrorCode) { super(`csnaps ${method} request failed: ${code}`); this.name = "CsnapsRequestError"; } }
export interface CsnapsDeadlines { ping: DeadlinePolicy; initialize: DeadlinePolicy; applyCodebaseSpecs: DeadlinePolicy; snapshot: DeadlinePolicy; triggerUpload: DeadlinePolicy; flushPendingUploads: DeadlinePolicy; shutdown: DeadlinePolicy; exit: DeadlinePolicy }
export interface CsnapsProcessState { readonly tracked: readonly { readonly codebaseUuid: string; readonly path: string; readonly kind: number; readonly environment: number }[] }
interface Pending { method: string; resolve(value: unknown): void; reject(error: unknown): void; signal: AbortSignal; onAbort(): void }
export class CsnapsProcess {
  readonly terminalFailure: Promise<Error>; private readonly resolveTerminalFailure: (error: Error) => void; private readonly childClosed: Promise<void>; private terminalError: Error | undefined; private closePromise: Promise<void> | undefined; private isClosing = false; private nextRequestId = 0; private readonly pending = new Map<number, Pending>(); private readonly decoder = new CsnapsResponseDecoder();
  constructor(private readonly child: ChildProcessByStdio<Writable, Readable, null>, private readonly deadlines: CsnapsDeadlines) { const terminal = Promise.withResolvers<Error>(); this.terminalFailure = terminal.promise; this.resolveTerminalFailure = terminal.resolve; this.childClosed = new Promise((resolve) => child.once("close", (code, signal) => { let error = this.terminalError; if (error == null) { try { this.decoder.assertComplete(); error = new CsnapsProcessError(describeCsnapsExit(code, signal)); } catch (cause) { error = cause instanceof Error ? cause : new CsnapsProcessError("invalid csnaps response", { cause }); } } this.terminalError = error; this.rejectPending(error); if (!this.isClosing) this.resolveTerminalFailure(error); resolve(); })); child.once("error", (error) => this.fail(new CsnapsProcessError(`csnaps child process failed: ${error.message}`, { cause: error }))); child.stdin.on("error", (error) => this.fail(new CsnapsProcessError(`csnaps stdin failed: ${error.message}`, { cause: error }))); child.stdout.on("error", (error) => this.fail(new CsnapsProcessError(`csnaps stdout failed: ${error.message}`, { cause: error }))); child.stdout.on("data", (chunk: Buffer) => this.handleChunk(chunk)); }
  static async spawn(options: { executablePath: string; initializeParams: Record<string, unknown>; deadlines: CsnapsDeadlines; signal?: AbortSignal }): Promise<{ handle: CsnapsProcess; initialState: CsnapsProcessState }> { options.signal?.throwIfAborted(); const process = new CsnapsProcess(spawn(options.executablePath, [], { env: {}, stdio: ["pipe","pipe","inherit"] }), options.deadlines); try { await process.ping(options.signal); const initialized = await process.initialize(options.initializeParams, options.signal); return { handle: process, initialState: initialized.state }; } catch (error) { try { await process.terminate(); } catch {} throw error; } }
  async initialize(params: Record<string, unknown>, signal?: AbortSignal): Promise<{ state: CsnapsProcessState }> { const operation = { method: "initialize" as const, params }; return parseCsnapsOperationResult(operation, await this.request(operation, signal)) as { state: CsnapsProcessState }; }
  async applyCodebaseSpecs(codebases: readonly unknown[], signal?: AbortSignal): Promise<{ state: CsnapsProcessState; rejected: readonly unknown[] }> { const operation = { method: "apply_codebase_specs" as const, params: { codebases } }; return parseCsnapsOperationResult(operation, await this.request(operation, signal)) as { state: CsnapsProcessState; rejected: readonly unknown[] }; }
  async snapshot(reason: unknown, signal?: AbortSignal): Promise<void> { const operation = { method: "snapshot" as const, params: { reason } }; parseCsnapsOperationResult(operation, await this.request(operation, signal)); }
  async triggerUpload(credentials: Record<string, unknown>, signal?: AbortSignal): Promise<void> { const operation = { method: "trigger_upload" as const, params: credentials }; parseCsnapsOperationResult(operation, await this.request(operation, signal)); }
  async flushPendingUploads(credentials: Record<string, unknown>, signal?: AbortSignal): Promise<void> { const operation = { method: "flush_pending_uploads" as const, params: credentials }; parseCsnapsOperationResult(operation, await this.request(operation, signal)); }
  async ping(signal?: AbortSignal): Promise<void> { const operation = { method: "ping" as const }; parseCsnapsOperationResult(operation, await this.request(operation, signal)); }
  close(): Promise<void> { this.isClosing = true; return this.closePromise ??= this.shutdown(); }
  private async shutdown(): Promise<void> { try { const operation = { method: "shutdown" as const }; parseCsnapsOperationResult(operation, await this.request(operation)); await this.waitForChildClose("shutdown"); } catch { await this.terminate(); } }
  async terminate(): Promise<void> { if (this.child.exitCode != null || this.child.signalCode != null) { await this.waitForChildClose("exit"); return; } this.child.stdin.destroy(); this.child.kill("SIGTERM"); try { await this.waitForChildClose("SIGTERM"); } catch { this.child.kill("SIGKILL"); await this.waitForChildClose("SIGKILL"); } }
  private async waitForChildClose(trigger: string): Promise<void> { try { await this.deadlines.exit.run(async () => await this.childClosed); } catch (cause) { throw new CsnapsProcessError(`csnaps process did not close after ${trigger}`, { cause }); } }
  private request(operation: CsnapsOperation, signal?: AbortSignal): Promise<unknown> { return this.deadlineFor(operation.method).run(async (deadlineSignal) => { if (this.terminalError != null) throw this.terminalError; const id = this.nextRequestId++, frame = encodeCsnapsRequest(id, operation), response = Promise.withResolvers<unknown>(); const onAbort = () => { if (!this.pending.delete(id)) return; const error = new CsnapsProcessError(`csnaps ${operation.method} request ${deadlineSignal.reason instanceof Error && deadlineSignal.reason.name === "DeadlineExceededError" ? "timed out" : "cancelled"}`, { cause: deadlineSignal.reason }); response.reject(error); this.fail(error); }; this.pending.set(id, { method: operation.method, resolve: response.resolve, reject: response.reject, signal: deadlineSignal, onAbort }); deadlineSignal.addEventListener("abort", onAbort, { once: true }); if (deadlineSignal.aborted) onAbort(); else try { await writeFrame(this.child.stdin, frame); } catch (error) { const failure = this.terminalError ?? (error instanceof Error ? error : new CsnapsProcessError("csnaps stdin write failed", { cause: error })); this.fail(failure); throw failure; } return await response.promise; }, signal).catch((error) => { throw this.terminalError ?? error; }); }
  private deadlineFor(method: CsnapsOperation["method"]): DeadlinePolicy { switch (method) { case "ping": return this.deadlines.ping; case "initialize": return this.deadlines.initialize; case "apply_codebase_specs": return this.deadlines.applyCodebaseSpecs; case "snapshot": return this.deadlines.snapshot; case "trigger_upload": return this.deadlines.triggerUpload; case "flush_pending_uploads": return this.deadlines.flushPendingUploads; case "shutdown": return this.deadlines.shutdown; } }
  private handleChunk(chunk: Buffer): void { if (this.terminalError != null) return; try { const responses = this.decoder.decode(chunk), seen = new Set<number>(); for (const response of responses) { if (seen.has(response.id)) throw new CsnapsProcessError("csnaps returned a duplicate request ID"); if (!this.pending.has(response.id)) throw new CsnapsProcessError("csnaps returned an unknown request ID"); seen.add(response.id); } for (const response of responses) this.settle(response); } catch (error) { this.fail(error instanceof Error ? error : new CsnapsProcessError("invalid csnaps response", { cause: error })); } }
  private settle(response: CsnapsResponse): void { const pending = this.pending.get(response.id); if (pending == null) throw new CsnapsProcessError("csnaps returned an unknown request ID"); this.pending.delete(response.id); pending.signal.removeEventListener("abort", pending.onAbort); response.ok ? pending.resolve(response.result) : pending.reject(new CsnapsRequestError(pending.method, response.error)); }
  private fail(error: Error): void { if (this.terminalError != null) return; this.terminalError = error; this.child.stdin.destroy(); this.child.kill("SIGTERM"); this.rejectPending(error); if (!this.isClosing) this.resolveTerminalFailure(error); }
  private rejectPending(error: Error): void { for (const pending of this.pending.values()) { pending.signal.removeEventListener("abort", pending.onAbort); pending.reject(error); } this.pending.clear(); }
}
export function spawnCsnaps(options: Parameters<typeof CsnapsProcess.spawn>[0]) { return CsnapsProcess.spawn(options); }
export function describeCsnapsExit(exitCode: number | null, signal: NodeJS.Signals | null): string { return exitCode != null ? `csnaps process exited with code ${exitCode}` : signal != null ? `csnaps process exited due to signal ${signal}` : "csnaps process exited"; }
export function writeFrame(stream: Writable, frame: Buffer): Promise<void> { return new Promise((resolve,reject) => { try { stream.write(frame, (error) => error == null ? resolve() : reject(new CsnapsProcessError(`csnaps stdin write failed: ${error.message}`, { cause: error }))); } catch (cause) { reject(new CsnapsProcessError(`csnaps stdin write failed${cause instanceof Error ? `: ${cause.message}` : ""}`, { cause })); } }); }
