import type { MethodInfoUnary } from "@bufbuild/protobuf";
import { DashboardService } from "../../../packages/proto/generated/aiserver/v1/dashboard_connect.js";
import { GetUserPrivacyModeRequest, type GetUserPrivacyModeResponse } from "../../../packages/proto/generated/aiserver/v1/dashboard_pb.js";
import { PrivacyMode as ProtoPrivacyMode } from "../../../packages/proto/generated/aiserver/v1/privacy_mode_pb.js";
import { createSandCursorBackendClient } from "../../../shared/node/cursor-backend/cursor-inference.js";
import type { DeadlinePolicy, PollingPolicy, RetryPolicy } from "../../../internal/scheduling.js";
export const PrivacyModes = { Unspecified: 0, NoStorage: 1, NoTraining: 2, UsageDataTrainingAllowed: 3, UsageCodebaseTrainingAllowed: 4 } as const;
export type PrivacyMode = number;
export interface TelemetryAuth { readonly authId: string; readonly authToken: string }
export interface WatchReceiver<T> { get(): T; subscribe(listener: (value: T) => void): { dispose(): void } }
function watch<T>(initial: T, onError: (error: unknown) => void) { let value = initial; const listeners = new Set<(value: T) => void>(); return { receiver: { get: () => value, subscribe(listener: (next: T) => void) { listeners.add(listener); return { dispose: () => listeners.delete(listener) }; } } satisfies WatchReceiver<T>, send(next: T) { value = next; for (const listener of listeners) try { listener(next); } catch (error) { onError(error); } }, dispose() { listeners.clear(); } }; }
export function createSandPrivacyModeLoader(authApi: { getMachineId(): Promise<string> }) { return async ({ auth, signal }: { auth: TelemetryAuth; signal: AbortSignal }): Promise<PrivacyMode> => { const service = DashboardService as typeof DashboardService & { readonly methods: typeof DashboardService.methods & { readonly getUserPrivacyMode: MethodInfoUnary<GetUserPrivacyModeRequest, GetUserPrivacyModeResponse> } }; const client = createSandCursorBackendClient(service, { getAccessToken: async () => auth.authToken, getMachineId: () => authApi.getMachineId() }); const response = await client.getUserPrivacyMode(new GetUserPrivacyModeRequest({ inferredPrivacyMode: ProtoPrivacyMode.NO_STORAGE }), { signal }); return response.privacyMode; }; }
export function toPrivacyMode(value: number): PrivacyMode { switch (value) { case PrivacyModes.NoStorage: case PrivacyModes.NoTraining: case PrivacyModes.UsageDataTrainingAllowed: case PrivacyModes.UsageCodebaseTrainingAllowed: return value; default: return PrivacyModes.Unspecified; } }
export function createCodebaseTelemetryPrivacyMode(options: { readonly load: (args: { auth: TelemetryAuth; signal: AbortSignal }) => Promise<PrivacyMode>; readonly lookupDeadline: DeadlinePolicy; readonly lookupRetry: RetryPolicy; readonly refreshPolling: PollingPolicy; readonly logger: { error(message: string, error?: unknown): void; warn(message: string, error?: unknown): void } }) { const channel = watch<PrivacyMode>(PrivacyModes.Unspecified, (error) => options.logger.error("Privacy mode subscriber failed", error)); let activeAuth: TelemetryAuth | undefined, activeRefresh: AbortController | undefined, generation = 0, disposed = false; const refresh = async () => { const auth = activeAuth; if (auth == null || disposed) return; const current = ++generation; activeRefresh?.abort(); const controller = new AbortController(); activeRefresh = controller; try { const mode = await options.lookupRetry.runWithRetry((_attempt, retrySignal) => options.lookupDeadline.run((signal) => options.load({ auth, signal }), retrySignal), controller.signal); if (!disposed && current === generation) channel.send(toPrivacyMode(mode)); } catch (error) { if (!disposed && current === generation) options.logger.warn("Privacy mode lookup failed", error); } finally { if (activeRefresh === controller) activeRefresh = undefined; } }; const polling = options.refreshPolling.start(refresh); return { receiver: channel.receiver, setAuth(auth: TelemetryAuth) { const changed = activeAuth?.authId !== auth.authId; activeAuth = auth; if (changed) { generation += 1; channel.send(PrivacyModes.Unspecified); } void refresh(); }, clearAuth() { activeAuth = undefined; generation += 1; activeRefresh?.abort(); activeRefresh = undefined; channel.send(PrivacyModes.Unspecified); }, dispose() { if (disposed) return; disposed = true; generation += 1; activeRefresh?.abort(); activeRefresh = undefined; polling.dispose(); channel.dispose(); } }; }
export function isRetryablePrivacyModeLookupError(error: unknown): boolean { if (!(error instanceof Error)) return false; const candidate = error as Error & { code?: unknown; metadata?: { has(name: string): boolean } }; if (error.name === "DeadlineExceededError") return true; if (error.name !== "ConnectError") return false; return candidate.code === 4 || candidate.code === 14 && candidate.metadata?.has("retry-after") !== true; }
