import { parseSandDeepLink, SAND_DEEP_LINK_SCHEME, SAND_HTTPS_DEEP_LINK_ORIGIN, SAND_HTTPS_DEEP_LINK_PATH_PREFIX, type ParsedSandDeepLink } from "../../shared/deep-link.js";
export const SAND_DEEP_LINK_PENDING_MAX = 16; export const SAND_DEEP_LINK_DEDUPE_WINDOW_MS = 2_000; const HTTPS_CANDIDATE_PREFIX = `${SAND_HTTPS_DEEP_LINK_ORIGIN}${SAND_HTTPS_DEEP_LINK_PATH_PREFIX}`.toLowerCase();
export function extractDeepLinkCandidatesFromArgv(argv: readonly string[]): string[] { return argv.filter((arg) => { const lower = arg.toLowerCase(); return lower.startsWith(`${SAND_DEEP_LINK_SCHEME}:`) || lower.startsWith(HTTPS_CANDIDATE_PREFIX); }); }
export function describeRejectedCandidate(raw: unknown): string { if (typeof raw !== "string") return `<non-string:${typeof raw}>`; const colon = raw.indexOf(":"); return `<scheme=${colon > 0 && colon <= 16 ? raw.slice(0, colon) : "<none>"} length=${raw.length}>`; }
export class SandDeepLinkController {
  #rendererReady = false; readonly #pending: ParsedSandDeepLink[] = []; readonly #recentlyAccepted = new Map<string, number>();
  constructor(readonly options: { readonly dispatch: (link: ParsedSandDeepLink) => void; readonly focusWindow: () => void; readonly log: (message: string) => void; readonly now?: () => number; readonly parse?: (raw: unknown) => ParsedSandDeepLink | null }) {}
  handleCandidate(raw: unknown, origin: string): boolean { const parsed = (this.options.parse ?? parseSandDeepLink)(raw); if (parsed == null) { this.options.log(`deep-link: ignored invalid candidate from ${origin}: ${describeRejectedCandidate(raw)}`); return false; } if (this.#isDuplicate(parsed.canonicalUrl)) { this.options.log(`deep-link: deduped ${parsed.canonicalUrl} from ${origin} (already accepted)`); return false; } if (!this.#rendererReady && this.#pending.length >= SAND_DEEP_LINK_PENDING_MAX) { this.options.log(`deep-link: dropped ${parsed.canonicalUrl} from ${origin} (pending queue full)`); return false; } this.#recentlyAccepted.set(parsed.canonicalUrl, (this.options.now ?? Date.now)()); this.options.focusWindow(); if (this.#rendererReady) { this.options.log(`deep-link: dispatching ${parsed.canonicalUrl} from ${origin}`); this.options.dispatch(parsed); } else { this.options.log(`deep-link: queued ${parsed.canonicalUrl} from ${origin} (renderer not ready)`); this.#pending.push(parsed); } return true; }
  handleArgv(argv: readonly string[], origin: string): void { for (const candidate of extractDeepLinkCandidatesFromArgv(argv)) this.handleCandidate(candidate, origin); }
  hasPendingActivation(): boolean { return this.#pending.length > 0; }
  markReady(): void { this.#rendererReady = true; if (this.#pending.length === 0) return; const links = this.#pending.splice(0); this.options.log(`deep-link: renderer ready, flushing ${links.length} pending`); for (const link of links) this.options.dispatch(link); }
  markNotReady(): void { this.#rendererReady = false; const pendingKeys = new Set(this.#pending.map((entry) => entry.canonicalUrl)); for (const key of this.#recentlyAccepted.keys()) if (!pendingKeys.has(key)) this.#recentlyAccepted.delete(key); }
  #isDuplicate(canonicalUrl: string): boolean { const now = (this.options.now ?? Date.now)(); for (const [key, acceptedAt] of this.#recentlyAccepted) if (now - acceptedAt > SAND_DEEP_LINK_DEDUPE_WINDOW_MS) this.#recentlyAccepted.delete(key); return this.#pending.some((entry) => entry.canonicalUrl === canonicalUrl) || this.#recentlyAccepted.has(canonicalUrl); }
}
