import { existsSync } from "node:fs";
import { join } from "node:path";
import type { Clock, DebouncePolicy, PollingPolicy, RetryPolicy } from "../../../internal/scheduling.js";
import { SAND_BOX_PERSIST_ARCHIVE_EXCLUDES } from "../../../packages/constants/sand-box-archive.js";
import { isAgentStoreSourceId } from "../../../packages/constants/agent-store-ids.js";
import { errorMessage } from "../../../shared/errors.js";
import { getBoxStoreBackendPolicy, isBoxStoreSyncEnabled, type BoxStoreBackendPolicy } from "../../box/box-store-backend-policy.js";
import { BOX_STORE_SAND_DATA_EXCLUDED_FILE_NAMES } from "../../durable-file-policy.js";
import { getSandRootDir } from "../../host-paths.js";
import type { AgentStoreClientDependencies } from "./agent-store-sand-files.js";
import { AgentStoreObjectStoreProvider, resolveBoxObjectStoreProvider, type BoxObjectStoreProvider } from "./box-object-store.js";
import { CHROME_AUTH_STATE_CACHE_EXCLUDE_NAMES, CHROME_AUTH_STATE_REL_DIRS, CHROME_SESSION_CATEGORY_NAME, CHROME_SESSION_DB_DIR, CHROME_SESSION_DB_NAMES, CHROME_SESSION_DB_REL_DIR, stageBoxChromeSession, type ChromeStageReport } from "./chrome-session-stage.js";
import { ChromeSessionWatcher } from "./chrome-session-watcher.js";
import { BOX_STORE_HYDRATION_HANDOFF_FILE_NAME } from "./box-store-hydration.js";
import { SAND_MANIFEST_V2_ENV } from "./box-store-manifest-format.js";
import { boxStoreDbCaptureTelemetry } from "./store-db-capture.js";
import { BoxStoreSync, boxStoreSyncCycleTelemetry, evaluateBoxStoreFlush, type BoxStoreCaptureSummary, type BoxStoreCategory, type BoxStoreCycleSummary } from "./box-store-sync.js";
import { compileWorkspaceIgnore, loadWorkspaceIgnore } from "./workspace-ignore.js";

export const SAND_STORE_BETTER_CLI_ENV = "SAND_STORE_BETTER_CLI";
export const BOX_HOME_CATEGORY_NAME = "home";
export const BOX_HOME_DIR = "/home/box";
export const BOX_HOME_REL_PREFIX = "home/box";
export const BOX_HOME_PRUNE_GUARDED_FOREIGN_TREES = [`${BOX_HOME_REL_PREFIX}/cli-config`, `${BOX_HOME_REL_PREFIX}/chrome-profile*`, `${BOX_HOME_REL_PREFIX}/sand-data`, `${BOX_HOME_REL_PREFIX}/sand-host`, `${BOX_HOME_REL_PREFIX}/deps`] as const;
export const BOX_HOME_REGENERABLE_JUNK_IGNORE_PATTERNS = ["/cli-config/", "/chrome-profile*/", "/sand-data/", "/sand-host/", "/deps/", ".cache/", "/.npm/", "/.nvm/", "/.rustup/", "/.cargo/registry/", "/.cargo/git/", "/.local/share/pnpm/", "/.local/share/Trash/", "/.local/state/", "/.docker/buildx/", "/.gradle/caches/", "/.gradle/daemon/", "/.gradle/wrapper/", "/.m2/repository/", "/.vnc/", "/.dbus/", "/.Xauthority", "*.sock"] as const;
export function buildBoxHomeCategory(absRoot: string): BoxStoreCategory { return { name: BOX_HOME_CATEGORY_NAME, absRoot, relPrefix: BOX_HOME_REL_PREFIX, excludes: BOX_HOME_PRUNE_GUARDED_FOREIGN_TREES, ignore: () => compileWorkspaceIgnore(BOX_HOME_REGENERABLE_JUNK_IGNORE_PATTERNS) }; }
export const BOX_STORE_SYNC_INTERVAL_MS = 2 * 60_000;
export const BOX_STORE_CHROME_INTERVAL_MS = 15 * 60_000;
export const BOX_STORE_DB_DEBOUNCE_MS = 5_000;
export const CHROME_SESSION_CHANGE_DEBOUNCE_MS = 5_000;
export const BOX_STORE_MANIFEST_RETRY_ATTEMPTS = 3;
export const BOX_STORE_MANIFEST_RETRY_DELAY_MS = 100;

export interface BoxStoreTelemetry { reportBoxStoreSyncCycle(level: string, metadata: Record<string, string | undefined>): void; reportChromeSessionStage(level: string, metadata: Record<string, string | undefined>): void; reportBoxStoreManifestConflict(level: string, metadata: Record<string, string | undefined>): void; reportBoxStoreDbCapture(level: string, metadata: Record<string, string | undefined>): void }
export interface BoxStoreSyncServiceDependencies { env?: NodeJS.ProcessEnv; auth: AgentStoreClientDependencies; sourceMap: { getOrCreateBoxStore(): Promise<{ sourceId: string }> }; clock: Clock; polling: PollingPolicy; storeDbDebounce: DebouncePolicy; chromeSessionDebounce: DebouncePolicy; chromeStageRetry: RetryPolicy; manifestRetry: RetryPolicy; isIdle(): boolean; log(message: string): void; telemetry: BoxStoreTelemetry }
export interface BoxStoreSyncApi { isEnabled: boolean; objectStoreProvider: BoxObjectStoreProvider; getStoreId(): Promise<string>; snapshotBoxStoreNow(args: { includeIdleOnly?: boolean }): Promise<ReturnType<typeof evaluateBoxStoreFlush>>; getBoxStoreStatus(): ReturnType<BoxStoreSync["readStoreStatus"]>; clearBoxStoreNow(): Promise<{ ok: boolean; reason?: string }>; scheduleStoreDbSnapshot(agentId: string): void; forgetAgent(agentId: string): Promise<void> }

export class DefaultBoxStoreSyncService {
  readonly api: BoxStoreSyncApi;
  readonly env: NodeJS.ProcessEnv;
  readonly sandRoot: string;
  readonly backendPolicy: BoxStoreBackendPolicy;
  readonly sync: BoxStoreSync | undefined;
  private accessorInstance: BoxStoreSync | undefined;
  private pollingHandle: { dispose(): void } | undefined;
  private chromeSessionWatcher: ChromeSessionWatcher | undefined;
  private lastChromeSyncMs: number;
  private started = false;
  constructor(readonly deps: BoxStoreSyncServiceDependencies) {
    this.env = deps.env ?? process.env; this.sandRoot = getSandRootDir(); this.backendPolicy = getBoxStoreBackendPolicy(this.env);
    const objectStoreProvider = resolveBoxObjectStoreProvider({ env: this.env, agentStore: deps.auth }), enabled = isBoxStoreSyncEnabled(this.env); this.lastChromeSyncMs = deps.clock.monotonicNow();
    this.sync = enabled ? this.createSync(buildBoxStoreCategories({ sandRoot: this.sandRoot, chromeStageRetry: deps.chromeStageRetry, reportChromeSessionStage: (outcome) => this.reportChromeSessionStage(outcome), env: this.env }), objectStoreProvider, "[box-store-sync]") : undefined;
    this.api = { isEnabled: enabled, objectStoreProvider, getStoreId: () => this.getStoreId(), snapshotBoxStoreNow: (args) => this.snapshotBoxStoreNow(args), getBoxStoreStatus: () => this.accessor().readStoreStatus(), clearBoxStoreNow: () => this.clearBoxStoreNow(), scheduleStoreDbSnapshot: (agentId) => this.sync?.scheduleStoreDbSnapshot(agentId), forgetAgent: async (agentId) => { await (this.sync ?? this.accessor()).forgetAgent(agentId); } };
  }
  start(): void { if (this.started) return; this.started = true; if (this.sync == null) { this.deps.telemetry.reportBoxStoreSyncCycle("warn", { ok: "false", reason: "disabled", phase: "startup" }); return; } const startupSweep = this.sync.sweepLeakedTemps().then((removed) => { if (removed > 0) this.deps.log(`swept ${removed} leaked box-store temp file(s)`); }).catch((error) => this.deps.log(`box-store temp sweep failed: ${errorMessage(error)}`)); this.pollingHandle = this.deps.polling.start(async () => { await startupSweep; await this.runCycle(); }); this.chromeSessionWatcher = new ChromeSessionWatcher({ watchDir: CHROME_SESSION_DB_DIR, sessionDbNames: CHROME_SESSION_DB_NAMES, debounce: this.deps.chromeSessionDebounce, onSessionChange: () => { void this.sync?.snapshotNow({ chromeSessionOnly: true, waitForInFlight: true }).catch((error) => this.deps.log(`chrome-session snapshot rejected: ${errorMessage(error)}`)); }, log: this.deps.log }); this.chromeSessionWatcher.start(); this.deps.log("box-store sync enabled (snapshot-out only)"); this.deps.telemetry.reportBoxStoreSyncCycle("info", { ok: "true", reason: "enabled", phase: "startup" }); }
  async dispose(): Promise<void> { this.pollingHandle?.dispose(); this.pollingHandle = undefined; this.chromeSessionWatcher?.stop(); this.chromeSessionWatcher = undefined; await this.sync?.dispose(); if (this.accessorInstance != null && this.accessorInstance !== this.sync) await this.accessorInstance.dispose(); this.accessorInstance = undefined; }
  private createSync(categories: readonly BoxStoreCategory[], objectStoreProvider: BoxObjectStoreProvider, logPrefix: string): BoxStoreSync { return new BoxStoreSync({ resolveStoreId: () => this.getStoreId(), categories, objectStoreProvider, manifestV2: this.env[SAND_MANIFEST_V2_ENV] === "1", hydrationHandoffMarkerPath: join(this.sandRoot, BOX_STORE_HYDRATION_HANDOFF_FILE_NAME), storeDbDebounce: this.deps.storeDbDebounce, manifestRetry: this.deps.manifestRetry, now: () => this.deps.clock.now(), log: (message) => this.deps.log(`${logPrefix} ${message}`), ...(categories.length > 0 ? { lockPath: join(this.sandRoot, "box-store-sync.lock"), windowId: `sand-host-${process.pid}`, onCycle: (summary: BoxStoreCycleSummary) => this.reportBoxStoreSyncCycle(summary), onStoreDbCapture: (summary: BoxStoreCaptureSummary) => this.reportBoxStoreDbCapture(summary), onManifestWriteConflict: (info: Record<string, unknown>) => this.reportBoxStoreManifestConflict(info) } : {}) }); }
  private accessor(): BoxStoreSync { if (this.sync != null) return this.sync; this.accessorInstance ??= this.createSync([], this.api.objectStoreProvider, "[box-store-access]"); return this.accessorInstance; }
  async getStoreId(): Promise<string> { const override = this.env.SAND_BOX_STORE_ID?.trim(); if (override != null && override.length > 0 && isAgentStoreSourceId(override)) return override; return (await this.deps.sourceMap.getOrCreateBoxStore()).sourceId; }
  async snapshotBoxStoreNow(args: { includeIdleOnly?: boolean }) { if (this.sync == null) return { ok: false, manifestEntries: 0, storeDbEntries: 0, agentDirEntries: 0, storeDbComplete: false, filesUploaded: 0, reason: "store-sync-disabled" }; const summary = await this.sync.snapshotNow({ includeIdleOnly: args.includeIdleOnly === true, includeStoreDbs: true, waitForInFlight: true, acceptMatchingCanonicalOnConflict: true }).catch((error) => { this.deps.log(`flush snapshot rejected: ${errorMessage(error)}`); return undefined; }); return evaluateBoxStoreFlush(summary, { sessionCategoryName: CHROME_SESSION_CATEGORY_NAME }); }
  async clearBoxStoreNow(): Promise<{ ok: boolean; reason?: string }> { if (this.backendPolicy.kind === "sand-box-store-v2") { const legacy = this.createSync([], new AgentStoreObjectStoreProvider(this.deps.auth), "[box-store-clear-legacy]"), legacyResult = await legacy.clearStore(); await legacy.dispose(); if (!legacyResult.ok) return { ok: false, reason: `legacy store clear failed: ${legacyResult.reason ?? "unknown"}` }; } return this.accessor().clearStore(); }
  async runCycle(): Promise<void> { if (this.sync == null) return; const idle = this.deps.isIdle(), now = this.deps.clock.monotonicNow(), hydrationHandoffPending = existsSync(join(this.sandRoot, BOX_STORE_HYDRATION_HANDOFF_FILE_NAME)), sealHydrationHandoff = hydrationHandoffPending && idle, includeIdleOnly = sealHydrationHandoff || idle && now - this.lastChromeSyncMs >= BOX_STORE_CHROME_INTERVAL_MS; if (includeIdleOnly) this.lastChromeSyncMs = now; await this.sync.snapshotNow({ includeIdleOnly, includeStoreDbs: idle, skipLiveHandleStoreDbs: !sealHydrationHandoff, includePacks: includeIdleOnly }).catch((error) => this.deps.log(`periodic snapshot rejected: ${errorMessage(error)}`)); }
  private reportChromeSessionStage(outcome: ChromeStageReport): void { const failure = outcome.failure; this.deps.telemetry.reportChromeSessionStage(outcome.skipped > 0 ? "warn" : "info", { staged: String(outcome.staged), skipped: String(outcome.skipped), skipped_dbs: outcome.skippedDbNames.length > 0 ? outcome.skippedDbNames.join(",") : undefined, error_class: outcome.errorClass ?? undefined, failure_db: failure?.db, failure_phase: failure?.phase, failure_operation: failure?.operation, failure_path_stage: failure?.pathStage, failure_cause: failure?.cause, errno: failure?.errno, sqlite_code: failure?.sqliteCode === undefined ? undefined : String(failure.sqliteCode) }); }
  private reportBoxStoreSyncCycle(summary: BoxStoreCycleSummary): void { const event = boxStoreSyncCycleTelemetry(summary); if (event != null) this.deps.telemetry.reportBoxStoreSyncCycle(event.level, event.metadata); }
  private reportBoxStoreManifestConflict(info: Record<string, unknown>): void { this.deps.telemetry.reportBoxStoreManifestConflict("warn", { store_id: info.storeId as string, attempts: String(info.attempts), accepted: String(info.accepted), covered: String(info.covered), canonical_matches_attempt: String(info.canonicalMatchesAttempt), live_view_changed: String(info.liveViewChanged), attempted_entries: String(info.attemptedEntries), last_base_etag: info.lastBaseEtag as string | undefined, last_baseline_source: info.lastBaselineSource as string | undefined, last_conflict_rel_path: info.lastConflictRelPath as string | undefined, canonical_readable: String(info.canonicalReadable), canonical_entry_count: info.canonicalEntryCount == null ? undefined : String(info.canonicalEntryCount), canonical_updated_at_ms: info.canonicalUpdatedAtMs == null ? undefined : String(info.canonicalUpdatedAtMs), canonical_writer_window_id: info.canonicalWriterWindowId as string | undefined, our_window_id: info.ourWindowId as string | undefined }); }
  private reportBoxStoreDbCapture(summary: BoxStoreCaptureSummary): void { const event = boxStoreDbCaptureTelemetry(summary); this.deps.telemetry.reportBoxStoreDbCapture(event.level, event.metadata); }
}

export function buildBoxStoreCategories(args: { sandRoot: string; chromeStageRetry: RetryPolicy; reportChromeSessionStage(outcome: ChromeStageReport): void; env: NodeJS.ProcessEnv }): BoxStoreCategory[] { const sandDataPrefix = "home/box/sand-data"; return [{ name: "sand-data", absRoot: args.sandRoot, relPrefix: sandDataPrefix, containsAgentStoreDbs: true, excludes: [`${sandDataPrefix}/host.lock`, `${sandDataPrefix}/gateway.json`, `${sandDataPrefix}/box-store-sync.lock`, `${sandDataPrefix}/${BOX_STORE_HYDRATION_HANDOFF_FILE_NAME}`, ...BOX_STORE_SAND_DATA_EXCLUDED_FILE_NAMES.map((name) => `${sandDataPrefix}/${name}`)] }, { name: "workspace", absRoot: "/workspace", relPrefix: "workspace", ignore: () => loadWorkspaceIgnore("/workspace") }, { name: "cli-config", absRoot: "/home/box/cli-config", relPrefix: "home/box/cli-config", excludes: ["home/box/cli-config/.cli-auth-tmp*", "home/box/cli-config/*.cli-auth-old", "home/box/cli-config/**/*.cli-auth-old"] }, { name: CHROME_SESSION_CATEGORY_NAME, absRoot: CHROME_SESSION_DB_DIR, relPrefix: "home/box/chrome-profile", stageOnly: true, stage: () => stageBoxChromeSession({ retry: args.chromeStageRetry, report: args.reportChromeSessionStage }) }, ...CHROME_AUTH_STATE_REL_DIRS.map((dir) => ({ name: `chrome-${dir.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`, absRoot: `${CHROME_SESSION_DB_DIR}/${dir}`, relPrefix: `${CHROME_SESSION_DB_REL_DIR}/${dir}`, excludes: CHROME_AUTH_STATE_CACHE_EXCLUDE_NAMES.map((cache) => `${CHROME_SESSION_DB_REL_DIR}/${dir}/${cache}`) })), { name: "chrome-profile", absRoot: "/home/box/chrome-profile", relPrefix: "home/box/chrome-profile", excludes: [...SAND_BOX_PERSIST_ARCHIVE_EXCLUDES, ...CHROME_SESSION_DB_NAMES.flatMap((name) => ["", "-wal", "-shm", "-journal"].map((suffix) => `${CHROME_SESSION_DB_REL_DIR}/${name}${suffix}`)), ...CHROME_AUTH_STATE_REL_DIRS.map((dir) => `${CHROME_SESSION_DB_REL_DIR}/${dir}`)], idleOnly: true }, ...(args.env[SAND_STORE_BETTER_CLI_ENV] === "1" && args.env.SAND_USER_NON_ROOT === "1" ? [buildBoxHomeCategory(BOX_HOME_DIR)] : [])]; }
export function createBoxStoreSyncService(deps: BoxStoreSyncServiceDependencies): DefaultBoxStoreSyncService { return new DefaultBoxStoreSyncService(deps); }
