import { existsSync } from "node:fs";
import { join } from "node:path";
import type { DebouncePolicy } from "../../../internal/scheduling.js";
import { tryAcquireStoreLock } from "../../../packages/agent-store-sync/store-lock.js";
import { errorMessage } from "../../../shared/errors.js";
import { isBoxStoreManifestFileEntry } from "./box-store-manifest-format.js";
import { BoxStoreManifestStore, countAgentDirManifestEntries, countStoreDbManifestEntries, type ManifestStoreDependencies } from "./box-store-manifest.js";
import type { BoxStoreDownloadOptions, BoxStoreDownloadSummary } from "./box-store-download.js";
import { removeHydrationHandoffMarker } from "./box-store-hydration.js";
import { isBoxStorePackBuildEnabled } from "./box-store-pack.js";
import { aggregateStoreDbSweepOutcome, StoreDbCapture, type StoreDbCaptureOutcome, type StoreDbSweepResult } from "./store-db-capture.js";
import { createStoreDbCaptureTrace, recordStoreDbCaptureFailure } from "./store-db-bundle-capture.js";
import { BoxStoreTransfer, type BoxStoreTransferCategory, type CategoryTransferSummary } from "./box-store-transfer.js";

export const DEFAULT_MAX_OBJECT_BYTES = 32 * 1024 * 1024 * 1024;
export const DEFAULT_COPY_IN_CONCURRENCY = 128;
export const DEFAULT_SNAPSHOT_OUT_CONCURRENCY = 8;
export const LARGE_OBJECT_THRESHOLD_BYTES = 64 * 1024 * 1024;
export const DOWNLOAD_IN_FLIGHT_BYTE_BUDGET = 256 * 1024 * 1024;
export type BoxStoreCategory = BoxStoreTransferCategory;
export type CategorySummary = CategoryTransferSummary;
export interface BoxStoreCycleSummary { ok: boolean; reason?: string; storeId: string | null; durationMs: number; categories: CategorySummary[]; manifestEntries: number; storeDbEntries: number; storeDbComplete: boolean; agentDirEntries: number; totalFilesUploaded: number; totalBytesUploaded: number; totalFailures: number; metadataFailures: number }
export interface BoxStoreCaptureSummary extends Record<string, unknown> { trigger: "flush" | "turn_end"; outcome: StoreDbCaptureOutcome; agentCount: number; filesScanned: number; filesUploaded: number; bytes: number; durationMs: number; queueDurationMs: number; captureDurationMs: number; blobUploadDurationMs: number; manifestCommitDurationMs: number; isCommitted: boolean; failurePhase?: string | undefined; storeId?: string | null }
export interface BoxStoreSyncDependencies extends ManifestStoreDependencies { categories: readonly BoxStoreCategory[]; maxObjectBytes?: number; downloadConcurrency?: number; uploadConcurrency?: number; largeObjectThresholdBytes?: number; downloadInFlightByteBudgetBytes?: number; now?: () => number; log?: (message: string) => void; readFreeDiskBytes?(path: string): Promise<number | undefined>; hasLiveHandle?(dbPath: string): boolean; vacuumInto?(args: { srcPath: string; destPath: string }): Promise<void>; getWriteGeneration?(dbPath: string): number; lockPath?: string; acquireWriterLock?(args: { lockPath: string; windowId: string }): Promise<{ release(): Promise<void> } | null>; storeDbDebounce: DebouncePolicy; onCycle?(summary: BoxStoreCycleSummary): void; onStoreDbCapture?(summary: BoxStoreCaptureSummary): void }
export interface SnapshotOptions { includeIdleOnly?: boolean; includeStoreDbs?: boolean; skipLiveHandleStoreDbs?: boolean; chromeSessionOnly?: boolean; waitForInFlight?: boolean; acceptMatchingCanonicalOnConflict?: boolean; includePacks?: boolean }

export class BoxStoreSync {
  readonly manifestStore: BoxStoreManifestStore;
  readonly transfer: BoxStoreTransfer;
  readonly storeDbCapture: StoreDbCapture;
  readonly now: () => number;
  readonly log: (message: string) => void;
  private writerLock: { release(): Promise<void> } | undefined;
  private readonly pendingStoreDb = new Map<string, ReturnType<DebouncePolicy["wrap"]>>();
  private cycleInFlight = false;
  private flushWaiters = 0;
  private inFlight: Promise<BoxStoreCycleSummary> | undefined;
  private disposed = false;
  private stopped = false;
  constructor(readonly deps: BoxStoreSyncDependencies) {
    const maxObjectBytes = deps.maxObjectBytes ?? DEFAULT_MAX_OBJECT_BYTES, downloadConcurrency = Math.max(1, deps.downloadConcurrency ?? DEFAULT_COPY_IN_CONCURRENCY), uploadConcurrency = Math.max(1, deps.uploadConcurrency ?? DEFAULT_SNAPSHOT_OUT_CONCURRENCY), largeObjectThreshold = Math.max(1, deps.largeObjectThresholdBytes ?? LARGE_OBJECT_THRESHOLD_BYTES), downloadByteBudget = Math.max(1, deps.downloadInFlightByteBudgetBytes ?? DOWNLOAD_IN_FLIGHT_BYTE_BUDGET);
    this.now = deps.now ?? Date.now; this.log = deps.log ?? ((message) => console.log(`[box-store-sync] ${message}`));
    this.manifestStore = new BoxStoreManifestStore({ deps, now: this.now, log: this.log, isDisposed: () => this.disposed });
    this.transfer = new BoxStoreTransfer({ deps, now: this.now, log: this.log, manifestStore: this.manifestStore, maxObjectBytes, downloadConcurrency, uploadConcurrency, largeObjectThreshold, downloadByteBudget, getFlushWaiters: () => this.flushWaiters });
    this.storeDbCapture = new StoreDbCapture({ deps, now: this.now, log: this.log, manifestStore: this.manifestStore, transfer: this.transfer, maxObjectBytes, uploadConcurrency, largeObjectThreshold, ensureWriterLock: () => this.ensureWriterLock(), isStopped: () => this.stopped });
  }
  get manifestV2Enabled(): boolean { return this.manifestStore.isManifestV2Enabled; }
  enrollManifestV2(): void { this.manifestStore.enrollManifestV2(); }
  objectStore(storeId: string) { return this.deps.objectStoreProvider.forStore(storeId); }
  private elapsedDurationMs(startedAt: number): number { return Math.max(0, this.now() - startedAt); }
  async ensureWriterLock(): Promise<boolean> { if (this.writerLock != null) return true; const acquire = this.deps.acquireWriterLock ?? defaultAcquireWriterLock; const lockPath = this.deps.lockPath; if (lockPath == null) return true; try { const lock = await acquire({ lockPath, windowId: this.deps.windowId ?? `box-store-${process.pid}` }); if (lock == null) return false; this.writerLock = lock; return true; } catch (error) { this.log(`writer lock error: ${errorMessage(error)}`); return false; } }
  async snapshotNow(options: SnapshotOptions = {}): Promise<BoxStoreCycleSummary> { if (this.stopped) return this.emptyCycle("stopped", this.now()); if (this.cycleInFlight) { if (!options.waitForInFlight) return this.emptyCycle("in-flight", this.now()); this.flushWaiters += 1; try { while (this.cycleInFlight) await Promise.allSettled([this.inFlight]); } finally { this.flushWaiters -= 1; } } this.cycleInFlight = true; const run = this.runCycle(options); this.inFlight = run; try { return await run; } finally { this.cycleInFlight = false; this.inFlight = undefined; } }
  async runCycle(options: SnapshotOptions): Promise<BoxStoreCycleSummary> {
    const start = this.now(); let storeDbCapture: { startedAt: number; storeId: string; sweep: StoreDbSweepResult } | undefined, isStoreDbCaptureReported = false;
    try { if (!await this.ensureWriterLock()) return this.report(this.emptyCycle("locked", start)); const storeId = await this.deps.resolveStoreId(), categories: CategorySummary[] = [];
      for (const category of this.deps.categories) { if (options.chromeSessionOnly && !category.stageOnly || category.idleOnly && !options.includeIdleOnly) continue; try { categories.push(await this.transfer.syncCategory(storeId, category)); } catch (error) { this.log(`category ${category.name} failed: ${errorMessage(error)}`); categories.push({ name: category.name, filesScanned: 0, filesUploaded: 0, bytesUploaded: 0, skippedUnchanged: 0, removed: 0, oversize: 0, failures: 1, metadataFailures: 0 }); } }
      await this.storeDbCapture.pruneMissingAgentStoreDbs(storeId); let storeDbComplete = false, capturedThisSweep = new Set<string>();
      if (options.includeStoreDbs) { const startedAt = this.now(); let sweep: StoreDbSweepResult; try { sweep = await this.storeDbCapture.runAgentStoreDbsSweep(storeId, options.skipLiveHandleStoreDbs === true); } catch (error) { this.log(`store.db flush failed: ${errorMessage(error)}`); const captureTrace = createStoreDbCaptureTrace(); recordStoreDbCaptureFailure(captureTrace, "capture"); sweep = { summary: { name: "store.db", filesScanned: 0, filesUploaded: 0, bytesUploaded: 0, skippedUnchanged: 0, removed: 0, oversize: 0, failures: 1, metadataFailures: 0 }, complete: false, agentCount: 0, capturedThisSweep: new Set(), captureTrace, manifest: undefined }; } storeDbCapture = { startedAt, storeId, sweep }; categories.push(sweep.summary); storeDbComplete = sweep.complete; capturedThisSweep = sweep.capturedThisSweep; }
      const prunedAfterSweep = await this.storeDbCapture.pruneMissingAgentStoreDbs(storeId); if (options.includeStoreDbs && storeDbComplete && prunedAfterSweep > 0) { const category = this.deps.categories.find((candidate) => candidate.containsAgentStoreDbs); if (category != null) storeDbComplete = await this.storeDbCapture.verifyAgentDbsComplete(join(category.absRoot, "agents"), category.relPrefix, await this.manifestStore.loadManifest(storeId), capturedThisSweep); }
      const markerPath = this.deps.hydrationHandoffMarkerPath, promoteFullyHydrated = markerPath != null && existsSync(markerPath) && options.includeIdleOnly === true && options.includeStoreDbs === true && storeDbComplete && categories.every((category) => category.failures === 0 && category.oversize === 0), hasCycleFailures = categories.some((category) => category.failures > 0 || category.oversize > 0);
      try { await this.manifestStore.saveManifest(storeId, { acceptMatchingCanonicalOnConflict: options.acceptMatchingCanonicalOnConflict === true, isForced: hasCycleFailures, hydrationUpdate: promoteFullyHydrated ? "promote-complete" : undefined, captureTrace: storeDbCapture?.sweep.captureTrace }); } catch (error) { if (storeDbCapture != null) recordStoreDbCaptureFailure(storeDbCapture.sweep.captureTrace, "manifest_commit"); throw error; }
      if (storeDbCapture != null) { const outcome = aggregateStoreDbSweepOutcome(storeDbCapture.sweep.summary); this.reportStoreDbSweepCapture(storeDbCapture, outcome, { isCommitted: storeDbCapture.sweep.complete && (outcome === "uploaded" || outcome === "unchanged") && this.manifestStore.isStoreDbSweepCommitted(storeDbCapture.sweep.manifest, storeDbCapture.sweep.capturedThisSweep) }); isStoreDbCaptureReported = true; }
      if (promoteFullyHydrated) await removeHydrationHandoffMarker(markerPath).catch((error) => this.log(`hydration handoff marker cleanup failed: ${errorMessage(error)}`));
      if (options.includePacks === true && isBoxStorePackBuildEnabled()) categories.push(await this.transfer.syncPacks(storeId));
      return this.report(this.buildSummary(storeId, start, categories, storeDbComplete));
    } catch (error) { if (storeDbCapture != null && !isStoreDbCaptureReported) { recordStoreDbCaptureFailure(storeDbCapture.sweep.captureTrace, "capture"); this.reportStoreDbSweepCapture(storeDbCapture, "error", { isCommitted: false }); } this.log(`cycle failed: ${errorMessage(error)}`); return this.report(this.emptyCycle(errorMessage(error), start)); }
  }
  scheduleStoreDbSnapshot(agentId: string): void { if (this.disposed || this.stopped) return; let trigger = this.pendingStoreDb.get(agentId); if (trigger === undefined) { trigger = this.deps.storeDbDebounce.wrap(() => { void this.snapshotStoreDb(agentId).catch((error) => this.log(`turn-end store.db snapshot rejected: ${errorMessage(error)}`)); }); this.pendingStoreDb.set(agentId, trigger); } trigger(); }
  async snapshotStoreDb(agentId: string): Promise<BoxStoreCaptureSummary["outcome"]> { const start = this.now(), result = await this.storeDbCapture.runAgentStoreDbSnapshot(agentId); this.reportStoreDbCapture({ trigger: "turn_end", outcome: result.outcome, agentCount: result.outcome === "skipped" ? 0 : 1, filesScanned: result.summary.filesScanned, filesUploaded: result.summary.filesUploaded, bytes: result.summary.bytesUploaded, durationMs: this.elapsedDurationMs(start), queueDurationMs: result.captureTrace.queueDurationMs, captureDurationMs: result.captureTrace.captureDurationMs, blobUploadDurationMs: result.captureTrace.blobUploadDurationMs, manifestCommitDurationMs: result.captureTrace.manifestCommitDurationMs, isCommitted: result.isCommitted, failurePhase: result.captureTrace.failurePhase, storeId: result.storeId }); return result.outcome; }
  async download(targetDir: string, options: BoxStoreDownloadOptions = {}): Promise<BoxStoreDownloadSummary> { return this.transfer.download(targetDir, options); }
  async readManifestStrict() { return this.manifestStore.readManifestStrict(); }
  async readManifestStrictDetailed() { return this.manifestStore.readManifestStrictDetailed(); }
  async markLegacyHydrationIncomplete(): Promise<void> { return this.manifestStore.markLegacyHydrationIncomplete(); }
  async markLegacyHydrationCompleteForHandoff(): Promise<void> { return this.manifestStore.markLegacyHydrationCompleteForHandoff(); }
  async sweepLeakedTemps(): Promise<number> { return this.transfer.sweepLeakedTemps(); }
  async readStoreStatus() { const empty = { durable: false, fullyHydrated: undefined, entryCount: 0, storeDbEntries: 0, agentDirEntries: 0, totalBytes: 0, lastSnapshotAtMs: 0 }; try { const snapshot = await this.manifestStore.readCanonicalManifestSnapshot(); if (snapshot == null) return empty; const manifest = new Map(Object.entries(snapshot.entries)), entries = [...manifest.values()], totalBytes = entries.reduce((sum, entry) => sum + (isBoxStoreManifestFileEntry(entry) ? entry.size : 0), 0); return { durable: entries.length > 0, fullyHydrated: snapshot.fullyHydrated, entryCount: entries.length, storeDbEntries: countStoreDbManifestEntries(manifest), agentDirEntries: countAgentDirManifestEntries(manifest), totalBytes, lastSnapshotAtMs: snapshot.updatedAtMs }; } catch (error) { this.log(`readStoreStatus failed: ${errorMessage(error)}`); return empty; } }
  async clearStore(): Promise<{ ok: boolean; reason?: string }> { this.stopped = true; for (const trigger of this.pendingStoreDb.values()) trigger.dispose(); this.pendingStoreDb.clear(); try { if (!await this.ensureWriterLock()) return { ok: false, reason: "locked" }; const storeId = await this.deps.resolveStoreId(); await this.manifestStore.prepareCanonicalManifestReset(storeId); if (this.deps.hydrationHandoffMarkerPath != null) await removeHydrationHandoffMarker(this.deps.hydrationHandoffMarkerPath); this.manifestStore.hydrationManifestReadBlocked = false; this.manifestStore.manifest = new Map(); this.manifestStore.initializeManifestRevision(this.manifestStore.manifest, undefined); this.manifestStore.uncommittedStoreDbEntries.clear(); await this.manifestStore.saveManifest(storeId, { hydrationUpdate: "reset-complete" }); return { ok: true }; } catch (error) { return { ok: false, reason: errorMessage(error) }; } }
  async forgetAgent(agentId: string): Promise<{ ok: boolean; reason?: string }> { const pending = this.pendingStoreDb.get(agentId); if (pending != null) { pending.dispose(); this.pendingStoreDb.delete(agentId); } try { if (!await this.ensureWriterLock()) return { ok: false, reason: "locked" }; const storeId = await this.deps.resolveStoreId(), manifest = await this.manifestStore.loadManifest(storeId), needle = `/agents/${agentId}/`, ownPrefix = `agents/${agentId}/`; let removed = 0; for (const relPath of [...manifest.keys()]) if (relPath.includes(needle) || relPath.startsWith(ownPrefix)) { this.manifestStore.deleteManifestEntry(manifest, relPath); this.transfer.localStat.delete(relPath); this.storeDbCapture.storeDbCaptures.delete(relPath); removed += 1; } if (removed > 0) { await this.manifestStore.saveManifest(storeId); this.log(`forgot ${agentId} (${removed} entries)`); } return { ok: true }; } catch (error) { this.log(`forget ${agentId} failed: ${errorMessage(error)}`); return { ok: false, reason: errorMessage(error) }; } }
  async dispose(): Promise<void> { this.disposed = true; for (const trigger of this.pendingStoreDb.values()) trigger.dispose(); this.pendingStoreDb.clear(); await this.manifestStore.writeQueue; await this.writerLock?.release().catch((error) => this.log(`writer lock release failed: ${errorMessage(error)}`)); this.writerLock = undefined; }
  private buildSummary(storeId: string, start: number, categories: CategorySummary[], storeDbComplete: boolean): BoxStoreCycleSummary { return { ok: true, storeId, durationMs: this.now() - start, categories, manifestEntries: this.manifestStore.manifest?.size ?? 0, storeDbEntries: countStoreDbManifestEntries(this.manifestStore.manifest), storeDbComplete, agentDirEntries: countAgentDirManifestEntries(this.manifestStore.manifest), totalFilesUploaded: categories.reduce((sum, category) => sum + category.filesUploaded, 0), totalBytesUploaded: categories.reduce((sum, category) => sum + category.bytesUploaded, 0), totalFailures: categories.reduce((sum, category) => sum + category.failures + category.oversize, 0), metadataFailures: categories.reduce((sum, category) => sum + category.metadataFailures, 0) }; }
  private emptyCycle(reason: string, start: number): BoxStoreCycleSummary { return { ok: false, reason, storeId: null, durationMs: this.now() - start, categories: [], manifestEntries: this.manifestStore.manifest?.size ?? 0, storeDbEntries: countStoreDbManifestEntries(this.manifestStore.manifest), storeDbComplete: false, agentDirEntries: countAgentDirManifestEntries(this.manifestStore.manifest), totalFilesUploaded: 0, totalBytesUploaded: 0, totalFailures: 0, metadataFailures: 0 }; }
  private reportStoreDbSweepCapture(capture: { startedAt: number; storeId: string; sweep: StoreDbSweepResult }, outcome: StoreDbCaptureOutcome, publication: { isCommitted: boolean }): void { const { sweep } = capture; this.reportStoreDbCapture({ trigger: "flush", outcome, agentCount: sweep.agentCount, filesScanned: sweep.summary.filesScanned, filesUploaded: sweep.summary.filesUploaded, bytes: sweep.summary.bytesUploaded, durationMs: this.elapsedDurationMs(capture.startedAt), queueDurationMs: sweep.captureTrace.queueDurationMs, captureDurationMs: sweep.captureTrace.captureDurationMs, blobUploadDurationMs: sweep.captureTrace.blobUploadDurationMs, manifestCommitDurationMs: sweep.captureTrace.manifestCommitDurationMs, isCommitted: publication.isCommitted, failurePhase: sweep.captureTrace.failurePhase, storeId: capture.storeId }); }
  private reportStoreDbCapture(summary: BoxStoreCaptureSummary): void { try { this.deps.onStoreDbCapture?.(summary); } catch {} }
  private report(summary: BoxStoreCycleSummary): BoxStoreCycleSummary { if (summary.ok) this.log(`cycle ok in ${summary.durationMs}ms: ${summary.totalFilesUploaded} files / ${summary.totalBytesUploaded}B up, ${summary.manifestEntries} entries, ${summary.totalFailures} failures`); else this.log(`cycle skipped (${summary.reason})`); try { this.deps.onCycle?.(summary); } catch {} return summary; }
}

async function defaultAcquireWriterLock(args: { lockPath: string; windowId: string }): Promise<{ release(): Promise<void> } | null> {
  const result = await tryAcquireStoreLock({ lockPath: args.lockPath, windowId: args.windowId });
  if (result.kind === "acquired") return { release: () => result.lock.dispose() };
  return null;
}

export function boxStoreSyncCycleTelemetry(summary: BoxStoreCycleSummary): { level: "info" | "warn"; metadata: Record<string, string> } | null { if (!summary.ok) { if (summary.reason === "in-flight") return null; return { level: "warn", metadata: { ok: "false", reason: summary.reason === "locked" ? "locked" : "error", duration_ms: String(summary.durationMs), manifest_entries: String(summary.manifestEntries), store_db_entries: String(summary.storeDbEntries) } }; } const excludedFiles = summary.categories.reduce((sum, category) => sum + (category.excludedFiles ?? 0), 0), excludedBytes = summary.categories.reduce((sum, category) => sum + (category.excludedBytes ?? 0), 0), prunedDirs = summary.categories.reduce((sum, category) => sum + (category.prunedDirs ?? 0), 0), metadata: Record<string, string> = { ok: "true", duration_ms: String(summary.durationMs), files_uploaded: String(summary.totalFilesUploaded), bytes_uploaded: String(summary.totalBytesUploaded), manifest_entries: String(summary.manifestEntries), excluded_files: String(excludedFiles), excluded_bytes: String(excludedBytes), pruned_dirs: String(prunedDirs), store_db_entries: String(summary.storeDbEntries), store_id: summary.storeId ?? "", failures: String(summary.totalFailures) }; for (const category of summary.categories) { metadata[`${category.name}_uploaded`] = String(category.filesUploaded); metadata[`${category.name}_bytes`] = String(category.bytesUploaded); } return { level: "info", metadata }; }
export function evaluateBoxStoreFlush(summary: BoxStoreCycleSummary | null | undefined, options: { sessionCategoryName: string }) { if (summary?.ok !== true) return { ok: false, manifestEntries: 0, storeDbEntries: 0, agentDirEntries: 0, storeDbComplete: false, filesUploaded: 0, reason: summary?.reason ?? "error" }; if (summary.categories.some((category) => category.name === "store.db") && !summary.storeDbComplete) return { ok: false, manifestEntries: summary.manifestEntries, storeDbEntries: summary.storeDbEntries, agentDirEntries: summary.agentDirEntries, storeDbComplete: false, filesUploaded: summary.totalFilesUploaded, reason: "store-db-incomplete" }; if (summary.metadataFailures > 0) return { ok: false, manifestEntries: summary.manifestEntries, storeDbEntries: summary.storeDbEntries, agentDirEntries: summary.agentDirEntries, storeDbComplete: summary.storeDbComplete, filesUploaded: summary.totalFilesUploaded, reason: "filesystem-metadata-incomplete" }; if ((summary.categories.find((category) => category.name === options.sessionCategoryName)?.failures ?? 0) > 0) return { ok: false, manifestEntries: summary.manifestEntries, storeDbEntries: summary.storeDbEntries, agentDirEntries: summary.agentDirEntries, storeDbComplete: summary.storeDbComplete, filesUploaded: summary.totalFilesUploaded, reason: "chrome-session-stage-failed" }; return { ok: true, manifestEntries: summary.manifestEntries, storeDbEntries: summary.storeDbEntries, agentDirEntries: summary.agentDirEntries, storeDbComplete: summary.storeDbComplete, filesUploaded: summary.totalFilesUploaded, reason: "" }; }
