import { createHash } from "node:crypto";
import { createWriteStream } from "node:fs";
import { open, readFile, stat } from "node:fs/promises";
import { gzipSync, gunzipSync } from "node:zlib";
import { z } from "zod";
import { SandBoxStoreSyncError } from "./box-store-sync-error.js";

export const BOX_STORE_PACKS_PREFIX = "packs";
export const BOX_STORE_PACK_INDEX_KEY = "packs/index.json";
export const BOX_STORE_PACK_RETIRED_KEY = "packs/retired.json";
export const PACK_INDEX_VERSION = 1;
export const PACK_RETIRED_VERSION = 1;
export const PACK_MEMBER_MAX_BYTES = 8 * 1024 * 1024;
export const PACK_MAX_MEMBER_SIZE_SUM = 256 * 1024 * 1024;
export const PACK_MEMBER_CLEN_BOUND = (size: number): number => size + 4_096 + Math.ceil(size / 512);
export const PACK_OBJECT_MAX_BYTES = 320 * 1024 * 1024;
export const PACK_INDEX_MAX_BYTES = 64 * 1024 * 1024;
export const packMemberSchema = z.object({ sha: z.string().min(1), size: z.number().int().nonnegative().max(PACK_MEMBER_MAX_BYTES), offset: z.number().int().nonnegative(), clen: z.number().int().nonnegative(), vmtime: z.number().int().nonnegative() }).refine((member) => member.clen <= PACK_MEMBER_CLEN_BOUND(member.size), { message: "member clen exceeds the gzip expansion bound for its size" });
export const packEntrySchema = z.object({ id: z.string().min(1), bytes: z.number().int().nonnegative().max(PACK_OBJECT_MAX_BYTES), members: z.array(packMemberSchema) }).superRefine((pack, context) => { let sizeSum = 0; for (const member of pack.members) { if (member.offset + member.clen > pack.bytes) { context.addIssue({ code: z.ZodIssueCode.custom, message: "member range exceeds the pack object size" }); return; } sizeSum += member.size; } if (sizeSum > PACK_MAX_MEMBER_SIZE_SUM) context.addIssue({ code: z.ZodIssueCode.custom, message: "member size sum exceeds the pack cap" }); });
export const packIndexSchema = z.object({ version: z.number().int(), maxVmtime: z.number().int().nonnegative(), packs: z.array(packEntrySchema) });
export type PackMember = z.infer<typeof packMemberSchema>; export type PackEntry = z.infer<typeof packEntrySchema>; export type PackIndex = z.infer<typeof packIndexSchema>;
const packRetiredSchema = z.object({ version: z.number().int(), retired: z.array(z.string().min(1)) });
export function parsePackIndex(raw: string): PackIndex | null { let parsed: unknown; try { parsed = JSON.parse(raw); } catch { return null; } const result = packIndexSchema.safeParse(parsed); return !result.success || result.data.version !== PACK_INDEX_VERSION ? null : result.data; }
export function serializePackIndex(index: PackIndex): string { return JSON.stringify(index); }
export function parsePackRetired(raw: string): string[] | null { let parsed: unknown; try { parsed = JSON.parse(raw); } catch { return null; } const result = packRetiredSchema.safeParse(parsed); return !result.success || result.data.version !== PACK_RETIRED_VERSION ? null : result.data.retired; }
export function serializePackRetired(retired: readonly string[]): string { return JSON.stringify({ version: PACK_RETIRED_VERSION, retired }); }
export interface PackSource { readonly absPath: string; readonly sha: string; readonly size: number; readonly vmtime: number }
export async function buildPackFile(destPath: string, sources: readonly PackSource[], shouldAbort?: () => boolean): Promise<{ members: PackMember[]; fileBytes: number; skipped: number } | null> { const members: PackMember[] = []; let offset = 0, skipped = 0, outError: unknown; const out = createWriteStream(destPath); out.on("error", (error) => { outError ??= error; }); const write = (bytes: Uint8Array) => new Promise<void>((resolve, reject) => out.write(bytes, (error) => error == null ? resolve() : reject(error))); try { for (const source of sources) { if (shouldAbort?.() === true) { out.destroy(); return null; } let bytes: Buffer; try { bytes = await readFile(source.absPath); } catch { skipped += 1; continue; } if (bytes.byteLength !== source.size || createHash("sha256").update(bytes).digest("hex") !== source.sha) { skipped += 1; continue; } const compressed = gzipSync(bytes); await write(compressed); members.push({ sha: source.sha, size: source.size, offset, clen: compressed.byteLength, vmtime: source.vmtime }); offset += compressed.byteLength; } await new Promise<void>((resolve) => out.end(resolve)); if (outError != null) throw outError; } catch (error) { out.destroy(); throw error; } return { members, fileBytes: (await stat(destPath)).size, skipped }; }
export async function extractPackMembers(args: { packPath: string; members: readonly PackMember[]; concurrency?: number; wants(member: PackMember): boolean; admitBytes?(bytes: number): Promise<() => void>; onBlob(member: PackMember, bytes: Uint8Array): Promise<void> }): Promise<{ extracted: number; mismatched: number }> { const handle = await open(args.packPath, "r"), concurrency = Math.max(1, args.concurrency ?? 1); let extracted = 0, mismatched = 0, next = 0; const extractOne = async (member: PackMember) => { const release = args.admitBytes == null ? undefined : await args.admitBytes(member.clen + member.size); try { const compressed = Buffer.alloc(member.clen), { bytesRead } = await handle.read(compressed, 0, member.clen, member.offset); let bytes: Buffer; try { if (bytesRead !== member.clen) throw new SandBoxStoreSyncError("short read"); bytes = gunzipSync(compressed, { maxOutputLength: Math.max(member.size, 1) }); } catch { mismatched += 1; return; } if (bytes.byteLength !== member.size || createHash("sha256").update(bytes).digest("hex") !== member.sha) { mismatched += 1; return; } await args.onBlob(member, new Uint8Array(bytes.buffer, bytes.byteOffset, bytes.byteLength)); extracted += 1; } finally { release?.(); } }; try { const workers = Array.from({ length: Math.min(concurrency, args.members.length) }, async () => { for (;;) { const index = next++; if (index >= args.members.length) return; const member = args.members[index]; if (member != null && args.wants(member)) await extractOne(member); } }); const settled = await Promise.allSettled(workers), failure = settled.find((result) => result.status === "rejected"); if (failure?.status === "rejected") throw failure.reason; } finally { await handle.close(); } return { extracted, mismatched }; }
interface PackCandidate { sha: string; size: number; survivor: boolean }
export function planPackMaintenance(input: { index: PackIndex | null; live: ReadonlyMap<string, number>; eligible: ReadonlyMap<string, number>; maxPackMemberSizeSum: number; minPackMembers: number; minPackBytes: number }): { keptPacks: PackEntry[]; retiredPackIds: string[]; newPacks: Array<Array<{ sha: string; size: number; vmtime: number }>>; deferredMembers: number; newMaxVmtime: number } { const keptPacks: PackEntry[] = [], retiredPackIds: string[] = [], survivors: Array<{ sha: string; size: number }> = [], packedShas = new Set<string>(); for (const pack of input.index?.packs ?? []) { const live = (member: PackMember) => input.live.get(member.sha) === member.size; if (pack.members.length > 0 && pack.members.every(live)) { keptPacks.push(pack); for (const member of pack.members) packedShas.add(member.sha); } else { retiredPackIds.push(pack.id); for (const member of pack.members) if (live(member)) survivors.push({ sha: member.sha, size: member.size }); } } let untouchedMax = 0; for (const pack of keptPacks) for (const member of pack.members) untouchedMax = Math.max(untouchedMax, member.vmtime); const survivorShas = new Set(survivors.map((item) => item.sha)), newbies: Array<{ sha: string; size: number }> = []; for (const [sha, size] of input.eligible) if (!packedShas.has(sha) && !survivorShas.has(sha)) newbies.push({ sha, size }); const compare = (a: { sha: string }, b: { sha: string }) => a.sha < b.sha ? -1 : a.sha > b.sha ? 1 : 0; newbies.sort(compare); survivors.sort(compare); const candidates: PackCandidate[] = [...survivors.map((item) => ({ ...item, survivor: true })), ...newbies.map((item) => ({ ...item, survivor: false }))], groups: PackCandidate[][] = []; let current: PackCandidate[] = [], currentBytes = 0; for (const member of candidates) { if (current.length > 0 && currentBytes + member.size > input.maxPackMemberSizeSum) { groups.push(current); current = []; currentBytes = 0; } current.push(member); currentBytes += member.size; } if (current.length > 0) groups.push(current); let deferredMembers = 0; const last = groups.at(-1); if (last != null && last.length < input.minPackMembers && last.reduce((sum, member) => sum + member.size, 0) < input.minPackBytes) { deferredMembers = last.length; groups.pop(); } let nextVmtime = Math.max(input.index?.maxVmtime ?? 0, untouchedMax); const newPacks = groups.map((group) => group.map((member) => member.survivor ? { sha: member.sha, size: member.size, vmtime: untouchedMax } : { sha: member.sha, size: member.size, vmtime: ++nextVmtime })); return { keptPacks, retiredPackIds, newPacks, deferredMembers, newMaxVmtime: Math.max(nextVmtime, untouchedMax, input.index?.maxVmtime ?? 0) }; }
export function isBoxStorePackBuildEnabled(env: NodeJS.ProcessEnv = process.env): boolean { const raw = env.SAND_BOX_STORE_PACKS?.trim().toLowerCase(); return !(raw === "0" || raw === "false" || raw === "no"); }
