import { statSync, watch, type FSWatcher } from "node:fs";
import { join } from "node:path";
import type { DebouncePolicy } from "../../../internal/scheduling.js";
export interface ChromeSessionWatcherDependencies { watchDir: string; sessionDbNames: readonly string[]; debounce: DebouncePolicy; onSessionChange(): void; startWatch?(dir: string, listener: (filename: string | null) => void): { close(): void }; statMtimeMs?(path: string): number | undefined; log?(message: string): void }
export class ChromeSessionWatcher { private watcher: Pick<FSWatcher, "close"> | undefined; private stopped = false; private readonly startWatch: NonNullable<ChromeSessionWatcherDependencies["startWatch"]>; private readonly trigger: (() => void) & { dispose(): void }; private readonly statMtimeMs: NonNullable<ChromeSessionWatcherDependencies["statMtimeMs"]>; private readonly log: NonNullable<ChromeSessionWatcherDependencies["log"]>; readonly lastMtimes = new Map<string, number>();
  constructor(readonly deps: ChromeSessionWatcherDependencies) { this.startWatch = deps.startWatch ?? ((dir, listener) => watch(dir, { persistent: false }, (_event, name) => listener(typeof name === "string" ? name : null))); this.trigger = deps.debounce.wrap(() => { if (this.stopped) return; try { deps.onSessionChange(); } catch (error) { this.log(`onSessionChange threw (ignored): ${String(error)}`); } }); this.statMtimeMs = deps.statMtimeMs ?? ((path) => { try { return statSync(path).mtimeMs; } catch { return undefined; } }); this.log = deps.log ?? ((message) => console.log(`[chrome-session-watcher] ${message}`)); }
  start(): void { if (this.stopped || this.watcher != null) return; this.refreshSessionDbMtimes(); try { this.watcher = this.startWatch(this.deps.watchDir, (name) => this.handleFsEvent(name)); this.log(`watching ${this.deps.watchDir} for session-db changes`); } catch (error) { this.log(`watch could not arm (periodic cycle is the backstop): ${String(error)}`); } }
  handleFsEvent(filename: string | null): void { if (this.stopped) return; if (filename === null) { if (!this.sessionDbChangedSinceLastCheck()) return; } else if (!this.isSessionDbFile(filename)) return; this.trigger(); }
  isSessionDbFile(filename: string): boolean { return this.deps.sessionDbNames.some((name) => filename.startsWith(name)); }
  sessionDbChangedSinceLastCheck(): boolean { let changed = false; for (const name of this.deps.sessionDbNames) { const mtime = this.statMtimeMs(join(this.deps.watchDir, name)); if (mtime == null) continue; const last = this.lastMtimes.get(name); if (last == null || mtime > last) { this.lastMtimes.set(name, mtime); changed = true; } } return changed; }
  refreshSessionDbMtimes(): void { for (const name of this.deps.sessionDbNames) { const mtime = this.statMtimeMs(join(this.deps.watchDir, name)); if (mtime != null) this.lastMtimes.set(name, mtime); } }
  stop(): void { this.stopped = true; this.trigger.dispose(); try { this.watcher?.close(); } catch {} this.watcher = undefined; }
}
