import { COORDINATOR_PROTOCOL_VERSION, parseCoordinatorFrame, type CoordinatorFrame, type CoordinatorReplyOutcome } from "../../shared/rpc/coordinator-port.js";
import { COORDINATOR_MAIN_METHOD_TABLE } from "../../shared/rpc/coordinator-main.js";

export class CoordinatorMainPortCallError extends Error { constructor(readonly code: string, message: string) { super(`${code}: ${message}`); this.name = "CoordinatorMainPortCallError"; } }
export function createCoordinatorMainPortClient(endpoint: { post(frame: CoordinatorFrame): void; close(): void }) {
  let phase: "awaiting-ready" | "serving" | "settled" = "awaiting-ready"; let nextRequestId = 0;
  const pending = new Map<string, { method: string; resolve(value: unknown): void; reject(error: unknown): void }>(); const { promise: settled, resolve: resolveSettled } = Promise.withResolvers<any>();
  const settle = (settlement: any) => { if (phase === "settled") return; phase = "settled"; for (const call of pending.values()) call.reject(new Error(`coordinator main data port settled (${settlement.outcome}) before the ${call.method} reply`)); pending.clear(); endpoint.close(); resolveSettled(settlement); };
  const breach = (detail: string) => { if (phase === "settled") return; endpoint.post({ kind: "lifecycle", phase: "shutdown", reason: "protocol-error", detail }); settle({ outcome: "protocol-breach", detail }); };
  endpoint.post({ kind: "lifecycle", phase: "hello", protocolVersion: COORDINATOR_PROTOCOL_VERSION });
  const call = (method: string, args: unknown) => { if (phase === "settled") return Promise.reject(new Error(`coordinator main data port settled before ${method} was posted`)); const requestId = `m-${++nextRequestId}`; const outcome = new Promise((resolve, reject) => pending.set(requestId, { method, resolve, reject })); endpoint.post({ kind: "request", requestId, method, args }); return outcome; };
  const settleReply = (requestId: string, outcome: CoordinatorReplyOutcome) => { const waiting = pending.get(requestId); if (waiting == null) return; pending.delete(requestId); if (outcome.status === "ok") waiting.resolve(outcome.value); else waiting.reject(new CoordinatorMainPortCallError(outcome.failure.code, outcome.failure.message)); };
  const handleFrame = (frame: CoordinatorFrame) => { if (frame.kind === "lifecycle" && frame.phase === "shutdown") { settle(frame.reason === "requested" ? { outcome: "coordinator-shutdown" } : { outcome: "protocol-breach", detail: frame.detail ?? "peer reported a breach" }); return; } if (frame.kind === "lifecycle" && frame.phase === "ready") { if (phase !== "awaiting-ready") return breach("ready repeated on a live main-data session"); if (frame.protocolVersion !== COORDINATOR_PROTOCOL_VERSION) return breach(`ready.protocolVersion ${frame.protocolVersion} is not the supported ${COORDINATOR_PROTOCOL_VERSION}`); phase = "serving"; return; } if (frame.kind === "reply") { settleReply(frame.requestId, frame.outcome); return; } if (frame.kind === "event") return; breach(`coordinator posted a client-direction ${frame.kind} frame`); };
  const legs: Record<string, (first?: unknown) => Promise<unknown>> = {}; for (const [name, wire] of Object.entries(COORDINATOR_MAIN_METHOD_TABLE)) legs[name] = wire.args === "none" ? () => call(name, {}) : (first) => call(name, first);
  return { legs, handleMessage(value: unknown) { if (phase === "settled") return; const intake = parseCoordinatorFrame(value); if (!intake.accepted) return breach(intake.rejection.detail); handleFrame(intake.frame); }, handlePortClosed: () => settle({ outcome: "port-closed" }), dispose() { if (phase === "settled") return; endpoint.post({ kind: "lifecycle", phase: "shutdown", reason: "requested", detail: null }); settle({ outcome: "shutdown-requested" }); }, settled };
}
